CHANGELOG.md, backend/etcd/etcd.go
This adds etcd autocompaction to the embedded etcd config. Every 5minutes (the schedule for revision-based autocompaction), we'll compact every revision except the newest.
Without compaction, we'll retain every version of every key until we hit the db size limit.
=> Add autocompaction by revision to the etcd config

.appveyor.yml, build.ps1
Changes the `wait_for_appveyor_jobs` task to exit as soon as possible upon detecting that a build is not tagged.
We're currently wasting an AppVeyor worker during non-tagged builds.
Nope!
Nope!
Nope!
=> Only deploy on appveyor if building tag

CHANGELOG.md, backend/monitor/monitor.go
Resolves a bug in the keepalive monitor timer which was causing it to erroneously expire.
Closes #997.
Yas.
Nah, but added everyone who seemed interested in this bug to review, even though its incredibly small.
The issue is intermittent, so its very hard to reproduce. This change passed tests 200/200 times under medium load locally.
=> Bugfix: Keepalive monitor timeout

CHANGELOG.md, agent/agent.go, agent/cmd/start.go, util/url/LICENSE, util/url/url.go, util/url/url_test.go
Append `:8081` any of an agent's backend urls that do not have a port specified.
Fixes #985.
Yes.
Nope!
Nope!
=> Append :8081 to Agent backend URLs if no port set

backend/messaging/benchmark_test.go
Pass loop variable in via function params so it does not get captured by the function.
The lint checks were producing the following error:
```
backend/messaging/benchmark_test.go:20::error: loop variable i captured by func literal (vet)
```
Nope!
Nope!
Nope!
=> Pass loop variable into func to prevent capture

CHANGELOG.md, backend/schedulerd/executor.go, testing/e2e/proxy_checks_test.go
Resolves a bug in how an executor processes checks. If a check contains proxy requests, the check should not duplicately execute after the proxy requests.
Closes #1054.
Yas.
Nah.
Copying and pasting code is deadly.. glad this is resolved and interfaced! Also, this is another intermittent failure which after this change did not reproduce on 200 attempts under medium load locally.
=> Checks should not duplicately execute after its proxy requests have executed

CHANGELOG.md, dashboard/src/components/EventsListItem.js
Adds a simple, non-functioning disclosure (3 dots) dropdown for silencing and resolving events. The actions are to be added later.
Required for the web ui.
I added one.
N/A
Resolving events has yet to be implemented. So this must be revisited when it's available. In addition, the dialog that will appear for silencing requires more thought, so we will revisit that later as well.
=> [Web] Silencing and Resolve

agent/entity.go
Uses EntityAgentClass constant when assigning an agent entity's class.
It's good practice to use our entity class constants when assigning entities their class.
Probably not.
Nah.
Nah.
=> Use EntityAgentClass constant when assigning an agent entity's class

Gopkg.lock
An incorrect Gopkg.lock was merged into master.
dep is importing the wrong dependencies when running dep ensure.
No, not really.
=> Update Gopkg.lock with latest dependencies on master

CHANGELOG.md, agent/check_handler.go, types/check.go, types/check_test.go
Removes an erroneous check validation statement in check handler. Cron and interval are mutually exclusive, so interval _may_ be < 1.
Fixes the error that came up in @jamesdphillips demo.
Yas.
Nah.
Nah.
=> Remove erroneous check validation statement

.appveyor.yml, .travis.yml, CHANGELOG.md, Dockerfile.packaging, Vagrantfile, build.ps1, build.sh
Go 1.10 has been released, so we should use it. As a side effect, it should fix a build error in a dependency of fileb0x.
=> Upgrade Go to 1.10 for Travis and AppVeyor.

README.md
Just fixing a couple of typos in the readme and removing the Travis token for you now that your project isn't secret anymore. (Looking forward to checking Sensu 2.0 out more. Hi, ~Heavy Water~ Sensu team!)
Good prose makes good open source.
I doubt it.
=> Fix a few typos and grammar errors

dashboard/package.json, dashboard/src/components/AppContent.js, dashboard/src/components/AppFrame.js, dashboard/src/components/EventsListItem.js, dashboard/src/components/QuickNav.js
Hide quick navigation when media min width becomes too small.
Free up more room for app content on smaller screens.
=> [Web UI] Hide quick navigation when media is too small

CHANGELOG.md, agent/hook.go, agent/hook_test.go, cli/commands/check/subcommands/set_hooks_test.go, types/hook.go, types/hook_test.go
Fixes HookList validation and messages, and ensures we do not duplicate hook execution for return codes that may fall under multiple types (ex. 0, ok).
This clarifies confusion around an oversight on documentation. "0" and "ok" are valid types of check hooks!
Yas.
Nah.
Nah.
=> Fix HookList validation

agent/agent.go
Fix up typo in agent configuration defaults
Otherwise by default the agent is configured with the wrong environment. 
I believe the change was introduced after the last release.
=> [Agent] Fix up typo in agent configuration defaults

backend/eventd/integration_test.go, backend/keepalived/integration_test.go
Fixes a bug in the integration tests introduced with https://github.com/sensu/sensu-go/pull/1100.
It fixes the integration tests!
No; it fixes a bug introduced in an unreleased feature
Nope!
Nope!
=> Fix integration tests that verify a check status

agent/assetmanager/asset_test.go, agent/assetmanager/manager_test.go, agent/assetmanager/set_test.go, agent/assetmanager/store_test.go, backend/keepalived/keepalived_test.go, cli/commands/completion/cmd_test.go, cli/elements/list/list_test.go, testing/e2e/keepalive_test.go
Removes all uses of testify's suite package. I did not use subtests, instead favouring a light refactoring that involved creating a test struct in most cases.
Closes #939
=> Refactor tests to not use testify.Suite.

CHANGELOG.md, README.md
It replaces the Travis badge from travis-ci.com with the good one from travis-ci.org.
Additionally, I removed the sensu/sensu-go repository from the list of enabled repos in order to prevent confusion. 
So the build badge reflects the right status.
Added!
Nope!
Nope!
=> Change travis badge to travis-ci.org

CHANGELOG.md, types/asset.go, types/check.go, types/filter.go, util/eval/eval.go, util/eval/eval_test.go
It adds a second boolean argument to `eval.ValidateStatements` so modifier tokens can be optionally forbidden.
As per 1.x documentation on filters, arithmetic operators (which are considered as modifiers) can be useful in govaluate expressions: https://sensuapp.org/docs/latest/reference/filters.html#example-handling-repeated-events
Added!
Nope!
Nope!
=> Govaluate's modifier tokens can now be optionally forbidden

CHANGELOG.md, backend/cmd/start.go
Adds a `--debug` flag which starts a pprof endpoint.
Debuggin! Profiling! Tracing!
Added.
=> Add debug pprof endpoint

backend/apid/graphql/node.go, backend/apid/graphql/schema/entity.gql.go, backend/apid/graphql/schema/entity.graphql, backend/apid/graphql/schema/event.gql.go, backend/apid/graphql/schema/event.graphql, backend/apid/graphql/schema/handler.gql.go, backend/apid/graphql/schema/handler.graphql, backend/apid/graphql/schema/hook.gql.go, backend/apid/graphql/schema/hook.graphql, backend/apid/graphql/schema/rbac.gql.go, backend/apid/graphql/schema/rbac.graphql
Implement a node resolver for events so that they can be easily re-queried.
Unblock @dabria on #1130.
=> [GraphQL] Implement node resolver for events

CHANGELOG.md, backend/etcd/etcd.go
Fixes #1143. 
This change allows us to recover a sensu-backend whose db has grown past the default etcd limit of 2GB.
Added note in unreleased.
Nope!
Nope!
=> Increase etcd default storage to 4GB.

CHANGELOG.md, util/eval/predicate.go, util/eval/predicate_test.go
It adds custom functions to govaluate, in order to support evaluation of an event timestamp.
In order to reproduce the 1.x filters functionalities.
Added!
Nope!
Nope!
=> Add custom functions to govaluate

CHANGELOG.md, cli/client/interface.go, cli/client/mutator.go, cli/client/testing/mock_mutator_client.go, cli/commands/commands.go, cli/commands/handler/interactive.go, cli/commands/mutator/create.go, cli/commands/mutator/create_test.go, cli/commands/mutator/delete.go, cli/commands/mutator/delete_test.go, cli/commands/mutator/help.go, cli/commands/mutator/info.go, cli/commands/mutator/info_test.go, cli/commands/mutator/interactive.go, cli/commands/mutator/list.go, cli/commands/mutator/list_test.go, cli/commands/mutator/update.go, cli/commands/mutator/update_test.go, types/mutator.go
Adds support for mutators to the cli.
Closes #1119 
Yup!
Nope!
I also noticed an incorrect flag for filters in the handler interactive code, so I fixed it.
=> Add cli support for CRUD mutators

.travis.yml, cli/commands/mutator/interactive.go
After some trial and error, I found that the GC was disabled for the lint job. Megacheck uses too much memory for that, so I re-enabled GC for the lint job.
No, this isn't really pertinent to the actual software.
=> Don't set GOGC=off for lint jobs

backend/ring/ring.go, backend/ring/ring_test.go
Only uses a single lease, and keepalive, per ring. This keeps us from creating a ton of goroutines.
Closes #1163 
Yes
=> Only use one lease per ring

backend/ring/ring.go, backend/ring/ring_test.go
Because new rings are made again and again, even for rings that
already exist, checking for a ring-scoped lease ID is not useful.
Instead, keep a cache of the lease IDs at the package scope,
keyed by ring ID.
Closes #1163 
The previous fix was suboptimal.
=> Use a package level cache for ring leases.

CHANGELOG.md, backend/agentd/agentd.go, backend/agentd/session.go, backend/agentd/session_test.go, backend/backend.go, backend/eventd/eventd_test.go, backend/eventd/integration_test.go, backend/keepalived/integration_test.go, backend/keepalived/keepalived_test.go, backend/messaging/benchmark_test.go, backend/messaging/message_bus.go, backend/messaging/wizard_bus.go, backend/messaging/wizard_bus_test.go, backend/messaging/wizard_topic.go, backend/pipelined/pipelined_test.go, backend/ring/ring.go, backend/schedulerd/check_scheduler.go, backend/schedulerd/check_scheduler_test.go, backend/schedulerd/executor_test.go, backend/schedulerd/round_robin_scheduler.go, backend/schedulerd/round_robin_scheduler_test.go, backend/schedulerd/schedule_manager.go, backend/schedulerd/schedulerd.go, backend/schedulerd/schedulerd_test.go, testing/mockbus/mock.go
* Add PublishDirect method to messaging.MessageBus.
* Use ring for WizardBus PublishDirect implementation.
* Refactor codebase to use messaging.NewWizardBus.
* Remove ring-specific code from schedulerd.
* Remove ring-specific code from agentd.
Closes #1165 
Affirmative
=> Handle round-robin scheduling through WizardBus.

CHANGELOG.md, backend/keepalived/deregisterer.go, backend/keepalived/keepalived.go
Adds some logging to Keepalived in case of monitor timeout or entity de-registration.
Closes #1179 
Added note under Changed.
Nope!
Nope!
=> Add informational logging for entity keepalives

.github/PULL_REQUEST_TEMPLATE.md
This updates the PR template to comment out the descriptions of these heads.
We do this in our issue template, so it seems reasonable to be consistent.
As this is a cosmetic change to the PR template and no functional change to the code, it seems reasonable not to have a changelog entry.
=> Comment out descriptions of PR template headings

CHANGELOG.md, backend/backend.go
Removes an unnecessary format string parameter in backend shutdown messages.
Cosmetics.
=> Fixed shutting down message to not include %s

build.sh
The readme for golint specifically states that we should not be
using golint for build acceptance, so we should respect that and
not include it in ours.
=> Don't use golint in the build process.

CHANGELOG.md, Gopkg.lock, Gopkg.toml, backend/etcd/etcd.go
Updates etcd to 3.3.2 so we can set autocompaction revision to an actual int instead of a time-based value.
Closes #1069 
Added a note under Changed section.
Nope!
Nope!
=> Updated etcd to 3.3.2

CHANGELOG.md, backend/eventd/eventd.go
Only write an event once when handling it in eventd.
We were erroneously double-writing all events.
=> backend/eventd: don't double write events

CHANGELOG.md, backend/agentd/session.go, backend/eventd/eventd.go, backend/eventd/integration_test.go, backend/keepalived/integration_test.go, backend/keepalived/keepalived.go, backend/keepalived/keepalived_test.go, backend/messaging/benchmark_test.go, backend/messaging/message_bus.go, backend/messaging/wizard_bus.go, backend/messaging/wizard_bus_test.go, backend/messaging/wizard_topic.go, backend/pipelined/pipelined.go, backend/schedulerd/check_scheduler_test.go, backend/schedulerd/executor_test.go, backend/schedulerd/schedulerd_test.go, testing/mockbus/mock.go
Removes the concept of subscriber IDs from the message bus, and instead Subscribe takes a Subscriber and returns a Subscription (which can be later cancelled).
This fixes #1097. Rather than simply prolonging the life of user-supplied subscriber IDs, we decided to tackle this bit of tech debt now.
Added.
=> Rework WizardBus Subscribe() method to remove subscriber ID

CHANGELOG.md, cli/cmd/cobra.go, cli/cmd/start.go
It adds a distinction between the type of flags in sensuctl usage.
Before:
```
$sensuctl check create -h
[...]
Options:
--api-url string               host URL of Sensu installation
--cache-dir string             path to directory containing cache & temporary files (default "/Users/splourde/Library/Caches/sensu/sensuctl")
-c, --command string               the command the check should run
--config-dir string            path to directory containing configuration files (default "/Users/splourde/.config/sensu/sensuctl")
--cron string                  the cron schedule at which the check is run
--environment string           environment in which we perform actions (default "default")
--handlers string              comma separated list of handlers …
```
=> Add distinction between global & local flags in sensuctl usage

backend/apid/apid.go, backend/apid/graphql/mutations.go, backend/apid/routers/events.go, cli/client/event.go
Message bus was not being passed down to the events router, causing a panic when the controller attempted to publish the event.
Unable to resolve events.
I believe the bug was introduced prior to last release.
=> Fixup panic when resolving events

CHANGELOG.md, cli/commands/role/create.go, cli/commands/role/create_test.go, testing/e2e/rbac_test.go
Signed-off-by: Mercedes Coyle <mercedes@sensu.io>
Adds type, create, read, update, delete flags to role creation in
sensuctl.
Closes #1196 
Added a note to the **Changed** section.
Nope.
This command is laid out slightly differently than our other commands, in add_rule.go takes the place of interactive.go in our other commands. I'm thinking that add_rule should really be a subcommand, and we create an interactive.go for create/update etc. Thoughts? This is also something we can refactor later if we choose to.
=> Support adding rules to role on creation via cli.

cli/cmd/start.go
Removes the short description from the usage template.
Fixes duplicate description in the help text.
It's really minor and doesn't affect usage, so I didn't add one.
Nope!
Nope!
=> Remove short description

.travis.yml, Makefile, build.sh
Only builds version-bin once in the first-pass of the Makefile.
We need version-bin in the first-pass of the Makefile but it was being built in the second-pass.
Nope!
Nope!
Nope!
=> Build version-bin in Makefile first-pass

build.sh
Builds version-bin in build.sh after dep installation.
We're trying to use version-bin before it's built.
Nope!
Nope!
Nope!
=> Build version-bin in build.sh after dep installation

Makefile, build.sh
Prepends GOOS and GOARCH with the host's values to `go generate` to build the webui.
Using GOOS / GOARCH values with `go generate` that do not match the host's values will not work.
Nope!
Nope!
Nope!
=> Run go generate using host's GOOS & GOARCH

CHANGELOG.md, Dockerfile.packaging, Makefile
It fixes the build process when manually running it. Node 8.x is now required by our dashboard and the `build_dashboard` command does not exist in `build.sh`.
So we can manually build the package if required (i.e., load testing).
Added!
Nope!
Nope!
=> Fix the manual packaging process

testing/testutil/util.go
The previous port allocation strategy could lead to collisions
in rare circumstances.
Closes #1237
EDIT: Also closes https://github.com/sensu/sensu-go/issues/791
=> Use each port only once during e2e tests.

build-gcs-release.sh, build.sh
Pass the `SENSU_BUILD_ITERATION` environment variable into the packaging docker container. Remove `build_dashboard` from `build-gcs-release.sh`.
The packaging docker container needs access to the build iteration env var.
`build_dashboard` is no longer a valid `build.sh` command. The dashboard is built with the backend now.
Nope!
Nope!
Nope!
=> Nightly build fixes

build.sh
Disables GCS binary releases for nightly builds.
The `build-gcs-release.sh` script will need to be refactored to support nightly builds.
Nope!
Nope!
Nope!
=> Avoid building nightly binaries for now

CHANGELOG.md, backend/pipelined/handle.go
It ensures the event is properly displayed in logs when it's being handled.
Closes https://github.com/sensu/sensu-go/issues/1245.
Added!
Nope!
Nope!
=> Properly log the event being handled in pipelined

CHANGELOG.md, cli/commands/check/execute.go
Signed-off-by: Mercedes Coyle <mercedes@sensu.io>
Removes the -c (check) flag from the execute command.
Check name is already taken as the first arg to the command, so this
additional flag is redundant and a little confusing as it is marked
required. Removing it in favor of passing check name as the first arg
fits with the conventions of our other commands.
Added note under changed.
Nope!
Nope!
=> Remove -c check flag

build.sh
Reverts a change to build.sh that was breaking the deploy step. Removes the `node_modules` directory before running `yarn install` to simulate a cleanroom environment between builds.
Deploy stage was broken due to a change in https://github.com/sensu/sensu-go/commit/b7dbfdf8a9d4aead3ddf99d92012a3b5e0178f88.
We were running into another issue during the during the deploy stage that was failing due to files already existing:
```
error An unexpected error occurred: "EACCES: permission denied, unlink '/home/travis/gopath/src/github.com/sensu/sensu-go/dashboard/node_modules/.bin/acorn'".
```
Nope!
Nope!
Nope!
=> Revert build.sh docker changes from b7dbfdf8; rm node_modules in build.sh

backend/monitor/monitor.go
The deadlock only occurs under load; in testing, it took around
5500 agent sessions to expose the problem.
On reset, the monitor acquires a mutex and then performs a channel
send. However, if another select case in the monitor is trying to
acquire the mutex, then the channel send will never occur.
Adding a buffer to the resetChan fixes the problem.
Closes #1264
=> Fix a deadlock in the monitor.

CHANGELOG.md, testing/e2e/agent_reconnection_test.go, testing/e2e/keepalive_test.go, testing/e2e/process_test.go, testing/e2e/rbac_test.go
Terminate processes gracefully in e2e tests, allowing ports to be reused.
Fixes #1228 
Yes:
- Terminate processes gracefully in e2e tests, allowing ports to be reused.
I need clarification on the hardest part: naming things. If there is a name or place for `terminate_helper` that would fit project conventions better, I'd love to hear about it.
I spent some time trying to find a way to gracefully terminate CLI processes on Windows -- sadly there is no supported way to do this in Windows.
=> Terminate processes gracefully in e2e tests

CHANGELOG.md, examples/checks/http_check.sh
I'm using this script in our proxy entities guide and it's currently outputting the entire HTML code of a page in the event output, so I simply moved the output to `/dev/null`.  git
Documentation!
Added!
Nope!
Nope!
=> http_check.sh hides its output

dashboard/src/pages/RootRedirect.js
When accessing `getAccessToken()`, we need to handle the potential server error in the case that we have a cached invalid refresh token.
This is currently a very naive solution that redirects to "/login" for any error case. We should revisit this we tackle more thorough error handling.
=> Prevent app from crashing with expired refresh token

dashboard/config/webpack.config.dev.js
Allow the dev build to continue, resulting in a normal browser reload, in the case that a lint error is detected.
This allows running WIP code without worrying about strict lint adherence enabling faster dev cycles.
Detected errors are still reported to the build process output, this change does not silence anything.
Production builds are not affected by this change, and still require passing lint at build-time.
=> Prevent dev build from halting on lint error

CHANGELOG.md, backend/authorization/authorization.go, backend/seeds/seeds.go, backend/seeds/seeds_test.go
Seed the sensu RBAC store with a user by the name "sensu" with global read-only permissions.
It's useful for customers to have a non-admin user when setting up sensu. It's a common enough use case to warrant creating one by default.
Yes.
I did need some clarification on the use of constants in RBAC related code. Ended up creating #1285 to track it.
Because the RBAC seed functionality was already in place, adding a second user (after the admin user) was straightforward.
=> Create default read-only user

CHANGELOG.md, agent/agent.go, agent/cmd/start.go, agent/statsd_server.go
Adds the `--statsd-event-handlers` flag to sensu-agent which configures the event handlers for statsd metrics.
Closes #1127.
Yas.
Nah.
Nah.
=> Provide a means of configuring event handlers for metrics

backend/apid/graphql/globalid/environments.go, backend/apid/graphql/globalid/environments_test.go
Have environment global match intended format.
Previously the environment's name was duplicated in the id. eg. `srn:environments:org:env:env`.
=> [GraphQL] Snip extra value from environment id

backend/apid/graphql/query.go, backend/apid/graphql/query_test.go, backend/apid/graphql/schema/mutations.go, backend/apid/graphql/schema/schema.gql.go, backend/apid/graphql/schema/schema.graphql
Add an event field to Query type so that a consumer can retrieve an event given an entity and check.  
Directly unblocks development of #1130 & #835 
unlikely.
=> [GraphQL] Add root field to query events

CHANGELOG.md, agent/statsd_server.go, agent/statsd_server_test.go
Adds a unit test and integration test surrounding the sensu-agent's statsd server and udp port. Refactors some reusable code into "fixture" functions.
Testing is 🔑 
Yas.
Nah.
Part of the test is blocked by #1247 but a `TODO` has been created.
=> [Agent statsd] Additional unit and integration tests

backend/apid/graphql/check.go, backend/apid/graphql/check_test.go, backend/apid/graphql/environment.go, backend/apid/graphql/environment_test.go, backend/apid/graphql/schema/check.gql.go, backend/apid/graphql/schema/check.graphql, backend/apid/graphql/schema/environment.gql.go, backend/apid/graphql/schema/environment.graphql, backend/apid/graphql/util.go
Expose an environment's check history for use in web UI's history graph. (And more! maybe.)
Unblocks #1132 
Same "complication" as mentioned in #1296.
> Mocking each controller is cumbersome. Took a peak at https://github.com/vektra/mockery to possibly go:generate mocks for the controllers.
=> [GraphQL] Expose an environment's check history

backend/apid/graphql/entity.go, backend/apid/graphql/entity_test.go, backend/apid/graphql/schema/entity.gql.go, backend/apid/graphql/schema/entity.graphql, util/strings/strings.go, util/strings/strings_test.go
Expose related entities using simple heuristic
Unblocks #1133 
Mocking each controller is cumbersome. Took a peak at https://github.com/vektra/mockery to possibly go:generate mocks for the controllers.
=> [GraphQL] Expose related entities using simple heuristic

CHANGELOG.md, agent/agent.go, agent/cmd/start.go
Add the `--statsd-disable` flag to sensu-agent which configures the statsd listener. The listener is enabled by default.
Closes #1128.
Yas.
Nah.
Nah.
=> Option to configure statsd listener with statsd-disable flag

CHANGELOG.md, rpc/extension/LICENSE, rpc/extension/doc.go, rpc/extension/example/LICENSE, rpc/extension/example/main.go, rpc/extension/extension.go, rpc/extension/server.go
The extension package contains convenience types and functions for
writing third-party Sensu extensions in Go. An example is also provided.
Closes #341 
Yes
=> Add extension package and extension example.

dashboard/src/utils/authentication/index.js, dashboard/src/utils/authentication/tokens.js
Any code that access auth tokens immediately at app load will receive the tokens from localstorage.
This allows components to access stored tokens without having to call the `getAccessToken` function, avoiding the automatic token refresh behavior.
=> [Web UI] Retrieve any stored tokens during the initial load

CHANGELOG.md, backend/agentd/benchmark_test.go, backend/agentd/session.go, types/check.go
```
This commit significantly reduces the amount of time spent
marshaling json in agentd. It replaces stdlib encoding/json with
json-iterator, and it avoids using dynamic.Marshal when there are no
dynamic attributes to be marshaled.
Profiling performed during load testing shows that json encoding
and decoding can comprise a substantial portion of time spent in
the backend. This is most evident when there are many thousands of
checks being executed per second.
The benchmark results below are for a single iteration of subPump.
subPump is part of agentd; it receives messages on a channel, and
forwards them along to the agent. Profiling shows that the majority
of time in subPump is spent dealing with json rendering. For every
check that an agent executes, it must process a single subPump …
```
=> Optimize check marshaling and add a benchmark for subPump

dashboard/src/apollo/client.js, dashboard/src/index.js
Avoid singleton instance and load-time side-effects from the `apollo/client.js` file by wrapping everything in a function.
=> [Web UI] Wrap apollo client initialization in function

backend/apid/graphql/check.go, backend/apid/graphql/check_test.go, backend/apid/graphql/schema/check.gql.go, backend/apid/graphql/schema/check.graphql
Change the return type of the check type's `issued` field.
Unblocks #1130
=> [GraphQL] Change return type of issued field

CHANGELOG.md, agent/statsd_server.go
When creating a new statsd server, check if the config provided has a flush interval of 0. If so, use the default statsd flush interval.
Closes #1345.
Yas.
Nah.
Nah.
=> Default statsd flush interval

agent/cmd/start.go
Statsd metrics port is an int, not string.
Flag should accept an integer value.
Nah, updating documentation.
Nah.
Nah.
=> Fix agent flag value

CHANGELOG.md, backend/apid/actions/filters.go, cli/commands/filter/help.go, cli/commands/filter/subcommands/LICENSE, cli/commands/filter/subcommands/remove_when.go, cli/commands/filter/subcommands/remove_when_test.go, cli/commands/filter/subcommands/set_when.go, cli/commands/filter/subcommands/set_when_test.go, types/filter.go
It adds the `remove-when` and `set-when` subcommands to sensuctl filter command.
Closes https://github.com/sensu/sensu-go/issues/1121
Added!
Non!
Non!
=> Add filters time windows management in sensuctl

packaging/services/sensu-agent/sysvinit/etc/init.d/sensu-agent, packaging/services/sensu-backend/sysvinit/etc/init.d/sensu-backend
Centos 6, perhaps others, using chkconfig to enable services fail if
missing the "chkconfig" line or LSB in the head comment to set runlevels and
priority. The longer LSB style form is also supported by Ubuntu 14.04 init, in theory
Resolves the following error on centos 6:
STDERR: service sensu-backend does not support chkconfig
ref:
- https://linux.die.net/man/8/chkconfig (heading: Runlevel Files)
Signed-off-by: Sean Escriva <sean.escriva@gmail.com>
Updates the sysv init scripts 
Testing for chef cookbook development on centos 6 revealed this issue and it seemed possibly better to fix upstream instead of patching the initscripts with the cookbook.
Maybe? I didn't want to presume.
Don't think so.
Nope.
=> Make sensu-{backend,agent} sysvinit compat for centos 6 family

build.sh
Temporary fix for https://github.com/golang/lint/issues/397.
Fix CI.
Added!
Non!
Non!
=> Workaround for golint 404 issue

build.sh
Revert the workaround introduced in https://github.com/sensu/sensu-go/pull/1365.
The golint error has been resolved: https://github.com/golang/lint/issues/397#issuecomment-383995911
Non!
Non!
Non!
=> Revert golint workaround

dashboard/src/components/views/EnvironmentView/ChecksContent.js, dashboard/src/components/views/EnvironmentView/EventsContent.js
This implements a temporary workaround until we commit to a full solution for #1328
Closes #1359 
Nah.
Nah.
The button implementation on the entities page is intentionally oversimplified. This page will be soon overhauled with new styles, doing anything polished here is a waste at this point.
=> [Web UI] Disable query polling on checks and events pages

backend/queue/queue_test.go
Clean up the etcd client in queue tests.
closes #1280 
See #1280 for context and info.
Nope, this change is test-only.
Do we want to take the time to report this bug to etcd? Doing so would require making a minimal set of code to reproduce the issue.
There were certainly complications in reproducing this bug, but the change is minor and straightforward.
=> Prevent etcd client goroutine leaks in queue tests

backend/apid/graphql/query.go, backend/apid/graphql/query_test.go
Fix bug where environment could not be found.
Allow web UI (or any consumer of GraphQL service) to fetch environments.
🤔 this might be where a smattering of APId integration tests may be helpful useful.
=> [GraphQL] Fixup bug where env could not found

CHANGELOG.md, agent/check_handler.go, agent/hook.go, agent/hook_test.go, command/command.go
A fix to allow checks and hooks to escape zombie processes (likely created by commands with `sudo`) that have timed out.
Closes #1194.
Yas.
Nah.
Yes, zombies created with `sudo` are inevitable. We need to document our recommendation to avoid command execution's that require `sudo`.
=> Allow checks and hooks to escape zombie processes that have timed out

CHANGELOG.md, build.sh
Install all dependencies with `dep ensure` in build.sh.
We need to run `dep ensure` to install new dependencies in build and ci.
Yas.
Nah.
Nah.
=> Install golang dependencies in build.sh

CHANGELOG.md, Gopkg.lock, Gopkg.toml, build.ps1, build.sh, handlers/influx-db/LICENSE, handlers/influx-db/main.go, handlers/influx-db/main_test.go
Adds an influx-db event handler.
Allows users to configure an event handler which will write sensu metrics to an influx-db of their choice!
Yas.
Nah.
Nah.
=> InfluxDB Handler

.appveyor.yml, .travis.yml, README.md, build.ps1, build.sh
It makes sure we are using a specific dep version to build our PRs.
Previously we were using master of dep.
NEIN
NEIN
There probably will be tbh
=> Pin dep version to 4.1.

build.ps1
Removes iteration.txt from build.ps1.
Closes #1399.
Nah.
Nah.
Yas. Appveyor failures are difficult to repro, and fixing one issue usually uncovers another.
=> Remove reference to iteration.txt as it doesn't exist anymore

backend/apid/graphql/asset.go, backend/apid/graphql/check.go, backend/apid/graphql/entity.go, backend/apid/graphql/environment.go, backend/apid/graphql/event.go, backend/apid/graphql/handler.go, backend/apid/graphql/hook.go, backend/apid/graphql/mutations.go, backend/apid/graphql/organization.go, backend/apid/graphql/query.go, backend/apid/graphql/rbac.go, backend/apid/graphql/schema/asset.gql.go, backend/apid/graphql/schema/check.gql.go, backend/apid/graphql/schema/entity.gql.go, backend/apid/graphql/schema/environment.gql.go, backend/apid/graphql/schema/event.gql.go, backend/apid/graphql/schema/handler.gql.go, backend/apid/graphql/schema/hook.gql.go, backend/apid/graphql/schema/mutations.gql.go, backend/apid/graphql/schema/mutator.gql.go, backend/apid/graphql/schema/organization.gql.go, backend/apid/graphql/schema/rbac.gql.go, backend/apid/graphql/schema/schema.gql.go, backend/apid/graphql/user.go, graphql/generator/object.go, graphql/generator/types.go
The `ID` scalar type represents a unique identifier, often used to
refetch an object or as key for a cache. The ID type appears in a JSON
response as a String; however, it is not intended to be human-readable.
When expected as an input type, any string (such as ) or integer
(such as `4`) input value will be accepted as an ID.
As such, when resolving a field we can safely assume the value
encountered will always be a string value.
Spec: http://facebook.github.io/graphql/October2016/#sec-ID
Unblocks #837 
Unlikely
nada 
nada
=> [GraphQL] Use string to represent ID scalar

CHANGELOG.md, backend/agentd/session.go, backend/messaging/wizard_bus.go, backend/messaging/wizard_bus_test.go, backend/messaging/wizard_topic.go
Fixes an issue in which agents re-connecting may experience missed or skipped check requests.
Closes #1407 
Added under `Fixed`.
Nope!
This was a really gnarly bug that took the debugging efforts of myself, @cyphus, and @echlebek to deduce.
=> Fix bug in topic done chan closed on subscribe

.appveyor.yml, build.ps1
Updates build.ps1 to use the version tool like we're currently doing in build.sh.
Closes #1409.
Consistency between our CI platforms.
Nope!
Nope!
Nope!
=> Update build.ps1 to use version tool

types/check.go, types/check_test.go
Adds some basic validation for flap thresholds.
Closes #1235 (working as intended)
No
=> Add validation for flap thresholds.

CHANGELOG.md, agent/entity.go
Signed-off-by: Mercedes Coyle <mercedes@sensu.io>
Adds a timestamp to `LastSeen` when an entity is created for an event on the agent.
Closes #1377.
Added a note in bug fixes.
Nope!
There was some discussion as to what the source of truth should be for determining an entity's last seen time. This fix does not update the last_seen time in the store, so the entity may have multiple last_seen times depending on where it is viewed. I've opened #1434 to address that.
=> Ensure event entity has a last_seen time.

CHANGELOG.md, cli/commands/check/create.go, cli/commands/check/help.go, cli/commands/check/info.go, cli/commands/check/interactive.go, cli/commands/check/list.go, cli/commands/check/subcommands/remove_metric_format.go, cli/commands/check/subcommands/remove_metric_format_test.go, cli/commands/check/subcommands/remove_metric_handlers.go, cli/commands/check/subcommands/remove_metric_handlers_test.go, cli/commands/check/subcommands/set_metric_format.go, cli/commands/check/subcommands/set_metric_format_test.go, cli/commands/check/subcommands/set_metric_handlers.go, cli/commands/check/subcommands/set_metric_handlers_test.go, types/check.go
Adds CLI support and CRUD operations for the `metric_format` and `metric_handlers` fields of a check in `sensuctl`. Check commands have been updated and check subcommands have been created.
Closes #1382.
Yas.
Nah.
Nah.
=> Add CLI support for metric_format and metric_handlers

CHANGELOG.md, cli/commands/commands.go
This commit removes the namespace flags (--organization and
--environment) from the global flags, and instead uses local flags
to implement those features.
This was done so that we could avoid having these flags for the
create command, which does not use them and should not.
Closes #1233 
It was difficult to decide how to do this. I would have preferred to leave the namespace and organization flags as global flags, but there was no way to do that and also drop those flags from the create sub-command. I settled on adding them as local flags to every command with a for loop.
=> Don't add namespace flags for create command.

CHANGELOG.md, testing/e2e/metric_extraction_test.go
It adds an e2e test for metric extraction functionality.
Closes https://github.com/sensu/sensu-go/issues/1389
Added!
Non!
Non!
=> Add e2e test for metric extraction

CHANGELOG.md, cli/commands/silenced/info.go, cli/commands/silenced/interactive.go, cli/commands/silenced/list.go, cli/commands/timeutil/time.go
This commit adds a 'Begin' time to silenced entries so that users
will be able to recognize which entries have already begun and
which haven't. Also, expiry time is computed as an offset from
begin, if the silenced entry hasn't begun yet.
The commit also improves the ergonomics of using the interactive
mode for creating silenced entries, by defaulting the silenced
begin time to 'now'. (Previously, the default was 0, which was
both confusing, and also interpreted as the start of the unix
epoch.)
Closes #1176
=> Improve display and ergonomics of silenced entries.

README.md
Adds install instructions for protoc-gen-go.
The current instructions are missing this step. It is necessary to be able to run `go generate` on our packages with proto files.
Nope!
Nope!
Nope!
=> Add install instructions for protoc-gen-go to readme

dashboard/src/components/partials/EventDetailsContainer/EventDetailsContent.js, dashboard/src/components/partials/EventDetailsContainer/EventDetailsSummary.js
As 'Configuration' was both wrong and confusing; rename card to 'Summary'. 
From discussion with @portertech on Friday.
unlikely
`undefined`
`undefined`
=> [Web UI] Rename 'Configuration' card to 'Summary' 

version/cmd/version/version.go
Regex was failing due to `git describe` output ending with a newline.
=> Trim git describe output

CHANGELOG.md, agent/transformers/influx_db_test.go, agent/transformers/nagios_test.go, agent/transformers/opentsdb.go, agent/transformers/opentsdb_test.go
Fixed a small bug in the opentsdb transformer so that it trims trailing whitespace characters.
Check output containing one or multiple metrics in opentsdb metric format can also contain trailing whitespace or newline characters. We should not attempt to parse the newline character for a metric, rather we should ignore it.
Yas.
Nah.
Nah.
=> Trim whitespace from check output in opentsdb transformer

CHANGELOG.md, backend/pipelined/handle.go, util/logging/logging.go
It adds some useful log entries, using the `INFO` level, around the Sensu pipeline, so users can more easily understand the progress of their events through the pipeline.
During our QA party, Eric and I tracked what we thought was a bug during few hours, because we couldn't see events from statsd UDP socket. Turns out we simply forgot to configure the `--statsd-event-handlers` flag on the agent and since metrics are not stored in the store and no log entries for this event were added, it took us a long time to realize that.
Added!
I feel like the messages I added could be improved, open to suggestions!
Non!
=> Add logging around event pipeline

CHANGELOG.md, agent/entity.go, agent/event.go, agent/transformers/nagios.go, backend/agentd/entity.go, backend/apid/actions/events.go, backend/apid/graphql/globalid/events.go, backend/apid/graphql/mutations.go, backend/eventd/eventd.go, backend/eventd/flapping.go, backend/eventd/silenced.go, backend/keepalived/deregisterer.go, backend/keepalived/keepalived.go, backend/pipelined/mutate.go, handlers/influx-db/main.go, handlers/slack/main.go, rpc/extension/example/main.go, types/event.go, util/logging/logging.go
Never assume the presence of a check or metrics in an event (unless you're dealing with the store or cli). Adds nil checks for `event.HasCheck()` and `event.HasMetrics()` before invoking either field.
Closes #1484.
Yas. I moved an unreleased changelog entry into the appropriate place too!
Nah.
Nah.
=> Audit event polymorphism

CHANGELOG.md, types/handler.go, types/handler_test.go, types/validators.go, types/validators_test.go
This commit fixes several issues around handler validation.
* Add grpc as a recognized handler type.
* Remove transport as a recognized handler type.
* Ensure tcp and udp handlers have valid sockets.
Closes #1452
=> Fix handler validation.

CHANGELOG.md, cli/commands/check/create.go, cli/commands/check/help.go, cli/commands/check/interactive.go, cli/commands/check/subcommands/set_round_robin.go, cli/commands/check/subcommands/set_round_robin_test.go
This commit adds the ability to set and update round-robin
scheduling in sensuctl.
Closes #1465
=> Add round-robin scheduling to sensuctl.

CHANGELOG.md, agent/agent.go, agent/statsd_server_test.go
Sensu-agent logs an error if the statsd listener is unable to start due to an invalid address or is stopped due to any other error.
Closes #1473.
Yas.
Nah.
Found https://github.com/sensu/sensu-go/issues/1498 and working on it next.
=> Log statsd errors

.circleci/config.yaml
Adds basic circleci configuration to get project setup on circleci.
Setting up a paid account and need to invite team members. This satisfies their project setup checklist.
=> Add circleci configuration

CHANGELOG.md, types/environment.go
This commit fixes a bug where an incorrect path was specified in
the URIPath method for types.Environment, causing the sensuctl
create command to fail.
Closes #1521 
I have filed #1525 as a follow-up issue.
=> Fix a bug where URIPath for Environment was wrong.

dashboard/package.json
Ensure all `.js` files in the `dashboard` dir are targeted and formatted by the `prettier` script.
This needs to be the same as the files targeted by `eslint`.
For some reason the glob doesn't match correctly unless it is quoted.
nah
nope
naw
=> [Web UI] Fix prettier package script

CHANGELOG.md, cli/commands/silenced/interactive.go, cli/commands/timeutil/time.go, cli/commands/timeutil/time_test.go, subdue.json, testing/e2e/check_subdue_test.go
It adds support for additional time format. So we now support these formats:
- 12-hour kitchen (zone): `3:04PM UTC`
- 24-hour kitchen (zone & offset): `15:04 UTC` or `07:04 -08:00`
- Sensu alpha legacy format (zone): `May 10 2018 3:04PM UTC`
- RFC3339 (offset): `2018-05-10T15:04:00Z`
- RFC3339 with space delimiters (offset): `2018-05-10 07:04:00 -08:00` 
Closes https://github.com/sensu/sensu-go/issues/1448
Added!
Nope!
The `time` pkg is hard.
=> Add support for additional time formats and better handle timezones

build.sh
nightly deploy was breaking due to incorrect version reporting. The `sensu-go-build` docker container was reporting its build type as `dev`.
Fixed by passing the `CI` environment variable into `sensu-go-build` so that it can report the correct build type of `nightly`
=> Pass CI env var to sensu-go-build docker image

dashboard/package.json, dashboard/src/apollo/authLink.js, dashboard/src/apollo/resolvers/auth.js, dashboard/src/errors/FetchError.js, dashboard/src/utils/authAPI.js, dashboard/src/utils/promise.js, dashboard/src/utils/promise.test.js, dashboard/yarn.lock
This prevents the app from crashing, and instead kicks the user back to the login screen when token refresh fails.
This change also disallows multiple parallel requests to the auth API with the same data. If a token refresh request is fired while an identical one is in-flight, the `refreshTokens` function will resolve the current pending fetch for both requests.
In the event that an auth token refresh fails while processing a mutation or query, abort the operation with the failed token request error. There is no sense in continuing to attempt the operation if authentication has failed. This prevents a cascade of additional failed attempts with the API.
When a token refresh is required, there are likely to be multiple pending queries that have just been fired. Each of these will trigger an …
=> [Web UI] Prevent cascading errors when token refresh fails

CHANGELOG.md, types/wrapper.go, types/wrapper_test.go
This commit disallows unknown fields in types that do not support
extended attributes, when the types are created with the
`sensuctl create` command. Types that do support extended
attributes will function as before when created with this command.
Closes #1480
=> Don't allow unknown fields when creating resources.

Makefile
I suspect that nightly builds are failing because the packaging phase is
being run with a different user. By wiping /all/ artifacts before
continuing we ensure that the next step never writes / deletes a file
they do not have access to.
Docker images for nightlies fail to deploy.
maybe?
nada
Using Docker for /all the things/ would probably avoid this problem in the first place.
=> Wipe all artifacts when clean task is invoked

CHANGELOG.md, types/typemap.go, types/typemap.tmpl, types/typemap_test.go
This commit fixes a bug where the same pointer is returned from
ResolveResource every time. This causes havoc with functions that
expect the value coming from ResolveResource to be a new resource
every time.
The effect of this was that unmarshalling tended to simply not work
properly.
This commit uses the reflect package to copy the type from the
type map, providing a new Resource with every invocation.
Closes #1565
WIP, I'll add a test and a changelog entry to this PR on monday.
=> Fix an aliasing bug in ResolveResource.

CHANGELOG.md, util/logging/logging.go
Provides additional context to metric event logs included # of metrics and first metric.
Metric event logs are vague.
Yas.
Nah.
Nah.
=> Make metric event logs more specific with additional fields

dashboard/config/webpack.config.js, dashboard/package.json, dashboard/src/.eslintrc, dashboard/src/buildInfo.macro.js, dashboard/src/components/ErrorRoot.js, dashboard/src/exceptionHandler.js, dashboard/src/renderError.js, dashboard/yarn.lock
Display caught errors in a modal showing error stack track and other details. The error modal contents are anonymous, and can be copied for to share as an error report.
This will be a great benefit to early testers enabling them to accurately report errors.
Closes #1360 
nah
nope
no
=> [Web UI]  Create error display modal

.appveyor.yml, .travis.yml, CHANGELOG.md
Removes the linux/386 windows/386 e2e jobs from CI.
We are not planning on supporting Sensu Backend on linux/386 or windows/386. As a result, the e2e tests for those platforms do not provide us any value.
Yes.
Nope!
Nope!
=> Remove linux/386 & windows/386 CI jobs

dashboard/src/components/ErrorRoot.js
Tiny bugfix
`componentStack` is a string if it exists, not a `ReactError` instance.
no
no
no
=> [Web UI] Fix bug in error modal

dashboard/src/components/AppRoot.js, dashboard/src/components/util/DefaultRedirect.js, dashboard/src/components/views/SignInView.js
The app currently has a mix of "login" and "sign out". Replace references to "login" with "sign in"
Research shows that "sign in" and "sign out" are a good choice. (https://ux.stackexchange.com/questions/1080/using-sign-in-vs-using-log-in#answer-1084)
Because consistency.
no
no
no
=> [Web UI] Standardize "sign in" and "sign out" copy

dashboard/src/components/AppWrapper.js, dashboard/src/components/util/Query.js, dashboard/src/components/views/EnvironmentView/ChecksContent.js, dashboard/src/components/views/EnvironmentView/EntitiesContent.js, dashboard/src/components/views/EnvironmentView/EntityDetailsContent.js, dashboard/src/components/views/EnvironmentView/EventDetailsContent.js, dashboard/src/components/views/EnvironmentView/EventsContent.js, dashboard/src/errors/QueryAbortedError.js
This component enhances the original `<Query>` component from `react-apollo` giving us a few extra features. OOB it is compatible with the original component interface.
This new component gives us an `onError` callback for handling errors within the original request continuation. By default `<Query>` will now globally reject errors not handled within `onError`, fixing the issue of `<Query>` silencing errors.
A new `QueryAbortedError` class allows us to "abort" a GraphQL query request without triggering a failure state. The aborted status is returned to the consumer as an `aborted` boolean among the query render callback props. Once a query has been aborted, it can be be manually restarted with the `refetch` render prop.
no
**Why not use `apollo-link-error` to handle errors as part of the …
=> [Web UI] Create wrapped <Query> component

dashboard/.eslintrc.yml, dashboard/src/apollo/authLink.js, dashboard/src/apollo/client.js, dashboard/src/apollo/schema/combinedTypes.macro.js, dashboard/src/components/RelativeDate/RelativeDate.js, dashboard/src/components/partials/EventDetailsContainer/EventDetailsDeleteAction.js, dashboard/src/components/partials/EventDetailsContainer/EventDetailsResolveAction.js, dashboard/src/components/views/EnvironmentView/ChecksContent.js, dashboard/src/components/views/EnvironmentView/EntitiesContent.js, dashboard/src/components/views/EnvironmentView/EntityDetailsContent.js, dashboard/src/components/views/EnvironmentView/EventsContent.js, dashboard/src/utils/checkStatus.js, dashboard/src/utils/consecutivePairs.js, dashboard/src/utils/dispatcher.js
Add rule to disallow omission of curly braces.
> JavaScript allows the omission of curly braces when a block contains
only one statement. However, it is considered by many to be best
practice to never omit curly braces around blocks, even when they are
optional, because it can lead to bugs and reduces code clarity.
https://eslint.org/docs/rules/curly
Also, omission of curly braces makes it [more difficult to set breakpoints](https://github.com/sensu/sensu-go/pull/1606#discussion_r191593693).
I'd always rather the linter be the source of pedantry and not PR reviews.
`null`
`undefined`
`0`
=> [Web UI] Add ESLint rule 'curly'

CHANGELOG.md, Gopkg.lock, Gopkg.toml, vendor/github.com/sensu/govaluate/evaluationStage.go
=> Upgrade govaluate to release 3.1.0.

build.sh
Passes the `SENSU_BUILD_ITERATION` environment variable into the sensu-go-build docker container when deploying packages.
Sensu nightly builds were broken on Travis because the version command could not determine the build iteration.
Not this time.
I'm good.
I noticed that the package_cloud gem was being installed on the host, which is unnecessary because it's only installed/used inside the sensu-go-build docker container. Builds should be a few seconds faster now too.
=> Pass SENSU_BUILD_ITERATION to packaging container

dashboard/src/apollo/authLink.js, dashboard/src/apollo/client.js, dashboard/src/apollo/resolvers/auth.js, dashboard/src/apollo/schema/client.graphql, dashboard/src/apollo/schema/combined.graphql, dashboard/src/components/AppRoot.js, dashboard/src/components/partials/AuthInvalidDialog.js, dashboard/src/components/util/AuthInvalidRoute.js
In the event that automatic session refresh fails, show the user a message instead of redirecting directly to the sign in page.
This provides a nicer experience than forcefully redirecting to the sign-in page and gives us a platform for further enhancements such as a login form modal.
no
nah
naw
=> [Web UI] Display a modal when authentication fails

CHANGELOG.md, agent/agent_test.go, system/system.go, system/system_test.go
Use a default hostname if one cannot be retrieved from the system.
Closes #1636 
Yas.
Nah.
Nah.
=> Use default hostname

CHANGELOG.md, cli/commands/create/create.go
The create command should print a warning if --environment or
--organization are specified, but should not print a warning if the
sensuctl client is configured to use a non-default namespace.
The intent of the warning is to let people know that namespace
flags are not consulted when creating resources with the create
command.
Closes #1651
=> Fix a spurious warning in sensuctl create.

dashboard/config/webpack.config.js, dashboard/src/components/CheckList.js, dashboard/src/components/EventsContainer.js, dashboard/src/components/Preferences.js, dashboard/src/components/partials/EntityDetailsContainer/EntityDetailsDeleteAction.js, dashboard/src/store/createStore.js, dashboard/yarn.lock
Reduce lodash's footprint on the bundle by no longer using `html-webpack-plugin`'s default loader (see: [this comment](https://github.com/jantimon/html-webpack-plugin/issues/681#issuecomment-351471890) for context) and by removing needless instances from src.
Reduces uncompressed bundle size by ~500KBs.
**previously**
**after changes**
unlikely.
`null`
`null`
=> [Web UI] Reduce lodash's footprint on the bundle

dashboard/src/apollo/resolvers/auth.js
Prevent private data from leaking between auth sessions by clearing apollo client cache when logging out.
Closes #1301
no
naw
nope
=> [Web UI] Clear apollo state cache on logout

CHANGELOG.md, cli/client/environment.go, cli/client/organization.go, cli/commands/configure/configure.go
The commit modifies the behaviour of sensuctl configure, so that
if a user attempts to configure an organization or environment that
does not exist, an error will be returned.
Previously, sensuctl would allow an organization or environment
to be configured even if they did not exist.
Closes #1515
=> Return an error from configure on invalid env/org.

CHANGELOG.md, cli/commands/environment/create.go
In testing, it was discovered that the --org parameter is actually
not necessary for the environment create command. Users can specify
the --organization parameter instead.
This commit removes the parameter.
Closes #1514
=> Remove --org parameter from environment command.

testing/config/resources.json, testing/config/staging-agent-0.yml.example
Moves test organization before environment.
In order for `sensuctl create -f` to work for the test resources, the organization must be created before called upon by the environment.
Nah.
Nah.
Nah.
We good.
=> Organization must be created before environment

CHANGELOG.md, agent/assetmanager/asset.go, backend/pipelined/filter.go, backend/schedulerd/proxy_check.go, util/eval/predicate.go, util/eval/predicate_test.go
Add two error types to the eval package, which allows users of the
package to distinguish between syntax errors and type errors.
In the asset manager, if errors are not SyntaxErrors or TypeErrors,
then only issue a debug log entry. Otherwise issue an error log
entry. Do the same thing for proxy check entities.
Closes #1512
=> Add nuance to govaluate error handling.

.appveyor.yml, CHANGELOG.md, build.ps1
It updates the AppVeyor API token, used by the `wait_for_appveyor_jobs` script.
Fixes https://github.com/sensu/sensu-go/issues/1496.
Added!
Nope!
Nope!
Not required!
=> Renew AppVeyor API token

agent/agent.go
Added Agent Transport "sending message" debug log event.
Could be enough to close https://github.com/sensu/sensu-go/issues/1725
For example:
```
{"component":"agent","level":"debug","message":"{\"timestamp\":1529627830,\"entity\":{\"class\":\"agent\",\"deregister\":false,\"deregistration
\":{},\"environment\":\"default\",\"id\":\"portertech.local\",\"keepalive_timeout\":120,\"last_seen\":1529627801,\"organization\":\"default\",\
"redact\":[\"password\",\"passwd\",\"pass\",\"api_key\",\"api_token\",\"access_key\",\"secret_key\",\"private_key\",\"secret\"],\"subscriptions
\":[\"workstation\"],\"system\":{\"hostname\":\"portertech.local\",\"os\":\"darwin\",\"platform\":\"darwin\",\"platform_version\":\"10.13.5\",\
"network\":{\"interfaces\":[{\"name\":\"lo0\",\"addresses\":[\"127.0.0.1/8\",\" …
```
=> Agent Transport debug log event

backend/monitor/monitors.go
Don't need to check that the error is not nil before returning it.
Nikki helpfully pointed out an error handling simplification, so I fixed it!
=> Return result of error check immediately

CHANGELOG.md, types/check.go, types/check_test.go, types/dynamic/encoding.go, types/dynamic/encoding_test.go
This commit fixes a bug in the dynamic marshaler that could lead to JSON objects being written out with duplicate object names. Through a series of unfortunate events, this was causing checks created with `sensuctl create` (vs `sensuctl check create`) to never fail.
This is a critical bug and after merging this PR we should do a release.
This took a while to debug. If a user created a check with the `Check` type instead of `CheckConfig`, the `Status` field of a Check would become a custom attribute, as the message would be unmarshaled into a `CheckConfig` on the other side.
This resulted in the extended attributes being blindly copied over to the Check when the agent created a Check from the CheckConfig, and shadowing the Status of the Check. As a result, the Check could never fail. …
=> Fix a bug where checks created with `sensuctl create` would never fail

cli/client/check.go
It adds support for `--environment` & `--organization` flags in `sensuctl check execute` subcommand, and otherwise use the configured env & org in the user profile.
This is a quick fix, until we revisit https://github.com/sensu/sensu-go/issues/1008.
Closes https://github.com/sensu/sensu-go/issues/1646.
Added!
Nope!
Nope!
Nope!
=> Support check execution via sensuctl with RBAC

backend/schedulerd/check_watcher.go
I'm hoping this will resolve the panic that occurs in the check
watcher integration test.
Somewhat speculative change here, as I'm not sure if the channel closing is actually causing this problem. However, I can't see another reason that there would be a nil dereference, and it's hard to reproduce, so I think this is a decent safety valve in any event.
Closes #1640
=> Restart the check watcher when the watch chan closes.

CHANGELOG.md, backend/ring/ring.go, backend/ring/ring_test.go
Next creates a goroutine that watches an etcd key for deletes.
After Next returns, the goroutine is supposed to be shut down, but
isn't, because the context it is using to determine cancellation is
the wrong one.
This commit refactors the watcher into a separate function, and
passes the correct context into it.
Closes #1746
=> Fix a goroutine leak in Ring.Next.

testing/config/resources.json, testing/config/staging-agent-0.yml.example, testing/config/staging-agent-1.yml.example, testing/config/staging-agent-2.yml.example, testing/config/staging-backend.yml.example
- Add `--debug` flag to sensu-backend config file for pprof
- Add 2 more round-robin checks (all entities subscribe to “round-robin”)
Addresses initial feedback from QA testing on the staging env resources.
Nah, it's kind of an ongoing process.
Nah.
Nah.
We good.
=> Address staging env feedback from QA testing

testing/config/resources.json
Ensures check robin checks are reporting under a specific proxy entity ID.
QA in staging
Nope!
Nope!
Nope!
Nope!
=> Set proxy entity IDs for round-robin checks

testing/config/resources.json
It adds a check in our staging environment to test the timeout execution mechanism.
QA in staging
Nope!
Nope!
Nope!
Nope!
=> Add check for testing execution timeout in staging

CHANGELOG.md, cli/commands/extension/list.go
It makes sure the name of extensions are properly displayed when showing all extensions.
Closes https://github.com/sensu/sensu-go/issues/1757
Added!
Nope!
Nope!
Nope!
=> Fix table formatting for 'sensuctl extension list'

CHANGELOG.md, build.ps1, build.sh
Upgrade gometalinter to v2.
I upgraded gometalinter in sensu-enterprise-go after submitting a patch for v1 and learning that it is no longer supported.
Added!
The `install_deps` function inside build.sh installs gocov and golint, but neither appear to be used anywhere else in the build system. Can they be removed?
The gometalinter command's invocation did not need to be changed, making this an easy PR.
No docs required!
=> Upgrade gometalinter to v2

CHANGELOG.md, build.sh
The commit forces the version command to run with GOOS=linux and
GOARCH=amd64. The version command was failing to run properly when
cross-compiling to Mac OS and Windows, since the environment
variables were causing the binary produced to not be executable
on Travis CI.
Closes #1759
=> Make sure GOOS=linux and GOARCH=amd64 for version cmd.

testing/config/resources.json, testing/tcphandler/LICENSE, testing/tcphandler/main.go
Addresses the following in the staging env resources:
- Configure splay & splay_coverage for “proxy-check” check
- We need a check that uses TTL
- TCP/UDP handlers
- Handler set
- Replace “handle-failing-only” filter with built-in “is_incident” filter
- Two checks are using the “silenced-check” name, so the first definition is overriden.
- Create a “silenced-cat” handler, using the “not_silenced” filter so silenced events are not handled, and modify the “silenced-check” to use that handler
- Remove “cat” handler from “feed-statsd” check. This handler is unnecessary, it is handled by the statsd-metrics-handler
- Extension handlers should be of type “grpc” not “pipe”
To cover more use cases and features in test.
Nah.
Nah.
Nah.
Manual staging …
=> Address staging env resources to include more use-cases

CHANGELOG.md, Dockerfile.rhel
Adds a dockerfile for RHEL (rhel-atomic).
We're going to start shipping RHEL containers for the RedHat container registry.
=> Add dockerfile for rhel-atomic

.circleci/config.yml
Separate out CircleCI build+test jobs
There are a number of reasons this is beneficial, but the main one is to get some data around which failures are build failures and which failures are test failures. Recent job failures on CircleCI have been mostly unit tests failures, but since it's one item, it's hard to tell that. This should help sort that out.
There are also a number of other benefits to splitting these two things out:
- Builds can be published, distinct from whether or not the tests pass; this can be useful for...
- ... If the unit tests fail on Circle, but work for the developer, the developer can pull down the artifacts from Circle and look at them
- As tests take longer to run, get quicker feedback about build status
- This setup also allows us to parallelize tests in the …
=> Issue 1730, part 1

CHANGELOG.md, Dockerfile, Dockerfile.rhel, build.sh, docker-compose.yaml
This changes how we tag nightly images to be "sensu/sensu:nightly" and removes the build type from all docker tags (no more 2.0.0-alpha-alpha.1). It also moves us over the sensu/sensu from sensu/sensu-go.
We'll be flipping to 2.0 being The Sensu eventually, and I'd rather start as early as possible with a small change like the docker image.
There will be a corresponding docs change.
=> Docker changes

CHANGELOG.md, cli/commands/helpers/flags.go
Fixes the help string for the --format sensuctl flag.
closes #1785
=> Fix format strings for --format help flag in sensuctl

agent/check_handler_internal_test.go
While this won't fix the master build, this will at least prevent a race condition with file flushing and give us a more accurate test against the check types in the test.
I don't really think this requires a changelog entry.
=> Check execution test failures

backend/apid/middlewares/environment_test.go, backend/authorization/authorization.go, backend/authorization/organizations.go, backend/authorization/roles.go, backend/seeds/seeds.go, backend/store/etcd/environment_store.go, backend/store/etcd/event_store.go, backend/store/etcd/event_store_test.go, backend/store/etcd/helpers.go, backend/store/etcd/helpers_test.go, cli/commands/asset/list.go, cli/commands/check/list.go, cli/commands/entity/list.go, cli/commands/environment/list.go, cli/commands/event/list.go, cli/commands/filter/list.go, cli/commands/handler/list.go, cli/commands/hook/list.go, cli/commands/mutator/list.go, cli/commands/silenced/list.go, types/environment.go, types/organization.go, types/rbac_test.go
First pass at implementing the change outlined in #1285 by defining necessary constants and using them throughout the code where seemed appropriate.
Constants are better than literals, there might be some risk of issues around text encoding.
Yes, added.
I am a first-time contributor to Sensu, and super open to any input on how I should engage as a contributor or if I need to sign a contributor agreement!
Nah, it was my first golang work, and I felt pretty comfy, just needed to find the right time and mood to lock it all together, had thought about this for weeks.
Would happily update documentation that folks should use these constants instead of literal splat, and would welcome input and guidance on that!
@mercul3s
=> Use constants instead of hardcoded strings for all rules, all orgs, all envs #1285

CHANGELOG.md, backend/apid/apid.go, backend/apid/routers/checks.go, backend/apid/routers/checks_test.go
Adds unit test coverage for check routes.
Closes #1802 
Yas.
Nah.
Nah.
We good.
=> Add unit test coverage for check routers

backend/backend.go, backend/cmd/start.go
It corrects some changes made during the Backend struct refactoring. More specifically:
- The `Etcd` & `Daemons` fields of `Backend` struct are now exported so they can be manipulated by the EE.
- The `backend/cmd` package uses the `Initialize` function passed to the package and not directly `backend.Initialize`. 
Required by https://github.com/sensu/sensu-enterprise-go/issues/39
Nope; these are bugfixes to an unreleased change.
Nope!
Nope!
Nope!
=> Bugfixes to the Backend refactoring

agent/check_handler_internal_test.go
Improves TestExecuteCheck, add debug print statement in the event future failures happen, avoid panic by using `require`.
Closes #1825 
Nah.
Nah.
🤞 Hoping the behavior is the same on windows.
=> Improve TestExecuteCheck

backend/apid/graphql/schema/mutations.gql.go, backend/apid/graphql/schema/mutations.graphql, dashboard/src/apollo/schema/combined.graphql, dashboard/src/components/partials/ChecksList/ChecksListItem.js, dashboard/src/mutations/executeCheck.js
Allow check to be executed when no subscriptions are given.
See above.
Issue was introduced prior to last release. Introduced in #1747.
`undefined`
`undefined`
`undefined`
=> [Web UI] Allow check to be executed when no subscriptions are given

backend/apid/apid.go, backend/apid/routers/assets.go, backend/apid/routers/checks.go, backend/apid/routers/entities.go, backend/apid/routers/environments.go, backend/apid/routers/events.go, backend/apid/routers/extensions.go, backend/apid/routers/filters.go, backend/apid/routers/handlers.go, backend/apid/routers/hooks.go, backend/apid/routers/mutators.go, backend/apid/routers/organizations.go, backend/apid/routers/roles.go, backend/apid/routers/routers.go, backend/apid/routers/silenced.go, backend/apid/routers/users.go
Exports apid router and resource routes.
Required by https://github.com/sensu/sensu-enterprise-go/issues/40
Probably okay without it.
Nah.
Nah.
=> Export apid router and resource routes

CHANGELOG.md, build.sh
It fixes the nightly build by properly tagging and pushing the `sensu/sensu:nightly` Docker image.
So the nightly build stops failing.
Added!
Non!
Non!
Non!
=> Properly tag and push the Docker nightly image

CHANGELOG.md, backend/apid/actions/cluster.go, backend/apid/actions/cluster_test.go, backend/apid/apid.go, backend/apid/routers/cluster.go, backend/apid/routers/cluster_test.go, backend/authorization/cluster.go, backend/backend.go, types/rbac.go
This commit adds API support for cluster management.
The following new routes are supported:
GET    /cluster/members
POST   /cluster/members
PUT    /cluster/members/{id}
DELETE /cluster/members/{id}
=> Add API support for cluster management.

CHANGELOG.md, backend/messaging/wizard_bus.go, backend/messaging/wizard_topic.go, backend/ring/logger.go, backend/ring/ring.go, backend/ring/ring_test.go, types/ring.go
This commit re-works the ring data structure after testing revealed
that round robin check execution in the presence of multiple
backends could be too frequent.
The ring is now administered by only a single writer. Backends race
to obtain a mutex on each ring, and the backend that obtains the
lock is responsible for administering the ring. The backends are
apprised of ring events via etcd watchers.
Round-robin check execution now works properly in the presence of
multiple backends.
This commit also removes the un-used Peek method of the ring.
=> Re-work ring for round-robin check execution.

.circleci/config.yml
Apparently, we need to apply the filter logic to both jobs in the workflow.
Right now, we're building everything, and testing master/build branches, which isn't what we (currently) want.
=> Issue 1730, part 2

backend/store/etcd/watchers.go
Export GetWatcherAction function for use by sensu-enterprise-go.
We're going to have etcd watchers defined in both repos, and should avoid code duplication.
Nah.
I'm good.
None
This is a source level change
=> Export GetWatcherAction function for use by sensu-enterprise-go

CHANGELOG.md, cli/client/authentication.go, cli/client/authentication_test.go, cli/client/config/basic/basic.go, cli/client/config/basic/reader.go, cli/client/config/basic/reader_test.go, cli/client/config/basic/writer.go, cli/client/config/basic/writer_test.go, cli/client/config/config.go, cli/client/interface.go, cli/client/testing/mock_authentication_client.go, cli/client/testing/mock_config.go, cli/commands/configure/configure.go, cli/commands/root/templates.go, cli/commands/user/change_password.go, types/edition.go
It adds the notion of a Sensu _edition_ in sensuctl
More specifically:
- It retrieves a header containing the edition when running `sensuctl configure`
- It saves the edition name in the cluster configuration file
- Cleanup the help usage template for Cobra, since some white lines were missing
- Mocking of some enterprise template functions
Required by https://github.com/sensu/sensu-enterprise-go/issues/42.
Added!
Non!
Non!
Non!
=> Introduce Sensu edition detection in sensuctl

cli/client/cluster.go, cli/client/interface.go, cli/client/testing/mock_cluster_client.go, cli/commands/cluster/help.go, cli/commands/cluster/member-remove.go, cli/commands/cluster/member-update.go
This commit adds the sensuctl cluster member-remove command.
Operators can use the member-remove command to remove cluster
members.
Closes #1721
=> Add sensuctl cluster member-remove command.

CHANGELOG.md, cli/client/client.go, cli/client/interface.go, cli/client/license.go, cli/client/testing/mock_license_client.go
It adds support for licensing in the API client, so these methods can be overridden in the enterprise codebase. This is a workaround until https://github.com/sensu/sensu-go/issues/1870 is implemented.
I locally tested the complete solution, which works great.
Required by https://github.com/sensu/sensu-enterprise-go/issues/17
Required by https://github.com/sensu/sensu-enterprise-go/issues/34
Added!
Nope!
Nope!
Nope!
=> Add support for licensing in API client

CHANGELOG.md, backend/apid/apid.go, backend/apid/middlewares/edition.go, build.ps1, build.sh, version/version.go
Adds an edition header to api calls.
Required by https://github.com/sensu/sensu-enterprise-go/issues/47
Yas.
Nah.
Nah.
We good.
=> Add edition header to middleware and build scripts

build.ps1, build.sh, version/version.go
It removes the build flag used to determine the Sensu edition. Instead, we will override the edition directly within the enterprise codebase.
Required by https://github.com/sensu/sensu-enterprise-go/issues/47
Nah, I consider it's part of this entry
> Added a header to API calls that returns the current Sensu Edition
Nope
Nope
Nope
=> Do not use build flags for the Sensu edition

build.ps1, build.sh
Remove unused golint tool installation from Travis and Appveyor CIs.
The `golint` tool is being installed but not used on both travis and appveyor configs. Furthermore, golint isn't meant to be used as part of a build pipeline according to its readme https://github.com/golang/lint#purpose.
N/A
The Travis changes will probably be made irrelevant with the upcoming migration to CircleCI, but I think there's still value in removing it from Appveyor.
We are not running any linting on Appveyor. Should we be?
N/A
N/A
=> Remove unused golint from build

dashboard/package.json, dashboard/yarn.lock
Use pre-packaged instead of referencing repo. 
Avoids issues seen on CI, such as:
```
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/jest-changed-files/-/jest-changed-files-22.4.3.tgz: ENOENT: no such file or directory, chmod '/home/travis/.cache/yarn/v1/npm-jest-changed-files-22.4.3-8882181e022c38bd46a2e4d18d44d19d90a90fb2/build/index.js'".
info If you think this is a bug, please open a bug report with the information provided in "/home/travis/gopath/src/github.com/sensu/sensu-go/dashboard/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
Stop the CI failures.
Unlikely; tooling related.
`undefined`
`undefined`
`undefined`
=> [Web UI] Use pre-packaged instead of referencing repo

cli/commands/asset/info_test.go, cli/commands/asset/list_test.go, cli/commands/check/info_test.go, cli/commands/check/list_test.go, cli/commands/cluster/health_test.go, cli/commands/entity/info_test.go, cli/commands/entity/list_test.go, cli/commands/extension/list_test.go, cli/commands/filter/info_test.go, cli/commands/filter/list_test.go, cli/commands/handler/list_test.go, cli/commands/hook/info_test.go, cli/commands/hook/list_test.go, cli/commands/mutator/info_test.go, cli/commands/mutator/list_test.go, cli/commands/organization/list_test.go, cli/commands/role/list_rules_test.go, cli/commands/role/list_test.go, cli/commands/silenced/info_test.go, cli/commands/silenced/list_test.go, cli/commands/testing/cli.go, cli/commands/user/list_test.go
Removes a redundant code block and adds it as a helper function for testing. Noticed this when reviewing https://github.com/sensu/sensu-go/pull/1885.
Good coding practices.
Nah.
Nah.
Nah.
We good.
=> Remove code duplication from newCLI() func

cli/commands/asset/create.go
Adds a newline after "OK" during interactive asset creation.
Closes https://github.com/sensu/sensu-go/issues/1906
Nah.
Nah.
Nah.
We good.
=> Add a newline after asset creation confirmation

CHANGELOG.md, backend/agentd/session.go
It prevents agentd from subscribing to empty subscriptions, because the `transport.HeaderKeySubscriptions` header could be empty.
Closes https://github.com/sensu/sensu-go/issues/1853
Added
Nope
Nope
Nope
=> Prevent empty subscriptions in agentd

CHANGELOG.md, cli/client/authentication.go, cli/client/authentication_test.go, cli/client/client.go, cli/client/interface.go, cli/client/testing/mock_authentication_client.go, cli/commands/config/view.go, cli/commands/config/view_test.go, cli/commands/configure/configure.go, cli/commands/user/change_password.go
It inspects the headers returned by the Sensu API on each request to verify the Sensu edition, and updates sensuctl configuration if required.
It ensures a user has access to the enterprise version of sensuctl whenever they upgrade Sensu Backend.
Added
Nope
Nope
Nope
=> Improve Sensu edition header handling

CHANGELOG.md, backend/authorization/authorization.go, backend/authorization/authorization_test.go, cli/commands/role/add_rule.go, cli/commands/role/create.go, cli/commands/role/help.go, cli/commands/role/info.go, cli/commands/role/info_test.go, types/rbac.go
This PR introduces several bug fixes for RBAC, which I discovered with Jason. Each bug fix has its own commit for simplicity.
- I renamed the `sensuctl role list-rules` subcommand to `sensuctl role info` so it's consistent with other commands. I also added an alias to this subcommand for backward compatibility so you can still run the subcommand with its previous name.
- The allowed values for a rule type are now directly displayed in the help usage in `sensuctl role create` & `sensuctl role add-rule`, so users don't have to look in the docs.
- The rules are now implicitly granting read access to their organization and environment, so a user can list the environments & organization it has access to without having to explicitly give these permissions.
It fixes small UX problems we …
=> RBAC bugfixes

CHANGELOG.md, agent/cmd/start.go, backend/cmd/start.go
It prevents help usage and duplicated error message from being  printed on sensu-backend & sensu-agent startup. 
Closes https://github.com/sensu/sensu-go/issues/1814
Added
Nope
Nope
Nope
=> Silence usage on startup

CHANGELOG.md, cli/commands/check/subcommands/set_proxy_request.go, cli/commands/check/subcommands/set_proxy_request_test.go
It ensures we use the default value for splay_coverage if not provided.
Closes https://github.com/sensu/sensu-go/issues/1470
Added
Nope
Nope
Nope
=> Use default value for splay_coverage in sensuctl

CHANGELOG.md, backend/keepalived/keepalived.go, backend/keepalived/keepalived_test.go
Sets the `Issued` and `History` attributes on a keepalive event.
Fixes #1440.
Fixes https://github.com/sensu/sensu-go/issues/1731.
Yes.
Nope.
Nope.
No documentation updates required.
=> Set issued & history on keepalive events

CHANGELOG.md, backend/store/etcd/health_store.go
Avoids a panic in `sensuctl cluster health` in the event there is an error creating a new client. Discovered when investigating https://github.com/sensu/sensu-go/issues/1928.
Panic no good.
Yas.
Nah.
Nah.
Nah.
=> Resolve panic in sensuctl cluster health

CHANGELOG.md, backend/agentd/agentd.go, backend/agentd/session.go
Added information as to which agent is connecting and disconnecting in the agentd session logs in sensu-backend.
Before
```
{"component":"agentd","id":"t-sensu","level":"info","msg":"agent connected","subscriptions":["","entity:t-sensu"],"time":"2018-08-06T17:27:32-06:00"}
{"component":"agentd","level":"warning","msg":"stopping session","recv error":"Connection closed: websocket: close 1001 (going away): bye","session":"91c9cb92-bf1c-49b4-bfa1-e68d99940bf9","time":"2018-08-06T17:27:58-06:00"}
```
After:
```
{"addr":"127.0.0.1:52888","id":"t-sensu","component":"agentd","level":"info","msg":"agent connected","subscriptions":["","entity:t-sensu"],"time":"2018-08-06T17:15:57-06:00"} …
```
=> Add agent ID and IP address to agentd session logs

Dockerfile
The Sensu operator (work in progress) expects `etcdctl` to be available
in the base image. `etcdctl snapshot restore ...` is used from an init
container when a Sensu cluster is restored from a backup.
https://github.com/kinvolk/sensu-operator/blob/6e46ed44cc6a09daad45ad8557012819290b8cc9/pkg/util/k8sutil/k8sutil.go#L127
Also, update the Alpine base image (3.6 -> 3.8)
Signed-off-by: Michael Schubert <michael@kinvolk.io>
=> Dockerfile: add etcdctl

Gopkg.lock, Gopkg.toml, vendor/github.com/StackExchange/wmi/README.md, vendor/github.com/StackExchange/wmi/swbemservices.go, vendor/github.com/StackExchange/wmi/wmi.go, vendor/github.com/shirou/gopsutil/README.rst, vendor/github.com/shirou/gopsutil/disk/disk.go, vendor/github.com/shirou/gopsutil/disk/disk_darwin.go, vendor/github.com/shirou/gopsutil/disk/disk_freebsd.go, vendor/github.com/shirou/gopsutil/disk/disk_linux.go, vendor/github.com/shirou/gopsutil/disk/disk_openbsd.go, vendor/github.com/shirou/gopsutil/disk/disk_unix.go, vendor/github.com/shirou/gopsutil/host/host_linux.go, vendor/github.com/shirou/gopsutil/host/host_windows.go, vendor/github.com/shirou/gopsutil/internal/common/common.go, vendor/github.com/shirou/gopsutil/mem/mem.go, vendor/github.com/shirou/gopsutil/mem/mem_linux.go, vendor/github.com/shirou/gopsutil/mem/mem_windows.go, vendor/github.com/shirou/gopsutil/net/net.go, vendor/github.com/shirou/gopsutil/net/net_unix.go, vendor/github.com/shirou/gopsutil/process/process_fallback.go, vendor/github.com/shirou/gopsutil/process/process_linux.go, vendor/github.com/shirou/gopsutil/process/process_posix.go, vendor/github.com/shirou/gopsutil/process/process_windows.go
Bumps `gopsutil` to `v2.18.07` and updates `wmi` to the `b12b22c` SHA.
An attempt to solve the `wmi` timeout we're hitting in https://github.com/sensu/sensu-go/issues/1829.
Nope!
Nope!
Nope!
N/A
=> Bump gopsutil to v2.18.07 and wmi to b12b22c

.appveyor.yml, .travis.yml
Removes the `build.[sh|ps1] deps` command from Travis & AppVeyor as it's no longer a command in the scripts.
CI is running the entire test suite when it tries to call the `deps` command.
Nope!
Nope!
Nope!
Nope!
=> build.[sh|ps1] deps command no longer exists

.circleci/config.yml
Removes the deps & lint steps from Circle CI.
We're no longer running these steps on Travis CI & AppVeyor. This brings Circle CI up to speed.
Nope!
Nope!
Nope!
Nope!
=> Remove deps & lint steps in Circle CI

dashboard/fallback.go
Eliminates redirect loop encountered when backend is missing dashboard and user attempts to navigate to the root path.
Closes #1908 
Primarily DX related so it's unlikely.
nada
nada
nada
=> Fixup redirect loop encountered when backend is missing dashboard

CHANGELOG.md, agent/transformers/influx_db.go, agent/transformers/influx_db_test.go
Fixes a bug in InfluxDB metric parsing. The timestamp is now optional and compliant with InfluxDB line protocol.
Closes #1882 
Yas.
Nah.
Nah.
We good.
=> InfluxDB metric transformer allows the 3rd timestamp argument to be optional

CHANGELOG.md, backend/backend.go, backend/etcd/etcd.go, backend/etcd/sequence.go, backend/etcd/sequence_test.go, backend/queue/queue.go, backend/queue/queue_test.go, backend/ring/ring.go, backend/ring/ring_test.go
This commit modifies the queue so that each backend can consume
messages from it - also known as fan-out.
As an unrelated refactoring change, this commit also factors out
the sequencing method from the ring and places it in the etcd
package.
I initially intended to use the ring sequencing method for the
queue, but later remembered that the queue uses timestamps, as it
relies on the timestamp value to compute queue item freshness.
During the course of this work, I discovered that the queue is not
safe to use with multiple producers and consumers for the same
backend. To support this use case, I believe we would need to
use etcd's concurrency.STM datatype.
However, we do not currently have this use case, so I think such
a feature is not needed. Therefore, the test case that tests
concurrent …
=> Re-work queue to support one-to-many messaging.

CHANGELOG.md, backend/store/etcd/health_store.go
Prevents panic and closes the client.
Fixes bug in `sensuctl cluster health` so that the proper error is handled.
Nah.
Nah.
Nah.
We good.
=> Bugfix for sensuctl cluster health error handling

CHANGELOG.md, Gopkg.lock, Gopkg.toml, vendor/github.com/mholt/archiver/tar.go
Updates the archiver dependency to fix a bug with extracting git tarballs.
Closes #1700
Yas.
Nah.
I had to open a pr to the dependency: https://github.com/mholt/archiver/commit/85d3d0b511eae05958ddb34e9eac57d8ffea03bf
https://github.com/sensu/sensu-docs/pull/667
=> Update archiver sha to fix git tarball bug

dashboard/package.json, dashboard/yarn.lock
Fixes an issue where event objects and raw values were not correctly differentiated in minified builds.
Closes sensu/sensu-go#1967
Closes #1982 
Closes #1986 
No
No
No
No
=> [Web UI] Update to patched @10xjs/form release

CHANGELOG.md, build-gcs-release.sh
Adds windows/386 support to `build-gcs-release.sh` for sensu-agent and sensuctl.
We were already building 32-bit windows packages but we missed adding support for 32-bit binary releases.
Yes, updated.
Nope!
Nope!
I'll look into this.
=> Add windows/386 support to build-gcs-release.sh

CHANGELOG.md, agent/assetmanager/asset.go
When installing assets, ensure that an absolute path is used to obtain the lockfile.
https://github.com/nightlyone/lockfile/blob/master/lockfile.go#L45-L47
Discovered while helping debug #2003. If the agent is configured with a relative path asset installation will fail. (eg. `sensu-agent start --cache-dir ./tmp`.)
It certainly should!
=> [Agent] Use absolute path when obtaining lockfile

CHANGELOG.md, cli/elements/globals/colors.go, cli/elements/table/standard.go
Use terminals configured default text colour.
Fixes #2006 
Yes!
NO!
No [exclaimation mark]
Unlikely.
=> [CLI] Use terminals configured default text colour

backend/backend_test.go, build.sh
Removes race flag from `build.sh` integration tests.
Just an attempt to fix our CircleCI builds from OOM-ing.
=> Remove race flag from build.sh integration tests

CHANGELOG.md, agent/agent.go, agent/entity.go, agent/entity_test.go
Instead of `agent.getAgentEntity()` being responsible for gathering system info, the agent itself now spawns a goroutine responsible for periodically updating a local cache of system info.
`agent.getAgentEntity()` now reads that cache whenever it needs to retrieve system information.
Closes #1947.
Might help #1829. 
Yes, added as part of of the change.
- Initial keepalive message might not have system info. That doesn't change how
it used to work, but is that OK?
- Unsure how/if I should add tests for the change. It might lead to some refactoring?
- Any potential impact I might be missing? Would you have done it differently?
- `lsb_release` needed for some distros to pass tests in `system` package (eg:
Arch). I'll open a separate issue for which the "fix" would probably simply be
an …
=> Separate system info collection from getAgentEntity()

CHANGELOG.md, cli/commands/check/interactive.go
This commit fixes a bug in sensuctl check update where once a
metrics output format had been set, it could no longer be unset.
Closes #2023
Yes
No
It seems likely that a slew of similar bugs exists in the interactive mode of sensuctl. We should discuss how to resolve this on a product-wide basis.
=> Fix a bug in sensuctl check update.

CHANGELOG.md, backend/backend.go, backend/etcd/etcd.go, backend/etcd/testing.go, backend/store/etcd/testutil/store.go
* --listen-client-urls can now be a comma-separated list.
* The etcd service no longer forcibly binds to localhost.
There were a couple of etcd configuration issues that I thought were closely related enough to be worthwhile folding together into a single commit.
Closes #1965
Closes #2016 
Yes
No
No
No documentation requires updating, as clustering documentation is still an outstanding effort.
=> Resolve some etcd configuration and operation issues

CHANGELOG.md, agent/agent.go, agent/agent_test.go
Fails the agent if the ID is invalid.
Closes #2022 
Yas.
Nah.
Nah.
We good.
=> Add agent id validation

docker-compose.yaml
Adds `log-level` and `depends_on` to docker cluster configuration.
Ensures backends are running before agents attempt to start up.
Nah.
Nah.
Nah.
We good.
=> Add some helpers to docker cluster configuration

dashboard/src/apollo/authLink.js, dashboard/src/apollo/resolvers/auth.js, dashboard/src/apollo/schema/client.graphql, dashboard/src/apollo/schema/combined.graphql, dashboard/src/components/partials/SigninDialog/SigninDialog.js, dashboard/src/components/util/DefaultRedirect.js, dashboard/src/components/util/LastEnvironmentRedirect.js, dashboard/src/components/util/UnauthenticatedRoute.js, dashboard/src/mutations/flagTokens.js
Better handles case where server has invalidated the authorization
token pair or the server's secret has changed.
Closes #1975 
`undefined`
`null`
my poor debugging skills..?
`[]`
=> [Web UI] Refresh tokens when GraphQL request produces 401

CHANGELOG.md, backend/apid/routers/status_test.go, backend/store/etcd/health_store.go, backend/store/etcd/health_store_test.go, cli/commands/cluster/health_test.go, types/health.go
Changes `ClusterHealth.Err` to a string rather than an error. This fixes a bug associated to an unmarshal error in sensuctl when a cluster is unhealthy.
Before:
```
$ ~/sensuctl cluster health
Error: json: cannot unmarshal object into Go struct field ClusterHealth.Err of type error
```
After:
```
$ ~/sensuctl cluster health
ID            Name                              Error                           Healthy  
────────────────── ─────────── ─────────────────────────────────────────────────────── ───────── 
1e8b542f60611ee    backend-2   dial tcp x:2379: connect: connection refused            false    
7918dd0d1856841b   backend-0                                                           true     
f7cdce3577ddf3fc   backend-1 …
```
=> sensuctl cluster health response contains string representation of error

CHANGELOG.md, backend/backend.go, backend/cmd/start.go, backend/config.go, backend/etcd/etcd.go, backend/etcd/id.go, backend/etcd/id_test.go, backend/queue/queue.go, backend/queue/queue_test.go
This commit adds the --no-embed flag to the backend. When this flag
is specified, sensu-backend will dial whatever URLs are specified
in the --listen-client-urls flag, and not start up etcd.
Closes #2015 
Closes #1963
Yes
No
This change required some refactoring of the queue package, which
depended on the cluster member ID for operation. This ID has been
replaced by a client lease ID which is created on backend startup.
As a result, this made queue garbage collection easier to
guarantee, because now all queue keys are created with a lease.
The test that tested queue garbage collection has been removed,
because the logic that removes the keys is no longer part of the
queue package.
Testing was done by starting up an external etcd instance and
pointing the backend at it. No issues were …
=> Support using sensu-backend with external etcd instances

backend/apid/graphql/mutations.go, backend/apid/graphql/mutations_test.go, backend/apid/graphql/services.go, backend/apid/graphql/services_test.go
Allow updateCheck mutation to update individual fields of given check.
---
Unblocks #1935.
unlikely
n/a
Without any mocks / stubs for the actions package we continue to accrue redundant code when writing field resolver tests.
n/a
=> Allow updateCheck mutation to update individual fields

CHANGELOG.md, agent/agent.go, cmd/sensu-agent/start.go, packaging/files/agent.yml.example, packaging/files/windows/agent.yml.example, types/dynamic/dynamic.go
Deprecates --custom-attributes in the sensu-agent command and changes it to --extended-attributes.
Closes #2051 
Yas.
Nah.
No, but filed https://github.com/sensu/sensu-go/issues/2079 to address a concern that was brought up in the original issue.
We good.
=> Deprecate custom-attributes

CHANGELOG.md, backend/schedulerd/check_timer.go
Adds a debug log message for interval timer initial offset.
Closes #2053.
Yas.
Nah.
Proxy splay vs initial offset/timer splay is confusing (see https://github.com/sensu/sensu-go/issues/2053#issuecomment-423290142).
I'm gonna add a note to the docs about this to avoid future confusion: https://github.com/sensu/sensu-docs/pull/752
=> Add a debug log message for interval timer initial offset

CHANGELOG.md, cli/client/config/config.go, cli/commands/configure/configure.go, cli/commands/configure/configure_test.go
Fixes the interactive selection of the preferred output format when using `sensuctl configure`: an incorrect option called `none` has been replaced with `tabular` in accordance with the documentation.
Fixes #2063 
Yes, added.
No.
No.
No documentation changes required. This change brings the `sensuctl configure` interface in line with the current documentation.
=> Fix interactive selection of output format

CHANGELOG.md, cli/commands/check/interactive.go
Fixes the interactive values shown in `sensuctl check create` and `sensuctl check update`.
Closes https://github.com/sensu/sensu-go/issues/1971
yas
nah
code duplication isn't consistent
we good
=> Fix sensuctl check update interactive values

dashboard/src/components/relocation/ExecuteCheckStatusToast.js
Signed-off-by: Neal Granger <neal@nealg.com>
Fix a bug that occurs when the check execution status toast is closed by the user while still loading.
Fixes an app-crashing bug.
No
No
No
No
=> [Web UI] Fix bug in ExecuteCheckStatusToast component

CHANGELOG.md, backend/backend.go
It ensures the etcd client uses the proper TLS configuration when connecting to an external etcd cluster. 
Fix a problem encountered while writing the clustering docs.
Added
Nope
Nope
Nope
=> Use EtcdClientTLSInfo for external etcd cluster

.circleci/config.yml, asset/boltdb_manager.go, asset/boltdb_manager_test.go, asset/integration_test.go, backend/apid/graphql/relay/node.go, backend/apid/middlewares/allowlist.go, backend/apid/middlewares/refresh_token.go, backend/etcd/logrus_formatter.go, backend/store/etcd/logrus_formatter.go, build/ci/gofmt-linting-check.sh, cli/elements/report/report.go, scripts/gengraphql/gengraphql.go
Addresses #2011.
Adds a tiny script to call `gofmt` on the `sensu-go` repo, but excludes the `vendor` directory.
Also fixes the few errors doing this check on CircleCI surfaced.
Example of linting failure: https://circleci.com/gh/sensu/sensu-go/731
Example of success: https://circleci.com/gh/sensu/sensu-go/734
From an engineering process perspective, tapping @oferrigni and @grepory too.
=> Issue 2011-Validate Go code style formatting

backend/backend.go
Reverts formatting in backend.go to gofmt v1.10.
It makes CI happy!
Nope
Nope
Nope
Nope
=> Use gofmt 1.10 for linting

CHANGELOG.md, agent/agent_test.go
It ensures our integration test does not fail when running in CircleCI.
So CircleCI is happy.
Added
Nope
Nope
Nope
=> Increase duration delta in TestPeriodicKeepalive integration test

CHANGELOG.md, backend/authorization/authorization_test.go
This adds a test for privilege escalation in the authorization component apid.
As we go forward refactoring RBAC, it will be important to make sure that we do not inadvertently allow privilege escalation.
=> Add test for privilege escalation in rbac

.circleci/config.yml, build/ci/circle-ci-setup.sh
Changes required to post the CircleCI workspace logs (from both the build and test stages) to S3, making those logs a first-class artifact.
This PR depends on https://github.com/sensu/sensu-release/pull/1
=> Issue 2121-Post build/test logs as artifacts to S3

.circleci/config.yml
This will mimic behavior we had on TravisCI; while it isn't distinct (in terms of tasks run) from the build_and_test job, I could easily see a future where it _is_ distinct and does additional release-related takss, so creating is as a separate job now.
Signed-off-by: J. Paul Reed <preed@release-approaches.com>
=> Create a "release" build_and_test job that fires on release tags.

.circleci/config.yml
Cleans up the CircleCI config, so jobs don't double-fire.
=> Issue 2119, part 3

dashboard/package.json, dashboard/src/apollo/authLink.js, dashboard/src/components/util/Query.js, dashboard/src/components/views/EnvironmentView/CheckDetailsContent.js, dashboard/src/components/views/EnvironmentView/ChecksContent.js, dashboard/src/components/views/EnvironmentView/EntitiesContent.js, dashboard/src/components/views/EnvironmentView/EntityDetailsContent.js, dashboard/src/components/views/EnvironmentView/EventDetailsContent.js, dashboard/src/components/views/EnvironmentView/EventsContent.js, dashboard/src/components/views/EnvironmentView/SilencesContent.js, dashboard/yarn.lock
Differs from `react-apollo`'s implementation by:
- reflecting the value last emitted by the configured watcher instead of
firing a `forceUpdate` and relying the observer's currentResult. By
doing so, re-renders should not be affected by the inconsistent behavior
of the observer's `currentResult` method (see apollographql/apollo-client#3947).
As well as being slightly more efficient by virtue of not having to reselect
the same data from the cache on each render.
- gives us more control so that we can handle error's however we like.
Closes #2062 
Probably not. Issue #2062 likely started after the AppLayout changes, which were merged since the last release.
nada.
Debugging the issue was tricky. 
Still not 100% on the correct behavior of the QueryObserver's `currentResult` method. Opened …
=> [Web UI] Drop in replacement for Apollo's Query component

CHANGELOG.md, agent/token.go, backend/monitor/supervisor.go, backend/queue/queue_test.go
In Go 1.11, functions called by the template package are always
handed two arguments, instead of one or conditionally two.
This commit also fixes some formatting directives that were not
previously noticed by the old go vet.
Closes #2073
Yes
No
=> Fix some Go 1.11 issues.

agent/agent_test.go, agent/timeproxy_test.go
This test uses mocked time provided by the `timeproxy` and `crock` library
but the settings we were using for the mocked time appeared to be
problematic and made the test fail intermittently.
This commit attempt to solve that by more carefully choosing the
settings for the mocked time.
Test would fail intermittently.
No.
No.
Making sure I fully understood the actual meaning and influence of the mocked time's `Resolution` and `Multiplier`.
Not needed.
=> Attempt to fix TestPeriodicKeepalive()

agent/agent_test.go, agent/timeproxy_test.go
The `TestPeriodicKeepalive` test in the `agent` package still fails
intermittently, even after 4fd2ce93.
In an attempt to stop those intermittent failures, this commit:
- makes the mock time 5 times coarser
- makes the mock time tick 10 times less
- doubles the allowed time drift in the test
Stop intermittent test failures on CircleCI.
No.
No.
No.
Not needed.
=> Fine tune mock time for CI

internal/apis/meta/meta.go, internal/cmd/gen-register/main.go, runtime/registry/registry.go, runtime/registry/registry.go.tmpl, runtime/registry/registry_gen.go
This PR adds the gen-register tool, and an initial generated registry for the new sensu-go types.
A type registry is necessary for features like `sensuctl create`.
=> Add gen-register, a tool for generating type registries.

agent/api.go, agent/token.go, asset/fetcher.go, backend/agentd/entity.go, backend/apid/apid.go, backend/apid/routers/authentication.go, backend/backend.go, backend/dashboardd/dashboardd.go, backend/keepalived/deregisterer.go, cmd/sensu-agent/main.go, cmd/sensu-backend/main.go, types/dynamic/redact.go, util/eval/predicate.go
Uses `err` (type `error`) in place of `err.Error()` (type `string`) when called from `fmt`.
Quality of life.
Nah.
Nah.
Nah.
We good.
=> fmt.Errorf cleanup

internal/astutil/kind.go, internal/cmd/freeze-api/convert.go, internal/cmd/freeze-api/copy.go, internal/cmd/freeze-api/main.go, internal/cmd/gen-register/main.go, internal/registry/registry.go, runtime/registry/registry_gen.go
Add a conversion utility to the freeze-api command. This feature
generates type converters between the package being frozen and
the package being created.
For now, only pointer conversions are supported. In the future,
a more featureful conversion interface will be required.
Here is an example of code generated by this utility:
```go
package v1
import (
"unsafe"
"github.com/sensu/sensu-go/internal/apis/rbac"
)
// Convert converts a *ClusterRole to a *rbac.ClusterRole. It panics if the
// to parameter is not a *ClusterRole.
func (r *ClusterRole) Convert(to interface{}) {
ptr := to.(*rbac.ClusterRole)
convert_ClusterRole_To_rbac_ClusterRole(r, ptr)
}
var convert_ClusterRole_To_rbac_ClusterRole = func(from *ClusterRole, to *rbac.ClusterRole) {
*to …
```
=> Add freeze-api conversion utility.

dashboard/package.json, dashboard/yarn.lock
Fixes exception thrown when browser window is resized.
Closes #2161 
No
No
No
No
=> Update to patched `react-resize-observer`

dashboard/src/components/SearchBox/SearchBox.js
Closes #2094 
Allows the user to clear their filter easier
I don't think so
I did notice that when applying filters (like on the Events List) the `AppLayout-content` div occasionally moves approx. 5px to the right. It looks like it's related to the automatic margins. Setting it to a pixel value would stop this, but be frustrating due to having to add more breakpoints to make it scale nicely. A percent value would help with scaling, but still moves slightly when the data set is empty.
=> [Web UI] Clear filter button

CHANGELOG.md, dashboard/package.json, dashboard/yarn.lock
Update to the latest version of `@10xjs/date-input-controller`.
Fixes #2223 
React 16.4 included a change to the behavior of getDerivedStateFromProps which is now called after internal state updates in addition to received props. This surfaced as a bug prevent the begin date field in the silencing entry form from accepting changes.
See: https://github.com/10xjs/date-input-controller/pull/1
Changelog updated.
No
No
No
=> [Web-UI] Fix date input bug surfaced by React 16.4

CHANGELOG.md, backend/apid/graphql/environment.go, backend/apid/graphql/schema/mutations.gql.go, dashboard/src/components/partials/ListSortSelector/Menu.js
Closes #2196 
Fixes the sort order implementation of Silences. Fixes the sort button not switching to descending on initial click. Changes the arrow to point the "direction" of the action to be taken on click (ascending is up, descending is down).
It wasn't working optimally and was a little confusing from a user perspective.
Added one.
=> [Web UI] Sort order fixes

CHANGELOG.md, backend/keepalived/keepalived.go, backend/keepalived/keepalived_test.go, backend/monitor/supervisor.go, types/event.go
Fixes a panic on the backend when handling keepalives from older agent versions., fixes a bug that would prevent some keepalive failures from occurring, and improves event validation error messages.
Closes https://github.com/sensu/sensu-go/issues/2153
Closes https://github.com/sensu/sensu-go/issues/2190
Fixes event validation error messages. For example:
```
{"component":"eventd","error":"check check interval must be greater than or equal to 1","level":"error","msg":"eventd - error handling event","time":"2018-10-30T10:47:05-07:00"}
```
becomes 
```
{"component":"eventd","error":"check is invalid: check interval must be greater than or equal to 1","level":"error","msg":"eventd - error handling event","time":"2018-10-30T10:47:05-07:00"}
```
Yas. …
=> Keepalive bugfixes

CHANGELOG.md, agent/statsd_server.go
Adds a debug log message on the agent side when it sends a statsd event.
```
{"component":"agent","entity":"Nikkis-MacBook-Pro","level":"debug","metrics":{"handlers":["statsd-log"],"points":[{"name":"Nikkis-MacBook-Pro.cpu.value","value":41,"timestamp":1541005037755019464,"tags":[{"name":"s","value":"127.0.0.1"}]},{"name":"Nikkis-MacBook-Pro.cpu.per_second","value":4.100051771763727,"timestamp":1541005037755019464,"tags":[{"name":"s","value":"127.0.0.1"}]}]},"msg":"sending statsd metrics","time":"2018-10-31T09:57:17-07:00"}
```
Logs already exist on the backend
```
{"component":"pipelined","entity":"Nikkis-MacBook-Pro","environment":"default","level":"debug","metrics":{"handlers":[],"points":[{"name":"Nikkis-MacBook-Pro.cpu.value","value":41,"tim …
```
=> Improve agent statsd log

backend/apid/actions/error.go, backend/apid/actions/roles.go, backend/apid/apid.go, backend/apid/graphql/error.go, backend/apid/graphql/node.go, backend/apid/graphql/schema/errors.gql.go, backend/apid/middlewares/namespace.go, backend/apid/routers/roles.go, backend/apid/routers/routers.go, backend/store/etcd/clusterrole_store.go, backend/store/etcd/clusterrolebinding_store.go, backend/store/etcd/role_store.go, backend/store/etcd/rolebinding_store.go, backend/store/etcd/store.go, backend/store/etcd/store_test.go, backend/store/key_builder.go, backend/store/namespace.go, backend/store/store.go, cli/commands/role/create.go, cli/commands/role/create_test.go, cli/commands/role/list_test.go, testing/mockstore/clusterrole.go, testing/mockstore/clusterrolebinding.go, testing/mockstore/role.go, testing/mockstore/rolebinding.go, types/rbac.go
It adds stores for `clusterroles`, `clusterrolebindings`, `roles` & `rolebindings`.
I also made a small refactoring to `roles` in order to standardize how we deal with validation/errors/empty responses, so most of the logic in now in generic methods (see `backend/store/etcd/store.go`).
Closes https://github.com/sensu/sensu-go/issues/2280
=> Add new RBAC stores

CHANGELOG.md, backend/store/etcd/asset_store_test.go, cli/commands/asset/create.go, cli/commands/asset/create_test.go, cli/commands/asset/info.go, cli/commands/asset/info_test.go, types/asset.go, types/asset.pb.go, types/asset.proto
This removes the asset Metadata field--a map[string]string that is currently unused by the agent and backend.
It's a non-functional field and the field name conflicts with the new object metadata field name.
https://github.com/sensu/sensu-docs/pull/863
closes #2270
=> Remove unused asset metadata field

CHANGELOG.md, agent/cmd/start.go
This moves us from using `pflag.String` and manual parsing for the `--subscriptions` flag to `pflag.StringSlice`.
This allows users to specify subscriptions as an array while preserving the command-line argument as a comma-delimited list of strings.
closes #2291
=> Use StringSlice for subscriptions flag in sensu-agent

backend/apid/apid.go, backend/apid/middlewares/namespace.go
It re-adds the namespace middleware so the namespace is added into context of the request, which is later used by the store.
Bug reported by Eric
Nope, it fixes a bug introduced is an unreleased feature.
Nope
Nope
Nope
=> Re-introduce the namespace middleware for now

backend/apid/actions/clusterrolebindings.go, backend/apid/actions/clusterrolebindings_test.go, backend/apid/actions/clusterroles.go, backend/apid/actions/clusterroles_test.go, backend/apid/actions/rolebindings.go, backend/apid/actions/rolebindings_test.go, backend/apid/actions/roles.go, backend/apid/actions/roles_test.go, backend/apid/apid.go, backend/apid/graphql/globalid/clusterrolebindings.go, backend/apid/graphql/globalid/clusterroles.go, backend/apid/graphql/globalid/rolebindings.go, backend/apid/graphql/node.go, backend/apid/graphql/schema/errors.gql.go, backend/apid/graphql/schema/rbac.gql.go, backend/apid/graphql/schema/rbac.graphql, backend/apid/graphql/service.go, backend/apid/routers/clusterrolebindings.go, backend/apid/routers/clusterroles.go, backend/apid/routers/rolebindings.go, backend/apid/routers/roles.go, backend/store/etcd/rolebinding_store.go, backend/store/store.go, types/rbac.go
Introduce the following endpoints in `apid` to manipulate the corresponding objects:
- `/apis/rbac/v2/namespaces/{namespace}/roles`
- `/apis/rbac/v2/namespaces/{namespace}/rolebindings`
- `/apis/rbac/v2/clusterroles`
- `/apis/rbac/v2/clusterrolebindings`
Closes #2281.
=> New RBAC Endpoints

backend/apid/routers/authentication.go, cli/client/interface.go, cli/client/testing/mock_user_client.go, cli/client/user.go, cli/commands/configure/configure.go
Closes https://github.com/sensu/sensu-go/issues/2321
Add the `system:users` group upon login and token renewal so all users can _view_ themselves, which is used to validate the users credentials.
=> Use the get user endpoint to validate credentials

dashboard/src/components/partials/ChecksList/ChecksListHeader.js, dashboard/src/components/partials/EntitiesList/EntitiesListHeader.js, dashboard/src/components/partials/EventsList/EventsListHeader.js, dashboard/src/components/partials/EventsList/StatusMenu.js, dashboard/src/components/relocation/ExecuteCheckStatusToast.js, dashboard/src/components/views/EnvironmentView/EventsContent.js
Update filtering to use ES5 expressions instead of govalutate.
Closes https://github.com/sensu/sensu-go/issues/2309
> Move fast and break things
Regression was introduced prior to the last beta release.
=> [Web UI] Update filtering to use JS expressions

backend/apid/graphql/globalid/entity.go, backend/apid/graphql/globalid/handlers.go, backend/apid/graphql/globalid/silences.go, graphql/resolvers.go, graphql/resolvers_test.go
Ensure default GraphQL resolver can traverse embedded structs.
Previously implementation would would stop traversing parent if an embedded struct was encountered.
Regression was introduced prior to last release.
Pulled in test cases from https://github.com/jamesdphillips/graphql.
=> ensure default resolver can traverse embedded structs

CHANGELOG.md, backend/cmd/start.go, backend/messaging/message_bus.go, backend/messaging/wizard_bus.go, backend/messaging/wizard_bus_test.go, backend/messaging/wizard_topic.go, backend/monitor/monitor_test.go, backend/monitor/supervisor.go, backend/ring/ring.go, backend/schedulerd/round_robin_scheduler.go, backend/schedulerd/round_robin_scheduler_test.go, docker-compose.yaml, testing/mockbus/mock.go, util/strings/strings.go, util/strings/strings_test.go
```
Fix resource leaks in the monitor and ring.
This commit fixes a goroutine leak in the supervisor, where each
monitor would create a goroutine that would never terminate until
the end of the program. It also adds some code that guards against
watchers that are still waiting on events after the TTL has been
reached.
This commit also fixes a goroutine leak in the ring, where Next
calls would build up over time. Now, Next calls will last no
longer than the check interval duration they are associated with.
```
Closes #2314
=> Fix resource leaks in the monitor and ring.

CHANGELOG.md, dashboard/src/components/partials/EventDetailsContainer/EventDetailsCheckResult.js, dashboard/src/components/partials/EventDetailsContainer/EventDetailsSummary.js, dashboard/src/components/partials/EventDetailsContainer/EventDetailsToolbar.js
Closes #2312 
- Removes re-run button from the event details page for keepalive events
- Removes links to keepalive check details page from the event details page because it would 404
Stability
Sure
=> [Web UI] Event Details keepalive improvements

CHANGELOG.md, backend/store/etcd/check_store.go, backend/store/key_builder.go, backend/store/key_builder_test.go
Resources from namespaces that share a common prefix, eg: "sensu" and
"sensu-devel", could be listed together.
This was due to a bug with key construction and key prefix usage in the
etcd client.
Closes #2371.
Yes, added.
No.
=> Fix object listing in namespaces

dashboard/.eslintrc.yml, dashboard/src/components/CodeHighlight/CodeHighlight.js, dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsConfiguration.js, dashboard/src/components/partials/ChecksList/ChecksListItem.js, dashboard/src/components/partials/EntityDetailsContainer/EntityDetailsInformation.js, dashboard/src/components/partials/EventDetailsContainer/EventDetailsSummary.js
Refactor the `<CodeHighlight>` component so that it does not require using the `dangerouslySetInnerHTML` prop at each instance.
This allows us to leave the `react/no-danger` lint rule enabled to catch other potential issues elsewhere.
No
No
No
No
=> [Web UI] Remove global `react/no-danger` suppression

CHANGELOG.md, cli/commands/create/create.go, cli/commands/filter/help.go
Remove the filter when feature until time windows have been fixed.
closes #2384
=> Remove filter-when support temporarily

CHANGELOG.md, agent/agent.go, agent/agent_test.go, agent/timeproxy_test.go, util/retry/retry.go
This commit fixes a bug in the agent where the send queue could
fill up with keepalives after a long period of disconnection. On
successful reconnection, the agent would try to send an immediate
keepalive, before returning control to the event loop responsible
for normal operation. This operation would block forever, resulting
in deadlock.
Agents will now only buffer a single keepalive; when the agent
reconnects, instead of sending multiple keepalives, it will send
only one, regardless of how much time has progressed.
This commit also fixes a bug in the retry library, where the
MaxDelayInterval parameter was not considered in computing the
amount of time to wait before retrying.
Finally, the agent's retry timeout has been adjusted. The agent
will retry on the following schedule:
10 ms, …
=> Fix a deadlock in the agent

CHANGELOG.md, util/logging/logging.go
Checks event.Check for nil before adding check fields
Closes #2407
Yes
=> Fix a nil panic when logging non-check events

dashboard/src/components/partials/SilencesList/SilencesList.js, dashboard/src/components/partials/SilencesList/SilencesListHeader.js, dashboard/src/components/partials/SilencesList/SilencesListItem.js
Closes #2382 
Implements ClearSilencesDialog in a slightly different manner, removes a console error and a potential memory leak (according to the error).
Made the code a bit more DRY, and removed error and potential memory leak.
Not this time.
=> [Web UI] SilencesList silence confirmation error removal

CHANGELOG.md, dashboard/src/components/partials/ChecksList/ChecksListHeader.js, dashboard/src/components/partials/ChecksList/ChecksListItem.js, dashboard/src/components/partials/EventsList/EventsListHeader.js, dashboard/src/components/partials/EventsList/EventsListItem.js
Closes #2410
Removes the ability to re-run keepalives from the events and checks list
We don't have a way to do this at this point in time, so it causes an exception in the frontend.
Added one
Disabling the button instead of not rendering it solves this ~There's some weirdness if you are doing bulk actions, the list header icon for re-run is removed if you add a keepalive to the selected items. However, if you unselect that keepalive the re-run button does not return unless you deselect the whole list. I'm open to suggestions on how to correct this.~
=> [Web UI] Remove re-run keepalives on Events and Checks List

api/core/v2/adhoc.go, api/core/v2/adhoc.pb.go, api/core/v2/adhoc.proto, backend/apid/graphql/mutations.go
This commit adds ObjectMeta to AdhocRequest. For an AdhocRequest
to identify a check uniquely, it needs this information. The
GraphQL resolver has also been updated as part of this change.
=> Add ObjectMeta to AdhocRequest

CHANGELOG.md, backend/monitor/supervisor.go
This allows monitor TTLs to be set to 0, which will cause a monitor to immediately fail and send a failing event on startup instead of panicking.
closes #2406 
Added.
=> Grepory/monitor panic#2406

backend/seeds/seeds.go
This allows any user to implicitly list the namespaces and prevent
issues in the current implementation of the dashboard.
Closes #2418 
No.
No.
No.
No.
=> Add list namespaces rule to system:user cluster role

CHANGELOG.md, backend/monitor/supervisor.go
This properly stores monitors in the entity namespace in etcd.
closes #2432
=> Namespace keepalive and check ttl monitors

backend/apid/routers/users.go
Ensure that a user's groups can be updated. 
The addition of API groups conflicted with the existing named path component, causing all updates to result in the user having their assigned groups be `[]string{"core"}`.
Issue was introduced prior to the last release.
=> Fix user group management

backend/apid/apid.go, backend/apid/graphql/fetch.go, backend/apid/graphql/namespace.go, cli/client/asset.go, cli/client/entity.go, cli/client/filter.go, cli/client/handler.go
Updates the GraphQL service to drop `PermissionDenied` errors when resolving fields that list resources. Selecting a field shouldn't result in an error unless something unrecoverable occurred.
In the future, we will need a method of retrieving permissions so that the UI can communicate lack of permission properly.
**NOTE** this should not be conflated with displaying resources despite lack of permission; we simply return an empty list in lieu of the error.
Without this change the exception modal is displayed in the web application when a user navigates to a page with resources they do not have access to.
unlikely.
=> GraphQL service unauthorized err

CHANGELOG.md, backend/schedulerd/round_robin_scheduler.go, backend/schedulerd/round_robin_scheduler_test.go
Per https://github.com/sensu/sensu-go/issues/2444, we are temporarily
disabling round-robin scheduling. Issues with round-robin
scheduling, https://github.com/sensu/sensu-go/issues/2431 that made
us uncomfortable shipping this enabled as it can lead to a potential
deadlock in the scheduler.
closes #2444
=> Temporarily disable round-robin scheduling

dashboard/flow-typed/npm/react-apollo_v2.x.x.js, dashboard/src/apollo/client.js, dashboard/src/apollo/httpLink.js, dashboard/src/apollo/resolvers/localNetwork.js, dashboard/src/apollo/schema/client.graphql, dashboard/src/apollo/schema/combined.graphql, dashboard/src/apollo/stateLink.js
This is >probably< to be merged in after GA
Closes #2423 and #2422
Adds LocalNetwork to the Query component. LocalNetwork contains fields for offline and retry. These fields do nothing at this point in time and are an initial step towards #2103
This is to help track the state of the network better and add appropriate errors for the user.
I don't think so, when this functionality is completed in it's entirety then it would make more sense to add an entry. As of now these fields do nothing.
=> [Web UI] Network error improvements - offline and retry fields

dashboard/src/components/AppRoot.js, dashboard/src/components/util/GlobalAlert.js
This component provides a mechanism for declaring alert banners with life-cycles coupled to the current app state.
Supports the upcoming offline alert banner.
No
No
No
No
=> [Web UI] Set up GlobalAlert component

cli/client/entity.go
Fix API path used by `sensuctl entity create`.
Closes #2467
=> Fix API path used by entity create

CHANGELOG.md, backend/backend.go, backend/eventd/eventd.go, backend/eventd/integration_test.go, backend/keepalived/integration_test.go, backend/monitor/monitor_test.go, backend/monitor/supervisor.go, build.sh, docker-compose.yaml
This commit fixes a bug that caused check TTL monitors to be
aliased to keepalive monitors. The previous behaviour was that
passing keepalives would cancel out failing check TTLs, and
passing checks would cancel out failing keepalives, depending on
order of execution.
This commit also fixes a bug in check TTL where the failing check
event is not created properly.
Additionally, docker-compose has been modified so that the agents
involved use the subscriptions defined in the staging resources.
The build.sh script has been modified so that users who run
`./build.sh docker` get a newly installed sensuctl in $GOPATH/bin.
Closes #2473 
Closes #2470 
I did several test runs with docker-compose, with a set of checks that caused the problem to occur previously.
=> Fix keepalive and check TTL bugs

CHANGELOG.md, dashboard/src/components/partials/ToolbarMenu/Menu.js
Prevent unintended null reference at `event.currentTarget` by not passing the event object into the async debounce handler.
Event objects in FireFox appear to get garbage collected sooner than in other browsers. 
Updated.
No
No
No
=> [Web UI] Quick fix for FireFox resize event bug

CHANGELOG.md, cli/client/error.go
It ensures an error message is always returned in sensuctl; if the response body is empty, return the HTTP status instead. Example:
```
$ sensuctl entity create foo -c proxy
Error: the API returned: 405 Method Not Allowed
```
Closes https://github.com/sensu/sensu-go/issues/2469
Added
Nope
Nope
Nope
=> Return the response status if body is empty in sensuctl

CHANGELOG.md
A fix was unintentionally excluded from the 5.0.0 release changes.
=> Fix error in changelog

.appveyor.yml
Remove e2e tests from AppVeyor test matrix.
E2E suite was removed but AppVeyor is trying to run them.
Unlikely.
=> Remove e2e tests from appveyor test matrix

dashboard/.flowconfig, dashboard/src/components/util/Query.js, dashboard/src/components/views/EnvironmentView/CheckDetailsContent.js, dashboard/src/components/views/EnvironmentView/ChecksContent.js, dashboard/src/components/views/EnvironmentView/EntitiesContent.js, dashboard/src/components/views/EnvironmentView/EntityDetailsContent.js, dashboard/src/components/views/EnvironmentView/EnvironmentView.js, dashboard/src/components/views/EnvironmentView/EventDetailsContent.js, dashboard/src/components/views/EnvironmentView/EventsContent.js, dashboard/src/components/views/EnvironmentView/SilencesContent.js
Update the `Query` component to observe the `localNetwork` status (from #2437) and automatically restart the query subscription when online status resumes or the user requests a retry attempt.
This provides a much more polished experience for users experiencing network connection issues.
Not yet. The changelog will be updated the banner is implemented.
No.
No.
No.
=> [Web UI]  Refetch query when api connection resumes

CHANGELOG.md, dashboard/src/components/partials/EventsList/EventsList.js, dashboard/src/components/views/EnvironmentView/EventsContent.js
Displays a toast when creating an adhoc check request from the events list.
Without the toast the feedback is confusing.
Probably.
=> [Web UI] Display toast when re-running a check from events page

CHANGELOG.md, backend/backend.go
It adds the etcd client generated by the `newClient` function to the `Backend` struct so it can be reused by the enterprise edition.
Related to https://github.com/sensu/sensu-go/issues/2499.
Required by https://github.com/sensu/sensu-enterprise-go/issues/151.
Added
There's a couple of ways we could have fixed this issue, for example the `Initialize` function could also return the etcd client or we could make the `newClient` function public. I don't have any strong opinion.
Nope
Nope
=> Add the etcd client to the backend struct

.appveyor.yml, build.ps1
The backend is unsupported on Windows. Also disables 386 tests for
Windows.
=> Do not build or test the backend for windows

backend/apid/graphql/entity.go, backend/apid/graphql/entity_test.go, backend/apid/graphql/schema/entity.gql.go, backend/apid/graphql/schema/entity.graphql
Updates the GraphQL service's entity status field to use the uint type.
* Windows exit codes are represented as unsigned 32bit integers.
* Discovered while attempting to replicate #2514 
Likely covered by the last entry.
=> Change the entity's status field to use uint type

CHANGELOG.md, backend/pipelined/handle.go, backend/pipelined/mutate.go
Fixes https://github.com/sensu/sensu-go/issues/2522.
Please review & merge https://github.com/sensu/sensu-go/pull/2519 before this PR.
Adds the backend's environment to handler & mutator execution requests.
While attempting to figure out why some checks were not executing on Windows agents, we found a regression in which backend's environments were not being included in handler & mutator execution requests.
Yup!
No new documentation required. This was supposed to be the expected behaviour.
=> Add backend environment to handler & mutator execution requests

CHANGELOG.md, backend/store/etcd/asset_store.go
When querying for a list of assets, instead of returning nil when there
are none to be returned, we return an empty slice of results instead.
This is to be in line with the behaviour of all the other object stores
and ensure a consistent behaviour across all the types.
Closes #2509.
Ensure a more consistent behaviour across the different stores. 
Yes.
Changelog entry added. 
Not needed.
=> Return empty slice instead of nil for assets

CHANGELOG.md, api/core/v2/hook.go
Update `Hook.URIPath()` to reflect the recent API re-rooting and namespaces changes. This change, which was missed during that last API re-work, allows `sensuctl create -f` to work with objects of type `Hook`, instead of generating an error after trying to hit a non-existent endpoint.
Closes #2510.
Yes; changelog entry added.
No documentation changes are needed. This is how `sensuctl create -f` used to work all along.
=> Allow hook creation with sensuctl create -f

CHANGELOG.md, dashboard/src/icons/Error.js, dashboard/src/icons/OK.js, dashboard/src/icons/Unknown.js, dashboard/src/icons/Warn.js
Fixes a bug where Firefox wouldn't properly render the entire status icon. The mask is used to apply the silence icon. However when there was no silence it would apply an empty mask and cause the side to be clipped.
The icons were messed up and didn't look good.
Added one
=> [Web UI] Fix firefox rendering bug

backend/monitor/monitor_test.go, backend/monitor/supervisor.go
This commit fixes a bug in the monitor that causes failing events
to be emitted on a schedule determined by the final TTL before
failure, instead of the check or keepalive interval. This could
cause a panic to occur when a backend was started after a cold
period.
Closes #2545 
No, since this issue was caused by a commit in the same milestone.
=> Use interval, not ttl, for keepalive event refresh

CONTRIBUTING.md, README.md
Sensu is and always will be open source, and we continue to highly value community contribution. The packages we’re releasing for new versions are from our Enterprise repo; Sensu Go is the upstream for Sensu Enterprise (as they’d say in the Go community: Sensu Go is vendored into the Sensu Enterprise Go repo). We encourage you to download new versions, as the functionality will be identical to what you find in the public repo, and access to the enterprise-only features can be unlocked with a license key. Because these releases are in our Enterprise repo, there may be times that you don’t see the actual work being done on an issue you open, but that doesn’t mean we’re not working on it! Our team is committed to updating progress on open issues in the sensu-go repo, even if that work is …
=> Updated contributing details for Enterprise packaging clarity/transparency

CHANGELOG.md, backend/schedulerd/check_scheduler.go, backend/schedulerd/check_scheduler_test.go, backend/schedulerd/check_scheduler_unit_test.go, backend/schedulerd/check_watcher.go, backend/schedulerd/check_watcher_test.go
Consolidates the `CheckScheduler` struct. Cleans up the check scheduler `schedule` function. Persists the check's timer if the schedule has not been updated (per 1.x parity). Special cases the interrupt issued by the check water to determine if the timer must be reset.
Closes https://github.com/sensu/sensu-go/issues/2550.
Yas.
Nah.
Nah.
We good.
=> Fix a bug in the check scheduler where a check would immediately fires if updated

backend/etcd/etcd.go, backend/liveness/liveness.go, backend/liveness/liveness_test.go, backend/store/namespace.go
Package liveness uses keepalives to determine liveness of
entities. It emits events corresponding with state changes.
(Alive -> Alive, Alive -> Dead, Dead -> Alive, Dead -> Dead)
The events that the SwitchSet emits are handled by the functions
passed to it with NewSwitch. The handlers will receive the key
of the entity, as well as the previous state of the entity.
=> Add package liveness

CHANGELOG.md, agent/check_handler.go, agent/transformers/graphite.go, agent/transformers/graphite_test.go, agent/transformers/influx_db.go, agent/transformers/influx_db_test.go, agent/transformers/logger.go, agent/transformers/nagios.go, agent/transformers/nagios_test.go, agent/transformers/opentsdb.go, agent/transformers/opentsdb_test.go, agent/transformers/transformer.go
- Parse functions accept an Event as a parameter.
- Parse functions log errors rather than returning them.
- Transformers do not abort metric extraction when a bad line is encountered.
- Fixes bugs associated with https://github.com/golang/go/wiki/CodeReviewComments#declaring-empty-slices.
Closes https://github.com/sensu/sensu-go/issues/2511
Yas.
Nah.
Nah.
We good.
=> Fixes a bug where a bad line in check output would abort metric extraction

backend/apid/routers/authentication.go, backend/apid/routers/authentication_test.go, cli/client/authentication.go, cli/client/interface.go, cli/client/testing/mock_authentication_client.go, cli/commands/user/help.go, cli/commands/user/test-creds.go, cli/commands/user/test-creds_test.go
Provide a Backend API endpoint for testing User credentials (username & password). This pull-request allows automation tooling to check if user credentials it has on record are still valid and manage the user accordingly (e.g. reset or rotate the user password).
A possible solution for https://github.com/sensu/sensu-go/issues/1437
Signed-off-by: Sean Porter <portertech@gmail.com>
closes #1437
=> API authentication credential test endpoint

CHANGELOG.md, cli/client/entity.go
Adds error checking and handling to the entity rest client used by sensuctl.
Closes https://github.com/sensu/sensu-go/issues/2598.
Yas.
Nah.
Nah.
We good.
https://github.com/sensu/sensu-go-qa-crucible/issues/5
=> Add better error checking/handling to entity cli client

CHANGELOG.md, api/core/v2/token.go, api/core/v2/typemap.go, backend/apid/apid.go, backend/apid/middlewares/allowlist.go, backend/apid/middlewares/allowlist_test.go, backend/apid/middlewares/authentication_test.go, backend/apid/middlewares/refresh_token_test.go, backend/apid/routers/authentication.go, backend/apid/routers/authentication_test.go, backend/apid/routers/graphql.go, backend/authentication/jwt/jwt.go, backend/authentication/jwt/jwt_test.go, backend/authentication/providers/LICENSE, backend/authentication/providers/basic/LICENSE, backend/authentication/providers/basic/basic.go, backend/authentication/providers/logger.go, backend/authentication/providers/providers.go, backend/backend.go, backend/daemon/daemon.go, backend/store/etcd/token_store.go, backend/store/etcd/token_store_test.go, backend/store/etcd/user_store.go, backend/store/etcd/user_store_test.go, backend/store/store.go, cli/commands/check/execute_test.go, cli/commands/configure/configure.go, testing/mockstore/token.go
This change introduces the notion of authentication providers and move all the current authentication logic into a `basic` authentication provider.
In details:
- Authentication providers have two main methods; `Authenticate` & `Refresh`. The former is used to authenticate a user with a username/password combinaison and the latter is used to renew the user claims (mainly groups) without the password.
- The JWT claims now contain a `ProviderClaims` struct, which informs us of the provider used to authenticate the user and its username (which might differs from the username used by Sensu).
- This is useful for renewing the user claims during the renewal of an access token
- Added the notion of an `Authenticator` to apid.
- It has the knowledge of all enabled authentication providers and it …
=> Add Authentication Providers

CHANGELOG.md, backend/store/etcd/clusterrole_store.go, backend/store/etcd/clusterrolebinding_store.go, backend/store/etcd/role_store.go, backend/store/etcd/rolebinding_store.go, backend/store/etcd/store.go, backend/store/etcd/store_test.go
It modifies previously private generic store methods into public functions, so they can be used from the enterprise codebase.
Required by https://github.com/sensu/sensu-enterprise-go/issues/184.
Added
Nope!
Nope!
Nope!
Nope!
=> Generic store functions

.circleci/config.yml, CHANGELOG.md
It removes an used workflow named `rel_build_and_test`, which relies on `beta` tags.
Simple cleanup.
Added
Nope!
Nope!
Nope!
Nope!
=> Removed unused workflow in CircleCI

CHANGELOG.md, agent/check_handler.go, agent/check_handler_internal_test.go, agent/hook_test.go, testing/mockexecutor/executor.go
This commit fixes a bug where otherwise-identical proxy checks
would prevent each other from executing, due to a deduplication
check that involved only the check name.
The duplicate check execution guard now also takes proxy entity
name into consideration.
Closes #2612 
Included
No
These changes bring the proxy check feature in line with what the docs describe.
Added
=> Fix a bug in proxy check execution

build/ci/circle-ci-setup.sh
It pins childprocess to v0.9.0, due to https://github.com/jordansissel/fpm/issues/1592.
So CI does not fail.
Added
Nope!
Nope!
Nope!
Nope!
=> Fix CI failure due to fpm installation

CHANGELOG.md, agent/check_handler.go, agent/check_handler_env_test_unix.go, agent/check_handler_env_test_windows.go, agent/check_handler_internal_test.go, agent/hook.go
To guard against publishing sensitive/redacted client attribute values,
always use the original command and hook values.
Matches functionality in Sensu Classic, see [comment](https://github.com/sensu/sensu/blob/44f58ebdc6881161b34c67feaff572650d0b0ded/lib/sensu/client/process.rb#L172-L174) and [implementation](https://github.com/sensu/sensu/blob/44f58ebdc6881161b34c67feaff572650d0b0ded/lib/sensu/client/process.rb#L185-L186).
Closes #2643 
Yeah.
Nada.
Hubris.
No.
Maybe!
=> Omit substituted values command & check hook values

CHANGELOG.md, backend/keepalived/keepalived.go, backend/keepalived/keepalived_test.go
This commit fixes a case in keepalived where the backend could
crash if the system was unable to find an event it expected to be
able to find. Now, if the backend is unable to find the event, an
error is logged and the keepalive processing terminates early.
Closes #2638 
Added a unit test and also a testrails QA test.
I made sure the same problem did not exist in eventd for check TTL.
=> Fix a bug in keepalived that could result in a crash

CHANGELOG.md, backend/store/etcd/store.go, backend/store/etcd/store_test.go
Fixes a bug where generic store methods assumed a namespace was provided for non-namespaced resources.
Required by sensu-enterprise-go ticket.
Yas.
Nah.
Nah.
We good.
We good.
=> Non-namespaced resources shouldn't return ErrNamespaceMissing

CHANGELOG.md, dashboard/src/components/partials/EntityDetailsContainer/EntityDetailsInformation.js
Closes #2651 
Adds the platform version to the entity details page. 
We should show this value. It's also listed on the entity list page.
Added one
=> [Web UI] Add platform version to entity details page

CHANGELOG.md, api/core/v2/provider.go, backend/apid/routers/authentication.go, backend/apid/routers/authentication_test.go, backend/authentication/authenticator.go, backend/authentication/providers/basic/basic.go, backend/backend.go, backend/store/etcd/store.go, cli/client/generic.go, cli/client/interface.go, cli/client/testing/mock_generic.go, cli/commands/create/create.go, cli/commands/edit/edit.go
This PR adds support for resources stored using the wrapper.
Specifically:
- The API authenticator now identifies providers using their name only
- `sensuctl create` & `sensuctl edit` have been modified so they send resources as `types.Wrapper` to the API for all API groups except `core/v2`, where it still sends `corev2.Resource`.
- It exports `KeyBuilderFn` so it can be re-used in the enterprise store
Required by https://github.com/sensu/sensu-enterprise-go/pull/201
Nope!
Nope!
Not required for now.
Not yet.
=> Add support for wrapped resources storage

CHANGELOG.md, backend/eventd/eventd.go, backend/eventd/integration_test.go, backend/keepalived/keepalived.go, backend/liveness/liveness.go, backend/liveness/liveness_test.go
This commit fixes bugs in keepalived and eventd, where entities
that have been removed by the user will continue to be partially
registered.
This had the effect of using up extra space in etcd, and writing
out extra logs, but was otherwise inconsequential.
Closes #2682 
Added
Test case added.
=> Ensure dead entities are buried when appropriate

CHANGELOG.md, cli/commands/helpers/prompts.go, cli/commands/user/delete.go
Fixes copy displayed to user when attempting to disable another user with `sensuctl`.
Closes #2677 
Why not.
no.
not really.
no changes required.
unlikely.
=> Fix copy displayed when disabling users with sensuctl

CHANGELOG.md, dashboard/src/components/partials/EntityDetailsContainer/EntityDetailsInformation.js
Reflect deregistration configuration on entity details.
Closes #2669 
oui
non
non
non
non
=> [Web UI] Reflect deregistration configuration on entity details

backend/apid/apid.go
Use TLS client config when configuring GraphQL service; otherwise skip verify option is not copied.
=> Use TLS client config when configuring GraphQL service

CHANGELOG.md, agent/agent.go, agent/entity.go, agent/entity_test.go, agent/event.go, agent/event_test.go, agent/timeproxy_test.go, api/core/v2/event.go, types/v1/check.go
This commit adds the Handlers field to v1.CheckResult, bringing us
in line with 1.x behaviour for the client socket.
The commit also cleans up a bit of the agent package, by avoiding
the use of pointers for concurrency primitives in the Agent type.
This makes it easier to write tests that rely on the Agent, since
people won't forget to initialize mutexes and waitgroups.
Finally, the use of timeproxy in the tests has been adjusted to
use a non-zero unix time.
Closes #2691
Added
There were no existing unit tests for the function that converts v1.CheckResult to v2.Event.
I've filed an issue for sensu-docs to clarify the intent of the socket feature.
I added several test cases, and I also did QA to make sure that handlers execute when events are sent via the agent socket.
=> Add handlers to v1.CheckResult

.gitignore, CHANGELOGS/unreleased/2700-strengthen_TLS_security_posture.md, api/core/v2/tls.go, backend/agentd/agentd.go, backend/apid/apid.go, backend/cmd/start.go, backend/dashboardd/dashboardd.go, backend/etcd/etcd.go, transport/client.go
Enforces stronger TLS settings
To mitigate known TLS vulnerabilities. The existing TLS settings were affected by:
```
LUCKY13 (CVE-2013-0169)  - uses cipher block chaining (CBC) ciphers with TLS.
SWEET32 (CVE-2016-2183, CVE-2016-6329)  - VULNERABLE, uses 64 bit block ciphers
BEAST (CVE-2011-3389) - TLS1: ECDHE-RSA-AES128-SHA
ECDHE-RSA-AES256-SHA
AES128-SHA AES256-SHA
ECDHE-RSA-DES-CBC3-SHA
DES-CBC3-SHA 
```
it's transparent (app functionality is no changed), but perhaps it should be mentioned?
no, but if a reviewer is not super familiar with TLS, I offer the explanation(s) below:
- min version of TLS 1.2 is being offered in order to ONLY support the best possible ciphers
- `DefaultCipherSuites` was modified to remove CBC ciphers and non-TLS_1.2 ciphers. This list now ONLY includes …
=> closes #2657 - strengthen our TLS security posture

.appveyor.yml
Updates the Go version on AppVeyor to 1.11.5.
We're testing & building on Go 1.11.5 on Circle and this change brings AppVeyor in sync.
Nope!
Nope!
Nope!
No documentation updates required.
Using this PR to test.
=> Update Go on AppVeyor to 1.11.5

CHANGELOG.md, dashboard/src/components/partials/EventDetailsContainer/EventDetailsCheckResult.js, dashboard/src/components/partials/EventDetailsContainer/EventDetailsCheckSummary.js, dashboard/src/components/partials/EventDetailsContainer/EventDetailsContent.js, dashboard/src/components/partials/EventDetailsContainer/EventDetailsEntitySummary.js, dashboard/src/components/partials/EventDetailsContainer/EventDetailsSummary.js
Closes #2666 
Adds several missing fields to the event details page. Fields for both the check config and the entity.
We wanted to show more information on the details page.
Yes.
We will likely need to discuss if anything can be removed or if we need to rearrange the way the data is displayed. What items should be initially hidden, etc.
Additionally, some information isn't displayed at all yet in the web ui but was requested in the ticket - `state`, `total_state_change`, etc. I did not add them yet, as it might make more sense for them to be displayed in the respective details pages first.
Trying to decide what information to display and what to hide was challenging for me. I'd like to discuss this further as mentioned above.
Manual testing. Our test cases should cover these changes.
=> [Web UI] Add additional info to event details page

CHANGELOG.md, dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsConfiguration.js
Closes #2734 
Uses a code block to prevent breakage when the command gets too long.
It broke before 
Yes
Manually tested. There is a still a test case for this in TestRail.
=> Use codeblock to prevent breakage

CHANGELOGS/unreleased/2745-bugfix_asset_fetcher.md, asset/fetcher.go
This commit instructs the asset fetcher to not apply any HTTP
client timeout when fetching assets. Previously, assets that took
longer than 30s to download would retry until they took less than
30s to download.
Buffering has also been added, which should improve the performance
of asset downloads.
Closes #2745 
Yes
Verified manually by Jef.
=> Don't set a timeout for asset downloads

CHANGELOGS/unreleased/2735-entity-subscription-bugfix.md, agent/cmd/start.go
This commit fixes a bug where agents were sending the wrong
subscriptions in entities, as they would not be split properly
before being sent to the config.
Due to a quirk in how subscriptions are handled, this doesn't
affect any current scheduling mechanism. Nevertheless,
subscriptions must be properly stored in entities, especially for
future work that depends on entity details being correct.
Closes #2753 
Yes
No doc changes required.
Manual verification.
=> Split agent subscriptions properly in CLI flags

CHANGELOG.md, dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsConfiguration.js
Actually fixes the command values not scrolling when you have a really long string with no spaces.
Actually addresses #2734. My fix earlier this week #2764 did not actually fix the issue.
It was broken and my original fix didn't actually fix it.
There's already one in there from my previous attempt at a fix.
This is sort of a hack. I had to move the command to the right side of the table to make it work. I have talked with another engineer about how we should rework the grid system for better scaling and issues like this. Therefore I couldn't implement a perfect solution today as we would like to do that at a later date.
=> [Web UI] Actually fix command wrapping on Check Details Page

CHANGELOGS/unreleased/2636-event-timestamp.md, api/core/v2/event_test.go, backend/store/etcd/event_store.go, backend/store/etcd/event_store_test.go
Events that are sent to the store with a zero value as a timestamp
will now be given the current time instead.
Closes #2636 
Integration test
=> Don't store events with a zero timestamp

CHANGELOG.md, dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsConfiguration.js, dashboard/src/components/partials/EventDetailsContainer/EventDetailsCheckSummary.js
Closes #2781 
Adds some scrolling for commands on the events page. Also formats the value in the case of null commands (keepalives)
Displays nicer, matches the scrolling we have on the checks page
Added one
=> [Web UI] Format command on event details page

dashboard/.eslintrc.yml, dashboard/package.json, dashboard/yarn.lock
Update `eslint-config-prettier` to v4.1.0; alleviates linter errors introduces after update `prettier`.
The package provides us with,
* verification that prettier was run or code matches prettier's style,
* by virtue of integrated into eslint provides nice error messages and editor support,
* disables any rules that conflict with prettier's style.
Purely related to devtooling, so may not be relevant.
No.
No.
No updates required.
`yarn lint`
=> Update eslint-config-prettier to v4.1.0

CHANGELOGS/unreleased/2817-creator-exception.md, backend/apid/graphql/schema/silenced.gql.go, backend/apid/graphql/schema/silenced.graphql, dashboard/src/components/partials/ClearSilencedEntriesDialog/Dialog.js, dashboard/src/components/partials/SilencesList/SilencesListItem.js, dashboard/src/components/partials/TableToolbarCell/FloatingTableToolbarCell.js
Handle case where the creator of a silence is inaccessible.
Creator can be inaccessible if the current user does not have read access for users or if the creator's user no longer exists.
Yup!
No.
No.
Yes, and no additional documentation is required.
Manually created a user with limited permissions and attempted to view silences.
=> [Web] Handle case where creator is inaccessible

CHANGELOGS/unreleased/2743-dinnae-store-metrics.md, backend/store/etcd/event_store.go, backend/store/etcd/event_store_test.go
This commit explicitly nils out metrics when events arrive at the
store, in order to ensure that metrics are never stored in etcd.
Care is taken to not write to the pointer that is given to the
store. To this end, some unrelated existing code in the same
UpdateEvent method has also been modified to be safer.
Closes #2743 
Included
This change brings us in line with the documentation.
A new integration test.
=> Don't allow metrics to be stored in any case

dashboard/config/app.webpack.config.js, dashboard/config/base.webpack.config.js, dashboard/config/lib.webpack.config.js, dashboard/config/vendor.webpack.config.js, dashboard/package.json, dashboard/scripts/serve.js, dashboard/src/app/component/partial/ToolbarMenu/Partitioner.js, dashboard/src/app/component/views/EventsContent.js, dashboard/yarn.lock
Reintroduce the web-ui dev server that was removed in #2822.
Developper sanity 😄 
No.
While this improves things, it is still not an ideal solution. In order to enable live-recompilation of changes to the `lib` bundle code, the DLL build is disabled in development. Only a single bundle is build containing the contents of what becomes multiple bundles in a final build. This shouldn't introduce any functional differences between dev and prod builds - but there's always the chance for some random side effect to appear in dev 🙃.
No.
=> [Web UI] Set up dev-server for app bundle

CHANGELOG.md, CHANGELOGS/unreleased/2829-fixup-find-user.md, backend/apid/routers/users.go, backend/apid/routers/users_test.go
Checks that the response from the controller was not nil before attempting to obfuscate the user's password. Previously this would lead to a panic, closing the end user's connection without a response.
Closes #2828
Yup!
Nada.
No.
None required.
* unit tests
* manual testing
=> [Api] Return 404 when user is not found for given name

CHANGELOGS/unreleased/2722-seperate_TLS_config_for_dashboard.md, backend/backend.go, backend/cmd/start.go, backend/config.go
Signed-off-by: gbolo <george.bolo@gmail.com>
See #2642
In the chance that someone would like to present a different certificate on the dashboard port
yes
there are two new flags. The behaviour of omitting the flags is the same as the previous release (backwards compatible). Is this desired?
no
I have not updated the docs yet, this change will require that.
would be nice, I did not include one yet.
=> closes #2642 separate TLS config for dashboard

dashboard/src/lib/component/base/AppLayout/AppLayout.js
Add a `fullWidth` prop to the `AppLayout` component.
Required for https://github.com/sensu/sensu-enterprise-go/pull/291
=> [Web UI] Allow AppLayout component to be full width

CHANGELOGS/unreleased/2791-tessen-daemon.md, CHANGELOGS/unreleased/2792-tessen-etcd-watcher.md, api/core/v2/tessen.go, api/core/v2/tessen_test.go, backend/apid/actions/tessen.go, backend/apid/actions/tessen_test.go, backend/apid/routers/tessen.go, backend/apid/routers/tessen_test.go, backend/backend.go, backend/store/etcd/tessen_store.go, backend/store/etcd/tessen_store_test.go, backend/store/etcd/watchers.go, backend/store/store.go, backend/tessend/LICENSE, backend/tessend/data.go, backend/tessend/logger.go, backend/tessend/tessend.go, backend/tessend/tessend_test.go, testing/mockstore/hook_config.go, testing/mockstore/tessen.go
Implements TessenD and TessenConfig watcher 🎉 Does not yet implement the ring, so right now every backend in the cluster will send data. Removes the unused hook config watcher.
Closes https://github.com/sensu/sensu-go/issues/2792
Closes https://github.com/sensu/sensu-go/issues/2791
Yas.
Nah.
Nah.
Nope!
See the [Tessen Chronograf](https://calvinklein-c257063e.influxcloud.net/sources/0/dashboards/3?lower=now%28%29%20-%2015m). TestRail tests will be added at the completion of the feature.
=> Implement tessend and etcd watcher

CHANGELOGS/unreleased/2799-proxy-request-logging.md, backend/schedulerd/proxy_check.go
Added more verbose logging to indicate when a proxy request matches an entity according to its entity attributes.
=> Added more verbose logging for proxy requests

backend/apid/graphql/silenced_test.go
Remove test case that verifies a removed method.
I broke `master`. Womp Womp.
```
--- FAIL: TestSilencedTypeCreatorField (0.00s)
<autogenerated>:1: 
Error Trace:    silenced_test.go:24
Error:          Received unexpected error:
unable to coerce value for field 'creator'
Test:           TestSilencedTypeCreatorField
FAIL
```
https://circleci.com/gh/sensu/sensu-go/3392
Largely irrelevant, so probably not.
No.
Not really a "complication" but it is odd that the CI didn't catch this in my [branch](https://github.com/sensu/sensu-go/pull/2843/checks).
None.
=> Remove test case for removed method

CHANGELOGS/unreleased/2847-add-put-mutation.md, backend/apid/graphql/error.go, backend/apid/graphql/mutations.go, backend/apid/graphql/mutations_test.go, backend/apid/graphql/node.go, backend/apid/graphql/schema/errors.graphql, backend/apid/graphql/schema/mutations.gql.go, backend/apid/graphql/schema/mutations.graphql, backend/apid/graphql/service.go, graphql/service.go
Adds a generic mutation that takes a wrapped resource, stores it and returns the new resource.
schema changes in brief,
```graphql
type PutWrappedPayload {
resource: Node
errors: [Error!]!
}
type Mutation {
putWrapped(raw: string!): PutWrappedResourcePayload!
}
```
example usage
```graphql
mutation AddCheck {
putWrapped(raw: ```
{
"metadata": {
"type": "CheckConfig",
"name": "test"
},
"spec": {
// ...
},
// ...
}
```) {
resource {
__typename
... on CheckConfig {
id
command
}
}
errors {
code
}
}
}
```
Closes sensu/sensu-enterprise-go#315.
Yes.
No.
The `StandardError` type was not working properly, which led to a painful amount of debugging.
No.
Unit tests & manual testing.
=> [GraphQL] Add generic put mutation

CHANGELOGS/unreleased/2849-add-wrapped-field.md, backend/apid/graphql/query.go, backend/apid/graphql/schema/schema.gql.go, backend/apid/graphql/schema/schema.graphql
Add field to Query type to retrieve the wrapped representation of any type.
Usage
```graphql
query FetchWrapped($id1: ID!, $id2: ID!, $id3: ID!) {
fetchForEditing:  wrappedNode(id: $id1)
toSensuctlCreate: wrappedNode(id: $id2)
anotherAlias:     wrappedNode(id:$id3)
}
```
Example response
```json5
{
"data": {
"fetchForEditing": {
"type": "CheckConfig",
"api_version": "core/v2",
"metadata": {
"name": "my-ttl-check",
"namespace": "sensu-devel"
},
"spec": {
// ...
},
"toSensuctlCreate": {
"type": "Asset",
// ...
},
"anotherAlias": {
"type": "WhateverYouDream",
// ...
},
},
}
```
Closes sensu/sensu-enterprise-go#316
Yup
No
Nada
No
=> [GraphQL] Query for wrapped resource

CHANGELOGS/unreleased/2720-add-source-agent-socket.md, CHANGELOGS/unreleased/2720-rename-source-agent-socket.md, agent/agent.go, agent/cmd/start.go, agent/event.go, agent/event_test.go, agent/sockets.go, agent/sockets_test.go, types/v1/check.go
Changes the 1.x `client` field to `source` in the 1.x compatible agent socket. The `client` field is now deprecated.
Closes https://github.com/sensu/sensu-go/issues/2720.
Yas.
Nah.
Filed https://github.com/sensu/sensu-go/issues/2873 after discussing the agent socket with @cwjohnston.
https://github.com/sensu/sensu-docs/issues/1356
1. Run `echo '{"name": "check", "status": 1, "output": "error!", "client":"client"}' | nc localhost 3030`
- An event `client/check` is created
- `event.check.proxy_entity_name=client`
- A proxy entity `client` is created
2. Run `echo '{"name": "check", "status": 1, "output": "error!", "source":"source"}' | nc localhost 3030`
- An event `source/check` is created
- `event.check.proxy_entity_name=source`
- A proxy entity …
=> Deprecates client in favor of source in the agent socket

CHANGELOG.md, CHANGELOGS/unreleased/2554-entity-annotations.md, agent/cmd/start.go, agent/config.go, agent/entity.go
Closes #2554 by adding entity annotations to agent (via command line and agent.yml).
Support for entity annotations is referenced several times, even in existing handlers (such as the [Slack Handler](https://github.com/sensu/sensu-slack-handler).  But there exists no way to actually populate the annotations on the entity.
Yes.
Possibly.  In the entity view in the web dashboard, annotations are displayed in a CodeBlock in JSON list format.  Labels are displayed similar to how they are referenced for token substitution in checks (Label | Value).  With multiple annotations, this might not be the most attractive way to surface them in that view.
No.
Yes.  PR will be submitted.
Compiled and ran in my existing environment.  Verified that `sensuctl entity info [entity name]` displayed the …
=> Entity annotations

CHANGELOG.md, agent/cmd/start.go
This PR fixes the `--annotations` & `--labels` flags with a workaround, since the actual problem in viper is still present: https://github.com/spf13/viper/issues/608.
Closes https://github.com/sensu/sensu-go/issues/2357
Added.
Nope!
Nope!
Nope!
Manually tested:
```bash
$ sensu-agent start --labels foo=bar
$ sensuctl entity info whisky.local --format json | jq -r '.metadata.labels'
{
"foo": "bar"
}
$ sensu-agent start -c agent.yml
$ sensuctl entity info whisky.local --format json | jq -r '.metadata.labels'
{
"baz": "qux"
}
$ sensu-agent start -c agent.yml --labels foo=bar
$ sensuctl entity info whisky.local --format json | jq -r '.metadata.labels'
{
"foo": "bar"
}
```
```bash
$ sensu-agent start --annotations foo=bar
$ sensuctl entity info …
```
=> Bugfix for annotations & labels flags

graphql/integration/service_test.go, graphql/integration/testdata/schema-kitchen-sink.gql.go, graphql/integration/testdata/schema-kitchen-sink.graphql, graphql/service.go
Ensures that all types are registered.
Types that are not directly referenced by the root Schema type or any of
their children are not immediately registered with the schema. As such to
ensure that ALL types are available we append any that are missing.
For example, consider the following:
```graphql
interface Err {
message: String!
}
type InputErr implements Err {
message: String!
code: Int!
input: String
}
type StdErr implement Err {
message: String!
}
type MutationRoot {
shutdown(node: String!) {
err: Err
}
}
schema {
mutation: MutationRoot
}
```
I would say no.
I am marking this as a regression as I tried to fix but only exacerbated the issue in #2847.
No.
When updating the integration test, I found another small issue with the union type.
None required.
An integration test and manual …
=> [GraphQL] Ensures that all types are registered

CHANGELOG.md, backend/apid/actions/tessen.go, backend/apid/actions/tessen_test.go, backend/apid/apid.go, backend/backend.go, backend/messaging/message_bus.go, backend/store/etcd/entity_store.go, backend/store/etcd/store.go, backend/store/etcd/store_test.go, backend/tessend/tessend.go, backend/tessend/tessend_test.go
Adds the message bus to Tessend in order to track Tessen configuration changes from the API.
Closes https://github.com/sensu/sensu-go/issues/2880.
Closes https://github.com/sensu/sensu-go/issues/2882.
Yas.
Nah.
Filed https://github.com/sensu/sensu-go/issues/2891.
We good.
[TestRail test case](https://sensuinc.testrail.io/index.php?/cases/view/5514&group_by=cases:section_id&group_order=asc&group_id=1074)
```
$ sensuctl tessen opt-in
$ sensuctl tessen opt-out --skip-confirm
```
**Tessen Go dashboard:**
=> Add message bus to tessend

backend/apid/actions/error.go, backend/apid/routers/routers.go
Signed-off-by: Cyril Cressent <cyril@sensu.io>
Add a new `actions.PaymentRequired` error code.
=> Add actions.PaymentRequired error

CHANGELOG.md, cli/commands/cluster/health.go, cli/commands/cluster/member-list.go, cli/commands/helpers/print.go
Implements a generic `PrintTitle` function and properly checks the configuration format. The function will print a styled title for tabular format only.
Closes #2917 
Closes #2918 
Yas.
Nope, this was totally my fault and I knew exactly what I did wrong.
Nah.
We good.
```
$ sensuctl cluster health --format tabular
$ sensuctl cluster health --format json
$ sensuctl cluster health --format wrapped-json
$ sensuctl cluster health --format yaml
$ sensuctl cluster health --format foo
$ sensuctl cluster member-list --format tabular
$ sensuctl cluster member-list --format json
$ sensuctl cluster member-list --format wrapped-json
$ sensuctl cluster member-list --format yaml
$ sensuctl cluster member-list --format foo
```
=> Create generic PrintTitle function, properly check for formats

CHANGELOG.md, backend/store/etcd/event_store.go, backend/store/etcd/event_store_test.go, backend/store/etcd/store.go, backend/store/etcd/store_test.go
If there were 2 namespaces with names like "sensu" and "sensu-dev",
querying the "sensu" namespace could also include objects from the
"sensu-dev" namespace!
Fixes https://github.com/sensu/sensu-enterprise-go/issues/418
Added.
Updated integration tests + manual testing.
=> Fix namespace escape issue

api/core/v2/check.go, command/command.go
When a user specifies a check called !sensu_test_check! then
agents will respond with an event that contains an ASCII image of
Rick Astley.
=> Create a special canned check for load testing

CHANGELOG.md, api/core/v2/handler.go, api/core/v2/handler_test.go, backend/apid/graphql/namespace.go, backend/apid/graphql/namespace_test.go, backend/apid/graphql/query.go, backend/apid/graphql/query_test.go, backend/apid/graphql/schema/handler.gql.go, backend/apid/graphql/schema/handler.graphql, backend/apid/graphql/schema/namespace.gql.go, backend/apid/graphql/schema/namespace.graphql, backend/apid/graphql/schema/schema.gql.go, backend/apid/graphql/schema/schema.graphql, backend/apid/graphql/service.go, types/aliases.go
This PR adds the ability to query for Handlers from the GraphQL schema to support sensu/web#89. There are two ways users can retrieve handlers. 
1. Users can retrieve a single `Handler` given a namespace and a name from the `handler` field on the root `query` type,
2. Or, users can retrieve a _collection_ of handers (`HandlerCollection`) from the `handlers` field on the `namespace` type.
This change supports a future update in the in the [sensu/web](https://github.com/sensu/web) repo (sensu/web#89), Sensu users want the ability to view a list of handers and see the details of a particular selected handler. This change allows the Web UI to query for handlers in order to display this data to the user. 
Yes, 5aae0c4
To manually verify this change you can run a `sensu-backend` and query the …
=> Allow users to query for Handlers from the GraphQL endpoint

CHANGELOG.md, backend/eventd/eventd.go, backend/eventd/eventd_test.go
This PR fixes a bug where _all_ checks that do not have a TTL would try to bury their switchset, which would result in two additional and unnecessary etcd operations (1 Put & 1 Delete) for _every_ event.
Closes https://github.com/sensu/sensu-go/issues/2707
Added!
Nope!
Nope!
Nope!
I added a unit tests to eventd to specifically test this scenario.
=> Only bury check switchsets when TTL is disabled

CHANGELOG.md, backend/eventd/eventd.go, backend/tessend/tessend.go, docker-compose.yaml
Instruments the prometheus metrics counter (used in `eventd` and `/metrics`) to send event processing metrics to tessen.
Closes https://github.com/sensu/sensu-go/issues/2910
Yas.
Nah.
https://github.com/sensu/sensu-go/issues/2911 was more complicated.
https://github.com/sensu/sensu-docs/issues/1445
By doing https://github.com/sensu/sensu-go/issues/2911
=> Add prometheus event processing counter to tessen data collection

scripts/make_typemap/make_typemap.go
The `godoc` command has been changed to `go doc -all` in the generator.
=> Fix a bug where typemap gen broke on Go 1.12

cli/client/generic.go
This fixes a bug where we would re-use the same pointer when decoding API results while using chunking.
Fixes a bug found in QA.
Nope, unreleased functionality.
Nope
Nope
Nope
Manually tested, I think it's fine for now. This function uses resty so it would require a good amount of mocking/refactoring to have a proper unit test.
=> Pass empty pointer to json.Unmarshal when chunking

build.sh
Compile with a linux build environment not specify the Version , SHA and date build.
This settings is correctly set with the windows build environnement.
This pull request fix this missing settings
=> Fix the number version with the build.sh script

CHANGELOG.md, backend/eventd/eventd.go, backend/eventd/eventd_test.go
Fixes a bug in the behavior of check `Occurrences` and `OccurrencesWatermark` which is properly defined in https://github.com/sensu/sensu-go/issues/1766#issuecomment-490687197.
Closes https://github.com/sensu/sensu-go/issues/1766
Yas.
Nah.
Nah.
https://github.com/sensu/sensu-docs/issues/1478
Observed how the check `Occurrences` and `OccurrencesWatermark` values changed according to the behavior defined in https://github.com/sensu/sensu-go/issues/1766#issuecomment-490687197.
=> Fix check Occurrences and OccurrencesWatermark

CHANGELOG.md, backend/seeds/seeds.go
Fixes a panic when seeding initial data by returning an error rather than swallowing it.
Closes https://github.com/sensu/sensu-go/issues/2989.
=> Return error to fix panic

backend/tessend/tessend.go
Adds an exportable `AllowOptOut` field to the Tessen daemon.
Closes https://github.com/sensu/sensu-go/issues/2967
No, this doesn't change functionality.
Nah.
Nah.
We good.
E2E testing. A new test case is not required at this time.
=> Tessend allow opt out

CHANGELOG.md, backend/dashboardd/dashboardd.go
Bundle dashboard assets are (relatively) large and would benefit from benefit from compression over the wire.
I believe this regression was introduced in #2786
Yes!
No.
No.
None required.
Manual.
=> [Web] G-Zip dashboard assets

backend/apid/graphql/mutations.go, backend/apid/graphql/mutations_test.go, backend/apid/graphql/schema/mutations.gql.go, backend/apid/graphql/schema/mutations.graphql, backend/apid/graphql/schema/namespace.gql.go
This change updates the GraphQL schema with a `deleteHandler` mutation to support the `sensu/sensu-enterprise-go/444` issue ([link](https://github.com/sensu/sensu-enterprise-go/issues/444)) which allows users to delete a handler resource via the Web UI.
This is the first PR to address `sensu/sensu-enterprise-go/444` ([link](https://github.com/sensu/sensu-enterprise-go/issues/444))
> As a user, I can delete a handler through the web UI.
Yes, 058cddd
Unit and manual. Create a Handler, use the GraphQL endpoint to delete the Handler with the following operation:
```
mutation {
deleteHandler(input: {
id: "srn:handlers:sensu-devel:slack"
}) {
clientMutationId
}
}
````
=> Add a DeleteHandler mutation on the GraphQL endpoint

CHANGELOG.md, build.sh, docker-compose.yaml
This change replaces the deprecated `master` tag for our Docker images, which is referred by the [docker-compose.yaml](https://github.com/sensu/sensu-go/blob/master/docker-compose.yaml) file.
Closes https://github.com/sensu/sensu-go/issues/2963
Added.
Nope.
Nope.
Nope.
=> Use latest docker tag instead of master

CHANGELOG.md, backend/apid/routers/silenced.go, cli/commands/silenced/list.go
This fixes the `/silenced/subscriptions/:subscription` & `/silenced/checks/:check` API endpoints, and make sure the `--subscription` & `--all-namespaces` flags are not used at the same time (otherwise it tries to query `/sensu.io/silenced/:subscription`), which shouldn't be happening).
Closes https://github.com/sensu/sensu-go/issues/2972
Added!
Nope!
Nope!
Nope!
Manually tested. Assigned https://github.com/sensu/sensu-go-qa-crucible/issues/46 to myself.
=> Fixed listing of silenced entries by check or subscription

backend/apid/graphql/entity.go, backend/apid/graphql/entity_test.go
Fixes a regression on the `Entity` type's `events` field, where events that are not directly related to the entity would be included in the result.
Introduced in #2951.
It's a regression to core functionality.
Regression was introduced prior to the last release.
No.
No.
None required.
Improved unit tests and manual testing.
=> [GraphQL] Ensure only events associated with an entity are returned

backend/backend.go, backend/eventd/eventd.go, backend/eventd/eventd_test.go, backend/eventd/integration_test.go, backend/keepalived/deregisterer.go, backend/keepalived/deregisterer_test.go, backend/keepalived/integration_test.go, backend/keepalived/keepalived.go
This commit refactors eventd and keepalived so that event storage is
decoupled from other stores.
This work will support alternative event storage systems in the Sensu Go enterprise product. Closes #2999 
No. No functionality has changed with this commit.
The change was verified with the docker-compose environment and with integration tests.
=> Refactor eventd and keepalived

asset/verifier.go
This PR fixes the error message sent if an asset SHA does not match.
Closes https://github.com/sensu/sensu-go/issues/2454
Nope!
Nope!
Nope!
Nope!
=> Fix error message for asset's SHA mismatch

cli/commands/logout/logout.go, cli/commands/logout/logout_test.go
Fixes the `sensuctl logout` confirmation message.
Closes https://github.com/sensu/sensu-go/issues/2450
Nope
Nope
Nope
Nope
=> Fix sensuctl logout message

CHANGELOG.md, backend/apid/actions/tessen.go, backend/apid/actions/tessen_test.go, backend/apid/apid.go, backend/apid/routers/tessen.go, backend/apid/routers/tessen_test.go, backend/messaging/message_bus.go
Adds the POST `/api/core/v2/tessen/metrics` API endpoint.
Closes #2982 
Yas.
Nah.
Nah.
New docs are not required.
Unit/integration coverage. E2E tested with POST the following []corev2.MetricPoint on `/api/core/v2/tessen/metrics`.
```
[
{
"name": "cpu.idle_percentage",
"value": 61,
"timestamp": 1525462242,
"tags": [
{
"name": "name0",
"value": "value0"
},
{
"name": "name1",
"value": "value1"
}
]
},
{
"name": "mem.sys",
"value": 104448,
"timestamp": 1525462242,
"tags": []
}
]
```
=> Implement POST /api/core/v2/tessen/metrics

backend/backend.go, backend/store/proxy.go, backend/store/proxy_test.go
EventStoreProxy is designed to allow patching the EventStore used
by the backend.
This is a strut for enterprise, so that we can support alternative event stores.
Nein
=> Add EventStoreProxy

api/core/v2/check.go, api/core/v2/check_test.go, api/core/v2/flapping.go, cli/commands/check/subcommands/set_low_flap_threshold_test.go
This fixes a regression introduced by an unreleased refactoring commit (#3000)
Without this change, check flap detection will not work correctly.
No, this is an unreleased regression.
=> Fix a regression where TotalStateChange was computed at the wrong time

CHANGELOG.md, backend/tessend/tessend.go, backend/tessend/tessend_test.go
Appends a tag `sensu_internal_environment` to each metric if the `SENSU_INTERNAL_ENVIRONMENT` environment variable is set. This differentiates internal, developmental, sandbox, etc environments in our Tessen data.
Closes https://github.com/sensu/sensu-enterprise-go/issues/498
Closes https://github.com/sensu/sensu-go/issues/2850
Yas.
Nah.
Nah.
We good.
Unit test. Verified query on Chronograph (added `"sensu_internal_environment"=''` to `WHERE` clause).
=> Append a tag to metric if an internal environment variable is set

CHANGELOG.md, backend/apid/graphql/mutations.go, backend/apid/graphql/mutations_test.go, backend/apid/graphql/schema/mutations.gql.go, backend/apid/graphql/schema/mutations.graphql
This change updates the `PutWrapped` mutation resolver in order to conditionally call the resource POST endpoint if the user of the mutation does not want the mutation to upsert the resource they are passing as the `raw` argument of the mutation. 
Previously, the mutation would always call the resource POST endpoint, which overwrites (upserts) the resource even if the resource already exists. Since users of the mutation don't always want this behaviour, we're updating the implementation of the `PutWrapped` mutation resolver to conditionally call the POST endpoint if the `upsert` parameter is `false`. By default, the `upsert` parameter is `true` in order to maintain the original behaviour of the mutation (for backwards compatibility).
To support this change, this PR also updates the …
=> Add an `upsert` parameter to the `PutWrapped` mutation

backend/apid/graphql/service.go, backend/apid/graphql/service_test.go, graphql/service.go
Adds an InitHooks global to the GraphQL service so that consumers and/or 
product variants can hook into the initialization of the service and make additions
to the schema.
Will allow our enterprise distribution to modify the schema.
Sure.
No.
No, not in particular.
No changes required.
A unit test and some manual testing upstream.
=> [GraphQL] Add ability to hook into initialization of service

CHANGELOG.md
This change updates the `CHANGELOG` for the `5.10.0` Release
To keep a record of changes going into the `5.10.0` Release
Yep.
=> Update CHANGELOG for 5.10.0 Release

CHANGELOG.md, Gopkg.lock, Gopkg.toml, agent/agent.go, agent/check_handler.go, agent/check_handler_internal_test.go, agent/cmd/start.go, agent/config.go, agent/queue.go, cmd/loadit/main.go, vendor/github.com/sensu/lasr/acknack.go
This commit adds an agent command line flag, and ability via the
agent config file, to disable assets. In the event that an agent
is instructed to execute a check that requires an asset, the agent
will respond with a status of 3, and a message indicating that the
agent could not execute the check, because assets are disabled.
Also added is the ability to use the null device as a cache
directory. When the null device (/dev/null on nix, NUL on Windows)
is used, the agent will not attempt to create an event queue.
If --disable-assets is not set, and the cache directory is set to
the null device, then an error will occur.
These changes make the agent require no storage to operate, at the
cost of the asset and durable events API features.
Closes #2287 
Yes
Automated tests.
=> Add --disable-assets flag to the agent

CHANGELOG.md, backend/apid/actions/delete_events_by_entity.go, backend/apid/actions/logger.go, backend/apid/apid.go, backend/apid/routers/entities.go, backend/apid/routers/entities_test.go
This commit fixes a bug where events were not deleted when their
associated entity was deleted via the API, the dashboard, or
sensuctl.
Closes #2846 
Yes
Tested manually
=> API: Delete events associated with deleted entity

backend/authorization/rbac/rbac.go, backend/authorization/rbac/rbac_test.go
This commit adds the VisitRulesFor method for the RBAC Authorizer.
It also rewrites the Authorizer's Authorize method in terms of the
VisitRulesFor method, which proves the implementation.
This is refactoring only, and does not require any documentation changes or CHANGELOG entries.
Closes #3060
=> Add VisitRulesFor RBAC Authorizer method

backend/apid/graphql/mutations.go, backend/apid/graphql/mutations_test.go
This change fixes a bug in the PutWrapped mutation were the wrong URL path is passed to the POST request when the mutation is called with `upsert === false`. The arguments to the `strings.TrimSuffix` method were reversed. :facepalm:
Supports https://github.com/sensu/sensu-enterprise-go/issues/496
Nope.
Manually.
=> [GraphQL] Fix wrong URL bug in PutWrapped mutation

backend/apid/graphql/mutator.go
Allows users to query the globally unique ID of a mutator.
Unblock sensu/web#148
Unlikely.
No.
Nope.
None required.
Manual.
=> [GraphQL] Add global id field to Mutator type

cmd/loadit/main.go
Adds flags to control keepalive params in the loadit tool.
Useful for exploring various load testing scenarios.
=> Add keepalive config for loadit

backend/pipelined/handle.go, backend/pipelined/handle_test.go
Disable looking up extensions for now, since extensions are not currently supported.
This saves one etcd read per keepalive event.
=> Disable lookup of extensions in pipelined

CHANGELOG.md, backend/apid/routers/checks_test.go, backend/apid/routers/events_test.go, backend/apid/routers/helpers_test.go, backend/apid/routers/lister.go, backend/apid/routers/routers.go, backend/apid/routers/silenced_test.go, backend/apid/routers/users_test.go
This PR changes the success status response code for POST & PUT requests from `204 No Content` to `201 Created`.
In a perfect world, we would make a distinction for PUT requests between a resource creation (201) or update (200 or 204) but this information is not currently available to the HTTP handlers, at least not without a major refactoring.
**N.B.** This change will require a PR to sensu-enterprise-go once merged!
This request came from Alex while discussing the API documentation.
Added
Nope
Nope
See https://github.com/sensu/sensu-docs/issues/1558
Unit tests.
=> Return 201 Created on POST & PUT

backend/apid/graphql/handler.go, backend/apid/graphql/handler_test.go
Return `nil` when no mutator is present on source handler.
Without this change, the client will attempt to list all mutators, leading to an error when trying to unmarshal the response to a single mutator.
Unlikely.
No.
Nope!
No changes required.
Unit test & manual.
=> [GraphQL] Return nil when no mutator is present on handler

CHANGELOG.md, backend/backend.go, backend/eventd/eventd.go, backend/ringv2/ringv2.go, backend/schedulerd/check_watcher.go, backend/schedulerd/schedulerd.go, backend/schedulerd/schedulerd_test.go, backend/store/cache/cache.go, backend/store/cache/cache_integration_test.go, backend/store/etcd/watcher.go, backend/store/etcd/watcher_test.go, backend/tessend/tessend.go, backend/tessend/tessend_test.go
This small change is the result of many hours of fighting with etcd watchers in a staging environment.
In a nutshell, it alters 2 abstractions we've built on top of etcd watchers, `etcd.Watcher` (in `/backend/store`, yes the name is unfortunate) and `ringv2.Ring`, so that they can better detect when an etcd watcher dies.
We also don't `range` over those etcd watcher channels anymore; we `for { select { } }` instead, which allows us to avoid cases where we would end up ranging over a closed channel.
Mostly addresses #3012 and #2635.
~There are still improvements that could be made, see #3092.~
Closes https://github.com/sensu/sensu-go/issues/3092
Closes https://github.com/sensu/sensu-go/issues/3012
Yes, added.
Even after spending that much time with etcd watchers, I'm still not 100% sure of …
=> Rework watchers to avoid tight loops

backend/apid/graphql/mutations.go, backend/apid/graphql/mutations_test.go, backend/apid/graphql/schema/mutations.gql.go, backend/apid/graphql/schema/mutations.graphql
Requires #3085 
Adds mutation for deleting event filters.
So that clients can implement deletion of event filters.
Sure
Nope!
Nope.
No changes required.
Unit & manual testing.
=> [GraphQL] Implement delete event filter mutation

CHANGELOG.md, backend/store/etcd/event_store.go
Fixes an alias regression introduced in https://github.com/sensu/sensu-go/commit/37a0401c76df06547460e297e70d2e2e1aff9008 where the timestamp was not being updated for the persisted event.
Closes https://github.com/sensu/sensu-go/issues/3105
Yas.
Nah.
Nah.
We good.
Followed the steps to produced detailed in https://github.com/sensu/sensu-go/issues/3105.
=> Fix event alias for timestamp

CHANGELOG.md, backend/backend.go, backend/cmd/start.go, backend/config.go, backend/eventd/eventd.go, backend/eventd/eventd_test.go, backend/keepalived/keepalived.go, backend/keepalived/keepalived_test.go, backend/pipelined/pipelined.go
This PR introduces configurable buffer size & worker count for keepalived, eventd & pipelined.
More specifically, it allows an operator to configure the `sensu:event-raw`, `sensu:event` & `sensu:keepalive` topics of Wizard Bus in order to determine the buffer size and the number of workers that consume these topics.
Closes https://github.com/sensu/sensu-go/issues/3098
Added!
Nope!
Nope!
https://github.com/sensu/sensu-docs/issues/1575
I manually tested this change and we successfully used this change on the performance testing environment.
=> Configurable buffer size & worker count

CHANGELOG.md, backend/agentd/agentd.go, backend/agentd/session.go, backend/messaging/message_bus.go, backend/messaging/wizard_bus.go, backend/messaging/wizard_topic.go
This PR adds additional prometheus metrics around topics in the Wizard Bus & agent sessions.
Closes https://github.com/sensu/sensu-go/issues/3099
Added!
Nope!
Nope!
Nope!
We successfully tested the topics metrics in the performance testing environment. I've successfully tested the rest.
=> Wizard Bus & agent sessions instrumentation

CHANGELOG.md, backend/store/etcd/entity_store.go
It fixes the behaviour of the DELETE endpoint for entities, which would not return an error if the entity didn't exist since 5.10.1.
Closes https://github.com/sensu/sensu-go/issues/3097
Added!
Nope!
Nope!
Nope!
Manually tested, we have a failing test case in sensu-staging that will be fixed with this patch.
=> Return an error when deleting an entity that does not exist

backend/agentd/session.go
It makes sure we identify the agent in log entries of a session, using its ID and its namespace.
Related to https://github.com/sensu/sensu-go/issues/3106
I don't believe it's worth mentioning it.
Nope
Nope
Nope
=> Properly identify the agent in agentd session

backend/authorization/rbac/rbac.go
Using the Authorizer in the enterprise codebase is cumbersome, due
to the large API surface that must be mocked. Because of an
implementation peculiarity in our mocking library, we cannot use
the sensu-go mock store, and must therefore recreate our mocks
as necessary.
By specifying the exact API of consumers through interfaces, this
process becomes much easier.
=> Refactor the storage requirements for Authorizer

CHANGELOG.md, backend/pipelined/handle.go, backend/pipelined/handle_test.go
This PR fixes a bug where set handlers could be incorrectly marked as too deeply nested if multiple nested set handlers are provided.
Closes https://github.com/sensu/sensu-go/issues/3109
Added
Nope
Nope
Nope
I've refactored the unit tests to make sure this use case was properly tested.
=> Multiple nested set handlers should not be flagged as deeply nested

CHANGELOG.md, backend/schedulerd/roundrobin_cron.go, backend/schedulerd/roundrobin_interval.go
This commit fixes a bug where check schedulers can be shut
down and recreated too often. In some cases this can lead to checks
not being executed frequently enough.
The problem is caused by entity updates being treated as cause for
shutting down schedulers, when in fact, it is only necessary to do
so in the rare circumstance that entity attributes change, leading
to a different cardinality of round robin ring.
To avoid this happening, before cancelling the existing scheduler,
the cardinality of the request is inspected, and if unchanged, the
existing scheduler is left alone.
Closes #3119 
=> Fix a bug in round robin check scheduling

backend/authorization/rbac/rbac.go, backend/authorization/rbac/rbac_test.go
This change is required to support a feature in the enterprise
product, and has no effect on basic auth or RBAC otherwise.
=> Add binding namespace to context in VisitRulesFor

api/core/v2/provider.go, backend/apid/routers/authentication.go, backend/authentication/authenticator.go, backend/authentication/providers/basic/basic.go
This PR changes the signature of the `Refresh` method of the `AuthProvider` interface so all the JWT claims are passed to the authentication provider, not just a subset of it and therefore allow the providers to return the same claims if required.
Required by https://github.com/sensu/sensu-enterprise-go/issues/590
Added
Nope
Nope
Nope
Unit & integration tests.
=> Pass the JWT claims to the Refresh authentication method

api/core/v2/token.go, backend/api/authentication.go, backend/api/authentication_test.go, backend/apid/routers/authentication.go
This change extracts business logic from the authentication router and places it in its own type. The intent is that this type will be reused by dashboardd, so that it doesn't need to reverse proxy requests. This is the first of many such changes.
These changes are in support of #2566
No
=> Refactor authentication into its own API

CHANGELOG.md, backend/store/etcd/event_store.go, backend/store/etcd/event_store_test.go, backend/store/key_builder.go, backend/store/key_builder_test.go
Fixes #3141 by adding the `WithExactMatch` method to `KeyBuilder` and utilising it in `GetEventsByEntity`.
To prevent `GET /events/:entity` from returning events for all entities whose name begins with `:entity`.
Yes, added one.
This is just a suggested approach to address this problem. I couldn't think of any other resource types exposed via the API that are prone to the same prefix failure case, but adding the separator in the `KeyBuilder` instead of in the event store implementation seemed like the correct approach.
I don't feel strongly about the approach I've taken so if you have one you prefer feel free to reject this PR in favour of it.
None, built and tested successfully locally with `build.sh`.
I don't think there's any documentation change necessary, unless you want to add a …
=> Add key separator to end of etcd key when listing events for a specific entity

CHANGELOG.md, cli/commands/filter/list.go, cli/commands/filter/list_test.go
Fixes the tabular output of `sensuctl filter list` so inclusive filter expressions are joined with `&&` and exclusive filter expressions are joined with `||`.
Closes https://github.com/sensu/sensu-go/issues/3038
Yas.
Nah.
Nah.
Yup, this behavior is in line with the docs.
```
$ sensuctl filter list
Name         Action                                                           Expressions                                                           
───────────────── ──────── ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 
two-expressions   allow    (event.check.occurrences == 5 && event.check.status != 0) && (event.is_resolution && event.check.occurrences_watermark >= 5) …
```
=> Fix tabular output of sensuctl filter list

CHANGELOG.md, agent/agent.go, backend/agentd/session.go
Removes encoded protobuf payloads from log messages (when decoded, they can reveal redacted secrets).
Closes https://github.com/sensu/sensu-go/issues/3158
Yas.
Nah.
Nah.
https://github.com/sensu/sensu-docs/issues/1623
Reviewed logs in e2e testing. See https://github.com/sensu/sensu-go-qa-crucible/pull/65.
=> Remove encoded protobuf payloads from log messages

.appveyor.yml, .circleci/config.yml
Uses the go proxy for modules, which should result in a build speedup for modules that are not cached.
=> Use module proxy

.circleci/config.yml
We should use a unique key for the go module cache that uses the cheksum of `go.sum` so when go modules are updated in a branch, it creates a new cache instead of overriding a single one that's shared across all branches. Overall, it should speed up build times because the cache will not be constantly updated when two branches use different `go.mod` files.
=> Use unique cache key for go modules

CHANGELOG.md, cli/commands/commands.go, cli/commands/dump/LICENSE, cli/commands/dump/dump.go, cli/commands/dump/dump_test.go, cli/commands/helpers/flags.go
Implements `sensuctl dump`.
Closes https://github.com/sensu/sensu-go/issues/2742
Yas.
Nah.
There was some nuance with error handling with regard to how unavailable enterprise resources might be handled.
Filing a docs issue now.
Filing QA crucible issues now.
examples:
```
$ sensuctl dump check
dumps all checks in the current namespace
$ sensuctl dump check --namespace dev
dumps all checks in the dev namespace
$ sensuctl dump check --all-namespaces
dumps all checks in all namespaces
$ sensuctl dump all --all-namespaces
dumps all resources in all namespaces
non-namespaced resources are prioritized first to mitigate errors when using sensuctl create (ex. namespaces must be created before resources within that namespace)
$ sensuctl dump check,foo
returns an error because foo is invalid
$ …
```
=> Sensuctl dump

CHANGELOG.md, api/core/v2/event.go
Signed-off-by: Cameron Johnston <cameron@sensu.io>
Adds event.check.name field selector
Closes https://github.com/sensu/sensu-enterprise-go/issues/524
I added one.
I'm hoping this one-liner is all thats needed. Let me know what I've missed?
Nope
https://github.com/sensu/sensu-docs/issues/1660
I have not verified this change.
=> Add support for event.check.name field selector

CHANGELOG.md, backend/apid/routers/assets.go, backend/apid/routers/assets_test.go, cli/commands/asset/delete.go, cli/commands/asset/delete_test.go, cli/commands/asset/help.go
Adds functionality for deleting assets via the API and sensuctl.
Closes https://github.com/sensu/sensu-go/issues/988
Yas.
Nah.
Nah. The generic functions and tests made this _super_ easy.
https://github.com/sensu/sensu-docs/issues/1658
Required by https://github.com/sensu/sensu-go-qa-crucible/pull/68
https://sensuinc.testrail.io/index.php?/cases/view/8785
=> Add functionality for deleting assets via the API and sensuctl

CHANGELOG.md, cli/commands/config/view.go, cli/commands/config/view_test.go, cli/commands/helpers/user.go
It prevents a panic error if `sensuctl config view` is run without any defined configuration.
Closes https://github.com/sensu/sensu-go/issues/3154
Added
Nope
Nope
Nope
Added a unit test.
=> Prevent segfault with sensuctl config view

.github/ISSUE_TEMPLATE/bug_template.md, .github/ISSUE_TEMPLATE/feature_template.md
It introduces new templates for bugs and features.
Closes https://github.com/sensu/sensu-go/issues/3020
Nope
Nope
Nope
Nope
N/A
=> Distinguish issue templates for bugs and feature requests

CHANGELOG.md, agent/check_handler.go, agent/hook.go, agent/hook_test.go
Previously, hooks that expected data on stdin received an empty event.  Now they are passed the event object constructed as part of check execution.
Fixes #3173, which also has more details on the motivation.
This fixes the behavior to match the documentation, so I don't think any changes are needed.
I haven't verified this in a real environment yet and the existing tests don't fully cover the functionality, so it is only partially tested.
=> Pass populated event object to ExecuteHooks

backend/apid/graphql/service.go, backend/apid/graphql/tracing.go, go.mod, go.sum, graphql/middleware.go, graphql/service.go, graphql/tracing/prometheus.go, graphql/tracing/prometheus_test.go
* Updates `graphql-go/graphql` module for it's "Extensions" feature. "Extensions" are in essence middleware that allow an implementer to wrap query executions and provide functionality, see: https://github.com/graphql-go/graphql/pull/448.
* Introduces a GraphQL middleware that captures the duration it took to perform different operations within a query execution. Parsing, validation, resolving field, and total resolver time are observed. Implementation borrows heavily from [Ruby implementation](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/tracing/prometheus_tracing.rb).
* Observations are written to a Prometheus summary.
Will allow us to get detailed metrics on GraphQL query performance.
Sure.
No.
Hubris.
I don't believe any will be required.
Unit tests
=> Trace GraphQL query executions

CHANGELOG.md, agent/check_handler.go, command/command.go
This PR prevents a segmentation fault when the `exec.Start()` method returns an error (usually a sign of a major problem with bash and its environment).
Closes https://github.com/sensu/sensu-go/issues/3216
Added
Nope!
I was unable to reproduce this issue; it's still not clear to me how the `Start()` could return an error; I tried multiple things (bad permissions, invalid `PATH`, etc.) without any success.
Nope
I mocked an error from `exec.Start()` to make sure the rest of the code would behave as expected.
=> Agent command execution segfault bugfix

CHANGELOG.md, api/core/v2/asset.go, api/core/v2/asset.pb.go, api/core/v2/asset.proto, api/core/v2/assetpb_test.go, api/core/v2/typemap.go, asset/asset.go, asset/boltdb_manager.go, asset/filtered_manager.go, asset/filtered_manager_test.go, asset/set_test.go
Adds a new concept of 0 or more builds within an asset.
Fixes #3067.
Yes.
See https://github.com/sensu/sensu-docs/issues/1685.
I have verified that existing asset definitions work along with newer asset definitions, and that the correct build asset was pulled in. For example:
```yaml
---
type: Asset
metadata:
name: sensu-go-cpu-check
labels: {}
annotations: {}
spec:
builds:
- url: https://assets.bonsai.sensu.io/981307deb10ebf1f1433a80da5504c3c53d5c44f/sensu-go-cpu-check_0.0.3_linux_amd64.tar.gz
sha512: 487ab34b37da8ce76d2657b62d37b35fbbb240c3546dd463fa0c37dc58a72b786ef0ca396a0a12c8d006ac7fa21923e0e9ae63419a4d56aec41fccb574c1a5d3
filters:
- entity.system.os == 'linux'
- entity.system.arch == 'amd64'
- url: …
```
=> Asset builds support

backend/dashboardd/dashboardd.go
Exposes the graphql subrouter so it can be patched by enterprise.
The enterprise UI features were not working properly.
No, this was found during QA.
=> Expose GraphQLSubrouter and CoreSubrouter

backend/apid/graphql/node.go, backend/apid/graphql/node_test.go
Registers the GraphQL's EventFilterType schema with the node registry and adds a resolver.
Allows reverse lookup of types and the ability to query filter through the node interface.
```graphql
node(id: "event-filter-global-id") {
id
... on EventFilter {
action
statements
}
}
```
---
I suspect that updating `graphql-go/graphql` may have exposed this error; previous version may have been more permissive.
=> Add node resolver for event filters

CHANGELOG.md, cli/cli.go, cli/client/config/basic/reader.go, cli/client/config/config.go, cli/client/config/mock.go, cli/client/testing/mock_config.go, cli/commands/commands.go, cli/commands/env/env.go, cli/commands/env/env_test.go
This PR adds the `sensuctl env` command.
bash:
```bash
$ sensuctl env
export SENSU_API_URL="http://127.0.0.1:8080"
export SENSU_NAMESPACE="default"
export SENSU_FORMAT="tabular"
export SENSU_ACCESS_TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.x.x"
export SENSU_ACCESS_TOKEN_EXPIRES_AT="1567716187"
export SENSU_REFRESH_TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.x.x"
export SENSU_TRUSTED_CA_FILE=""
export SENSU_INSECURE_SKIP_TLS_VERIFY="true"
```
cmd:
```cmd
$ sensuctl env --shell cmd
SET SENSU_API_URL=http://127.0.0.1:8080
SET SENSU_NAMESPACE=default
SET SENSU_FORMAT=tabular
SET SENSU_ACCESS_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.x.x
SET SENSU_ACCESS_TOKEN_EXPIRES_AT=1567716676
SET SENSU_REFRESH_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.x.x
SET SENSU_TRUSTED_CA_FILE=
SET …
```
=> Add sensuctl env command

cli/commands/create/create.go
sensuctl create now works with http and https URLs, and file:// URLs. Existing file functionality is implemented with the HTTP client, buts works the same as before from a UX perspective.
The tool also now accepts multiple files or URLs, and also supports directories with the -r flag.
Closes #2765 
Closes #2631 
Yes
Documentation changes are needed
```
$ sensuctl create -f resources.yaml
$ sensuctl create -f file://$(pwd)/resources.yaml
$ sensuctl create -f https://gist.githubusercontent.com/echlebek/85767b6c2f9e6e130bae8817c45c8c91/raw/50656db385073046e827365053d7a5a89a248395/gistfile1.txt
$ sensuctl create -r -f ./directory
$ sensuctl create -f resource1.yaml -f resource2.yaml
$ sensuclt create -f resources1.yaml,resource2.yaml
```
=> Add HTTP and directory support to sensuctl create

api/core/v2/check.go, api/core/v2/check_test.go
Only validate check interval and cron when publish is set to true. This reduces the required fields when posting to the Events API etc.
Part of https://github.com/sensu/sensu-go/issues/3257
=> Only validate check interval/cron when publish true

CHANGELOG.md, asset/filtered_manager.go, asset/filtered_manager_test.go
If an asset contains builds and none of the filters pass, the app will crash.
Panics in sensu-agent & sensu-backend are bad.
Yes.
I wrote a new test that reproduced the panic. After making the changes below, the panic no longer occurs.
=> Fix panic when no asset build filters pass

backend/backend.go, backend/etcd/etcd.go, backend/etcd/etcd_test.go, backend/store/etcd/health_store_test.go, backend/store/etcd/testutil/store.go, backend/store/etcd/watcher_test.go
This commit makes Sensu use an embedded client for etcd requests,
instead of connecing localhost. This has several useful effects:
* Avoids the network stack for etcd requests, for embedded etcd
* Avoids gRPC serialization, for embedded etcd
* Simplifies integration testing
The biggest win here is that we can have the integration test etcd
servers listen on ':0', which assigns an arbitrary port instead of
one that we have to pick. This should let the OS pick a port
instead of us, which solves a long-standing CI bug where our tests
could sometimes pick the same port to listen on in parallel,
causing failure.
There should also be some performance wins from avoiding the
network stack, but this is yet to be verified.
Closes #697 
Closes #3263 
No, this is not a user-visible change.
No …
=> Use the embedded client when etcd is embedded

CHANGELOG.md, cli/client/error.go, cli/client/generic.go, cli/commands/dump/dump.go, cli/commands/dump/dump_test.go, types/wrapper.go
Fixes sensuctl dump again, this time with support for wrapped resources as well.
The original edition was backed out.
Closes #3236
Yes
The original edition of this PR was merged, but backed out due to the enterprise resources not working correctly with it.
New documentation is required, for dumping enterprise resources.
I ran `sensuctl dump all`, and:
```
[eric@localhost sensu-enterprise-go]$ sensuctl dump 'store/v1.PostgresConfig'
type: PostgresConfig
api_version: store/v1
metadata:
name: postgres
spec:
dsn: foo=foo
pool_size: 0
```
=> sensuctl dump redux

cli/commands/dump/dump.go
Fixes an issue discovered when testing with enterprise resources, but in an unlicensed context.
=> Ignore PermissionDenied errors in sensuctl dump

CHANGELOG.md, cli/commands/asset/list.go, cli/commands/asset/list_test.go
This PR fixes the asset listing feature of sensuctl, by making sure asset builds are only separated into several assets when the `tabular` format is used.
Fixes https://github.com/sensu/sensu-go/issues/3270
Added
Nope
Nope
Nope
Added unit tests to cover this case.
=> Bugfix for sensu asset list

cli/client/generic.go, types/wrapper.go
* WrapResource now supports types with the GetTypeMeta method, and
uses that for TypeMeta if available. This fixes problems with
lifters.
* The generic HTTP client for sensuctl no longer panics when a
slice of wrappers is passed to it.
=> Fix two bugs in the type system

backend/backend_test.go, backend/etcd/testing.go, backend/store/etcd/health_store.go, backend/store/etcd/testutil/store.go, testing/testutil/util.go
Get rid of the remaining uses of testutil.RandomPorts.
Using testutil.RandomPorts resulted in incorrectly failing tests a significant portion of the time.
No, this is not a user-facing change.
=> Banish the remaining testutil.RandomPorts bits

CHANGELOG.md, cli/commands/dump/dump.go
Adds the --types flag to sensuctl dump. When this flag is activated, the dump command will list all of the resource types in the 'All' list.
It helps users to know which types are supported, and it helps us document sensuctl dump.
Yes
```
[eric@cube sensu-go]$ sensuctl dump --types 
core/v2.Namespace
core/v2.ClusterRole
core/v2.ClusterRoleBinding
core/v2.User
core/v2.TessenConfig
core/v2.Asset
core/v2.CheckConfig
core/v2.Entity
core/v2.Event
core/v2.EventFilter
core/v2.Handler
core/v2.Hook
core/v2.Mutator
core/v2.Role
core/v2.RoleBinding
core/v2.Silenced
[eric@cube sensu-go]$ sensuctl dump --types --format json
[
"core/v2.Namespace",
"core/v2.ClusterRole",
"core/v2.ClusterRoleBinding",
"core/v2.User",
"core/v2.TessenConfig",
"core/v2.Asset", …
```
=> sensuctl dump can now list supported resource types

api/core/v2/tls.proto
It fixes the unexpected diff caused by running `go generate github.com/sensu/sensu-go/api/core/v2`, which originated from https://github.com/sensu/sensu-go/pull/3282
=> Add missing proto attribute to TLSOptions

CHANGELOG.md, cli/commands/asset/outdated.go, cli/commands/asset/outdated_test.go
Properly declare flags for the `sensuctl asset outdated` command so that in doesn't error out with a 'flag accessed but not defined' message.
Closes #3269.
Yes, added.
I initially wanted to add more unit tests for the `asset outdated` command, but that will require refactoring it so that the Bonsai client can be mocked. Leaving this as future work for now.
Added minimal unit test to check that the command can be run.
=> Fix 'flag accessed but not defined' error in asset outdated

backend/etcd/etcd.go, backend/etcd/etcd_test.go, backend/etcd/testing.go, testing/testutil/util.go
The GetClientURLs method is useful when an etcd test instance has
been created, and a user would like to know how to dial it.
Some refactoring has also been done to use testing.TB instead of
testing.T; this allows the functions in question to be used by
*testing.B as well as *testing.T.
I need this change to support integration testing of replicators in sensu-enterprise-go.
No, this is merely plumbing.
The integration test verifies the functionality.
=> Add GetClientURLs method to Etcd type.

api/core/v2/asset.go, api/core/v2/check.go, api/core/v2/check_config.go, api/core/v2/entity.go, api/core/v2/event.go, api/core/v2/filter.go, api/core/v2/handler.go, api/core/v2/hook.go, api/core/v2/mutator.go, api/core/v2/rbac.go, api/core/v2/silenced.go
Fix a regression that was introduced by the sensuctl dump refactoring.
The --all-namespaces flag works with this change. Closes #3306 
No, as this regression was not shipped in a release.
I manually tested dumping every resource in sensu-go and sensu-enterprise-go with multiple namespaces to make sure they would all work properly.
=> Fix the --all-namespaces flag in sensuctl dump

CHANGELOG.md, backend/backend.go, backend/cmd/start.go, backend/config.go, backend/etcd/etcd.go
These new sensu-backend flags control the embedded etcd's heartbeat
interval and election timeout respectively. For details, see
https://github.com/etcd-io/etcd/blob/master/Documentation/tuning.md#time-parameters
Allow operators to tune these etcd options and potentially have more stable clusters when the nodes are not necessarily on the same local network.
Closes #3300.
Yes, added.
No.
No.
New documentation is required, along with links to the relevant etcd documentation.
Tracked by https://github.com/sensu/sensu-docs/issues/1807.
Since this is passing configuration straight to the embedded etcd, I don't think it warrants trying to test; that would equates to testing etcd itself. I've tested the input value validation manually though, e.g.:
```
$ sensu-backend start …
```
=> Add --etcd-{heartbeat-interval,election-timeout}

backend/apid/graphql/entity.go, backend/apid/graphql/entity_test.go, backend/apid/graphql/scalars.go
Fixes regression introduced in #3275.
Closes sensu/web#201
This regression was introduced prior to the last release.
Added an additional unit test.
=> [GraphQL] Fixup entity object meta regression

CHANGELOG.md, backend/api/event.go, backend/api/event_test.go, backend/api/silenced.go, backend/api/silenced_test.go
Allow users to update events and silences through GraphQL service.
Fixes an issue reported on [Discourse (#1353)](https://discourse.sensu.io/t/are-these-bugs-in-5-12/1353).
1. Set up with limited access.
```
sensuctl user create jeb --password meow1234 --groups linux
sensuctl role create local-admin --verb get,list,create,update,delete --resource assets,checks,entities,events,filters,hooks,silenced --namespace linux
sensuctl role-binding create local-admin --role=local-admin --group linux --namespace linux
```
2. Attempt to resolve an event or create a silence from the web app.
Yup.
It's unclear what the original intent was. Chesterton's fence, et al.
No.
None required.
Unit & manual
=> Fix authorization of event & silence updates

CHANGELOG.md, backend/apid/graphql/mutations.go
When creating resources, lifts namespace into context using resource's inner objectmeta.
The `putWrapped` mutation takes wrapped json and creates/updates the given resource. Previous to this change the mutation relied on the outer objectmeta to set the namespace for the operation. The downside to this is that _if_ the outer object was not set, the namespace would never be lifted into the context and authorization would fail.
I've updated the mutation to use the inner objectmeta because it should be more reliable. This is because the wrapper's `UnmarshallJSON` method will copy the contents of the outer json into the inner if it is present. See [types/wrapper#L72](https://github.com/sensu/sensu-go/blob/master/types/wrapper.go#L72-L89).
Closes sensu/web#202.
Sure.
=> [GraphQL] Lift namespace into context using innermeta

agent/agent.go
The agent was trying to use mTLS authentication when its config.TLS
option was nil; it should obviously use password authentication in that
case!
=> Fix predicate that selects mTLS or password

CHANGELOG.md, cli/commands/create/create.go, cli/commands/create/create_test.go
This commit fixes a regression in sensuctl create, where stdin mode
was no longer working. A test has been added to ensure that this
regression does not appear again.
Closes #3318 
Yes
`cat check.json | sensuctl create`
=> Fix sensuctl create stdin regression

CHANGELOG.md, agent/queue.go
This PR adds a timeout when bolt opens a database, so sensu-agent does not indefinitely hang without any error if the database is already opened.
I didn't make it configurable since I don't feel like it's worth adding yet an another configuration attribute but I can do it if we feel it's necessary.
While trying to run a second sensu-agent on my machine, it just hanged so I had to manually debug it to understand what conflicted with the first instance of sensu-agent.
Added
Nope!
Nope!
Nope!
I manually tested it; I don't feel like we necessarily need tests that test that library.
=> Add default timeout to bolt.Open

CHANGELOG.md, cli/commands/dump/dump.go
If you dump multiple types via the CLI dump command the separator for types would be printed to STDOUT instead of the file specified as a flag.
Example:
```
---
---
---
---
---
---
---
---
---
```
The command should not return any output like when exporting as JSON.
Changelog was updated.
=> Output yaml separator to file output stream instead of default cmd output

CHANGELOG.md, backend/messaging/wizard_topic.go
This commit guards against a panic when sending to a closed wizard topic.
In some cases, Sensu can crash after an agent session is terminated.
Yes
The change is unverified as it's very difficult to trigger the conditions that lead to this problem. However, we have verified that in production instances of Sensu, a panic occurs that can be traced back to this chunk of code.
I feel that the change is safe enough to deploy without a reproduction.
=> Fix a panic in wizard bus

CHANGELOG.md, backend/schedulerd/check_watcher.go, backend/schedulerd/cron_scheduler.go, backend/schedulerd/interval_scheduler.go, backend/schedulerd/roundrobin_cron.go, backend/schedulerd/roundrobin_interval.go, backend/schedulerd/schedulerd.go
Adds a prometheus gauge for each type of check scheduler, with a label for namespace.
We need to improve observability of the check scheduler.
Yes
I found and fixed a double-close bug in schedulerd as a result of testing the change.
I started a sensu-go instance, verified that the number of schedulers I was expecting to be in the metrics were there. Then I changed the scheduler type from interval to cron for one of the checks, and verified that the interval number dropped, and the cron number incremented.
=> Add prom gauges for schedulerd

CHANGELOG.md, backend/cmd/start.go
Fixes #2680
Support `SENSU_BACKEND` prefixed environment variables to configure `sensu-backend` service.
Matches behavior that already exists for sensu-agent. Resolves #2680. The service startup scripts for sensu-backend already try and import environment variables from config files but those environment variables currently don't have any impact on the daemon.
https://github.com/sensu/sensu-docs/pull/1724
```
[root@sensu-backend ~]# cat /etc/sensu/backend.yml 
---
state-dir: "/var/lib/sensu/sensu-backend"
api-url: http://sensu-backend.example.com:8080
[root@sensu-backend ~]# cat /etc/sysconfig/sensu-backend 
SENSU_BACKEND_AGENT_PORT="9081"
[root@sensu-backend ~]# netstat --listen -n -p | grep sensu-backend
tcp        0      0 127.0.0.1:2379          0.0.0.0:*               LISTEN …
```
=> Add support for sensu-backend service environment variables

go.mod, graphql/tracing/prometheus_test.go
The testutil package was introduced in v0.9 and exposes some helpers for
for writing simple unit tests.
=> Re-write tracing middleware tests to use prometheus_client/testutil

CHANGELOG.md, backend/apid/actions/events.go, backend/eventd/eventd.go, backend/eventd/eventd_test.go, backend/keepalived/keepalived.go, backend/keepalived/keepalived_test.go
Switches are now buried when:
- The entity is nil
- The event is nil
- Round-robin is configured with check TTL
Closes #3340 
Yes
No documentation change required.
I added and modified some tests, and I also verified manually that the switches were being deleted properly.
=> Bury switches when they are no longer needed

CHANGELOG.md, backend/liveness/liveness.go
Recent testing has revealed that we are creating leases at a ferocious rate, and they are not getting cleaned up quickly enough. For instance, in a 6000 entity cluster, the number leases from keepalives alone was over 40,000.
This change tracks leases that are in-use, and attempts to keep them alive if they are still valid. If they are not, a new lease is granted instead.
Etcd <3.4 has a performance problem when many leases are present or expiring, and I believe it is causing stability problems.
Closes #3355
Maybe, more testing needed.
No docs changes needed.
The existing test suite should suffice. I'm going to do some manual testing to see if we get a more reasonable number of leases.
=> Re-use leases instead of creating new ones

CHANGELOG.md, cli/commands/filter/interactive.go
Adds a missing colon to interactive filter commands in sensuctl.
Closes https://github.com/sensu/sensu-go/issues/3228.
Yas.
Nah.
Nah.
We good.
`sensuctl filter update`
=> Add a missing colon to interactive filter commands

backend/apid/apid.go, backend/apid/graphql/service.go, backend/apid/routers/graphql.go, backend/apid/routers/graphql_test.go, backend/backend.go, go.mod
Moves initialization of GraphQL service into the backend daemon and exposes it so that upstream implementations may extent and reconfigure it.
sensu-enterprise-go#702
Ensured existing tests worked and fixed those that didn't.
=> [GraphQL] Expose service for upstream implementations

backend/store/etcd/event_store.go
Uses `clientv3.WithSerializable` for event reads. This trades the possibility of stale event reads for performance.
I believe that for our use case, this will not have a correctness impact.
Closes #3349 
One should be added once the change is verified.
In progress.
=> Use serializable reads for events

backend/agentd/agentd.go, backend/agentd/middlewares.go, backend/store/cache/cache_test.go, cli/client/error.go, go.mod
Adds a placeholder middleware in core that will be overwritten by enterprise for entity limits on the agent websocket connection.
Required by https://github.com/sensu/sensu-enterprise-go/issues/710.
Nah, purely internal.
Nah.
Nah, thanks @palourde for figuring out this workaround!
We good.
Tested it against enterprise branch.
=> Export placeholder entity limiter middleware for agent websocket connection

backend/store/cache/cache_test.go
Add additional checking to ensure the cache map resulting from cache.GetAll contains each individual entity.
=> Make tests great again!

go.mod, graphql/integration/service_test.go, graphql/service.go
Fixes bug in GraphQL service definition that could lead to a panic when trying to regenerate the schema.
Allows any upstream implementations or extensions to add types without fear of a panic.
Given scope, it is probably unnecessary.
Added an assertion to integration test.
=> [GraphQL] Ensure generation of schema is idempotent

CHANGELOG.md, api/core/v2/entity.go, api/core/v2/event.go, api/core/v2/event_test.go, api/core/v2/silenced.go, api/core/v2/silenced_test.go
Fixes #3356 by removing dependence on silence name for applying silences.
There is a longer description in this comment: https://github.com/sensu/sensu-go/issues/3356#issuecomment-545471799
The tl;dr is that silences currently depend heavily on the name of the silence to determine whether a silence applies. The name contains the subscription, check, and may or may not have wildcards denoted with `*`.
This PR removes that dependency, instead checking the `subscription` and `check` properties of the silence directly.
Additionally, it adds better support for proxy entities, where subscriptions are used differently to non-proxy entities. Subscriptions on proxy entities may be used to target checks (via the `proxy_entity_attributes` field in check config), while the subscriptions actually …
=> Correctly apply silences to events from proxy entities

CHANGELOG.md, backend/cmd/start.go
I tested this manually to ensure that only localhost can serve pprof.
=> Only bind pprof to localhost

CHANGELOG.md, api/core/v2/asset.go, api/core/v2/asset_test.go, api/core/v2/validators.go, api/core/v2/validators_test.go
Updates the asset name regex so that colons are allowed.
Closes https://github.com/sensu/sensu-go/issues/3344
Yas.
Yes, I'm actually not sure if https://github.com/sensu/sensu-go/issues/3344 is intended for _all_ resources or just assets.
Nah.
We good.
Unit test and manual testing.
```$ sensuctl asset add sensu/sensu-influxdb-handler --rename sensu-influxdb-handler:3.1.2```
=> Allow colons to be used in asset names

api/core/v2/silenced.go, api/core/v2/silenced_test.go
Correctly handle an empty check/subscription in a silence as a wildcard.
I found a bug in my (now merged but not released) changes to how silences are applied to events.
Details here: https://github.com/sensu/sensu-go/pull/3376/files#r343748169
Not if it's merged before the above PR is released.
Nope.
Not a complication, just context. I decided to do it this way instead of changing `stringsutil.InArray` because it's used in a bunch of places and I don't have any context on why empty strings were chosen to be omitted or what changing that assumption may break.
No.
Tests continue passing, the adhoc test I was doing for https://github.com/sensu/sensu-go/pull/3382 which uncovered this bug started working after I ran a binary with this fix.
=> Match empty string correctly

cli/commands/root/templates.go
It remove the enterprise commands section in sensuctl help usage 
Required by https://github.com/sensu/sensu-enterprise-go/issues/725
Nope
Nope
Nope
Nope
Tested via sensu-enterprise-go
=> Remove the enterprise commands section in sensuctl help usage

CHANGELOG.md, backend/api/namespace.go, backend/api/namespace_test.go, backend/apid/apid.go, backend/apid/middlewares/authorization.go, backend/apid/middlewares/authorization_test.go, backend/apid/routers/helpers_test.go, backend/apid/routers/namespaces.go, backend/apid/routers/namespaces_test.go, backend/authorization/rbac/rbac.go, backend/authorization/rbac/rbac_test.go, backend/seeds/seeds.go
Users can now list namespaces that they can access other resources in, even if they don't have explicit permission via rbac to list all namespaces, or explicit permission to get the namespace in question.
This simplifies several aspects of access control, and also simplifies display of namespaces in the web ui.
Closes https://github.com/sensu/sensu-enterprise-go/issues/649
Yes
To accomplish this task, I have pulled code from the enterprise repository into the open source repository. We will need to update the enterprise repository accordingly.
Documentation changes may be required.
Unit tests only so far.
=> Add implicit access to namespaces

.appveyor.yml, .circleci/config.yml, asset/asset.go, bonsai/client.go, cli/cmdmanager/manager.go, cli/cmdmanager/manager_test.go, cli/commands/command/command.go, cli/commands/command/delete.go, cli/commands/command/exec.go, cli/commands/command/install.go, cli/commands/command/list.go, cli/commands/commands.go, go.mod, go.sum, testing/mockassetgetter/mockassetgetter.go, testing/mockexecutor/executor.go
Adds support for sensuctl commands which can be installed to extend the functionality of sensuctl.
This is currently a WIP.
A few things still need to be completed:
Yes.
=> sensuctl commands support

CHANGELOG.md, api/core/v2/check.go, api/core/v2/check_config.go, backend/ringv2/ringv2.go, backend/schedulerd/check_timer.go, backend/schedulerd/check_timer_test.go, backend/schedulerd/proxy_check.go, cli/commands/check/interactive.go, go.mod, go.sum
Bumps our cron dependency to a version which supports timezones in traditional cron strings.
Closes https://github.com/sensu/sensu-go/issues/3057
Yas. I updated some duplicated entries for an alpha release as well.
Nah.
Nah.
https://github.com/sensu/sensu-docs/issues/1933
Unit and e2e testing.
=> Bump cron dependency for timezone support

CHANGELOG.md, backend/store/etcd/health_store.go
It passes `context.WithTimeout` to `cli.Get` when retrieving the health of each cluster member.
Before this patch, when a node was down:
```
$ /usr/bin/time sensuctl cluster health
Error: GET "/health": Get http://127.0.0.1:8080/health: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
15.07 real         0.01 user         0.01 sys
```
Now:
```
$ /usr/bin/time sensuctl cluster health
=== Cluster ID: 80c05ee29d12458
ID            Name               Error             Healthy
────────────────── ────────── ─────────────────────────── ─────────
8927110dc66458af   backend0                               true
a23843c228b27241   backend2   context deadline exceeded   false
bb75bf8de77581cc   backend1 …
```
=> Pass context with timeout to etcd health requests

CONTRIBUTING.md, README.md
It removes the outdated and duplicated installation instructions from CONTRIBUTING.md.
Closes https://github.com/sensu/sensu-go/issues/3396
Nope
Nope
Nope
Nope
N/A
=> Remove duplicated instructions in CONTRIBUTING.md

CHANGELOG.md, cli/commands/config/view.go
It adds a field for the JWT expiration timestamp in `sensuctl config view` command.
To facilitate our QA around JWTs. 
Added
Nope
Nope
Nope
=> Display JWT expires timestamp in sensuctl config view

CHANGELOG.md, cli/commands/dump/dump.go
It fixes the default format value in the help usage of `sensuctl dump`:
```
$ sensuctl dump --help
sensuctl dump
[...]
Flags:
--all-namespaces   Include records from all namespaces
-f, --file string      file to dump resources to
--format string    format of data returned ("wrapped-json"|"yaml") (default "yaml")
```
Closes https://github.com/sensu/sensu-go/issues/3369
Added
Nope
Nope
Nope
=> Show correct default format value for sensuctl dump

backend/authentication/providers/basic/basic.go
It ensures a user is still enabled before renewing its access token.
Bug found during QA
Nope, fixes un-released code.
Nope
Nope
Nope
Manually tested, will be covered as part of our QA
=> Validate that a user is still enabled upon token renewal

agent/agent.go, agent/statsd.go, agent/statsd_server.go, agent/statsd_server_solaris.go, agent/statsd_server_test.go
This commit adds experimental support for the sensu-agent under the
Solaris 11 OS. This is accomplished by removing support for the
agent's statsd server, which is incompatible with Solaris.
No testing other than compilation has been done.
=> Add experimental solaris support for sensu-agent

CHANGELOG.md, backend/store/etcd/store.go, backend/store/etcd/store_test.go
It prevents a panic in the store's `CreateOrUpdate` function if a namespace does not exist.
It fixes a bug I found while investigating https://github.com/sensu/sensu-go/issues/3367
Added
Nope
Nope
Nope
Added a unit test to cover that case.
Yep
=> Prevent panic in CreateOrUpdate store function

.github/ISSUE_TEMPLATE/epic_template.md
Add an issue template for epics.
Closes https://github.com/sensu/sensu-go/issues/3209.
Nah.
Nah.
Nah.
We good.
Template will be visible at https://github.com/sensu/sensu-go/issues/new/choose once merged.
No, this will go to master!
=> Add an issue template for epics

CHANGELOG.md, backend/backend.go, backend/cmd/start.go, backend/config.go, backend/etcd/etcd.go
Two new flags, `--etcd-discovery` and `--etcd-discovery-srv` make it
possible to use two dynamic cluster configuration methods, etcd
discovery and DNS SRV discovery, instead of the static `--initial-cluster
method`.
See:
- https://etcd.io/docs/v3.3.12/op-guide/clustering/#overview
- https://etcd.io/docs/v3.3.12/op-guide/clustering/#discovery
Close #3327.
Yes, added.
No.
I initially wanted to also support the `--discovery-srv-name` option, but it's not available in the etcd version we're currently using.
New documentation is required, this is tracked in https://github.com/sensu/sensu-docs/issues/1956.
Manual invocation of `sensu-backend start` with various the various clustering options to verify that:
1. no option specified leads to the current behaviour: a default static cluster with 1 …
=> Add support for etcd and DNS SRV discovery

backend/cmd/init.go, backend/cmd/start.go
Fixes a bug that was introduced by https://github.com/sensu/sensu-go/pull/3414
The flag `--etcd-name` was accidentally removed.
No
Manual testing. Started a backend, used the init tool, etc.
=> Fix a CLI flag that was accidentally removed
