sensu/sensu-go

FAQ.md
FAQ to address likely questions for users.
A FAQ does not currently exist.
No.
Please review the migration specifics.
No.
=> Initial FAQ for Sensu Core 2.0

FAQ.md
Signed-off-by: obfuscurity <jason@dixongroup.net>
A minor change to the FAQ documentation.
It reflects the correct name of the project.
No.
No.
No.
=> Fix the project name in FAQ

CHANGELOG.md, dashboard/src/components/EventsContainer.js, dashboard/src/components/EventsListItem.js, dashboard/src/components/SearchBox.js, dashboard/src/pages/EventsPage.js
Adds a not-fulling-functioning filter box to the events page. It currently records input, but does nothing with it. We need to revisit this later when we decide how we should deal with the queries.
Requirement for web ui.
Added one.
N/A
No, however we will need to revisit this.
=> [Web] Search Box

build.sh
Build script cleanup.
Just minor cleanup
=> Minor cleanup

version/cmd/version/version.go, version/version.go, version/version_test.go
=> Add go port of version.sh.

CHANGELOG.md, agent/agent.go, agent/cmd/start.go, benchmark/cmd/main.go
This adds a load testing utility and the ability to disable the API and socket listeners in the agent.
Because load testing.
=> Add benchmarking utility and add ability to disable API and Socket listeners in the agent

CHANGELOG.md, CONTRIBUTING.md
=> Made the examples in CONTRIBUTING.md more obvious

CHANGELOG.md, backend/apid/routers/mutators.go, cli/commands/handler/create.go, cli/commands/handler/create_test.go, cli/commands/handler/interactive.go, cli/commands/handler/list.go, cli/commands/mutator/create.go, cli/commands/mutator/create_test.go, cli/commands/mutator/interactive.go, cli/commands/mutator/list.go
Adds support for setting environment variables via sensuctl.
Closes #1156 
Changelog updated
Nope!
Nope!
=> Add cli flag for environment variables

CHANGELOG.md, agent/agent.go, agent/check_handler.go, agent/sockets.go, backend/agentd/agentd.go, backend/agentd/session.go, backend/apid/middlewares/allowlist.go, backend/apid/middlewares/authentication.go, backend/apid/middlewares/refresh_token.go, backend/apid/routers/authentication.go, backend/apid/routers/graphql.go, backend/apid/routers/routers.go, backend/backend.go, backend/dashboardd/dashboardd.go, backend/eventd/eventd.go, backend/keepalived/deregisterer.go, backend/keepalived/keepalived.go, backend/migration/environments.go, backend/pipelined/handle.go, backend/pipelined/mutate.go, backend/schedulerd/check_scheduler.go, backend/schedulerd/executor.go, backend/schedulerd/round_robin_scheduler.go, backend/store/etcd/watchers.go
Updates and corrects logging style for variable fields (uses WithFields and WithError when applicable).
Closes #1199.
Yas.
Nah.
Nah.
=> Logrus logging should accept field arguments

testing/testutil/util.go
=> Second stab at dealing with port collisions.

README.md
Updated the readme, optimizing it for new users discovering Sensu and the 2.0 project. This is only the beginning, incremental improvements 👍 
The readme does not currently explain what Sensu or the 2.0 project are and lacks links to helpful resources. Need to optimize for users.
No.
No.
No.
=> Updated readme for new users

README.md
Signed-off-by: Caleb Hailey <calebhailey@gmail.com>
Better README formatting.
For readability. 
No.
No.
Yes. I suck at Git. :smile:
=> Improved README installation guide formatting

CHANGELOG.md, backend/backend.go, backend/pipelined/filter.go, backend/pipelined/filter_test.go, backend/pipelined/handle.go, backend/pipelined/handle_test.go, backend/pipelined/mutate.go, backend/pipelined/mutate_test.go, backend/pipelined/pipelined.go, rpc/extension_executor.go, rpc/extension_executor_test.go
Adds grpc extensions support to pipelined.
Closes #1115 
Filed #1270
=> Add extensions to pipelined

README.md
Just changes the link to be in line with new ✨ branding ✨ 
Because our ✨ brand ✨ 
NOPE!
I need clarification on just exactly how awesome we are 🤔 
💦 💦 💦 most difficult PR I've ever opened!
=> fix sensuapp.org -> sensu.io

backend/apid/graphql/schema/check.gql.go, backend/apid/graphql/schema/check.graphql
Add hook, silenced, lastOK & occurrences fields to Check
Unblocks #833
=> [GraphQL] Add hook, silenced, lastOK & occurrences fields to Check

README.md
Closes https://github.com/sensu/sensu-go/issues/1312
Added a Getting Started heading. Two steps, to add a working Sensu check (with plugin).
Helps users get started with Sensu 2.0 in under 60s.
No.
No.
No.
=> Initial README get started

backend/apid/graphql/check.go, backend/apid/graphql/check_test.go, backend/apid/graphql/schema/check.gql.go, backend/apid/graphql/schema/check.graphql
Change the return type of the check type's `lastOK` field.
Unblocks #833
=> [GraphQL] Change return type of LastOK field

backend/apid/graphql/schema/check.gql.go, backend/apid/graphql/schema/check.graphql
Add TTL field to check type.
Unblocks #835
=> [GraphQL] Add TTL field to check type

backend/apid/graphql/schema/check.gql.go, backend/apid/graphql/schema/check.graphql
Add timeout field to check type.
Unblocks #835
=> [GraphQL] Add timeout field to check type

backend/apid/graphql/check.go, backend/apid/graphql/entity.go, backend/apid/graphql/entity_test.go, backend/apid/graphql/schema/check.gql.go, backend/apid/graphql/schema/check.graphql, backend/apid/graphql/schema/entity.gql.go, backend/apid/graphql/schema/entity.graphql, graphql/generator/object.go
Change the return type of the entity's `lastSeen` field to be `DateTime`.
Unblocks #1133
=> [GraphQL] Change return type lastSeen field

dashboard/assets_generate.go
Tweaks the way we run yarn in hopes of getting better debugging output.
=> Use CombinedOutput to run yarn.

backend/apid/graphql/entity.go, backend/apid/graphql/entity_test.go, backend/apid/graphql/environment_test.go, backend/apid/graphql/schema/entity.gql.go, backend/apid/graphql/schema/entity.graphql, backend/apid/graphql/services_test.go, dashboard/src/components/InlineLink/InlineLink.js, dashboard/src/components/InlineLink/index.js, dashboard/src/components/Maybe/Maybe.js, dashboard/src/components/Monospaced/Monospaced.js, dashboard/src/components/partials/EntityDetailsContainer/EntityDetailsContainer.js, dashboard/src/components/partials/EntityDetailsContainer/EntityDetailsEvents.js, dashboard/src/components/partials/EntityDetailsContainer/EntityDetailsInformation.js, dashboard/src/components/partials/EntityDetailsContainer/index.js, dashboard/src/components/partials/EventDetailsContainer/EventDetailsContent.js, dashboard/src/components/partials/RelatedEntitiesCard/RelatedEntitiesCard.js, dashboard/src/components/partials/RelatedEntitiesCard/index.js, dashboard/src/components/views/EnvironmentView/EntityDetailsContent.js, dashboard/src/components/views/EnvironmentView/EnvironmentView.js
Adds page for displaying entity details.
Closes #841 
Closes #1442 
`undefined`
`undefined`
`undefined`
=> [Web UI] Entity details page

dashboard/src/components/EventsListItem.js
=> [Web UI] Fixup resolve event

backend/store/etcd/organization_store.go
Corrects the description for default environment.
I noticed this typo when looking at something else, so I went ahead and fixed it.
This is such a trivial fix that I didn't add one.
Nope!
Nope!
=> Fix default env description typo

.travis.yml, build.sh
Install a deterministic version of `yarn` during CI.
closes #1531
nope
nope
nope
=> Install yarn during travis before_install step

CHANGELOG.md, backend/backend.go, backend/dashboardd/dashboardd.go
Configure backend reverse proxy w/ tls info
Closes #1612 
likely.
`null`
`null`
=> Configure backend reverse proxy w/ tls info

cli/commands/timeutil/time_test.go
These tests are failing on some environments, and we don't know
why yet.
Closes #1635
=> Comment out failing tests.

CHANGELOG.md, backend/pipelined/filter.go, backend/pipelined/handle.go, backend/pipelined/mutate.go, util/logging/logging.go
Add debug log in pipelined with full event data.
Closes #1603.
Yas.
Nah.
Nah.
=> Add debug log in pipelined with full event data

testing/e2e/create_test.go, types/silenced.go
=> Add e2e test for sensuctl create command.

CHANGELOG.md, cli/commands/check/interactive.go
=> Fix the round robin CLI default.

.github/PULL_REQUEST_TEMPLATE.md
Closes #1493.
IMO a changelog entry is not appropriate for this type of commit. LMK if you disagree.
=> Add documentation section to PR template.

testing/config/resources.json
Make revisions to staging resources.
Closes #1586 
Nah.
Nah.
Found and filed https://github.com/sensu/sensu-go/issues/1700. This asset as is, will produce the error `error installing dependencies: error extracting asset: pax_global_header: unknown type flag: g`.
We good.
=> Use real sensu asset example, flip the bit on the round robin check

testing/e2e/main_test.go
It fixes the linting job in TravisCI
So CI stops failing.
Nope!
Nope!
Nope!
Nope!
=> Fix linting in testing/e2e pkg

CHANGELOG.md, rpc/README.md
Provides some introductory docs for developers wanting to work with extensions.
=> Add documentation for extensions in the rpc package.

CHANGELOG.md, cli/commands/completion/bash.go, cli/commands/completion/zsh.go
Signed-off-by: Josh Bradley <josh.bradley@oracle.com>
corrects sensuctl completion help
fixes documentation 
yes
no
=> fix #1753 completion issue

CHANGELOG.md
=> Update changelog for release.

CHANGELOG.md, build.sh
This time I was able to test the changes locally first. I think this should take care of things now.
=> Second stab at fixing the version command in build.sh

build.sh
=> Fix VERSION_CMD.

CHANGELOG.md, Dockerfile, Dockerfile.rhel, README.md, build.sh, docker-compose.yaml
Migrate from the sensu Docker Hub org to the sensu docker hub org
Closes #1770
=> Sensu docker org

Dockerfile
Add a line continuation marker for tags.
Fixes master build deploy step.
=> Add line continuation to Dockerfile

.circleci/config.yml
This reverts commit 1a08b8065cd7f640761ef5a999033cb13611fbae.
=> Revert "Per Justin, stop building tools."

cli/commands/config/set_format.go
Fix help output for `sensuctl config set-format --help`.
Resolves #1792
=> Fix help output for "sensuctl config set-format --help"

docker-compose.yaml
This commit adds two additional backend nodes to the docker compose
as well as two additional agents. Each agent connects to one
backend.
=> Use clustered sensu in docker-compose.yaml

CHANGELOG.md
=> Adjust CHANGELOG per @majormoses

backend/apid/actions/checks.go, backend/apid/graphql/query.go, backend/apid/graphql/schema/schema.gql.go, backend/apid/graphql/schema/schema.graphql, backend/apid/graphql/service.go
Add `check` to schema root `Query` to enable fetching individual checks by name.
Necessary to complete checks detail page in the web UI.
No
No
No
No
=> [GraphQL] Add check field to Query

dashboard/src/components/controller/MenuController.js
Fixup reversed arguments in MenuController, previously causing an exception.
Fixes bug introduced in #1815.
Fixes #1841.
Change wasn't introduced before last release.
nada
nada
nada
=> [Web UI] Fixup reversed arguments in MenuController

CHANGELOG.md, backend/apid/actions/cluster_test.go, backend/authorization/cluster.go, cli/client/cluster.go, cli/client/interface.go, cli/client/testing/mock_cluster_client.go, cli/commands/cluster/LICENSE, cli/commands/cluster/help.go, cli/commands/cluster/member-list.go, cli/commands/commands.go, cli/commands/helpers/print.go
=> Add sensuctl cluster member-list command.

CHANGELOG.md, cli/client/cluster.go, cli/client/interface.go, cli/client/testing/mock_cluster_client.go, cli/commands/cluster/help.go, cli/commands/cluster/member-add.go, cli/commands/cluster/member-add_test.go
=> Add sensuctl cluster member-add command.

backend/authorization/authorization.go, backend/authorization/authorization_test.go, backend/backend.go
Exports store within the backend.
Required by https://github.com/sensu/sensu-enterprise-go/issues/48
Nah.
Nah.
Nah.
=> Export store within the backend

backend/apid/graphql/entity.go, backend/apid/graphql/entity_test.go, backend/apid/graphql/schema/entity.gql.go, backend/apid/graphql/schema/entity.graphql, dashboard/src/apollo/schema/combined.graphql, dashboard/src/components/CardHighlight/CardHighlight.js, dashboard/src/components/CheckStatusIcon/CheckStatusIcon.js, dashboard/src/components/partials/ChecksList/ChecksListItem.js, dashboard/src/components/partials/EntitiesList/EntitiesListItem.js, dashboard/src/components/partials/EntityDetailsContainer/EntityDetailsEvents.js, dashboard/src/components/partials/EntityDetailsContainer/EntityDetailsInformation.js, dashboard/src/components/partials/EventDetailsContainer/EventDetailsCheckResult.js, dashboard/src/components/partials/EventsList/EventsListItem.js, dashboard/src/components/partials/StatusMenu.js, dashboard/src/icons/Error.js, dashboard/src/icons/IconGap.js, dashboard/src/icons/OK.js, dashboard/src/icons/Unknown.js, dashboard/src/icons/Warn.js
Ensure silenced state is reflected where applicable.
Closes #1858 
`undefined`
`undefined`
`undefined`
`undefined`
=> [Web UI] Ensure silenced state is reflected where applicable

README.md
=> Add CircleCI build status badge.

backend/apid/graphql/check.go, backend/apid/graphql/handler.go, backend/apid/graphql/hook.go, backend/apid/graphql/schema/check.gql.go, backend/apid/graphql/schema/check.graphql, dashboard/package.json, dashboard/src/apollo/schema/client.graphql, dashboard/src/apollo/stateLink.js, dashboard/src/components/Code.js, dashboard/src/components/Monospaced/Monospaced.js, dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsContainer.js, dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsDeleteAction.js, dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsExecuteAction.js, dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsUnsilenceAction.js, dashboard/src/components/partials/CheckDetailsContainer/index.js, dashboard/src/components/partials/ChecksList/ChecksListItem.js, dashboard/src/components/partials/ClearSilencedEntriesDialog/Dialog.js, dashboard/src/components/partials/CronDescriptor/CronDescriptor.js, dashboard/src/components/partials/CronDescriptor/index.js, dashboard/src/components/partials/EventDetailsContainer/EventDetailsSummary.js, dashboard/src/components/partials/ListHeader/ListHeader.js, dashboard/src/components/views/EnvironmentView/CheckDetailsContent.js, dashboard/src/components/views/EnvironmentView/EnvironmentView.js, dashboard/yarn.lock
Create `/:organization/:environment/checks/:check` page to display check details.
Closes #1774
No
No
No
No
=> [Web UI] Create check details view

rpc/extension_executor.go
This commit adds a hardcoded 5 second deadline to extension
methods. It has been observed that extensions can cause a lockup
in the backend, and this commit is designed to mitigate that.
More investigation is needed into why extensions are locking up in
the first place, but this is a starting point that makes the
situation less critical.
Placeholder PR for testing. Do not merge.
=> Add a deadline to extension methods.

dashboard/package.json, dashboard/yarn.lock
Properly parse events in minified builds.
Closes #1898 
Introduced after last release.
`undefined`
`undefined`
`undefined`
=> [Web UI] Properly parse events in minified builds

backend/apid/graphql/mutations.go, backend/apid/graphql/silenced.go, dashboard/src/components/RelativeDate/RelativeDate.js, dashboard/src/components/partials/SilenceEntryForm/SilenceEntryForm.js, dashboard/src/components/partials/SilencesList/SilencesListItem.js, types/event.go, types/event_test.go
* Previously `expireOnSilence` and `begin` default values were not being set.
* Took the opportunity to ensure begin date and author were reflected in silences list.
🐛 Bug.
`undefined`
`undefined`
`undefined`
`undefined`
=> [Web UI] Silence form bugfixes

dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsContainer.js, dashboard/src/components/partials/ChecksList/ChecksListItem.js, dashboard/src/components/partials/CronDescriptor/CronDescriptor.js, dashboard/src/components/partials/EventsList/EventsListItem.js, dashboard/src/components/partials/TableSelectableRow/TableSelectableRow.js
Reflect cron value in the check list.
Fixes #1909 
Introduced after last release.
`undefined`
`undefined`
`undefined`
=> [Web UI] Use cron value in check list

CHANGELOG.md
Updates the changelog for 2.0.0-beta.3-1 release
Because
Yup
Nope
Nope
Nope
=> Update changelog with 2.0.0-beta.3-1 release

README.md
Signed-off-by: Sean Porter <portertech@gmail.com>
=> Correct README getting started Docker image repo and tag

CHANGELOG.md
=> Move changelog entry to unreleased

CHANGELOG.md
Trying not to get trolled by auto-merges and changelogs..
=> Fix the changelog entries to unreleased

dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsDeleteAction.js, dashboard/src/components/partials/EntityDetailsContainer/EntityDetailsDeleteAction.js, dashboard/src/components/partials/EventDetailsContainer/EventDetailsDeleteAction.js
Remove reference to undefined method.
Fixes #1983
=> [Web UI] Fixup exception when deleting checks

backend/pipelined/filter.go, backend/pipelined/handle.go, backend/pipelined/handle_test.go, backend/pipelined/mutate.go, rpc/extension_executor.go
=> Close extension grpc client conns after execution.

CHANGELOG.md, agent/transformers/nagios.go, agent/transformers/nagios_test.go
Fixes a bug in the nagios perfdata parser and adds a test proving the fix is good.
Closes #2021 
Yes
No
No
No doc change required
=> Fix a bug in nagios perfdata parsing

CHANGELOG.md, backend/apid/actions/health.go, backend/apid/routers/status.go, backend/apid/routers/status_test.go, backend/store/etcd/health_store.go, backend/store/etcd/health_store_test.go, backend/store/store.go, cli/client/health.go, cli/client/interface.go, cli/client/testing/mock_health_client.go, cli/commands/cluster/health.go, cli/commands/cluster/health_test.go, testing/mockstore/health.go, types/health.go, types/status_map.go
Adds etcd alarms to the health api and cluster health command.
Closes #1978 
Added note under changed.
Nope!
I ran into a minor formatting issue with the table print that I was unable to track down. I filed  #1997 to look into this issue.
I don't think documentation is needed for this change.
=> Etcd alarms

Gopkg.lock, Gopkg.toml, agent/agent.go, agent/agent_test.go, agent/timeproxy_test.go, vendor/github.com/echlebek/crock/time.go, vendor/github.com/echlebek/crock/timer.go
Add the refactoring and testing changes that were discussed as part of the review of a previous PR (#2017).
Closes #2025.
No: no functionality or interfaces changed.
No.
I misused the `assert` library, causing me great grief.
No documentation impacted.
=> Refactor and tests in agent package

CONTRIBUTING.md
Make contributing a bit easier for newcomers, hopefully!
Requested by @jspaleta. Thanks Jef!
No
=> Clarify the fork/clone procedure.

CHANGELOG.md, backend/apid/graphql/schema/entity.gql.go, backend/apid/graphql/schema/entity.graphql, dashboard/src/apollo/schema/combined.graphql, dashboard/src/components/partials/EntityDetailsContainer/EntityDetailsInformation.js
Closes #2064
Removes instances of keepaliveTimeout from the front end as they were removed from the main project.
Errors were occurring
Yes, and it was updated.
Nothing additional
=> [Web UI] Remove keepalive timeout

dashboard/src/components/partials/EntitiesList/EntitiesListItem.js, dashboard/src/components/partials/EntityStatusDescriptor/EntityStatusDescriptor.js, dashboard/src/components/partials/EntityStatusDescriptor/index.js, dashboard/src/components/partials/RelatedEntitiesCard/RelatedEntitiesCard.js
Use a consistent description of entities everywhere.
Closes #1968
=> [Web UI] Use a consistent description of entities everywhere

.circleci/config.yml
It's not 100% clear to me that this is what we want as the final resolution to this issue; see the issue for more discussion.
=> Issue-2119: Remove CircleCI branch restrictions.

.circleci/config.yml
=> Bump CircleCI resource_class to medium+

CHANGELOG.md
Updates the changelog with the latest beta release.
keepachangelog.com
It _is_ a changelog entry.
Nah.
Nah.
I've made a note to discuss this during release retro.
=> Update changelog with release tag

CHANGELOG.md, dashboard/.eslintrc.yml, dashboard/config/webpack.config.js, dashboard/package.json, dashboard/src/components/Code.js, dashboard/src/components/CodeBlock/CodeBlock.js, dashboard/src/components/CodeBlock/index.js, dashboard/src/components/CodeHighlight/CodeHighlight.js, dashboard/src/components/CodeHighlight/CodeHighlight.worker.js, dashboard/src/components/Dictionary/DictionaryValue.js, dashboard/src/components/Monospaced/index.js, dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsConfiguration.js, dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsContainer.js, dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsPublishAction.js, dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsToolbar.js, dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsUnpublishAction.js, dashboard/src/components/partials/ChecksList/ChecksListItem.js, dashboard/src/components/partials/EntityDetailsContainer/EntityDetailsInformation.js, dashboard/src/components/partials/EventDetailsContainer/EventDetailsCheckResult.js, dashboard/src/components/partials/EventDetailsContainer/EventDetailsSummary.js, dashboard/yarn.lock
Closes #1934 
Improves readability and allows for [un]publishing action
Added one
=> [Web UI] Check details page improvements

CHANGELOG.md
=> Update changelog with beta 7

internal/apis/rbac/converters_v1alpha1_generated.go, internal/apis/rbac/converters_v1alpha1_generated_test.go, internal/cmd/freeze-api/convert.go
=> Adjust APIVersion field when converting types.

apis/rbac/v1alpha1/generated.pb.go, apis/rbac/v1alpha1/generated.proto, apis/rbac/v1alpha1/resource.go, apis/rbac/v1alpha1/types.go, internal/api/api.go, internal/apis/rbac/converters_v1alpha1_generated.go, internal/apis/rbac/converters_v1alpha1_generated_test.go, internal/apis/rbac/generated.pb.go, internal/apis/rbac/generated.proto, internal/apis/rbac/types.go, internal/cmd/gen-register/main.go, internal/registry/registry.go, runtime/registry/registry.go, runtime/registry/registry_gen.go, runtime/registry/registry_test.go
=> Add resource name kinds to the registry.

CHANGELOG.md, dashboard/src/components/partials/EventDetailsContainer/EventDetailsCheckResult.js, dashboard/src/components/util/NamespaceLink.js
Add links for entities and checks to events page.
Closes #2222 
yup!
=> [Web UI] Add links for entities and checks to events page

CHANGELOG.md, backend/pipelined/filter.go, util/logging/logging.go
Adds additional debug logging in pipelined.
Aids in debugging filters.
closes #1745 
Yes, added.
Please verify that the log messages match behavior. It can be really hard to reason about these things. I updated some of the comments to make things more clear (at least to me). If you can also make sure that these comments make sense to you and match behavior.
=> Improve debug logging for event filtering in pipelind

Gopkg.toml
Removes some unused constraints in Gopkg.toml
Cleanliness
NEIN
NEIN
NEIN
=> Remove unused constraints in Gopkg.toml

backend/apid/middlewares/namespace.go, backend/apid/middlewares/namespace_test.go
Inject the namespace found in path variable into the context too
=> Add support for namespaces into path variable

backend/authorization/LICENSE, backend/authorization/rbac/LICENSE, backend/authorization/rbac/rbac.go, backend/authorization/rbac/rbac_test.go, backend/store/etcd/rolebinding_store.go, backend/store/store.go
Closes https://github.com/sensu/sensu-go/issues/2257
=> Add RBAC authorizer

CHANGELOG.md, dashboard/src/components/CodeHighlight/CodeHighlight.js
Avoid infinite loop when code cannot be highlighted.
Yup!
=> [Web UI] Avoid infinite loop when code cannot be highlighted

CHANGELOG.md
Release checklist task `2.11.i`
Do not merge until task `2.17`
=> Update changelog with release candidate

CHANGELOG.md, dashboard/src/components/partials/EntityDetailsContainer/EntityDetailsSilenceAction.js
Fixup creation silence creation from entities page.
Closes #2346
A incorrect argument was being passed to the form.
Depends when this is merged.
=> [Web UI] fixup creation of silences for entities

dashboard/.babelrc, dashboard/.flowconfig, dashboard/flow-typed/npm/es6-error_v4.x.x.js, dashboard/package.json, dashboard/src/errors/FetchError.js, dashboard/src/utils/fetch.js, dashboard/yarn.lock
Fix a bug in the `FetchError` class to avoid seeing `undefined` in the error dialog. 
Introduce flow to help assert that the error constructor is called correctly in the future.
Slightly improves the experience when the app looses network connection.
No
No
No
No
=> [Web UI] Improve `NetworkError: undefined` message 

agent/token_test.go
* Use synthesized values to be more representative of actual use
* Add a test that involves labels
=> Improve token substitution unit tests

agent/agent_test.go
=> Remove a flaky test

CONTRIBUTING.md, README.md
* Move developer documentation into CONTRIBUTING.md
* Give a brief synopsis of some of the major differences between Sensu Classic and Sensu Go.
Closes #1313
=> Simplify and expand README.md

dashboard/src/components/AppLayout/AppLayout.js, dashboard/src/components/relocation/Banner.js, dashboard/src/components/relocation/BannerConnector.js, dashboard/src/components/relocation/BannerWell.js, dashboard/src/components/relocation/ToastWell.js, dashboard/src/components/relocation/types.js
Set up framework for displaying alert banners below the app top bar.
Allows displaying important persistent alerts.
No
No
No
No
=> [Web UI] Set up banner alerts

backend/monitor/supervisor.go
This commit removes a timer from the monitor, which was firing and
causing a goroutine to exit early, which would prevent keepalives
from firing.
Closes #2442
=> Fix a bug where keepalives were not firing

CHANGELOG.md
=> Update CHANGELOG for v5.1.0

api/core/v2/entity.go, asset/filtered_manager_test.go
=> Add test cases for entity system information

packaging/files/backend.yml.example
Updates the backend config example in this repo to match the one being included with Sensu packages
Even though this file isn't being included with Sensu packages, it can still be used as a reference, so keeping it up to dates reduces the change of someone working from an outdated version.
No
No
Nope
None required
=> Update backend config example

benchmark/cmd/main.go
Fixes the benchmark - it was broken, because using the same cachedir for all agents was causing a deadlock.
I've also updated the tool to support multiple backends for agent connection.
IMO no.
=> Fix benchmark, and update for clustered testing

.github/PULL_REQUEST_TEMPLATE.md
Adds a section to the PR template to include a test case.
New QA process.
Nah.
Nah.
Nah.
We good.
=> Update the PR template to include an acceptance test

CHANGELOG.md
Changelog entry for https://github.com/sensu/sensu-go/pull/2603.
Important changes need changelog entries.
It literally is one 😆 
Nah.
Nah.
We good.
Nah.
=> Add changelog entry for go version

.circleci/config.yml
=> Increase parallelism and resource_class for build and test jobs in circle ci

CHANGELOG.md
It updates the Changelog with the upcoming 5.1.1 release.
=> Update Changelog with 5.1.1 release

FAQ.md
=> Replace FAQ contents with a link to official FAQ

backend/authentication/providers/basic/basic.go
=> Change /provider to /auth-provider

CHANGELOG.md
=> Update CHANGELOG.md for 5.2.0 release

CHANGELOG.md, agent/check_handler.go, agent/check_handler_internal_test.go
Fixes #2612
Closes https://github.com/sensu/sensu-go/issues/2704
Fixes bug in #2612 fix highlighted here: https://github.com/sensu/sensu-go/issues/2612#issuecomment-461917501
So the original PR actually works.
Maybe? The original PR didn't have one.
No.
No
No new docs or review.
Maybe.
=> release checkKey lock correctly

CHANGELOG.md
=> Bump the changelog for the 5.2.1 release

CHANGELOG.md, dashboard/src/components/Dictionary/DictionaryEntry.js, dashboard/src/components/Dictionary/DictionaryValue.js, dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsConfiguration.js
Include proxy request configuration details on the check details page.
Closes #2668 
yes.
no.
no.
nada.
nada.
=> [Web UI] Include proxy request configuration

CHANGELOGS/unreleased/2710-sensuctl_httpclient_timeout.md, cli/client/client.go
Signed-off-by: gbolo <george.bolo@gmail.com>
Closes #2698 
very basic change
=> Set sensuctl http client timeout to 15 seconds

.github/PULL_REQUEST_TEMPLATE.md
Per the team discussion on bugifx/feature verification in QA, here is an updated PR template item for testing/verification.
=> Update the PR tempate with a more clear QA verification step

CHANGELOG.md, dashboard/src/components/Maybe/Maybe.js, dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsConfiguration.js, dashboard/src/components/partials/EntityDetailsContainer/EntityDetailsInformation.js
Fixes issue on check configuration page where the timeout could be omitted.
Fixes #2774 
Yup!
nada
nada
No additional documentation.
View a check that has a timeout value greater than 0.
=> [Web UI] Ensure that the timeout value can be displayed

CHANGELOGS/unreleased/2825-update-ui-library.md, dashboard/src/app/component/AppRoot.js, dashboard/src/app/component/PlaceholderCard.js, dashboard/src/app/component/partial/AppBar.js, dashboard/src/app/component/partial/CheckDetailsContainer/CheckDetailsConfiguration.js, dashboard/src/app/component/partial/DrawerButton.js, dashboard/src/app/component/partial/EntityDetailsContainer/EntityDetailsEvents.js, dashboard/src/app/component/partial/EntityDetailsContainer/EntityDetailsInformation.js, dashboard/src/app/component/partial/EventDetailsContainer/EventDetailsCheckSummary.js, dashboard/src/app/component/partial/EventDetailsContainer/EventDetailsEntitySummary.js, dashboard/src/app/component/partial/NamespaceLabel/NamespaceLabelBase.js, dashboard/src/app/component/partial/NamespaceSelector/NamespaceSelector.js, dashboard/src/app/component/partial/NotFound.js, dashboard/src/app/component/partial/RelatedEntitiesCard/RelatedEntitiesCard.js, dashboard/src/app/component/partial/SigninDialog/SigninDialog.js, dashboard/src/app/component/partial/TableToolbarCell/TableToolbarCell.js, dashboard/src/lib/component/base/ButtonIcon/ButtonIcon.js, dashboard/src/lib/component/base/DetailedListItem/DetailedListItemSubtitle.js, dashboard/src/lib/component/base/DetailedListItem/DetailedListItemTitle.js, dashboard/src/lib/component/base/Dictionary/Dictionary.js, dashboard/src/lib/component/base/Dictionary/DictionaryValue.js, dashboard/src/lib/component/base/Preferences.js, dashboard/src/lib/component/base/SearchBox/SearchBox.js, dashboard/src/lib/component/base/TableList/TableListEmptyState.js, dashboard/src/lib/component/icon/Hot.js, dashboard/src/lib/component/icon/Live.js, dashboard/src/lib/component/root/ErrorRoot.js, dashboard/src/lib/theme/defaults.js
Update material-ui to ^3.9 [[RELEASE NOTES](https://github.com/mui-org/material-ui/releases)]
Pre-req for sensu/sensu-enterprise#76
Probably.
Nope!
There were some items that were not dealt with the last time we updated.
None required.
`yarn test` & manual testing
=> [Web] [Chore] Update material-ui to ^3.9

backend/apid/routers/users.go, backend/apid/routers/users_test.go
```
An unfortunate sequence of PR merges lead to a broken master even though
the CI thought everything was OK and good to merge. This commit fixes
that.
Signed-off-by: Cyril Cressent <cyril@sensu.io>
```
=> Fix UserController after pagination merge

CHANGELOG.md, CHANGELOGS/unreleased/2345-sensuctl_flag_ordering_flag_ignored.md, CHANGELOGS/unreleased/2583-sensuctl_wont_delete.md, CHANGELOGS/unreleased/2604-api-pagination.md, CHANGELOGS/unreleased/2636-event-timestamp.md, CHANGELOGS/unreleased/2722-seperate_TLS_config_for_dashboard.md, CHANGELOGS/unreleased/2743-dinnae-store-metrics.md, CHANGELOGS/unreleased/2756-agent-cancellation.md, CHANGELOGS/unreleased/2786-add-asset-collections.md, CHANGELOGS/unreleased/2789-tessen-store.md, CHANGELOGS/unreleased/2795-tessen-api.md, CHANGELOGS/unreleased/2801-agent-api-queue.md, CHANGELOGS/unreleased/2817-creator-exception.md, CHANGELOGS/unreleased/2823-web-update-dev-packages.md, CHANGELOGS/unreleased/2824-web-update-babel.md, CHANGELOGS/unreleased/2825-update-ui-library.md, CHANGELOGS/unreleased/2829-fixup-find-user.md
Update CHANGELOG for release 5.4.0.
=> Release 5.4.0

CHANGELOGS/unreleased/2793-tessen-ring.md, api/core/v2/tessen.go, backend/backend.go, backend/ringv2/ringv2.go, backend/tessend/tessend.go, backend/tessend/tessend_test.go, docker-compose.yaml
Implements a ring so that TessenD operates in a round-robin fashion within a cluster.
Closes https://github.com/sensu/sensu-go/issues/2793.
Yas.
Nah.
Nah.
We good.
- https://github.com/sensu/sensu-go-qa-crucible/pull/33
- https://sensuinc.testrail.io/index.php?/cases/view/3842&group_by=cases:section_id&group_order=asc&group_id=1074
- https://sensuinc.testrail.io/index.php?/cases/view/3841&group_by=cases:section_id&group_order=asc&group_id=1075
- https://sensuinc.testrail.io/index.php?/cases/view/3840&group_by=cases:section_id&group_order=asc&group_id=1075
- https://sensuinc.testrail.io/index.php?/cases/view/3839&group_by=cases:section_id&group_order=asc&group_id=1075
=> Implement the ring for tessend

CHANGELOG.md, CHANGELOGS/unreleased/2791-tessen-daemon.md, CHANGELOGS/unreleased/2792-tessen-etcd-watcher.md, CHANGELOGS/unreleased/2793-tessen-ring.md, CHANGELOGS/unreleased/2794-tessen-sensuctl.md, CHANGELOGS/unreleased/2799-proxy-request-logging.md
=> Update CHANGELOG.md for 5.5.0

backend/backend.go, backend/tessend/tessend.go
=> Update metric point names and cluster id

.appveyor.yml, .circleci/config.yml, CHANGELOG.md
Bump Go version to 1.12.3 in CI.
=> Bump Go version to 1.12.3

backend/dashboardd/dashboardd.go
Proxy API from dashboard daemon.
Required for sensu/sensu-enterprise-go#310.
Sure!
No.
Absolutely not.
Nope!
Manual.
=> [Dashboardd] Proxy path /api

CHANGELOG.md, backend/store/etcd/event_store.go, backend/store/etcd/store.go
This PR introduces exports the ComputeContinueToken function and introduce events handling.
Required for enterprise filtering.
Added
Nope
Nope
Nope
Already covered by integration tests.
=> Create a generic function for continue token generation

CONTRIBUTING.md
This PR documents our git workflow in the CONTRIBUTING document.
Here's the image referred:
=> Document our git workflow

CHANGELOG.md, backend/store/etcd/asset_store.go, backend/store/etcd/check_store.go, backend/store/etcd/clusterrole_store.go, backend/store/etcd/clusterrolebinding_store.go, backend/store/etcd/event_store.go, backend/store/etcd/filter_store.go, backend/store/etcd/handler_store.go, backend/store/etcd/hook_store.go, backend/store/etcd/mutator_store.go, backend/store/etcd/namespace_store.go, backend/store/etcd/role_store.go, backend/store/etcd/rolebinding_store.go, backend/store/etcd/silenced_store.go, backend/store/etcd/user_store.go, backend/tessend/tessend.go, backend/tessend/tessend_test.go
Adds per resource counts to tessen data collection.
Closes #2909
Yas.
Nah.
We didn't estimate this ticket, so I understand if there are questions regarding the implementation.
https://github.com/sensu/sensu-docs/issues/1445
Verified the new data points showed up in the Tessen dashboard.
https://github.com/sensu/sensu-go-qa-crucible/issues/42
=> Add per resource counts to tessen data collection

CHANGELOG.md, backend/eventd/eventd.go, backend/keepalived/keepalived.go
=> Use 1000 handlers for eventd and keepalived

backend/liveness/liveness.go, backend/liveness/liveness_test.go
=> Fix flaky liveness tests

CHANGELOG.md
Updated the changelog's release date. Double checked to see if there were any other additions, but there were none.
So we have a record.
:)
=> 5.8.0 release date

cli/client/asset.go, cli/client/error.go, cli/client/extension.go, cli/client/filter.go, cli/client/generic.go, cli/client/handler.go, cli/client/namespace.go, cli/commands/create/create.go
Update cli/client package so that all API errors are handled consistently across all resources.
* Generally improves the user experience of using `sensuctl`.
* A predictable interface allows clients (`sensuctl` or for the foreseeable future `graphql`) to handle errors consistently.
Yes, probably.
No.
A reflex to shave yaks.
None required.
Manual.
=> Update cli/client package so errors are consistent

backend/apid/apid.go, backend/backend.go
This allows us to use alternative stores in apid.
No
=> Pass event store proxy to apid

backend/store/etcd/watcher.go
This commit extends the Watch() API by allowing arbitrary options
to be passed in. Since it uses variadic arguments to do so, the
previous API is preserved, and no breakage should result.
I would like to use additional watcher options, without modifying our watcher wrapper.
No.
The existing test suite covers watchers already.
=> Allow passing in arbitrary options to watchers

backend/apid/graphql/mutations.go, backend/apid/graphql/mutations_test.go, backend/apid/graphql/schema/mutations.gql.go, backend/apid/graphql/schema/mutations.graphql
Adds new mutation for deletion of mutators.
Deletion of mutators from clients.
Why not.
Nope!
Nope!
None required.
Unit test and manual.
=> Implement delete mutation for mutators

api/core/v2/adhoc.go, api/core/v2/namespace.go, api/core/v2/rbac.go, api/core/v2/tessen.go, api/core/v2/user.go, backend/apid/graphql/suggest/field.go, cli/commands/commands.go, cli/commands/create/create.go, cli/commands/delete/delete.go, cli/commands/delete/delete_test.go
Closes #2613 
Yes, waiting on the changelog to be updated from the last release.
cc @apaskulin new documentation is required for this command.
I created and deleted resources with `sensuctl create` and `sensuctl delete`.
=> Add sensuctl delete command

CHANGELOG.md
=> Update CHANGELOG for v5.11

CHANGELOG.md
Adds a change that I forgot to add to the CHANGELOG.
I forgot to add it to https://github.com/sensu/sensu-go/pull/3206.
It is a changelog entry!
=> Update CHANGELOG to include addition of arm_version attribute

CHANGELOG.md, backend/schedulerd/proxy_check.go
I created this PR for the benefit of @jspaleta, who filed #3136, which has become a bit stale.
=> Jspaleta remediation

CHANGELOG.md
Updates the changelog for 5.12.0
=> Update changelog for 5.12.0

cli/commands/dump/dump.go
=> Fix a bug where yaml output was broken in sensuctl dump

CHANGELOG.md
Signed-off-by: Melissa Page <73hl10n@gmail.com>
Updates to the changelog for 5.13 - release date and version number
=> Update changelog for 5.13

CHANGELOG.md
```
Signed-off-by: Cyril Cressent <cyril@sensu.io>
```
=> Prepare CHANGELOG for 5.13.1

cli/client/generic.go
The generic HTTP client can now handle APIs that return a single wrapped resource.
Allows `sensuctl dump` to work with licenses. Tested manually.
=> Handle single wrapped resource in generic client

.appveyor.yml, .circleci/config.yml, CHANGELOG.md
=> Use patch release

.appveyor.yml, .circleci/config.yml, CHANGELOG.md
This PR bumps Go to the new patch release: https://groups.google.com/forum/m/#!topic/golang-announce/cszieYyuL9Q
=> Bump Go to v1.13.1

CHANGELOG.md
=> Update CHANGELOG for 5.14.0

backend/store/etcd/watcher.go
This commit fixes a send on closed channel panic. It only affects the tests.
=> Fix a send on closed channel bug

agent/agent.go, backend/agentd/session.go
Clean up two of Greg's simple TODOs.
It cleans up the codebase slightly
No
=> Implement a couple of Greg's TODOs

CHANGELOG.md, agent/queue.go, api/core/v2/provider.go, backend/authentication/providers/basic/basic.go, backend/messaging/wizard_topic.go, backend/schedulerd/check_watcher.go, backend/schedulerd/cron_scheduler.go, backend/schedulerd/interval_scheduler.go, backend/schedulerd/roundrobin_cron.go, backend/schedulerd/roundrobin_interval.go, backend/schedulerd/schedulerd.go, cli/commands/dump/dump.go
It includes all required changes for the 5.14.1 release and updates the Changelog
=> Release 5.14.1

CHANGELOG.md, go.mod
I went through the changelog entries for each cherry picked commit on the release/5.14 branch.
=> Update changelog for 5.14.2 release

CHANGELOG.md, backend/pipelined/mutate.go
=> Make logs great again!

backend/liveness/liveness.go
As a result of refactoring, keepalive leases were being stored in
the wrong key prefix.
=> Fix a bug that broke keepalives and check TTL

CHANGELOG.md
Last line of changelog entry got cut off during a bad merge conflict resolution.
=> Fix bad merge resolution in changelog

.github/PULL_REQUEST_TEMPLATE.md
https://trello.com/c/tUxiIDdZ/154-merge-patches-to-a-release-branch-even-if-no-patch-release-is-scheduled
=> Add section to PR template

backend/backend.go, backend/etcd/etcd.go
=> Block on newClient until a read can be done

CHANGELOG.md, dashboard/.ref
Includes the following changes: https://github.com/sensu/web/compare/f1dab6c...95afbfb
=> [Web] Update embedded web assets w/ bug fixes

CHANGELOG.md, agent/agent.go, agent/cmd/start.go, agent/config.go, system/logger.go, system/system.go
This commit adds features that populate the LibCType, VMSystem,
VMRole, and CloudProvider fields in Entity.System.
LibCType, VMSystem, and VMRole are always populated on agent
startup.
CloudProvider is populated if the --detect-cloud-provider flag is
set. This feature can result in several HTTP requests or DNS
lookups being performed, so it may not be appropriate for all
environments.
There are no automated tests for cloud provider discovery yet.
Since the function requires an attempt to connect to a link-local
IP address, it may be difficult to achieve this.
Closes #3587 
Yes
Detecting the cloud provider required quite a bit of thorny work, involving DNS resolution, HTTP requests, timeouts, and synchronization.
I believe we have already documented the fields; this PR merely sets them. …
=> Add agent platform discovery

CHANGELOG.md, agent/agent.go, agent/agent_test.go, backend/agentd/session.go, backend/agentd/session_test.go, backend/eventd/eventd.go, backend/keepalived/keepalived.go
Fixes a variety of keepalive issues.
Closes #3676 
Closes #3675 
Closes #3673 
Closes #3671 
Yes
Each change was verified manually.
Yes
=> Various keepalive bug fixes

CHANGELOG.md
=> Update changelog for 5.19.1 patch

CHANGELOG.md
=> Update changelog for 5.19.3 release

.github/stale.yml
Adds config file for a github bot https://probot.github.io/apps/stale/
https://trello.com/c/rTfspzBD/41-start-utilizing-github-bots-https-probotgithubio-apps
=> Add config file for stale bot

CHANGELOG.md
=> Update CHANGELOG.md for v5.20 release

CHANGELOG.md
Signed-off-by: Melissa Page <73hl10n@gmail.com>
Updates the changelog for the coming release.
=> Update changelog for 5.21.0 release date

.appveyor.yml
Removes the GitHub deployment code in our AppVeyor config.
We haven't used this deployment code in years.
No.
Nope!
Nope!
Can't verify without merging this & tagging it.
No.
=> Remove AppVeyor GitHub deployment

docker-scripts/sensu-entrypoint.sh
This entry point was not used by anything, and can be removed.
=> Remove unused docker-scripts

types/dynamic/function.go, types/dynamic/function_test.go, types/go.mod
This commit adds a function that converts a Go function into a
Javascript function, suitable for calling from the Otto Javascript
environment.
Part of #3843 
No
=> Add dynamic.Function

backend/keepalived/keepalived.go
It fixes a bug found in QA around entity config updates published by keepalived to agentd.
So the entity config is sent back to the agent upon connection.
Nope
Nope
Nope
Manually verified by doing a quick e2e test; updating the entity via the backend is reflected in the new events coming in.
Nope
=> Publish *store.WatchEventEntityConfig for entity config updates

agent/agent.go, agent/entity.go
It ensures we always the entity config from the local config in keepalive events, in order to make sure we always register entities with their local config and not the stored one.
Found a bug @nikkictl found during QA.
Nope
Nope
Nope
Nope
Manually verified, and will be tested in the QA crucible.
Nope
=> Send the entity from local config in keepalives

backend/agentd/agentd.go
See https://github.com/sensu/sensu-go/pull/3851 for additional context
=> Don't attempt to read from conn if closed

CHANGELOG.md, api/core/v2/tls.go, backend/schedulerd/executor.go
It fixes a couple of bugs/UX issues around logging.
So it's easier to debug various errors.
Added
Nope
Nope
Nope
Manually
Yes, but no
=> Various UX improvements in logging

backend/api/namespace.go, backend/api/namespace_test.go
It fixes a bug where deleting a namespace would always fail to delete the role and its associated binding, but still delete the namespace and return an error to the client.
Closes https://github.com/sensu/sensu-go/issues/3918
Nope
Nope
I've discovered another potential bug: https://github.com/sensu/sensu-go/issues/3920
Nope
Manually verified + added some coverage for that in the existing unit tests.
Nope
=> Fix the DeleteNamespace method of NamespaceClient

types/dynamic/function.go, types/dynamic/function_test.go
Makes `dynamic.Function` compile Javascript source code if a string is passed to it.
It supports embedding Javascript functions in Sensu.
No
Unit tests, and the change is being used in the enterprise product.
=> Make dynamic.Function work on javascript source

CHANGELOG.md
Signed-off-by: Sean Porter <portertech@gmail.com>
=> CHANGELOG 6.0.0 release date

.appveyor.yml, .circleci/config.yml, .github/workflows/golangci-lint.yml, CHANGELOG.md
=> Bump go to 1.14.6

backend/agentd/agentd.go, backend/eventd/eventd.go, backend/messaging/wizard_bus.go
Add several new prometheus metrics
=> Metrics metrics metrics

backend/agentd/session.go, backend/agentd/session_test.go
=> Unsubscribe session from every configured check subscriptions

backend/store/cache/cache.go, backend/store/cache/v2/cache.go
=> Use a RWMutex in the caches

cmd/loadit/main.go
Add a configurable pprof endpoint to loadit.
We want to be able to get profiles from loadit.
No
=> Add pprof to loadit

agent/api.go, agent/entity_config_handler.go, agent/entity_config_handler_test.go, backend/agentd/agentd.go, backend/agentd/session.go, cmd/loadit/main.go
These are some various changes that I've made while doing performance testing.
=> Changes for 6.0 release

agent/check_handler.go
We found that token substitution was by far the largest consumer of CPU in loadit. I've added a hack that disables it if the undocumented test check command is used.
=> Disable token substitution for loadit

backend/apid/graphql/schema/meta.gql.go, backend/apid/graphql/schema/meta.graphql
=> [GraphQL] add created by field to schema

CHANGELOG.md
=> Update CHANGELOG for 6.1

CHANGELOG.md, asset/fetcher.go
=> Close asset resp body when done reading from it (#4026)

CHANGELOG.md
=> Update CHANGELOG for 6.1.2 release

cli/commands/configure/configure.go
This PR introduces a refactoring to the `sensuctl configure` command, so most of its logic can be re-used by our enterprise distribution.
Required by https://github.com/sensu/sensu-enterprise-go/issues/708.
Nope, the functionality was not changed.
Nope
Nope
Nope
Manually tested + I'll deploy & test the enterprise changes on staging.
Nope
=> Refactor sensuctl configure command to export most logic

backend/cmd/start.go
Enables block profiling in pprof.
=> Enable block profiler

api/core/v2/event.go, api/core/v2/event_test.go, backend/apid/graphql/schema/event.gql.go, backend/apid/graphql/schema/event.graphql, backend/apid/graphql/util.go
Adds the ability to sort a list events by entity name.
Contributes toward https://github.com/sensu/sensu-enterprise-go/issues/1218
---
=> [GraphQL] Add sort by entity name option

CHANGELOG.md, agent/check_handler.go, asset/boltdb_manager.go, asset/verifier.go, asset/verifier_test.go, go.mod
It fixes the error message around asset checksum mismatch.
Closes https://github.com/sensu/sensu-go/issues/3674
Closes https://github.com/sensu/sensu-go/issues/4064
Added
Nope
Nope
Nope
Manually verified
Yep
=> Improve error message around asset checksum mismatch

CHANGELOG.md
=> Update changelog for release v6.2

CHANGELOG.md, agent/cmd/start.go, agent/cmd/start_test.go
This PR restores the ability to set labels & annotations via flags.
Fixes a bug found by @amdprophet 
Added
Nope
Nope
Nope
Manually verified & added a unit test.
Yep
=> Fix labels & annotations set by flags

backend/eventd/eventd.go, backend/tessend/tessend.go
Adds metrics for the number of busy event handlers, e
We'd discussed adding more visibility into various components of Sensu Backend.
Yes.
I still need to determine if documentation is required.
Ran the backend & an agent with check & metrics. I then used `curl` against the metrics API to check if the new metrics were there.
No.
=> Add metrics for busy event handlers, errors, unknown & metric check types

backend/eventd/eventd.go, backend/eventd/eventd_test.go
Needed for work in sensu-enterprise-go
=> Add a method to eventd to get number of workers

.circleci/config.yml
Signed-off-by: Justin Kolberg <amd.prophet@gmail.com>## What is this change?
It will help us catch platform issues before we vendor sensu-go in our commercial offering.
No.
Nope!
None.
I verified that tests pass & fail for the platforms we expect. The `main` branch is currently broken for some platforms which is why we should see some failures.
No.
=> Test compilation on all supported platforms

CHANGELOG.md
=> Update CHANGELOG for 6.4.0 release

CHANGELOG.md
=> Remove 6.3 entry from changelog

backend/apid/graphql/mutations.go, backend/apid/graphql/schema/mutations.gql.go, backend/apid/graphql/schema/mutations.graphql, backend/apid/graphql/schema/silenced.gql.go, backend/apid/graphql/schema/silenced.graphql, backend/apid/graphql/silenced.go, backend/apid/graphql/silenced_test.go
=> Add Silenced#ExpireAt field to GraphQL service

backend/apid/graphql/mutations.go
=> Fixup issue where silence expire misapplied

backend/cmd/init.go, backend/cmd/upgrade.go, cli/commands/asset/create.go, cli/commands/asset/update.go, cli/commands/check/execute.go, cli/commands/check/interactive.go, cli/commands/check/subcommands/set_hooks.go, cli/commands/configure/configure.go, cli/commands/entity/interactive.go, cli/commands/filter/interactive.go, cli/commands/handler/interactive.go, cli/commands/helpers/prompts.go, cli/commands/hook/interactive.go, cli/commands/mutator/interactive.go, cli/commands/namespace/interactive.go, cli/commands/silenced/interactive.go, cli/commands/user/change_password.go, cli/commands/user/create.go, cli/commands/user/reset_password.go, cli/commands/user/test-creds.go, go.mod, go.sum
That PR update cli to use survey/v2 package.
Removes dependency on survey and survey.v1.
Perhaps no, because that's just a dependency update.
No.
No.
No.
Patched version used on testing site, but not much tested because most of things automated trough API.
No.
=> cli: update survey to survey/v2

backend/backend.go, backend/eventd/entity.go, backend/eventd/entity_test.go, backend/eventd/eventd_test.go, backend/keepalived/keepalived.go, backend/messaging/wizard_bus.go, backend/store/v2/proxy.go, backend/store/v2/proxy_test.go, backend/store/v2/wrap/wrapper.go
Refactor some aspects of the store and store v2.
These changes support work that we're doing to make the entire store swappable, not just the EventStore.
No, this is not a user-facing change.
=> Store refactoring

backend/ringv2/interface.go, backend/ringv2/ringv2.go, backend/ringv2/ringv2_util_test.go, go.mod, go.sum
That PR removes dependency on old cron package, the only place not yet updated to cron/v3.
And fixes `UnPath()` (my eyes was being captured by strange indexes, so i wrote test unit to prove me wrong, but it wasn't).
- Removes outdated dependency
- Fixes bug in a function without any calls...
Probbaly no, because there is no real changes.
No.
No.
No.
Compilled, ran tests.
Well yes, function fix is a patch, but i do not see any calls from whole codebase to it.
=> Ringv2: update deps

backend/apid/graphql/entity.go, backend/apid/graphql/schema/entity.gql.go, backend/apid/graphql/schema/entity.graphql, backend/apid/graphql/schema/mutations.gql.go, backend/apid/graphql/util.go
Additional part of https://github.com/sensu/sensu-go/pull/4364
Closes https://github.com/sensu/sensu-enterprise-go/issues/1461
=> [Graphql] Entity to return -1 if no events present (part 2)

CHANGELOG.md
Updated the changelog for the 6.4.2 patch release.
=> updated changelog for the 6.4.2 patch release

backend/pipelined/pipelined.go
Fixes the leaking of contexts in pipelined.
=> Fix leaky context in pipelined

backend/backend.go
Needed for sensu-enterprise-go, so that configuration can be accessed.
=> Export backend configuration

backend/backend.go
Logs an error but continues operation when the metrics log file cannot be opened.
Necessary for compatibility with older sensu versions.
No, this is net new functionality.
=> Don't crash when metrics log not writable

CHANGELOG.md
updated changelog for the 6.5.3 release
=> updated changelog for the 6.5.3 release

CHANGELOG.md
updated changelog for the 6.5.5 release
=> updated changelog for the 6.5.5 release

backend/apid/apid.go
=> [Bugfix] Don't multiple write timeout duration

backend/agentd/session.go, transport/transport.go
=> Clean up websocket close handling a bit

CHANGELOG.md
Updated the changelog for the 6.6.0 release.
=> updated changelog for the 6.6.0 release

backend/apid/graphql/mutations.go, cli/client/event.go
=> Set check's executed timestamp when resolving events

backend/etcd/etcd.go
Applies the `etcd-client-log-level` flag to the internal etcd client when using embedded etcd.
`etcd-client-log-level` has no effect when on the log level of the internal etcd client when using embedded etcd.
No.
Ensured that no log lines containing `rpc error: code = InvalidArgument desc = etcdserver: key not found` were produced after the change when using the default log level of `error`.
When setting `--etcd-client-log-level` to `warn` the `rpc error: code = InvalidArgument desc = etcdserver: key not found` errors are shown.
Yes.
=> Fix etcd-client-log-level when using embedded etcd

CHANGELOG.md
I had removed this in a previous commit but it seems that Git automerge has struck again and revived it.
cc @hillaryfraley
=> Remove changleog entry that is no longer needed

CHANGELOG.md, backend/eventd/eventd.go, backend/tessend/tessend.go
Cherry-pick changes from https://github.com/sensu/sensu-go/pull/4561 into release/6.6 and adjust changelog.
We want this functionality to be released in 6.6.4.
done
Y
=> metric points processed

backend/apid/graphql/entity.go, backend/apid/graphql/entity_test.go
Web browsers handle values greater than `math.MaxInt32` inconsistently and as a result the `graphql-go` nullifies said values. (Find relevant code [here](https://github.com/graphql-go/graphql/blob/master/scalars.go#L30-L32).) This patch caps the max value returned by the status resolver to `math.MaxInt32`.
---
=> [GraphQL] Cap max value of Entity.status to math.MaxInt32

CHANGELOG.md
=> Update changelog for 6.6.6 release

CHANGELOG-6.md
This updates the CHANGELOG in preparation of the upcoming release.
=> Update CHANGELOG for 6.7.0

CHANGELOG-7.md, cli/commands/clusterrole/create.go, cli/commands/clusterrole/create_test.go
I cherry-picked the changes from https://github.com/sensu/sensu-go/pull/4635 because it was proving difficult to get that branch up to current, due to the changelog disappearing and it being a branch in another repository. @agm650 thanks for the pull request, we'll work from this "rebased" PR with your changes.
=> Transplant agm650 changes

CHANGELOG-6.md
=> Prepare for 6.7.2 Release

backend/store/postgres/storev2.go
=> Include metrics in the postgres store/v2 watcher

backend/apid/graphql/schema/asset.gql.go, backend/apid/graphql/schema/asset.graphql, backend/apid/graphql/schema/corev2.gen.gql.go, backend/apid/graphql/schema/corev2.gen.graphql, backend/apid/graphql/schema/schema_gen.go, backend/apid/graphql/service.go
=> [Graphql] Query builds on asset resource

asset/store.go, asset/store_test.go, backend/pipeline/adapterv1.go, backend/pipeline/adapterv1_test.go, backend/pipeline/filter/legacy.go, backend/pipeline/filter_test.go, backend/pipeline/handler/legacy.go, backend/pipeline/handler/legacy_test.go, backend/pipeline/handler_test.go, backend/pipeline/mutator/javascript.go, backend/pipeline/mutator/legacy.go, backend/pipeline/mutator/pipe.go, backend/pipeline/mutator_test.go, backend/pipelined/pipelined.go
Migrate backend/pipelined and backend/pipeline to storev2
=> Migrate backend/pipeline to storev2

backend/schedulerd/check_scheduler_test.go, backend/schedulerd/check_watcher.go, backend/schedulerd/check_watcher_test.go, backend/schedulerd/cron_scheduler.go, backend/schedulerd/executor.go, backend/schedulerd/executor_test.go, backend/schedulerd/interval_scheduler.go, backend/schedulerd/roundrobin_cron.go, backend/schedulerd/roundrobin_interval.go, backend/schedulerd/schedulerd.go, backend/schedulerd/schedulerd_test.go, backend/schedulerd/testutil_test.go, backend/schedulerd/timeproxy_test.go, testing/mockstore/v2.go
=> Move schedulerd to storev2

backend/store/postgres/config_schema.go, backend/store/postgres/config_store.go, backend/store/postgres/config_store_test.go, backend/store/postgres/counter_integration_test.go, backend/store/postgres/counter_test.go, backend/store/postgres/entity_config_store.go, backend/store/postgres/entity_store.go, backend/store/postgres/helpers_test.go, backend/store/postgres/storev2.go, backend/store/postgres/watcher.go
Move the watcher out of the storev2 to make it reusable in the config store.
=> PG Config Store V2 Watches

backend/store/v2/etcdstore/entity_config_store.go, backend/store/v2/etcdstore/entity_state_store.go, backend/store/v2/etcdstore/migrations.go, backend/store/v2/etcdstore/migrations_test.go
It appeared like that code was not completed and the associated tests were
failing. This fixes the v2 to v3 entity migration and its associated test.
=> Fix v2 to v3 entity migration

backend/agentd/agentd_test.go, backend/apid/graphql/dataloader.go, backend/apid/graphql/interfaces.go, backend/apid/graphql/mock_test.go, backend/apid/graphql/mutations.go, backend/apid/graphql/node_test.go, backend/apid/graphql/query_test.go, backend/apid/graphql/util/relay/node.go, backend/apid/graphql/util/relay/node_test.go, backend/apid/graphql/viewer_test.go, backend/backend.go, backend/backend_test.go, backend/init.go, backend/resource/backend.go, backend/resource/backend_test.go, backend/store/v2/etcdstore/migrations.go
Notice I am not 100% sure about the changes I made to the `graphql` package.
=> Fix a plethora of build and test errors

go.mod, go.sum
* Implements fix from: https://github.com/graphql-go/graphql/pull/642
* I couldn't use the `replace` directive without a version tag so I've used my own fork.
---
=> Update graphql-go package to address issue

backend/apid/graphql/backendEntity.go, backend/apid/graphql/query.go, backend/apid/graphql/query_test.go, backend/apid/graphql/schema/entity.gql.go, backend/apid/graphql/schema/entity.graphql, backend/apid/graphql/schema/query.gql.go, backend/apid/graphql/schema/query.graphql, backend/apid/graphql/service.go, backend/backend.go
Adds the ability to query for the backend
Display in the UI which backend it was last connected to
=> [Graphql] Add ability to query for backend

backend/api/authentication_test.go
Signed-off-by: Abirdcfly <fp544037857@gmail.com>
=> fix minor unreachable code caused by t.Fatal

CHANGELOG-6.md
=> update changelog for 6.8.0 release

CHANGELOG-6.md
=> Set 6.8.2 build version to CHANGELOG-6.md file

CHANGELOG-6.md
Updates the CHANGELOG-6.md for the 6.9 release.
Fixes fumbled merges to the changelog over the past few releases.
=> update changelog for 6.9.0 release

CHANGELOG-6.md
=> update changelog for 6.9.1 patch release

backend/authentication/authenticator.go, backend/authentication/providers/basic/basic.go, go.mod, go.sum
Bumps core/v3 version and uses the corev3.AuthProvider type.
=> Use corev3.AuthProvider

backend/apid/apid.go
Namespace listing was broken due to not being mounted to /api/core/v3.
=> Fix namespace listing for API and sensuctl

backend/store/postgres/config_store_test.go, backend/store/postgres/store.go
=> add pagination to the configuration store

backend/store/postgres/sync.go
Ignore errors on commit when tx context has already been cancelled. Transaction should automagically be closed.
=> Improve logging in postgresql synchronized executor.

CHANGELOG-6.md
Update changelog date for release
=> update changelog for 6.9.2 release

go.mod, go.sum
Upgrades sensu/core/v2 to v2.17.0
Upgrades sensu/core/v3 to v3.8.1
=> update sensu/core/v2 sensu/core/v3 modules

cli/commands/helpers/yaml.go, cli/commands/helpers/yaml_test.go, cli/resource/resolve.go
* removes some printf debugging.
* Fixes sensuctl dump and other commands using yaml format.
=> fix yaml formatting in sensuctl

backend/apid/actions/users.go
This was broken in an early migration to the new store interface. We had been persisting the plaintext password instead of the hashed version for users.
=> Store password hash for new users

backend/apid/apid.go, backend/apid/handlers/list_v3.go, backend/apid/middlewares/selectors.go, backend/store/postgres/config_schema.go, backend/store/postgres/config_store_test.go, backend/store/postgres/migrations.go, backend/store/postgres/migrations_schema.go, backend/store/postgres/selector.go, backend/store/postgres/store.go
Changes the configuration store to be compatible with sensu-go selectors, and use them in the rest api.
=> Use Configuration Store Selectors

CHANGELOG-6.md
Update CHANGELOG in preparation of the upcoming release.
=> Update CHANGELOG for 6.10.0

.circleci/config.yml, CHANGELOG-6.md
Change log update with version number 6.12.0
Release process
=> Change log update 

.appveyor.yml
Go version update for Appveyor pipeline
=> Appveyor update with go version
