sensu/sensu-go

CHANGELOG.md, cli/cmdmanager/manager.go, cli/cmdmanager/manager_test.go
Checks for valid Bonsai labels before checking if a Bonsai asset has one or more builds.
Addresses a UX issue discovered by https://github.com/sensu/sensu-go/issues/3421. We still need a valid sensuctl command for the Sensu Docs example.
Yes.
It can be if we want it to. Do we want it to be?
=> Check Bonsai labels before checking if one or more builds exist

CHANGELOG.md, backend/tessend/data.go, backend/tessend/tessend.go
It adds a `distribution` field to Tessen's cluster data, with the default value `oss` for sensu-go.
Closes https://github.com/sensu/sensu-go/issues/3431
Added
Nope
Nope
Nope
Nope
=> Add distribution field to tessen's cluster data

CHANGELOG.md, agent/agent.go, agent/cmd/start.go, agent/config.go, backend/eventd/eventd.go, backend/keepalived/keepalived.go, cmd/loadit/main.go
Added a new flag, `--keepalive-critical-timeout` to define the time after which a critical keepalive event should be created for a dead agent.
Closes https://github.com/sensu/sensu-go/issues/2747
Yas.
Just some product input on the complications below.
Yes, these complications were discussed with @echlebek (the keeper of the keepalives) which I will outline, but we will need some product direction. 
While critical keepalive events are a 1.x parity feature, the implementation of keepalives in Sensu Go is vastly different than that of Classic. The [liveness package](https://github.com/sensu/sensu-go/blob/master/backend/liveness/liveness.go) implements switches with etcd leases that get flipped on life and death events for agent entities. This …
=> Add --keepalive-critical-timeout

CHANGELOG.md, cli/commands/helpers/json.go, cli/commands/helpers/json_test.go, cli/commands/helpers/yaml.go, types/wrapper.go, types/wrapper_test.go
It fixes a bug in the Wrapper's UnmarshalJSON method, which would cause wrapped resources to not properly display their metadata or prevent them from being created.
It also adds more comments and unit tests to the same UnmarshalJSON method.
Fixes https://github.com/sensu/sensu-enterprise-go/issues/704
Fixes https://github.com/sensu/sensu-go/issues/3442
Fixes https://github.com/sensu/sensu-go/issues/3444
Added!
Nope.
Nope.
Nope.
Manually tested that it fixed the reported bugs and added unit tests to cover these cases.
Yep, but we are not proceeding with a patch release for 5.15.
=> Set the outer ObjectMeta when decoding a wrapper struct

CHANGELOG.md, api/core/v2/health.go, backend/apid/routers/cluster.go, backend/apid/routers/health.go, backend/store/etcd/health_store.go, cli/client/health.go
* Fix a bug where the cluster health command would hang
indefinitely if one of the cluster members was not responding.
* Gather cluster health from members concurrently.
* Implement a static timeout of 3s for gathering cluster member
information from members.
* Add MemberIDHex field to the cluster health datatype, so that the
rendered JSON and YAML contain the hex representation as well as
the decimal representation.
Refs #3423 
Closes #3036 
Yes
We'll need to update the API reference for ClusterHealth.
Unverified beyond smoke tests currently.
No
=> Improve sensuctl cluster health

backend/authentication/jwt/jwt.go, backend/authentication/jwt/jwt_test.go, backend/backend.go, backend/seeds/seeds.go, backend/store/etcd/authentication.go, backend/store/etcd/authentication_test.go
This commit fixes a bug where the jwt secret was not correctly
being loaded on startup. The result was that jwts were being
created with a 0-byte secret.
This regression occurred in commit 6df9362dfe57c605608a1da9e384a9900f5dc2a4
jwt authentication is broken.
No, this regression was not present in 5.15.
Made sure that a user could not log in with an existing token with a fresh Sensu instance.
=> Fix a bug where jwt secret was not initialized

types/wrapper.go
This is to make the serialization consistent across all output formats.
=> Remove use of jsoniter in wrapper serialization

backend/cmd/init.go
Adds connection blocking to the etcd client in sensu-backend init.
Without this option, sensu-backend init might run before etcd is ready.
No
Ran sensu-backend init and verified that the client blocks.
Yes
=> Block on grpc dial in sensu-backend init

backend/cmd/init.go, backend/seeds/seeds.go, backend/seeds/seeds_test.go, cmd/sensu-backend/main.go
`sensu-backend init` exits with status 3 if the backend has already been initialized.
Closes #3448 
No
This should be documented, but I'm not exactly sure where. @hillaryfraley 
I initialized sensu-backend successfully, and then tried to initialize it again. The command exited with status 3.
Yes
=> Exit status 3 when backend already initialized

api/core/v2/context.go, backend/apid/routers/health.go, backend/store/etcd/health_store.go, backend/store/etcd/health_store_test.go
This PR fixes a bug where shutdown members of a cluster would not be shown in `sensuctl cluster health`.
=> Bugfix for sensuctl cluster health

CHANGELOG.md, backend/eventd/eventd.go
It initializes the `sensu_go_events_processed` metric with the `success` label so the metric is always displayed in the `/metrics` endpoint.
To avoid any confusion!
Added
Nope
Nope
Nope
Manually tested it.
Yep
=> Initialize the sensu_go_events_processed metric

docker-compose.yaml
Quick fix to docker-compose - backend3 command had wrong arg preventing it from coming up.
To make docker-compose up work as intended
Nope.
Nope
Nope
Nope ;)
ran `docker-compose up` and backend3 ran properly
I ... don't think so.
=> fixes typo in docker-compose.yml

CHANGELOG.md, backend/store/cache/cache.go, backend/store/cache/cache_test.go, backend/store/etcd/store.go
This commit fixes a memory leak in the resource cache by making it
avoid using etcd watchers. For reasons that are not clear, the
previous implementation was causing a memory leak under load.
It's unknown if the memory leak was a result of improperly using
the etcd client API, a bug in the etcd client API, or caused by
sensu-go in some other way.
Closes #3486 
Yes
The precise source of the memory leak was never determined.
Extensive performance testing.
Yes
=> Simplify the resource cache, fix memory leak

backend/schedulerd/executor.go, backend/secrets/provider.go
Adds a bool that can be set by the enterprise code if mTLS is enabled. 
> Secrets are only transmitted over a TLS websocket connection; unencrypted connections must not transmit privileged information. (for agent side resources, TLS/mTLS? must be enabled)
Required by https://github.com/sensu/sensu-enterprise-go/issues/792.
No.
No.
No.
We good.
Local testing on enterprise branch.
No, required for feature work.
=> Only send secrets over the wire if mTLS is enabled

CHANGELOG.md, api/core/v2/rbac.go, api/core/v2/rbac_test.go
It adds better validation around ClusterRole and Role rules, and also automatically split verbs, resources and resource names on commas, which often happen on YAML files and can lead to confusing errors (the rules are not applied when expected).
Fixes https://github.com/sensu/sensu-go/issues/3471
Added
Nope
Nope
Nope
Added unit tests.
Yep
=> Split rules ClusterRole and Role verbs & resources on comma

CHANGELOG.md, backend/api/namespace.go, backend/api/namespace_test.go, backend/apid/routers/namespaces_test.go, backend/authorization/rbac/rbac.go
This PR fixes a bug where a user with implicit access to a namespace couldn't access that namespace via the Web UI.
Long story short, the Web UI uses the [FetchNamespace](https://github.com/sensu/sensu-go/blob/9aa87c9060ae41198733373d49a22f32d9db08cc/backend/api/namespace.go#L116) method which was never retrofitted with the implicit namespace feature, probably because `sensuctl` doesn't use that API so we forgot to back-port it.
Fixes https://github.com/sensu/sensu-enterprise-go/issues/821
Added
Nope
Nope
Nope
Added unit tests + manual testing.
Yep!
=> Bugfix for implicit namespace access in Web UI

CHANGELOG.md, cli/commands/command/list.go
It adds support for the `--format` flag to the `sensuctl command list` subcommand.
Closes https://github.com/sensu/sensu-go/issues/3420
Added
Nope
Nope
Nope
Manually tested:
```
$ sensuctl command list --format yaml
type: CommandPlugin
api_version: cli/cmdmanager
metadata:
name: echo
spec:
alias: echo
asset:
builds:
- filters: null
headers: null
sha512: 4ae5dfbe9ca0c7d4050ad334d3117176e0720462505335a8c2b7d6cb28985cccc235a32f670a02a9dd10b1ecf6d016cf2e966b7f3222c56d4bdabd53b0fabd8c
url: http://localhost:8000/echo-asset-0.0.1.tar.gz
filters: null
headers: null
metadata:
name: echo
namespace: sensuctl
$ sensuctl command list --format json
[
{
"alias": "echo",
"asset": {
"url": "http://localhost:8000/echo-asset-0.0.1.tar.gz",
"sha512": …
```
=> Add format flag to "sensuctl command list"

CHANGELOG.md, backend/apid/handlers/handlers.go, backend/apid/routers/events.go, backend/apid/routers/events_test.go
It allows users to omit the namespace in an event payload when using POST `/events`, like it's already the case for the PUT verb.
Closes https://github.com/sensu/sensu-go/issues/3482
Added
Nope
Nope
Nope
Yep
=> Set event's namespace using route variables in POST /events

CHANGELOG.md, backend/apid/actions/delete_events_by_entity.go, backend/apid/routers/entities.go, backend/apid/routers/entities_test.go, backend/apid/routers/helpers_test.go
Adds more specific error checking for entity delete.
Closes https://github.com/sensu/sensu-go/issues/3501
Yas.
Nah.
Nah.
We good.
https://github.com/sensu/sensu-go-qa-crucible/blob/e3fba2059f6a5fb9a5494b21c4816daafafdc23d/spec/backend/entities_spec.rb#L31-L42
Yes, but in an attempt not to scope creep, I will merge this into master.
=> Add more specific error checking for entity delete

util/retry/retry.go, util/retry/retry_test.go
This commit adds JSON tags for retry.ExponentialBackoff, and
a customer marshaler and unmarshaler that allows users to specify
its durations in friendly formats like "5s" or "10m".
This is useful for provider types that need retry.
No
Unit tests
No
=> Add JSON niceties for retry.ExponentialBackoff

asset/expander.go, go.mod, go.sum
This commit upgrades mholt/archiver, which should bring performance
improvements, and bring us in line with other libraries that use
the latest major version.
Some minor refactoring was performed to deal with API drift.
=> Upgrade mholt/archiver

CHANGELOG.md, cli/cmdmanager/manager.go, cli/cmdmanager/manager_test.go
Sets the namespace field on Bonsai-installed sensuctl command assets to `sensuctl`.
It is currently impossible to install sensuctl command assets via Bonsai.
Yes.
Altered a test to ensure it fails when a namespace is not set. Hard-code the namespace in the Bonsai-install logic.
Yes but we're going to ship it with the next minor release.
=> sensuctl assets installed via Bonsai should have a namespace set

CHANGELOG.md, api/core/v2/event.go
Adds support for filtering by the name of an entity.
/cc @cwjohnston 
Close #3513 
Yup
=> Add support for event.entity.name field selector

CHANGELOG.md, backend/eventd/eventd.go, backend/eventd/eventd_test.go
This commit modifies how eventd responds to failing check TTL
events. Previously, check TTL events would occur even if failing
keepalive events had been recorded. Now, eventd will not issue
failing check TTL events if a keepalive event for the entity has
already occurred.
Closes #3304
Yes
No docs changes required.
I created a check with TTL greater than agent keepalive timeout, got it executing on an agent, and terminated the agent. I observed a keepalive failure occurred. I then observed in the backend logs that the check TTL switch had fired, but no failing event was created for the check.
On the flip side, if the keepalive timeout is longer than the check TTL, then a check TTL event does get created.
Yes
=> Don't fail on check TTL after keepalive fails

api/core/v2/rbac.go, api/core/v2/rbac_test.go
It allows RBAC rules with the `create` verb to be created.
Fixes a bug found during automated QA.
Nope
Nope
Nope
Yep
=> create is a valid RBAC verb

CHANGELOG.md, go.mod, go.sum
Update `graphql-go/graphql` dep, pulling in fixes to scalars and introspection. https://github.com/graphql-go/graphql/compare/199d20bbfed7...2e2b648
Closes #3524 
Sure.
Manual.
=> Bump graphql-go dep

CHANGELOG.md, api/core/v2/asset.go, api/core/v2/asset_test.go
It modifies the asset regex to allow uppercase in assets name.
Closes https://github.com/sensu/sensu-go/issues/3522
Added
Nope
Nope
Nope, the docs was actually wrong but it's now valid! (https://docs.sensu.io/sensu-go/latest/reference/assets/#metadata-attributes)
Added a unit test and did a quick e2e test, which was successful using the asset mentioned in the original issue:
```
$ s event list
Entity     Check                                                 Output                                                Status   Silenced             Timestamp
──────── ─────────── ───────────────────────────────────────────────────────────────────────────────────────────────── ──────── ────────── ───────────────────────────────
scotch   cpu         CheckLoad OK - value = 0.00, 0.00, 0.00 | …
```
=> Allow capital letters in assetsname

CHANGELOG.md, cli/client/config/basic/writer.go
I woke up in the middle of the night (international travel, yay!) and saw some chatter about this being the last thing needed for the 5.17.1 release. Didn't want to block anyone and I was wide awake anyway 🤷‍♀ 
When `--trusted-ca-file` is used to configure sensuctl, it now detects and saves the absolute file path in the cluster config, rather than the relative path.
Closes https://github.com/sensu/sensu-go/issues/3520
Yas.
Nah.
Nah.
We good.
Ran `sensuctl configure --url http://127.0.0.1:8080  --password P@ssw0rd! --namespace default --username admin -n --trusted-ca-file CA.pem` from multiple directories, verifying `.config/sensu/sensuctl/cluster` was updated with the correct absolute filepath.
Yup!
=> Fix trusted ca file path

cli/client/config/basic/writer.go
`filepath.Abs` will always return the  current working directory if the provided path is empty (which happens whenever the flag is specified), which will end up configuring it to the CWD and causing sensuctl to load the CA file from that path even if it wasn't configured, e.g.:
```bash
$ s configure -n --url http://127.0.0.1:8080 --username admin --password 'P@ssw0rd!'
$ s check list
WARN[0000] Error reading CA file: read /Users/splourde/src/sensu-go: is a directory  component=cli-client
WARN[0000] Trying to use the system's default CA certificates  component=cli-client
[...]
```
Therefore, we should only call it whenever a file path was provided.
=> Do not call filepath.Abs if the path is empty

.appveyor.yml, .circleci/config.yml, CHANGELOG.md
It bumps the Go version used from `1.13.5` to `1.13.7`.
To include some bug fixes & security fixes: https://golang.org/doc/devel/release.html#go1.13
Added
Nope
Nope
Nope
CI
Nope
=> Bump Go version to 1.13.7

CHANGELOG.md, backend/pipeline/filter.go, backend/pipeline/filter_test.go, backend/pipeline/handler.go
It adds the filter name that dropped an event via the returned error, so it can be logged within a single log entry.
Closes https://github.com/sensu/sensu-go/issues/3107
Added
Nope
Nope
Nope
Nope
=> Log the filter name that dropped an event

CHANGELOG.md, bonsai/bonsai.go, bonsai/bonsai_test.go, cli/cmdmanager/manager.go, cli/cmdmanager/manager_test.go, cli/commands/asset/add.go, cli/commands/asset/outdated.go, cli/commands/asset/outdated_test.go
It adds supports for Bonsai assets that use the version format `vX.Y.Z`, in addition to semver (`X.Y.Z`).
Closes https://github.com/sensu/sensu-go/issues/3425
Added
I tried my best to make sure I didn't forget anything; it appears this package is only used in sensuctl but I might be forgetting something.
Nope
Nope
Manually tested it and added a unit test where available.
Yep
=> Support Bonsai assets versions prefixed with v

CHANGELOG.md, backend/apid/routers/authentication.go
Returns 401 rather than 500 when there is an `err` when refreshing
fixes #3408 
It creates an expected response when there is an issue with a refresh token regenerating an access_token.
Yes.
I don't think so.
N/A
I don't believe so.
I didn't.  Although, I am moving from one `http` const to another.
As it was defined as low hanging and has aged, I don't believe this needs to be backported.
=> Return 401 when refresh has issues

CHANGELOG.md, backend/apid/actions/events.go, backend/apid/actions/events_test.go, cli/commands/create/create.go
Default `event.entity.entity_class` to `proxy` in the POST/PUT `/events` API.
Closes https://github.com/sensu/sensu-go/issues/3525
Yas.
Nah.
Nah.
We good.
Unit test added. Tested the payload in the original issue.
Milestone is 5.18.0 so merging this into master.
=> Make entity_class optional in /events API

CHANGELOG.md, bonsai/asset.go, bonsai/client.go, bonsai/client_test.go, cli/client/authentication.go, cli/client/authentication_test.go, cli/client/client.go, cli/client/error.go, go.mod, go.sum
This commit upgrades the HTTP client library used by sensuctl. In
doing so, it adds support for proxying HTTP requests from the
environment variables http_proxy, and https_proxy, and no_proxy.
Closes #3538 
The go-resty library had to be upgraded to a new major version.
Documentation changes are not required.
I used a free proxy to send requests to a sensu-staging instance, and it worked.
Yes, but targeting for 5.18.
=> Fix sensuctl proxy from environment

CHANGELOG.md, asset/fetcher.go, asset/fetcher_test.go
Signed-off-by: Vern Burton <me@vernburton.com>
Adding a non-200 status code check when fetching assets.
fixes #3302 
Yep.
Nope.
Nope.
No required.
Added test case.
Nope.
=> checking status code when fetching assets

CHANGELOG.md, backend/store/etcd/initialization.go
Signed-off-by: Vern Burton <me@vernburton.com>
This moves the initialization key into `EtcdRoot`, while supporting a fallback to the old location.
`FlagAsInitialized` only gets moved into the new location as we only want to write new files into the new location.  `IsInitialized` gates `FlagAsInitialized`  so that it should never be fallen into.
fixes #3560 
Yes
Nope
Nope
Nope
```
$ go test ./... 
ok      github.com/sensu/sensu-go/backend/seeds 1.038s
```
No.  Targeting 5.18.0
=> move initializationKey to EtcdRoot, and using old method as fallback

CHANGELOG.md, cli/commands/create/create.go, cli/commands/delete/delete.go
Assigns the namespace of the wrapper if not set.
Closes https://github.com/sensu/sensu-go/issues/3559
Yas.
Nah.
Nah.
We good.
`sensuctl create -f secret.yml `
```
---
type: Secret
api_version: secrets/v1
metadata:
name: mando
spec:
id: TEST_SECRET
provider: env
```
Targetting 5.18.0 in master
=> Fix wrapped resource namespaces

CHANGELOG.md, backend/backend.go, backend/cmd/start.go
This commit changes the way the sensu-backend starts. The call
to Run has been replaced with a call to RunWithInitializer. This
allows the commerical backend to pass its initializer to the OSS
start command.
Without this change, the commerical backend could lose its
enterprise-specific HTTP routes when the backend experienced an
internal restart.
Closes #3566 
Yes
I did manual tests with the enterprise codebase, both without this patch for reproduction verfication, and with the patch, and observed that the patch appears to fix the problem.
Yes
=> Pass an initialization function to start cmd

CHANGELOG.md, backend/api/authentication.go, backend/api/authentication_test.go, backend/authentication/providers/basic/basic.go
Fix #3556 
I suppose. Added.
I started by simply swapping 2 lines to get the right errors out of `TestCreds()`, but I soon realized that the tests for this function were broken in the first place. So I tried to fix them a little bit.
No.
Ran `sensuctl test-creds` and watched the backend's logs.
I thought it could have been, but Simon said no.
=> Rework TestCreds() errors and tests

CHANGELOG.md, backend/apid/actions/silenced.go, backend/apid/routers/silenced.go, backend/apid/routers/silenced_test.go
Adds support for API filtering in /silenced per the [documented behavior](https://docs.sensu.io/sensu-go/latest/api/overview/#field-selector).
Closes https://github.com/sensu/sensu-go/issues/3553
Yas.
Nah.
Nah.
We good.
Tested all endpoints from [Silenced API docs](https://docs.sensu.io/sensu-go/latest/api/silenced/).
No, merging to master.
=> Provide support for api filtering on /silenced

CHANGELOG.md, agent/api.go, agent/api_test.go
Signed-off-by: Vern Burton <me@vernburton.com>
Adds `/version` endpoint to Agent API
Response
```
{"version":"5.17.1"}
```
fixes #2879 
Yes.
Should this be expanded to other APIs?
No.
I haven't.  It might be useful to add some documentation for this endpoint.
Added Test Case
No.
=> adding /version to agent api

CHANGELOG.md, backend/apid/handlers/create.go, backend/apid/handlers/handlers.go, backend/apid/handlers/handlers_test.go, backend/apid/handlers/update.go, backend/apid/routers/events.go, backend/apid/routers/events_test.go, backend/apid/routers/silenced.go
It makes sure the entity & check names/namespaces match whatever is specified in the URL path. We previously assumed the name of the resources were always hold within the URL path variable `id`, which isn't the case for events.
Basically, the following requests now return an error:
```sh
$ curl -i -XPOST -H "Authorization: Bearer $SENSU_ACCESS_TOKEN" -H "Content-Type: application/json" \
-d '{"entity":{"metadata":{"name":"1-424242","namespace":"default"},"entity_class":"proxy"},"check":{"metadata":{"name":"helloworld","namespace":"default"},"status":0,"output":"everything is a-ok!"}}' \
http://127.0.0.1:8080/api/core/v2/namespaces/default/events/foo/foo
[...]
{"message":"the name of the resource (1-424242) does not match the name of the URI (foo)","code":1}
$ curl -i -XPOST -H …
```
=> Fix event payload validation on the backend events API

cli/commands/create/create.go, cli/commands/create/create_test.go
It fixes a bug where sensuctl would attempt to set a namespace to cluster-wide resources, such as authentication providers.
Fix a bug found in staging.
Nope, it fixes an unreleased commit.
Nope
The ValidateResource function was largely untested, so I had to take the time to write proper unit tests.
Nope
Manually tested with sensu-enterprise-go + unit tests.
Nope
=> Do not set namespace to global wrapped resources

backend/eventd/entity.go, backend/eventd/eventd.go
This change avoids an etcd read in eventd when the event's entity is an agent.
It avoids trying to create a proxy entity, assuming instead that the event's entity is already full specified.
No
Unverified.
Yes
=> Don't do an entity read when entity is an agent

CHANGELOG.md, agent/sockets_test.go, api/core/v2/check.go, api/core/v2/check_config.go, api/core/v2/check_config_test.go, api/core/v2/check_test.go, backend/keepalived/integration_test.go, cli/commands/check/subcommands/set_command_test.go
Signed-off-by: Vern Burton <me@vernburton.com>
This change ensures that check/check_config cannot have an empty `Command`.  
fixes #2551
Yes.
Nope.
Nope.  
Nope.
New test cases.
Nope.
=> ensuring that check/check_config has a valid command

CHANGELOG.md, asset/manager.go
It adds a timeout to `bolt.Open` when we try to open the asset manager cache, similar to what we have for other bolt databases.
It fixes a bug @cwjohnston experienced yesterday when two backends attempt to use the same `cache-dir`.
Added.
Nope
Nope
Nope
Yep
=> Add timeout when obtaining a file lock for the asset manager

api/core/v2/health.go, backend/apid/apid.go, backend/apid/routers/health.go, backend/backend.go, backend/store/etcd/event_store.go, backend/store/provider/provider.go
Adds support for exported fields and functions to display postgres health information from sensu-enterprise-go.
Required by https://github.com/sensu/sensu-enterprise-go/pull/871.
No functionality is changed. 
Nah.
https://github.com/gorilla/mux/issues/82#issuecomment-121411186
https://github.com/sensu/sensu-docs/issues/2223
QA crucible work will be created as part of the sensu-enterprise-go work.
Nope, feature work.
=> Support postgres health from sensu-go

CHANGELOG.md, agent/cmd/service_windows.go
Fixes an issue where `log-level` would not be applied when Sensu Agent is run under a Windows service.
Fixes #3407 
Yes.
No.
No.
Yes - no new documentation is required.
Tested on my Windows machine.
It could be considered a patch and I've targeted the release branch as a result.
=> Fix logging under windows services

api/core/v2/check.go, api/core/v2/handler.go, backend/keepalived/keepalived.go
This commit fixes a regression where the agent could no longer send keepalives to the backend.
Closes #3589 
No, this regression was not released.
Manual testing of the agent and backend.
=> Fix a regression introduced by #3574

CHANGELOG.md, api/core/v2/check.go
This fixes a bug where check history ordering could differ from the
order that events are processed by sensu-backend.
Closes #3583 
Yes
A lengthy discussion was spawned :)
We should assert that event history is ordered according to when events hit the backend, not when the check is executed. cc @hillaryfraley 
Only unit/integration testing.
=> Order event history in FIFO fashion

CHANGELOG.md, api/core/v2/check.go, api/core/v2/check_config.go, api/core/v2/check_config_test.go, api/core/v2/check_test.go
Unfortunately, it seems that check command validation is simply too
much of a change at this point. It breaks several test cases in our
QA suite, breaks examples in the docs, and cannot be done in the
5.x series of sensu-go.
cc @tarcinil 
An entry has been removed from CHANGELOG.md
Docs updates not required.
Unverified.
No
=> Revert check command validation

CHANGELOG.md, api/core/v2/meta.go, cli/commands/create/create.go, cli/commands/create/create_test.go
It automatically applies the `sensu.io/managed_by` label to resources created via `sensuctl create`.
Closes https://github.com/sensu/sensu-go/issues/3594
Added
Nope
It was surprisingly easy, I'm still wondering if I forgot something.
No docs required at the moment.
Manually tested with both core & commercial (wrapped) resources. Also added unit test coverage.
Nope
=> Apply managed_by label

CHANGELOG.md, backend/backend.go, backend/backend_test.go, backend/config.go, backend/etcd/etcd.go, backend/etcd/etcd_test.go, backend/etcd/sequence_test.go, backend/eventd/integration_test.go, backend/keepalived/integration_test.go, backend/liveness/liveness_test.go, backend/queue/queue_test.go, backend/ringv2/pool_test.go, backend/ringv2/ringv2_test.go, backend/store/cache/cache_integration_test.go, backend/store/etcd/store_test.go, backend/store/etcd/testutil/store.go, backend/tessend/tessend_test.go
It seems that in some circumstances, the etcd embedded client can
cause nil panics. For instance, when the embedded etcd is shut
down, the client cannot be safely used anymore.
Since this is an unacceptable state of affairs, we will revert to
using the gRPC client, which seems to be much more reliable.
Closes #3550
Closes #3571
Yes
We created a build of sensu-go that restarts internally every couple of seconds. In a clustered configuration, this was leading to nil panics quite frequently.
When we moved from the etcd embedded client to the etcd grpc client, the crashes stopped occurring.
Yes
=> Don't use the etcd embedded client

CHANGELOG.md, backend/store/cache/cache.go
Changes the cache Resource struct to be 64-bit aligned.
This is necessary to support 32-bit systems.
Fixes https://github.com/sensu/sensu-go/issues/3546.
Yes.
Nope!
Nope!
No new documentation required.
Tested that the backend no longer crashes on `linux/armv7`.
Yes.
=> Change struct alignment to support 32-bit systems

types/wrapper.go
Adds some logic for `created_by` in inner/outer object meta (required for wrapped enterprise resources).
Required by https://github.com/sensu/sensu-enterprise-go/issues/893 and https://github.com/sensu/sensu-enterprise-go/pull/895.
Nah.
Nah.
This was the complication for https://github.com/sensu/sensu-enterprise-go/issues/893.
We good.
Tested against enterprise branch. PR incoming.
Nope, part of feature work in master.
=> Add logic for created by to wrapper

CHANGELOG.md, backend/agentd/agentd.go, backend/authorization/rbac/rbac.go, backend/backend.go
```
This commit fixes a bug that caused sensu-backend to restart
whenever an agent terminates its connection. The bug was
introduced in 572b4b5facc4a4f7b310dcf0eb34ef711e9583e5, but went
unnoticed for the most part, due to the use of the embedded etcd
client, which appears to have different cancellation semantics than
the gRPC client.
Now that the gRPC client has been put back into place, this error
was exposed and made reproducible.
The nature of the error is that when RBAC authorization returned
an error, agentd would propagate the error back to its supervisor
in all cases, leading to an internal backend restart.
When a session's context is canceled, whether due to its client
disconnecting or otherwise, agentd should not propagate any
errors back to the backend supervisor.
```
Closes …
=> Fix a bug that caused sensu-backend to restart

CHANGELOG.md, backend/store/etcd/store.go, backend/store/etcd/store_test.go
Updates the behaviour of the store's `Create` method to marshal Wrapped objects using the JSON. Matches the behaviour of the `CreateOrUpdate` method.
Required for sensu/sensu-enterprise-go#870
Why not.
Chesterton's fence. If there was a good reason the method did not have the same behaviour I couldn't find it.
Integration & manual.
=> Update store to marshal wrapped resources on create

backend/apid/graphql/schema/mutations.gql.go, backend/apid/graphql/schema/mutations.graphql
The `putWrapped` mutation is unused by the open-source web application and when used in the commercial release can lead to failures.
=> [GraphQL] Deprecate putWrapped mutation

CHANGELOG.md, bonsai/asset.go
Sets the log level to debug for log messages in the Bonsai client.
Fixes #3605 
Yes.
Tested against my local cluster.
No.
=> Bonsai client should log out to debug instead of info

CHANGELOG.md, backend/dashboardd/dashboardd.go, cli/client/authentication.go, cli/client/client.go
This commit changes the dashboard service to write a status of 400
and an error message explaining that the user should not try to
connect to it with an API client.
For the purpose of this change, it is assumed that for the most
part, API clients will either be sensuctl or curl.
This should lead to less confusion, as users are prone to
connecting to the dashboard port with sensuctl or curl, and tend to
get confused when the service produces different results than what
is documented for the apid service running on a different port.
Several users have tried in error to connect to the dashboard port with an API client, which tends to partially work. This produces confusion.
See #3498
Closes #3279 
Yes
Documentation changes are not required.
I tested that the web UI still works, and that …
=> Don't service dashboard requests from API clients

CHANGELOG.md, api/core/v2/check.go, api/core/v2/check_config.go, api/core/v2/check_config_test.go, api/core/v2/check_test.go
Subscriptions cannot have empty strings in them.
cc: @echlebek - let's try this again.
fixes #2932 
It ensures that subscription elements are sane
Yeah.
N/A
N/A
N/A
I added tests to ensure that it functions as planned.  
Nope.
=> checking subscriptions to ensure that they do not have empty strings

CHANGELOG.md, backend/agentd/agentd.go, backend/agentd/session.go, backend/agentd/session_test.go, transport/client.go
This commit causes sensu-backend to reject websocket upgrade
requests from agents that try to connect to a namespace that does
not exist.
Closes #1028 
Yes
Docs changes not required.
The agent<->backend semantics are subtly different now, so this is not a patch-level change.
=> Disallow agent connect on inexistent namespaces

CHANGELOG.md, backend/apid/routers/routers.go
It fixes a bug where controllers that return either `actions.PermissionDenied` or `actions.Unauthenticated` would actually respond with an internal server error (500).
Closes https://github.com/sensu/sensu-go/issues/3634
Added
Nope
Nope
Nope
Manually verified
Yep
=> Return proper HTTP status code

CHANGELOG.md, backend/tessend/tessend.go
It allows tessen resource metrics to be registered at runtime. This is essential for adding count for commercial resources.
Required by https://github.com/sensu/sensu-enterprise-go/issues/902 & https://github.com/sensu/sensu-enterprise-go/issues/903
Added
Nope
Nope
Nope
Manually tested this commit on sensu-enterprise-go.
Nope
=> Additional Tessen resource metrics can now be registered at runtime

cli/commands/dump/dump.go, cli/commands/edit/edit.go, cli/resource/resolve.go
Refactors logic in `sensuctl dump` to the `resource` package so that it can be reused by other commands such as `sensuctl prune`.
Required by https://github.com/sensu/sensu-enterprise-go/pull/919
Nah, internal refactor.
Nah.
Nah.
We good.
`sensuctl dump`, unit tests here and in https://github.com/sensu/sensu-enterprise-go/pull/919
Nope, required for feature work.
=> Refactor dump logic into resource/resolve

CHANGELOG.md, cli/client/generic.go, cli/client/interface.go, cli/client/testing/mock_generic.go
Adds a generic client POST function that returns the response body.
Required by https://github.com/sensu/sensu-enterprise-go/pull/919
Yas.
Nah.
Deciding if we wanted to refactor `Post` to return a response body or create a new `PostBody` function.
We good.
Testing against https://github.com/sensu/sensu-enterprise-go/tree/sensuctl-prune
Nope.
=> Added a generic client POST function that can return the response body

CHANGELOG.md, backend/backend.go, backend/store/proxy.go, backend/tessend/data.go, backend/tessend/tessend.go
This commit annotates tessen metrics with the store provider (either "etcd", or "postgres", for now).
Closes https://github.com/sensu/sensu-enterprise-go/issues/557
Yes
Build sensu-go with the change, ran sensu-backend, and queried the metric in Tessen.
No
=> Add store metrics to tessen

cli/resource/parse.go
It prevents a panic in sensuctl create/prune if the input that gets parsed does not contain a valid file.
It fixes an unreleased bug that was introduced in the recent refactoring.
Nope
Nope
Nope
Nope
Nope
=> Prevent panics if JSON or YAML resources cannot be parsed

CHANGELOG.md, backend/backend.go, backend/keepalived/keepalived.go, backend/keepalived/keepalived_test.go, backend/store/etcd/event_store_test.go
This commit fixes an issue where keepalives would not always fire
correctly when using the postgres store. It seems that this
regression was introduced several releases ago, but it was not
always apparent for all users.
The keepalive mechanism was always consulting etcd when retrieving
events, and as such, when postgres was enabled, keepalives could be
incorrectly passing.
Unfortunately, due to the current architecture of sensu-go and
sensu-enterprise-go, it is not possible to write a unit test that
proves this commit fixes the issue. A test will need to be added
to the sensu-enterprise-go repo instead.
An unrelated unit test has been added that shores up testing of
check history generation; this has been done to maintain parity
between sensu-go and sensu-enterprise-go for tests.
Yes
The …
=> Keepalives now work correctly when using postgres

CHANGELOG.md, cli/client/client.go, cli/client/config/basic/basic.go, cli/client/config/basic/reader.go, cli/client/config/basic/reader_test.go, cli/client/config/basic/writer.go, cli/client/config/basic/writer_test.go, cli/client/config/config.go, cli/client/config/inmemory/inmemory.go, cli/client/config/mock.go, cli/client/testing/mock_config.go, cli/commands/config/help.go, cli/commands/config/set_timeout.go, cli/commands/config/set_timeout_test.go, cli/commands/config/view.go, cli/commands/config/view_test.go, cli/commands/configure/configure.go, cli/commands/configure/configure_test.go, cli/commands/root/root.go
Allow resty backend timeout to be configurable
Closes #3635 
The timeout isn't configurable, as gets triggered on highly used installations.
Yes, the changelog was updated in the "Unreleased" section
Documentation likely needs to be updated about this change.  Could someone point me to the right location?
Build sensuctl binary locally, and verified the setting was adjusted, and persisted in configuration file
No
=> Allow resty backend timeout to be configurable

CHANGELOG.md, backend/apid/actions/events.go, backend/apid/actions/events_test.go
Users can use the HTTP API to publish keepalives. If the published event's check name is "keepalive", then the event will be handled by keepalived.
Closes #2288
Yes
Docs updates may be required. CC @hillaryfraley.
```
[eric@cube sensu-go]$ sensuctl entity list
ID    Class    OS     Subscriptions             Last Seen            
────── ─────── ─────── ─────────────── ─────────────────────────────── 
cube   agent   linux   entity:cube     2020-03-05 15:46:07 -0800 PST  
me     proxy           test            N/A                            
[eric@cube sensu-go]$ curl -X PUT -H 'Authorization: Key <redacted>' --data @keepalive.json http://localhost:8080/api/core/v2/namespaces/default/events/me/keepalive -H 'Content-Type: application/json'
[eric@cube sensu-go]$ sensuctl entity list
ID …
```
=> Allow publishing keepalives via the HTTP API

CHANGELOG.md, agent/cmd/start.go, backend/cmd/start.go
When a user runs `sensu-backend start --help` or `sensu-agent start --help`, they can see the default path to the config file.
Closes #2563
Yes
I ran the commands and verified they worked as desired.
Yes
=> Print config file default location in help text

CHANGELOG.md, api/core/v2/handler.go, api/core/v2/handler_test.go, cli/commands/handler/create_test.go
This commit changes handler validation for pipe handlers. Pipe
handlers now require a command to be set, or their validation will
fail.
Closes #2696 
Yes
Only unit tests.
Yes
=> Require that handlers have a command set

CHANGELOG.md, agent/token.go, agent/token_test.go
Users can now escape quotes in token substitution templates, so that they can express quoted strings in these templates. For instance,
```
{{ .labels.frobber | default "\"foobar\"" }}
```
Would previously cause an error, but now correctly evaluates.
Closes #3640
Yes
No docs changes required.
Good old unit tests.
Yes
=> Support quoted strings in token substitution

backend/apid/routers/cluster.go
It modifies the default timeout value used when querying etcd for its members or its health.
Closes https://github.com/sensu/sensu-go/issues/3621
Added
Nope
Nope
This parameter is currently undocumented, so I opened https://github.com/sensu/sensu-docs/issues/2323.
Yep
=> Use a default timeout of 3s when querying etcd health

CHANGELOG.md, api/core/v2/event.go
It adds both the `event.is_silenced` & `event.check.is_silenced` field selectors; maybe we should only add one, but I feel like `event.is_silenced` is better in terms of UX.
Closes https://github.com/sensu/sensu-go/issues/3552
Added
Nope
Nope
I will open a new docs issue once we know which fields we are adding.
Manually tested in sensu-enterprise-go.
Nope
=> Add the is_silenced field selector for events

CHANGELOG.md, cli/client/client.go
It removes the following log entry whenever sensuctl is configured with an HTTP API: `WARN[0000] Using Basic Auth in HTTP mode is not secure, use HTTPS  component=cli-client`
Closes https://github.com/sensu/sensu-go/issues/3678.
Added
Nope. I reviewed the resty lib to make sure we weren't removing any other relevant warning messages.
Nope
Nope
Nope
=> Warning messages from Resty library are now suppressed in sensuctl

CHANGELOG.md, system/system.go
This is a workaround for alpine, since `ldd --version` returns an exit code of `1` but still display the relevant information. Therefore, we inspect `stderr` to figure out whether the pertinent data is available.
Closes https://github.com/sensu/sensu-go/issues/3664
Added
I think there's a couple of ways to fix that problem, like we could inspect the exit code with https://golang.org/pkg/os/#ProcessState.ExitCode but that feels a lot more work for the same result.
Nope
Nope
Built new docker images from sensu-enterprise-go and inspected the entity via sensuctl:
```
$ sensuctl entity info 9be8097ecd1f --format yaml
type: Entity
metadata:
name: 9be8097ecd1f
spec:
[...]
system:
arch: amd64
cloud_provider: "" …
```
=> The system's libc_type attribute is now populated on alpine containers

CHANGELOG.md, cli/commands/silenced/update.go
It removes deprecated flags for the `sensuctl silenced update` command; these flags were once supported about 2 years ago but at some point, the ability to update a silenced entry with flags was removed. Therefore, these flags are now misleading and should be removed.
Noticed by @nixwiz in Slack!
Added
Nope
Nope
Nope
Manually verified.
Yep
=> Removed deprecated flags in 'sensuctl silenced update' #3688)

CHANGELOG.md, cli/commands/commands.go, cli/commands/describetype/describe_type.go, cli/commands/describetype/describe_type_test.go, cli/commands/dump/dump.go
It adds the `sensuctl describe-type` command, which takes 1 argument, either `all` or a comma-separated list of short names and/or fully qualified names (e.g. `namespace,checks,authentication/v2.Provider`).
The output can be formatted in either the tabular, JSON or YAML format.
I also deprecated the `sensuctl dump --types` flag so it refers to this command, but it still work for now.
Closes https://github.com/sensu/sensu-go/issues/3632.
Added
Nope
Nope
I'll open a new sensu-docs issue so we document this new command and hopefully refer to this command when we list resources in our documentation (https://docs.sensu.io/sensu-go/latest/reference/rbac/#resources, https://docs.sensu.io/sensu-go/latest/sensuctl/reference/#sensuctl-edit-resource-types etc.)
Added rough unit tests and manually …
=> Add sensuctl describe-type command

CHANGELOG.md, agent/cmd/logger.go, agent/cmd/logger_unix.go, backend/cmd/logger.go, backend/cmd/logger_unix.go, util/logging/logging.go, util/logging/logging_test.go
This commit adds support to sensu-backend and sensu-agent for
incrementing the log level with SIGUSR1. When the process receives
this signal, the log level will be incremented in terms of
verbosity. When the level is at TRACE, the most verbose log level,
and the log level is incremented, it will wrap around to error
level.
Closes #1742
Yes
It's unclear at this time how to support this for Windows.
@hillaryfraley, we will need to document that users can now increase the log level at runtime, with the following commands for backends and agents:
```
kill -s SIGUSR1 $(pidof sensu-backend)
```
```
kill -s SIGUSR1 $(pidof sensu-agent)
```
I ran the above commands for the backend and agent.
No.
=> Support SIGUSR1 log level incrementing

CHANGELOG.md, backend/backend.go, backend/cmd/init.go, backend/cmd/start.go
It removes the use of a blocking client when attempting to initialize the backend, in order to have etcd log any TLS error encountered.
See https://github.com/sensu/sensu-go/issues/3663#issuecomment-613656403 for more context.
It also adds a `--timeout` flag to the `sensu-backend init` command.
This is a workaround for https://github.com/sensu/sensu-go/issues/3663. We can probably implement a better solution with a blocking client once [this PR](https://github.com/grpc/grpc-go/pull/3430) is released and etcd is updated to use it.
Added
Nope
go-grpc is not easy 😅 
Nope
I'd say so
=> Log TLS failures when initializing the backend

CHANGELOG.md, backend/store/etcd/check_store_test.go, backend/store/etcd/event_store.go, backend/store/etcd/event_store_test.go
This commit fixes two bugs where check state and last_ok properties
are not set on the first check execution. The properties are now
set before the event is written to the store.
Closes #3617 
Closes #3239 
Yes
We'll need to figure out if this bug affects the postgres event store in enterprise sensu.
Docs changes not required.
Integration testing seems to be good enough here.
Yes
=> Set check state and last OK on first event update

CHANGELOG.md, backend/backend.go, backend/cmd/start.go, backend/config.go
Adds `labels` and `annotations` as backend config options.
Closes https://github.com/sensu/sensu-go/issues/3698
Yup.
Nope.
Nope.
https://github.com/sensu/sensu-docs/issues/2383
**Backend logs:**
```
{"component":"backend","entity":{"entity_class":"backend","metadata":{"name":"Nikkis-MacBook-Pro","labels":{"mando":"baby yoda"}}},"level":"info","msg":"backend entity information","time":"2020-04-16T14:13:32-07:00"}
```
Nope.
=> Add labels and annotations as backend config options

asset/expander_test.go, asset/integration_test.go
Most tests already use ioutil or testutil to create one-off files/dirs.
These are the only ones left. Without this, tests tend to fail on on
multi-user machines if other users run the same tests.
Signed-off-by: Fabian Geisberger <fabi@hudson-trading.com>
Instead of writing directly to TEMPDIR, use testutil.TempDir to better isolate those tests.
If userA runs the test on a machine, and the directory doesn't get cleaned, userB is unable to write to that directory afterwards, breaking the tests.
I don't think so. Tiny test-only chagne.
Nope.
Creating temp files/dirs is not standardized in the code base. Eventually all tests should probably use the testutil helper.
n/a
Run the tests.
Nope.
=> Stop using deterministic directories in tests.

CHANGELOG.md, asset/fetcher.go
It adds any encountered error while fetching an asset to the returned error.
Closes https://github.com/sensu/sensu-go/issues/3211
Added
Nope
I wasn't able to reproduce the bug mentioned but while auditing the code, I found two cases where underlying errors were not returned nor logged.
Nope
N/A
Yep
=> Return underlying errors when fetching an asset

CHANGELOG.md, asset/filtered_manager.go
It changes the log level for the log entry whenever an asset cannot be installed because it didn't matched any of the build filters.
Closes https://github.com/sensu/sensu-go/issues/3391
Added
Nope
Nope
Nope
Manually verified
Yep
=> Log warning when assets are ignored because of filters

CHANGELOG.md, backend/agentd/agentd.go
#3614 was a partial fix for this issue, but only addressed cancellation during authorization; we shouldn't propagate context cancellation errors during authentication either.
Fixes #3571
Yes.
It was difficult to track down the origin of the logged error since that code branch didn't log anything itself, so the only log entry was incredibly generic:
```
{"component":"backend","error":"internal error: internal error: context canceled","level":"error","msg":"backend stopped working and is restarting","time":"2020-03-27T00:55:03-04:00"}
```
No docs.
Manual testing in my nonprod environment with an Ansible playbook that would previously reliably induce a restart.
Yes.
=> Fix another bug that caused sensu-backend restarts

CHANGELOG.md, agent/transformers/graphite.go, agent/transformers/influx_db.go, agent/transformers/opentsdb.go
Fixes a bug in multi-line metric extraction that appeared in windows agents by using `bufio` rather than manually splitting lines separated by `\n`.
Closes https://github.com/sensu/sensu-go/issues/3043
Yas.
Nah.
Nah.
We good.
Tested metrics with newline characters on a windows agent with the configuration below.
**check.yml**
```
type: CheckConfig
metadata:
name: extract-graphite
spec:
command: perl C:\print.pl
interval: 10
output_metric_format: graphite_plaintext
output_metric_handlers:
- ingest-graphite-metrics
subscriptions:
- windows
```
**print.pl**
```
print "os.SERVER.net.Ethernet.tx_bits 2562989216 1560358425\n";
```
**metric debug event**
```
$ sensuctl event info qa-automation …
```
=> Fix a bug in multi-line metric extraction that appeared in windows agents

CHANGELOG.md, backend/store/etcd/event_store.go, backend/store/etcd/event_store_test.go
Fixed a bug where the etcd event store would return prefixed matches rather than exact matches when getting events by entity.
Closes https://github.com/sensu/sensu-go/issues/3686
Yas.
Nah.
Nah.
We good.
Steps to reproduce in https://github.com/sensu/sensu-go/issues/3686, and unit test.
Yup.
=> Fix events by entity in etcd event store

CHANGELOG.md, api/core/v2/env_vars.go, api/core/v2/env_vars_test.go
It fixes the validation logic for the `env_vars` slice elements so equal signs (`=`) can be used in values.
Fixes https://github.com/sensu/sensu-go/issues/3252
Added
Nope
Nope
Nope
Successfully reproduce the use case in https://github.com/sensu/sensu-go/issues/3252, by printing the environment variable with `echo $API_TOKEN`.
```
$ s event list
Entity      Check                                 Output                               Status   Silenced             Timestamp                             UUID
────────── ──────────── ─────────────────────────────────────────────────────────────── ──────── ────────── ─────────────────────────────── ──────────────────────────────────────
gin        check-echo   bobsyouruncle==                                                      0   false …
```
=> Fix the validation for env_vars to allow the equal sign in values

CHANGELOG.md, cli/commands/logout/logout.go, cli/commands/logout/logout_test.go
This PR modifies `sensuctl logout` so it resets the `trusted-ca-file` & `insecure-skip-tls-verify` values.
There's currently an underlying bug which configure the CLI client with these two TLS values before the flags are even evaluated: https://github.com/sensu/sensu-go/blob/de25272fc85857fcab003eab874acef1bd791808/cli/cli.go#L40-L49
Here's a demo of the current behavior:
```
$ sensuctl configure -n --username admin --password P@ssw0rd! --url https://52.36.245.15:8080
Error: unable to authenticate with error: Get https://52.36.245.15:8080/auth: x509: certificate signed by unknown authority
exit status 1
$ sensuctl configure -n --username admin --password P@ssw0rd! --url https://52.36.245.15:8080 --insecure-skip-tls-verify
$
$ sensuctl …
```
=> sensuctl logout resets the TLS config

CHANGELOG.md, backend/backend.go, backend/etcd/etcd.go, backend/eventd/eventd.go, backend/eventd/eventd_test.go, backend/keepalived/keepalived.go, backend/liveness/liveness.go, backend/ringv2/ringv2.go, backend/schedulerd/executor.go, backend/store/etcd/store.go, backend/tessend/tessend.go
This commit solves several issues with backend restarts.
* stopGroup and errorGroup no longer block indefinitely after the
run context is cancelled, fixing a small goroutine leak.
* The liveness package no longer caches state at the package scope,
fixing a bug where clients that were closed after a run would be
used. This was the cause of errors like "unary invoker failed",
leading to a crash.
* The backend will no longer try to restart before the previous
run has completely shut down.
* Keepalived goroutines no longer persist between restarts, fixing
a rather large goroutine leak.
* Keepalived and eventd callbacks no longer execute beyond the
scope of their contexts.
* Tessen goroutines no longer persist past the lifetime of Tessen,
which could cause spurious error messages in the logs. …
=> Fix several stability bugs, add SIGHUP reloading

backend/backend.go, backend/store/proxy.go
This change ensures that after the backend restarts, the event store is closed. This fixes a bug where postgres connections can linger after the backend restarts internally.
In concert with another bug, where backend restarts occur far too often, connections can leak and overwhelm the server.
Yes
Documentation changes are not required.
I used the work done in https://github.com/sensu/sensu-go/pull/3723 to trigger internal restarts. It both helped me reproduce the issue and show that this patch fixes it.
This change is a  patch.
=> Close event store at end of backend run

CHANGELOG.md, backend/liveness/liveness.go, backend/queue/queue.go, backend/ringv2/ringv2.go, backend/store/etcd/asset_store.go, backend/store/etcd/authentication.go, backend/store/etcd/check_store.go, backend/store/etcd/cluster_id_store.go, backend/store/etcd/entity_store.go, backend/store/etcd/event_store.go, backend/store/etcd/filter_store.go, backend/store/etcd/handler_store.go, backend/store/etcd/handler_store_test.go, backend/store/etcd/hook_store.go, backend/store/etcd/keepalive_store.go, backend/store/etcd/mutator_store.go, backend/store/etcd/namespace_store.go, backend/store/etcd/silenced_store.go, backend/store/etcd/store.go, backend/store/etcd/user_store.go
This PR causes sensu-backend to retry etcd requests if it receives an error saying "too many requests". It retries using exponential backoff.
sensu-backend is too likely to crash when experiencing high load.
Yes
No docs changes required.
Extensive performance testing.
Yes
=> Don't restart sensu-backend on etcdserver: too many requests

CHANGELOG.md, version/version.go, version/version_test.go
Adds a new `GoVersion` field to `version.go` that records the version of Go used to build each binary.
Fixes https://github.com/sensu/sensu-enterprise-go/issues/976.
Yes.
No new docs required.
Updated tests and also tested manually.
No.
=> Add GoVersion to version.go

backend/apid/graphql/hook.go
By default field resolvers will use reflection to resolve a specific field, however, the default resolver has issues traversing embedded types. As such when it was trying to resolve the hook config field it was leading to a panic.
Required for sensu/web#305
Unlikely, the GraphQL service isn't publicly supported at this time.
Manual.
=> [GraphQL] Fix bug with hook config field resolver

backend/apid/graphql/mutations.go, backend/apid/graphql/mutations_test.go
By not unnecessary fetching the check when we queue an adhoc check, we avoid a potential panic in the case where the check is not available.
Sidesteps chance of a panic. See https://github.com/sensu/web/issues/141.
Unlikely, the GraphQL service is not publicly supported. 
I suspect we do not need to ensure that users have _both_ read & write access to checks, but it might be worth double checking.
Reviewed unit test & ran it manually.
=> [GraphQL] Avoid unnecessary fetch in adhoc check mutation

CHANGELOG.md, cli/commands/edit/edit.go
It makes notepad the default editor on Windows.
Quality of life improvement for Windows users.
Yes
```
wine ./sensuctl.exe edit check test
```
No
=> Make notepad the default Windows editor

CHANGELOG.md, agent/agent.go, agent/cmd/service_windows.go, agent/cmd/start.go, agent/cmd/windows.go, cmd/sensu-agent/main.go, util/logging/rotate_logger.go, util/logging/rotate_logger_test.go
This commit makes signifcant fixes and improvements to the Windows
sensu-agent, including log rotation features and improvements to
the way the service installer handlers its arguments.
The service installer now supports all of the arguments that the
regular sensu-agent start command does, and will remember those
arguments when launching the application.
Log rotation is now supported, with support for configurable
log file sizes, and reaping old log files. On rotate, logs are
zipped.
Closes #2937 
Yes
Documentation updates will be required. cc @hillaryfraley
Extensive manual testing, including:
* Testing that `service run` works the same as `service install`.
* Testing that logs are output as expected, in both default and specified locations.
* Testing that logs rotate after the maximum …
=> Windows agent: fix flag issues, add log rotation

agent/cmd/service_windows.go, agent/cmd/windows.go
This was missing from the previous PR. We need a way to patch the function used to create a new agent by the Windows service runner.
=> Use patchable AgentNewFunc

CHANGELOG.md, system/system.go
Checks `ldd --version` output for `glibc` per ubuntu:
```
$ sudo ldd --version
ldd (Ubuntu GLIBC 2.23-0ubuntu10) 2.23
```
Closes https://github.com/sensu/sensu-go/issues/3762
Yas.
Nah.
Nah.
We good.
Tested in staging against https://github.com/sensu/sensu-enterprise-go/tree/bugfix/ubuntu-libc with https://github.com/sensu/sensu-go-qa-crucible/pull/124.
Yup, targeting release/5.20 branch.
=> Fix libc implementation for ubuntu

backend/tessend/tessend.go, backend/tessend/tessend_test.go
Adds support for entity class counts in Tessen. Entity class counts will only be collected in commercial distributions.
Required by https://github.com/sensu/sensu-enterprise-go/pull/1041
Related https://github.com/sensu/tessen/pull/17
Closes https://github.com/sensu/sensu-go/issues/3741
No, entity class counts will only be collected in commercial distributions.
Nah.
Nah.
We log every metric for transparency, we do not have to document every metric.
```
SELECT
time as "time", value, cluster_id
FROM metrics
WHERE name = 'entity_class_agent_count' AND
$__timeFilter("time") AND tags->>'license_account_name' is not null and tags->>'license_account_name' != ''
GROUP BY time, cluster_id, value ORDER BY 1
```
No.
=> Add support for entity class counts to tessen

backend/apid/routers/users.go, backend/apid/routers/users_test.go
This PR fixes a bug introduced in https://github.com/sensu/sensu-go/pull/3753.
TL;DR We need to empty the `Password` field once we validated it was the proper one, otherwise the `CreateOrReplace` will refuse it because it differs from the hash.
Fixes a bug found in https://github.com/sensu/sensu-go-qa-crucible/pull/122#pullrequestreview-412794184.
Nope, unreleased stuff.
Nope
Nope
Nope
Deployed on staging & tested with the crucible tests.
Yes but it's a patch for an unreleased feature.
=> Fix a bug where users could not change password

CHANGELOG.md, cli/commands/dump/dump.go, cli/resource/resolve.go
Add --omit flag to sensuctl dump
Also fixed a bug where resources processed by dump could be dupes.
For instance, if both checks and core/v2.CheckConfig are specified
then the dumper will dump checks twice.
Closes #3724 
Yes
I had to write some additional tests for functions that were missing unit tests.
We'll need to document the new flag. cc @hillaryfraley 
I manually verified that types can now be omitted by running `sensuctl dump all --omit handlers`, and observed that handlers were trimmed from the resulting data set.
No
=> Add --omit flag to sensuctl dump

cli/cmdmanager/manager.go, cli/cmdmanager/manager_test.go
This commit fixes a bug where command assets can't be retrieved
from bonsai, because it assumes they will not be provided in a
wrapper. However, bonsai does serve the asset in a wrapper.
Fixes #3768 
Yes
I had to remove the requirement that command assets have the `io.sensu.bonsai.provider` and `io.sensu.bonsai.type` annotations. The installer will still consult these annotations, but if they are missing, installation will not be impeded.
We need developer documentation for writing bonsai assets.
```
[eric@cube sensu-go]$ sensuctl command install ec2-discovery portertech/sensu-ec2-discovery:0.3.0
fetching bonsai asset: portertech/sensu-ec2-discovery:0.3.0
command was installed successfully
```
Yes
=> Fix retrieving command assets from bonsai

CHANGELOG.md, backend/apid/apid.go, backend/apid/middlewares/authentication.go, backend/apid/middlewares/logging.go
Adds the username as a field in the API request logger by extracting the jwt claims from the request context. PR required in sensu-enterprise-go to ensure the `SimpleLogger` is called _after_ authentication.
Closes https://github.com/sensu/sensu-go/issues/3763
Yas.
Nah.
Nah.
We good.
Checked the logs on requests using tokens and api keys.
```
{"component":"apid","duration":"1.272ms","level":"info","method":"GET","msg":"request completed","path":"/api/core/v2/namespaces/default/events","size":2832,"status":200,"time":"2020-05-18T12:10:14-07:00","user":"admin"}
```
Yas, targeting release/5.20 branch.
=> Add username as field in API request logger

CHANGELOG.md, api/core/v2/rbac.go, api/core/v2/rbac_test.go, api/core/v2/validators.go
This commit adds validation for subjects in RBAC role bindings and
cluster role bindings. Previously, users could create bindings with
invalid subjects, leading to confusion.
Fixes #3770 
Yes
Docs changes are not required.
Unit testing should suffice.
Yes.
=> Add validation for subjects in role bindings.

CHANGELOG.md, backend/schedulerd/executor.go, backend/schedulerd/executor_test.go
It prevents the scheduler from stopping the scheduling of proxy check requests if token substitution or execution of a proxy check fails for a proxy entity, and continues with the next entity instead.
Closes https://github.com/sensu/sensu-go/issues/3784
Added
Nope
Nope
Nope
Added a unit test & manually verified.
Yep
=> Don't block proxy check requests scheduling on errors

api/core/v2/internal/codegen/check_protoc/LICENSE, api/core/v2/internal/codegen/check_protoc/main.go, api/core/v2/internal/codegen/generate_type/LICENSE, api/core/v2/internal/codegen/generate_type/generate_type.go, api/core/v2/internal/codegen/generate_type/generate_type_test.go, api/core/v2/types_gen.go, api/core/v3/internal/codegen/check_protoc/LICENSE, api/core/v3/internal/codegen/check_protoc/main.go, api/core/v3/internal/codegen/generate_type/LICENSE, api/core/v3/internal/codegen/generate_type/generate_type.go, api/core/v3/internal/codegen/generate_type/generate_type_test.go, api/core/v3/types_gen.go
This commit moves some programs needed for code generation to
internal packages. This is done to prevent 'go generate' from
breaking when used within a module.
Fixes 'go generate' for core/v2, and for core/v3, when we publish
its module.
=> Use code gen "scripts" from internal packages

CHANGELOG.md, go.mod, go.sum
Adds support for AIX by bumping a few of our dependencies and using our own fork of the fsnotify library.
Fixes #2944.
Yes.
No.
No.
We will need to add AIX for the ppc64 architecture to our docs and downloads page. It requires AIX 7.2 or later on POWER8 processors or later. cc @hillaryfraley 
It successfully builds.
No - targeting `release/5.21` so it can go out with the 5.21.0 release.
=> AIX support

backend/api/namespace.go, backend/api/namespace_test.go, backend/apid/graphql/dataloader.go, backend/apid/graphql/interfaces.go, backend/apid/graphql/mock_test.go, backend/apid/graphql/viewer_test.go, backend/apid/routers/namespaces.go, backend/apid/routers/namespaces_test.go, namespaces?limit=1
It fixes a bug introduced in https://github.com/sensu/sensu-go/pull/3776 by reverting to the use of the API client when listing namespaces.
I modified the `ListNamespaces` method of the `NamespaceClient` so it works similarly to the generic handlers, and therefore pass the `SelectionPredicate` pointer up to the generic store.
Fixes the QA crucible.
Nope, it fixes unreleased stuff.
Nope
Nope
Nope
Manually tested via sensuctl & web UI, and added a unit test.
```bash
$ curl -i -H "Authorization: Key $SENSU_API_KEY" http://127.0.0.1:8080/api/core/v2/namespaces\?limit\=1
HTTP/1.1 200 OK
Content-Type: application/json
Sensu-Continue: ZGVmYXVsdAA
Date: Thu, 04 Jun 2020 19:41:17 GMT
Content-Length: 20
[{"name":"default"}]
$ curl -i -H "Authorization: Key $SENSU_API_KEY" …
```
=> Bugfix for curated namespaces

cli/resource/parse.go, go.mod
It seems that goimports did the wrong thing here. Reverting the import to ghodss/yaml.
=> Remove k8s yaml dependency

cli/commands/user/change_password.go
It fixes a typo in a survey tag for the interactive mode of `sensuctl user change-password`.
It prevented users from changing a password using the interactive mode. Reported via https://github.com/sensu/sensu-docs/pull/2504#issuecomment-640714822.
Nope
Nope
Nope
Manually verified.
Yep
=> Change password survey bugfix

backend/api/authentication.go
Fixes bug in the `api` package where the previous expiry date was returned when renewing an auth token pair.
Could lead to unintended behaviour in clients.
Manual.
Yes.
=> Return new expiry date when renewing an auth token pair

cli/cmdmanager/manager.go, cli/cmdmanager/manager_test.go
Use `filepath` instead of `path` in tests in order to have tests that work on Windows.
Fix broken test in `cmdmanager` on Windows.
Not sure why AppVeyor didn't run on #3837 
No.
Not needed.
I didn't; I'm counting on AppVeyor.
No.
=> Fix cmdmanager tests on Windows

CHANGELOG.md, backend/secrets/broken_provider.go, backend/secrets/provider.go
Clarifies the wording of a secret provider error message, and also adds a new type of provider, BrokenProvider. BrokenProvider can be used to add a secret provider that isn't working properly. This helps users because they will be able to see the configuration error that the provider encountered in event output, instead of in the sensu logs.
A subsequent PR for enterprise sensu will be created, making use of the BrokenProvider facility.
Part of https://github.com/sensu/sensu-enterprise-go/issues/1104
Yes, only for the error message clarification however.
Documentation changes are not required.
Automated testing.
Yes, but the next release is 6.0, so I haven't applied it to the release branch.
=> Clarify secrets error message, add BrokenProvider

CHANGELOG.md, backend/agentd/agentd.go
Adds a ConnState function in agentd's http server to improve logging around the agent websocket connection.
Closes https://github.com/sensu/sensu-go/issues/3771
Yas.
Nah.
Nah.
We good.
See notes in original issue.
Yes, but next release is in master.
=> Improve logging around the agent websocket connection

CHANGELOG.md, backend/pipeline/handler.go, backend/pipeline/mutate_test.go, backend/pipeline/mutator.go
Logs and returns an error if a mutator cannot be found.
Closes https://github.com/sensu/sensu-go/issues/2784
Yas.
Nah.
Nah.
We good.
- Added a unit test that fails without the suggested changes.
- Verified e2e with the steps to reproduce from the original issue.
New enriched log with error:
```
{"check_name":"foo","check_namespace":"default","component":"pipelined","entity_name":"nikkictl","entity_namespace":"default","error":"mutator \"nope\" does not exist","handler":"cat","level":"error","msg":"error mutating event","time":"2020-06-29T12:43:11-04:00","uuid":"5192efe0-8645-4b2d-a55a-1e05ec3d1f20"}
```
Yes, but TBH I'm not sure what our branch strategy is right now with a few potential upcoming releases. Targeting master for now.
=> Log and return an error if a mutator cannot be found

.github/workflows/golangci-lint.yml
Adds a timeout for the golangci-lint github action (see https://github.com/golangci/golangci-lint-action/issues/25 and https://github.com/sensu/sensu-enterprise-go/blob/1856e77c4fe2b3bf4bf09f941d9c87751215dcc3/.github/workflows/golangci-lint.yml#L22).
Closes https://github.com/sensu/sensu-go/issues/3864
Nah.
Nah.
Nah.
We good.
CI did.
Targeting master.
=> Add a timeout for the golangci-lint github action

backend/store/cache/logger.go, backend/store/cache/v2/logger.go
This may have been an oversight from the original PR. `api_version` could be confused with the api version of a resource.
```
{"api_version":"v1","component":"cache","level":"debug","msg":"rebuilding the cache for resource type *v2.Silenced","time":"2020-07-02T11:52:03-04:00"}
{"api_version":"v2","component":"cache","level":"debug","msg":"rebuilding the cache for resource type *v3.EntityConfig","time":"2020-07-02T11:52:03-04:00"}
```
becomes
```
{"cache_version":"v1","component":"cache","level":"debug","msg":"rebuilding the cache for resource type *v2.Silenced","time":"2020-07-02T11:52:03-04:00"}
{"cache_version":"v2","component":"cache","level":"debug","msg":"rebuilding the cache for resource type …
```
=> Update logger field for cache version

backend/agentd/agentd.go, backend/agentd/session.go, backend/agentd/session_test.go, backend/backend.go, backend/messaging/message_bus.go, backend/messaging/message_bus_test.go, backend/store/store.go, transport/transport.go
This PR modifies the agent sessions in agentd so receive entity config updates via the bus, encode them and send them over the relevant agents via the transport.
Additionally, I removed the `sendq` channel, which is unused.
Closes https://github.com/sensu/sensu-go/issues/3880
There's no changes exposed to users yet.
As discussed, I omitted the integration of the cache/watcher, which will be implemented in a subsequent PR.
Nope
Not yet.
Unit test + manually verified the agent received a mocked entity config update.
Nope
=> Subscribe agentd sessions to entity config updates

backend/api/namespace.go, backend/api/namespace_test.go, backend/apid/routers/helpers_test.go, backend/apid/routers/namespaces.go, backend/apid/routers/namespaces_test.go, backend/store/etcd/migrations.go, testing/mockauthorizer/authorizer.go
This commit modifies how namespaces are created. When namespaces
are created, a special role and role binding are now created along
with them. This role is intended to allow pipelined to access the
event store in an authorized way.
Fixes #3867 
Yes
The PR is not finished because I can't figure out how to reconcile the handler unit tests.
Docs changes not required.
Unverified.
No
=> Create roles and bindings on namespace create

CHANGELOG.md, cli/client/client.go
Sets the User-Agent header once during client creation instead of on each request.
Setting it on each request triggers a concurrent map write issue as described in #3861 
I think so. I've included one.
I don't think so.
No
No doc update required.
In addition to the unit tests, I've tested this here (https://travis-ci.org/github/jtopjian/terraform-provider-sensu/builds/706001904) repeatedly, and has passed each time. Before this fix, the test suite would fail 9/10 times.
Yes, but I'm not sure which branch I should target, so I'm using master. Happy to resubmit if needed.
=> Set the User-Agent during client creation and not on each request

CHANGELOG.md, cli/commands/asset/add.go
Enriches output of `sensuctl asset add` with help usage for how to use the runtime asset.
Closes https://github.com/sensu/sensu-go/issues/3885
Yas.
Nah.
Nah.
Filed https://github.com/sensu/sensu-docs/issues/2599
```
$ sensuctl asset add sensu/monitoring-plugins
no version specified, using latest: 2.5.2
fetching bonsai asset: sensu/monitoring-plugins:2.5.2
added asset: sensu/monitoring-plugins:2.5.2
You have successfully added the Sensu asset resource, but the asset will not get downloaded until
it's invoked by another Sensu resource (ex. check). To add this runtime asset to the appropriate
resource, populate the "runtime_assets" field with ["sensu/monitoring-plugins"].
```
No, but targeting master for the next release.
=> Enrich output of sensuctl asset add

backend/keepalived/keepalived.go, backend/keepalived/keepalived_test.go
Initializes backend entity management in keepalived.
Closes https://github.com/sensu/sensu-go/issues/3872
Already covered in https://github.com/sensu/sensu-go/blob/master/CHANGELOG.md#breaking.
I did, but @echlebek clarified all of my questions in the original issue.
Nah.
Filed https://github.com/sensu/sensu-docs/issues/2597
Unit test. Some e2e testing. I was able to verify that entity config does not get overwritten by new flag options, however the entity within a keepalive event does get overwritten. Is this out of scope @echlebek?
_Edit:_ Event's entity is in scope, added logic to account for this use case in `handleUpdate`.
_Edit:_ Reverted the change to `handleUpdate`, as Eric believes this perhaps is handled by other in progress work. …
=> Initialize backend entity management in keepalived

backend/agentd/watcher.go, backend/agentd/watcher_test.go, backend/backend.go
It adds an etcd watcher to entity configs and publish updates to the bus, so sessions can receive updates about their subscribed entities.
Closes https://github.com/sensu/sensu-go/issues/3881
I believe this change can be considered as covered with the lines added via https://github.com/sensu/sensu-go/pull/3884.
Nope!
Nope!
We will need to cover the entity config update in a separate sensu-docs issue I believe.
Unit tests + manual testing. I'll open an issue on sensu-go-qa-crucible so we can automate some of this testing.
Nope
=> Publish entity config updates to agentd sessions

backend/cmd/upgrade.go
This commit fixes the confirmation dialog, so the user doesn't have
to enter "true" or "false", and instead can enter "y" or "n".
I've tested it manually and it now produces the desired UX.
Edit: also now supports the `--skip-confirm` flag.
Fixes #3900 
Fixes #3901
=> Improve sensu-backend upgrade UX

backend/agentd/session.go, backend/agentd/session_test.go
This PR adds support for automatically reflecting subscriptions changed made to entity configs in the agentd sessions.
In order to support that change, I had to refactor a bit the `Session` struct. The most notable change is the switch from a buffered channel of subscriptions (`subscriptions`) to a map of subscriptions (`subscriptionsMap`), so we don't have to deal with blocking senders and removing elements from it.
I also moved the logic around subscribing and unsubscribing from check subscriptions to their own methods, so it's re-usable and more easily testable.
Additionally, I refactored a bit the unit tests into test cases because most of these tests were sharing the same configuration logic.
Closes https://github.com/sensu/sensu-go/issues/3895
I think it can be included in the lines …
=> Subscribe and unsubscribe agents based on entity config updates

backend/agentd/agentd.go, backend/agentd/session.go, backend/agentd/session_test.go, testing/mocktransport/transport.go, transport/transport.go
It forces the session to send a close control message over the transport (websocket) when stopping, which allows the peer (agent) to close the transport on its side too.
I also modified a bit the `stop()` logic we don't block forever when stopping the session if the peer never send back a message.
It fixes a bug where the agent would always send back a last keepalive (with a possibly stale entity config) when a session would severe its connection.
Nope
Nope
Nope
Nope
Manually verified, and also applied this patch over Eric's PR while testing.
I probably need a second pair of 👀 just to make sure I'm not missing anything.
Unreleased stuff.
=> Send a close message over the websocket when closing a session

agent/agent.go, agent/entity.go, backend/keepalived/keepalived.go, backend/keepalived/keepalived_test.go
This commit fixes a bug where entity information in keepalive events
was not correct. To achieve this, the following things were done:
* Use a.getAgentEntity() when creating keepalives
* Clear the agent's cached entity on session restart
* Update keepalived to only send an entity notification if the
entity config is out of sync.
* Update keepalived to update keepalive events with the latest
entity config.
=> Ensure keepalive entities are consistent

cli/commands/asset/add.go, graphql/generator/common.go
@hillaryfraley found this bug when documenting https://github.com/sensu/sensu-docs/issues/2599. We should print the correct runtime asset name if it is renamed with `--rename`.
```
$ sensuctl asset add sensu/sensu-slack-handler --rename slack-handler
no version specified, using latest: 1.3.2
fetching bonsai asset: sensu/sensu-slack-handler:1.3.2
added asset: sensu/sensu-slack-handler:1.3.2
You have successfully added the Sensu asset resource, but the asset will not get downloaded until
it's invoked by another Sensu resource (ex. check). To add this runtime asset to the appropriate
resource, populate the "runtime_assets" field with ["slack-handler"].
$ sensuctl asset add sensu/sensu-slack-handler
no version specified, using latest: 1.3.2
fetching …
```
=> Print renamed asset in help message

CHANGELOG.md, backend/api/entity.go, backend/api/entity_test.go, backend/apid/actions/entities.go, backend/apid/actions/entities_test.go, backend/apid/apid.go, backend/apid/routers/entities.go, backend/apid/routers/entities_test.go, backend/backend.go
Unless the entity is a proxy entity, updates to entities now ignore state related fields.
Closes #3896 
Added.
No.
No.
I don't believe any documentation has to change:
- nothing changes for proxy entities
- altering entity state when updating an entity was not useful since the agent would quickly override that state
Updated and ran all unit and integration tests.
No.
=> Add Entity state update exception

backend/backend.go
>This is my bad; it was forgotten in a previous PR, leading to updates to
>non-proxy entities being broken in the REST API.
>
>GraphQL and backend API client were fine though!
>
>Signed-off-by: Cyril Cressent <cyril@sensu.io>
This fixes the null pointer dereference. This wasn't caught by unit tests because it's an integration issue in the backend's initialization code.
Make updating non-proxy entities via the REST API (and by extension, `sensuctl`) work again.
No.
No.
No.
No changes needed.
Re-tested updating existing entities locally, this time with combinations of proxy and non-proxy entities...
No.
=> Bugfix: set a storev2 in apid's config

backend/store/etcd/migrations.go
This commit fixes a bug in the database migration that creates
a system:pipeline role and role binding for each namespace. The
type of the role binding subject has been correct from "user" to
"Group".
=> Fix a db migration bug

backend/store/etcd/entity_store.go, backend/tessend/tessend.go
>With the entities now being stored as a split EntityConfig and
>EntityState in different etcd key prefixes, we can't count entities by
>looking at the old "entities" key prefix.
>
>We now consider "entity_count" to be the count of EntityConfig.
>
>Signed-off-by: Cyril Cressent <cyril@sensu.io>
Make Tessen's `entity_count` non-zero in 6.0 clusters.
I don't think it does, since this should have done as part of other 6.0 changes that are already mentioned in the change log.
No.
No.
On a local test setup with entities in it, I observed that before the change, tessen would always report an `entity_count` of zero in the logs. After this change, it reports the correct count.
No.
=> Update Tessen entity_count

backend/api/entity.go, backend/api/entity_test.go
Previously, the `EntityClient` (api package) used the generic store methods to list/get v2 entities and now with state/config being stored separately, this no longer works in 6.X.
Retain functionality.
No. Regression did not exist in previous release.
Unit tests.
=> Fix bug in api package where consumer was unable to retrieve entities

CHANGELOG.md, agent/agent.go, agent/cmd/start.go, agent/config.go, cmd/loadit/main.go, system/system.go
It permits an agent to optionally disable collection of system information. This is particularly relevant in case of the _loadit_ benchmarking tool.
For performance testing.
Added, although we don't need to ship this in 6.0
Nope
Nope
New docs will be required, just depends on whether we include that change within 6.0.
Nope
=> Allow mocking of system information collection

backend/agentd/agentd.go, backend/store/cache/cache_test.go
While this does not solve a large perf regression, it is a small performance win.
This change uses `cache.Get("")` rather than `cache.GetAll()` when retrieving non-namespaced resources in agentd. The benchmark tests I wrote show that it's much less efficient to iterate the cache twice. `GetAll()` iterates when consolidating resources across namespaces where `Get("")` retrieves all non-namespaced resources without iterating.
```
$ go test -bench=.
goos: darwin
goarch: amd64
pkg: github.com/sensu/sensu-go/backend/store/cache
BenchmarkGetEmpty-12            27691777                43.1 ns/op
BenchmarkGetAll-12               3771334               323 ns/op
PASS
ok      github.com/sensu/sensu-go/backend/store/cache   4.238s
```
=> Prevent duplicate iteration through namespace cache

backend/apid/graphql/dataloader.go, backend/apid/graphql/dataloader_test.go
Fixes potential error when using PostgreSQL store. If events were fetched in namespace with more than 1000 total events, GraphQL service might not have been able to retrieve all pages, resulting in an unexpected error.
Can cause web application to crash / return unexpected 404.
Unit & manual.
Yes.
=> Fixes potential crash when fetching events in namespace with more than 1000 events

CHANGELOG.md, backend/agentd/session.go, backend/ringv2/ringv2.go
```
commit d2bcb52d4c9fe26948194f593a0cfd8264321a4f (HEAD -> no-ring-remove-timeout, origin/no-ring-remove-timeout)
Author: Eric Chlebek <eric@sensu.io>
Date:   Tue Aug 4 09:10:12 2020 -0700
Revoke leases in ring Remove()
This commit ensures that leases are revoked on Remove() in the
ring Remove() method. This should be more performant than allowing
the lease to simply expire.
commit b00304ef4b8d7f98cd38652bf2fca872174b3393
Author: Eric Chlebek <eric@sensu.io>
Date:   Tue Aug 4 09:04:17 2020 -0700
Don't use a timeout for ring removal
This commit removes the 1s timeout from the ring Remove() method
called at agent deregistration. This should result in fewer leases
hanging around.
```
Yes
Only the …
=> Improve agent ring removal dance

CHANGELOG.md, backend/liveness/liveness.go
Leases can be obtained from the keys they were stored with. There
is no reason to explicitly store them in etcd.
This change gets us N fewer keys stored in etcd, where N is the
number of agent entities. It also lets us do puts instead of txns,
which should be a minor efficiency win.
Yes
Verification was only done in a performance testing setting. The change will need to be put through the regular QA process to be validated.
Yes
=> Don't explicitly store liveness leases

backend/messaging/wizard_bus.go, backend/messaging/wizard_bus_test.go
Use a sync.Map for the map of names to topics. This should reduce
mutex contention in WizardBus significantly.
In large installations, high mutex contention can lead to the application using more CPU than necessary.
No
Yes
=> Use a sync.Map for WizardBus

CHANGELOG.md, backend/eventd/eventd.go
Writes failed check events to the event file logger before publishing to the wizard bus. Previously, failed TTL check events would not get written to the event log file.
Closes https://github.com/sensu/sensu-enterprise-go/issues/1196
Yas.
Nah.
Nah.
We good.
E2E instructions from original issue.
Yup, targeting `release/6.0` branch.
=> Write failed check events to the event file logger

CHANGELOG.md, agent/agent.go, asset/boltdb_manager.go, asset/fetcher.go, asset/fetcher_test.go, asset/integration_test.go, asset/manager.go, backend/backend.go, cli/cmdmanager/manager.go, cli/cmdmanager/manager_test.go
Allows agent to provide configurable trusted CA for asset retrieval.
Closes https://github.com/sensu/sensu-go/issues/3948
Yas.
I'm unsure why we wouldn't want this for backend-side assets (ex. handlers, mutators) as well: https://github.com/sensu/sensu-go/issues/3948#issuecomment-675577475
Nah.
Nah.
Tested asset retrieval with and without `--trusted-ca-file` configured on the agent.
Change in functionality, I wouldn't consider this a patch, therefore targeting master.
=> Add trusted ca file for agent assets

CHANGELOG.md, agent/check_handler.go, backend/schedulerd/executor.go, util/strings/strings.go, util/strings/strings_test.go
It adds a warning log in the backend for assets that were configured as runtime_assets but do not exist. Previously, it would just silently ignore those, which would make troubleshooting really hard, since even the agent wouldn't know about any assets that were discarded.
I also adjusted a debug log in the agent depending on whether we have assets or not to install.
Help users troubleshoot issues like https://github.com/sensu/sensu-go/issues/3956.
Added
Nope
Nope
Nope
Manually verified, I don't think we need additional tests.
Nope
=> Improve UX around runtime assets

backend/api/auth.go, backend/apid/graphql/dataloader.go, backend/apid/graphql/error.go, backend/apid/graphql/fetch.go, backend/apid/middlewares/authorization_attributes.go, backend/authorization/interface.go
Handle "no claims found" error when retrieving resources within the GraphQL service. 
Fixes https://github.com/sensu/sensu-enterprise-go/issues/1224
Manual
=> [GraphQL] Handle "no claims found" error 

api/core/v2/apikey.go, api/core/v2/apikey_test.go, api/core/v2/asset.go, api/core/v2/asset_test.go, api/core/v2/check_config.go, api/core/v2/check_config_test.go, api/core/v2/entity.go, api/core/v2/entity_test.go, api/core/v2/event.go, api/core/v2/event_test.go, api/core/v2/extension.go, api/core/v2/extension_test.go, api/core/v2/filter.go, api/core/v2/filter_test.go, api/core/v2/handler.go, api/core/v2/handler_test.go, api/core/v2/hook.go, api/core/v2/hook_test.go, api/core/v2/internal/stringutil/map.go, api/core/v2/internal/stringutil/map_test.go, api/core/v2/mutator.go, api/core/v2/mutator_test.go, api/core/v2/namespace_test.go, api/core/v2/rbac.go, api/core/v2/silenced.go, api/core/v2/silenced_test.go, api/core/v2/user_test.go
Excerpt from our [Search Improvements Proposal](https://docs.google.com/document/d/1R-ofH3225OuyqjAsKE75j31UODJtMDRfd8zJE9UXh0A/edit#heading=h.el864xddxh43):
> In short I will suggest that we replace our existing search with one that is entirely built upon field selectors. By focusing on selectors we can fine tune the user experience for a single path, users no longer have to learn two different forms of searching, and our own code becomes simpler.
> 
> Of course this raises the question that if we focus on field selectors, how does one query labels? I will propose that we allow querying of labels through field selectors. Otherwise, the web interface would require a second distinct search box for labels, which I feel would be less intuitive.
Supports …
=> Export labels for use by field selectors

CHANGELOG.md, backend/eventd/eventd.go
Prepare for the 5.21.2 patch release by cherry picking https://github.com/sensu/sensu-go/commit/de7058aab1aabadec2e9367377b8b56bb8184da7 and resolving the changelog manually.
=> Prepare for the 5.21.2 patch release

cli/commands/dump/dump.go
Adds backwards compatible support for a `types` query parameter to be added to the URI to list resources.
Required by https://github.com/sensu/sensu-enterprise-go/issues/1216
No, purely internal. Changelog entry will be noted in enterprise.
Nah.
Nah.
We good.
See enterprise RP.
No, it supports a minor feature.
=> Support generic query params in sensuctl dump

api/core/v2/check.go, api/core/v2/event.go, api/core/v2/event_test.go
Add check state to event fields allowing events to be filtered by their state.
Required for sensu/sensu-enterprise-go#1083
=> Add check state to event fields

CHANGELOG.md, agent/check_handler.go
It simply ensures the stdin available to checks has the agent's entity available.
Closes https://github.com/sensu/sensu-go/issues/3827
Added
Nope
Nope
Nope
I manually created the following check:
```yaml
type: Check
metadata:
name: stdin
spec:
command: cat
interval: 5
publish: true
stdin: true
subscriptions:
- entity:gin
```
I realized that we don't have any coverage around that in our QA crucible so I'll work on that right away.
Kind of, but it was marked for the 6.1 milestone so we can just cherry-pick it in case we need that.
=> Include the agent entity in stdin for checks

CHANGELOG.md, backend/cmd/start.go
This commit causes sensu-go to exit with failure when parsing
configuration if both dashboard TLS flags are not specified.
Closes #3791 
Yes, included.
Documentation changes not required.
I started up the backend with only one dashboard TLS flag before and after the change. Before the change, the backend started up without complaint. After the change, it exited after parsing configuration, with:
```
{"component":"backend","error":"dashboard tls configuration error, both flags --dashboard-cert-file and --dashboard-key-file are required","level":"fatal","msg":"error executing sensu-backend","time":"2020-09-02T10:41:21-07:00"}
```
I'd say no; it's a different enough behaviour that even though it's a fix, I think it should be rolled out with the next minor release.
=> Don't start up with partial dashboard TLS config

CHANGELOG.md, backend/schedulerd/roundrobin_cron.go, backend/schedulerd/roundrobin_interval.go
Ensures that the interval/cron round robin schedulers do not use stale proxy entities when scheduling check requests.
Closes https://github.com/sensu/sensu-go/issues/3857
Yas.
Nah.
Originally thought https://github.com/sensu/sensu-go/pull/3999 would be a solution. Found another related bug within round-robin proxy requests using stale proxy entities and fixed both issues here instead.
We good.
```
$ sensuctl edit entity proxy
Updated /api/core/v2/namespaces/default/entities/proxy
$ sensuctl entity info proxy --format json | jq .metadata.annotations.ip_address
"127.0.0.1"
$ sensuctl event info proxy ping --format json | jq .entity.metadata.annotations.ip_address
"127.0.0.1"
$ sensuctl event info proxy ping --format json | jq .check.command
"ping …
```
=> Ensure proxy entities are not stale concurrently

asset/fetcher.go, asset/fetcher_unix.go, asset/fetcher_windows.go
Implements the workaround detailed in https://github.com/golang/go/issues/16736#issuecomment-540373689 to fix asset trusted ca file on windows agents.
Closes https://github.com/sensu/sensu-go/issues/4016
No, not a regression, fixes bug introduced in unreleased https://github.com/sensu/sensu-go/pull/3975 `The trusted CA file is now used for agent-side asset retrieval.`
Nah.
We good.
I deployed a whole windows golang env to test this 🙃 Verifying in a build with crucible now.
Yes, but targeting master for the next release.
=> Use workaround for windows x509.SystemCertPool()

CHANGELOG.md, js/js.go, js/vm_cache.go
This commit fixes a bug where the cache would behave incorrectly
if the supplied RuntimeAssets changed during the cached value's
lifetime.
Fixes #3997 
Yes
Because of the general architecture of the cache, it was very difficult to test the change for correctness. Thanks to @roganartu I was able to verify the change worked, but the test he wrote can't be added to the codebase as it depends on `time.Sleep` in library routines to work.
I used the verification test included in #3997 to make sure that the change works as expected. However, this test is not included in the PR, so technically it is unverified.
Yes
=> Fix a bug in the Javascript VM cache

CHANGELOG.md, backend/backend.go, cli/cmdmanager/manager.go
Allows backend and sensuctl to provide configurable trusted CA for asset retrieval.
I don't know if it is, asked this in https://github.com/sensu/sensu-go/issues/3948#issuecomment-675577475. @portertech @cwjohnston any thoughts on supporting this for backend and sensuctl assets as well?
Enhances https://github.com/sensu/sensu-go/pull/3975.
Yas.
Nah.
Nah.
We good.
Full QA crucible.
Nah, targeting master.
=> Add trusted ca file for backend and sensuctl assets

CHANGELOG.md, backend/store/etcd/entity_store.go, backend/store/etcd/entity_store_test.go
This commit fixes a bug in entity listing, when agent entities have
been created via the API, but not through sensu-agent.
Fixes #4010 
Included.
No.
New docs not required.
Unit testing.
Yes.
=> Fix a bug where entity list could be incorrect

cli/commands/create/create.go, cli/resource/process.go, cli/resource/process_test.go
Changes the order of operations for processing resource input. When provided multiple files, urls, or directories, all resources should be read first before the processing command (`create` or `prune`) take place.
Required by https://github.com/sensu/sensu-enterprise-go/pull/1284
Closes https://github.com/sensu/sensu-go/issues/3702
Yes, in enterprise.
Nah.
Nah.
We good.
```
$ sensuctl create -f check1.yaml -f check2.yaml -f check3.yaml 
$ sensuctl check list
Name    Command    Interval   Cron   Timeout   TTL   Subscriptions   Handlers   Assets   Hooks   Publish?   Stdin?   Metric Format   Metric Handlers  
──────── ────────── ────────── ────── ───────── ───── ─────────────── ────────── ──────── ─────── ────────── ──────── ─────────────── …
```
=> Change the OoO for processing resource input

backend/api/event.go, backend/api/event_test.go, backend/apid/graphql/dataloader.go, backend/apid/graphql/dataloader_test.go, backend/apid/graphql/entity.go, backend/apid/graphql/entity_test.go, backend/apid/graphql/interfaces.go, backend/apid/graphql/mock_test.go, backend/apid/graphql/namespace.go
Previously, determining an entity's status or fetching it's relevant events would
require retrieving all events in the entity's namespace. In cluster's with a great
many events this was lead to significantly negative performance impact.
---
=> [GraphQL] Where possible, avoid scanning all events

graphql/service.go
Expose registered middleware so that upstream implementations may invoke middleware chain. Will contribute to closing issue https://github.com/sensu/sensu-enterprise-go/issues/1294.
---
=> [GraphQL] Expose registered middleware

backend/store/v2/etcdstore/store.go
It ensures we return the patched resource in store v2, by updating the pointer underlying value. Previously we would only return the resource definition before it was patched.
Fixes a bug Hillary found while writing the docs.
Nope
Nope
Nope
Manually verified, I'll add a test case in the QA crucible.
Yep, but for 6.1.0
=> Return the patched resource in storev2.Patch

backend/api/check.go, backend/api/entity.go, backend/api/event.go, backend/api/generic.go, backend/api/meta.go, backend/api/namespace_test.go, backend/api/silenced.go
Updates the `backend/api` package so that the `ObjectMeta`'s `CreatedBy` field is filled on create & update. 
Fixes sensu/sensu-enterprise-go#1318.
---
=> [backend/api] fill created_by field

backend/apid/graphql/query.go
The suggestion service is reliant on the `backend/api` package's `GenericClient` which is no longer able to retrieve `core/v2` entities. This patch works adds a workaround to the service, allowing it to use the `EntityClient` directly.
```graphql
query MyAutoSuggestQuery {
suggest(
ref: "core/v2/entity/metadata/name"
namespace: "sensu-devel"
order: ALPHA_DESC
q: "dc01-"
) {
__typename
values
}
}
```
Fixes sensu/sensu-enterprise-go#1191
---
=> [GraphQL] Fix entity suggestions

CHANGELOG.md, agent/agent.go
This commit adds a timeout to agent termination so that graceful
shutdown can't block indefinitely. It seems there is a bug in
sensu-agent that will cause an infinite loop between the backend and
agent to occur.
This only papers over the real problem, but it will at least improve the
situation somewhat until the larger issue can be addressed.
Fixes #4036 
Included
The sensu-agent codebase has become a bit spaghettified. I couldn't easily fix the underlying issue.
To reproduce the original issue, simply start up a backend with two agents and terminate the second one. It will enter an infinite loop.
After applying the patch, the second agent will exit after 1 second, with a warning.
Yes
=> Don't wait for graceful termination on agent halt

CHANGELOG.md, backend/store/v2/etcdstore/store.go
It ensures the per-entity subscription cannot be removed when updating the subscriptions via a PATCH request.
Closes https://github.com/sensu/sensu-go/issues/4032
Added
Nope
Nope
Nope
Manually tested. I'll add a test case in our QA crucible and link it here.
Update: https://github.com/sensu/sensu-go-qa-crucible/pull/155
Yep
=> Persist the per-entity subscription in PATCH requests

cli/README.md, cli/commands/completion/bash.go, cli/commands/completion/cmd.go
This PR adds instructions to use bash-completion on Ubuntu and adds a newline at the end of the instruction.
Fixes #2478 
No, my change doesn't change the behavior of sensuctl
Yes, as described by the original issue I changed the file `cli/README.md`
To verify the newline issue, I executed `sensuctl completion -h`. To verify the lack of instruction for linux, I executed `sensuctl completion bash -h`
No
=> Add sensuctl completion instruction for Ubuntu and add new line at the end

CHANGELOG.md, js/js.go, js/vm_cache.go
Fixes #4049 
I couldn't preserve the original commit as it was based on newer code. So instead, I simply copied the JS code from 6.0, and this is the result. The 6.0 `js` package changes perserved interfaces, so things should just work.
=> Backport js vm fixes from 6.x to 5.21

CHANGELOG.md, cli/commands/dump/dump.go, cli/resource/resolve.go
It fixes a couple of bugs in `sensuctl dump`. First, it ensures API errors are properly logged. It also fix the type used for hooks so they can also be exported.
Fixes some bugs found while writing E2E tests for `sensuctl prune`.
Added
Nope
Nope
Nope
Manually verified. I'll add some coverage in the PR for our QA crucible I was working on.
Yep
=> Bugfixes for sensuctl dump

CHANGELOG.md, backend/cmd/init.go, cli/commands/user/create.go
This change added a password confirmation for sensuctl and sensu-backend when a password creation is requested in interactive mode.
This change implements the feature request #3848 
Yes
I'm not sure about the messages the commands should display, but for now i did the following:
Success cases:
```bash
./bin/sensuctl user create --interactive
? Username: ausername
? Password: ****
? Retype password: ****
? Groups:
./bin/sensu-backend init --interactive
? Cluster Admin Username: admin
? Cluster Admin Password: ********
? Retype Cluster Admin Password: ********
```
Unsuccessful cases:
```bash
./bin/sensuctl user create --interactive
? Username: ausername
? Password: *****
? Retype password: *****
? Groups: 
Error: Password confirmation doesn't match the password
./bin/sensu-backend init …
```
=> Added password confirmation for interactive commands (#3848)

CHANGELOG.md, backend/eventd/eventd.go
Ad-hoc improvement to eventd logging for store errors.
We have a customer experiencing errors from postgres, but we aren't sure which events are causing it.
Yes
I've only relied on automated tests but I'm feeling lucky!
Yep.
=> Add more logging context to eventd errors

CHANGELOG.md, backend/apid/middlewares/authorization_attributes.go, backend/apid/middlewares/authorization_test.go
:shamecube:
It fixes https://github.com/sensu/sensu-go/issues/4058
Added
Nope
Nope
Nope
Added unit test + manual e2e
Yep
=> The update verb now authorizes PATCH requests

README.md
Update the readme to explain that for users who will build from source, the web UI is separate from the backend as of 6.0 and add link to web UI-specific installation instructions.
Document separate web UI repo for OSS and point users to web UI installation instructions.
I don't think so. I think this change would have been properly entered on the changelog for 6.0 and this readme update does not need a separate entry.
No
No
This is already documented in the 6.0 release notes as a breaking change.
I confirmed w/James that we should point users to the web UI-specific instructions.
No
=> Document web UI separate from backend as of 6.0

CHANGELOG.md, backend/apid/actions/entities.go, backend/apid/actions/entities_test.go
It fixes entity creation when done via `sensuctl create`; only the entity_config key would be created, which would prevent entities from being queried.
Now we first try to create an entity when we have an agent entity, and if it already exists then we update the entity config.
Fixes https://github.com/sensu/sensu-go/issues/4062
Added
Nope
Nope
Nope, bug fix
Unit test + manual testing, also ran the QA crucible tests to make sure it didn't break anything.
Yep
=> Fix entity creation via sensuctl create

backend/apid/actions/silenced.go, backend/apid/routers/silenced.go, backend/apid/routers/silenced_test.go
This commit fixes a bug in the silenced HTTP API where expired silenced
entries can appear, even though they should not.
Fixes an issue introduced in #4034.
No, at the time of this PR the bug has not been released.
Not required.
I created a silenced entry and queried it. The regression is no longer present.
Nein
=> Fix a bug introduced by #4034

CHANGELOG.md, js/js_test.go, js/vm_cache.go
It fixes a race condition in the JS VM cache.
Fixes https://github.com/sensu/sensu-go/issues/4073
Nope
Nope
Nope
Nope
I've added the unit test before applying the patch, which created a fatal error 100% of the time.
Yep
=> Fix race condition in the JS VM cache

.circleci/config.yml
Adds authentication to Docker Hub for image pulls in CircleCI.
Docker image pulls will be limited for unauthenticated users starting next Monday.
Fixes https://github.com/sensu/sensu-enterprise-go/issues/1319.
No.
Nope!
Nope!
As per CircleCI's guide, if the tests pass, after adding the auth key, it's working.
No but I will cherry-pick / make the appropriate changes to the other release branches afterwards.
=> Use auth for pulling all docker images in CI

CHANGELOG.md, backend/agentd/agentd.go, backend/agentd/agentd_test.go, backend/backend.go
Adds an unauthenticated `/health` endpoint to the backend websocket API.
See #2773 
Yes.
No.
I initially misunderstood how the actions controller for health worked.
Yes, new documentation is required.
I wrote a test to ensure that the `/health` endpoint on the agentd websocket port returns a 200 status.
No.
=> Add health endpoint to backend websocket API

CHANGELOG.md, agent/cmd/start.go, backend/cmd/start.go
It adds support for the `SENSU_BACKEND_CONFIG_FILE` & `SENSU_CONFIG_FILE` environment variables to define the config file path for sensu-backend & sensu-agent respectively. 
Closes https://github.com/sensu/sensu-go/issues/4069
Added
Nope
Nope
Nope
Manually verified; due to the nature of viper, it's impossible to inspect which configuration file was loaded, because it does not get exported by the package.
Nope
=> Support env vars for config file of agent & backend

api/core/v2/event.go, api/core/v2/event_test.go
When sorting events by the value of their `last ok` property, use the event's state instead of status. In this way events that are in the flapping state but currently have a status of zero are not "shifting" between the top and bottom of the list.
Closes https://github.com/sensu/sensu-enterprise-go/issues/1218
---
=> [GraphQL] Sort using check state, instead of status

CHANGELOG.md, cli/commands/create/create.go, cli/resource/parse.go, cli/resource/parse_test.go, cli/resource/process.go, cli/resource/process_test.go
During a previous refactor, parts of the logic for the create, edit and
delete sub-commands were merged together. This resulted in the side
effect of having the edit and delete sub-commands automatically add a
"managed_by" label with a "sensuctl" value to resources they touched.
This is not what we want; only sensuctl create should be automatically
adding this label.
This commit removes the label creation from the code shared by the 3
sub-commands, creates a new Processor that labels resources before
submitting them to the API and uses it as part of the definition of the
create sub-command only.
Closes #4087.
Yes, added.
No.
No.
Unit tests for the new labeling Processor and manual testing showing that:
- `edit` doesn't add the label to existing resources …
=> Remove managed_by label creation with edit command

CHANGELOG.md, agent/cmd/start.go, backend/cmd/start.go
It fixes the config-file flag so we only return an error if a file was explicitly defined and it does not exist; otherwise if the default value was used as a fallback and the file does not exist, we do not return an error, so the flag is not required.
Also, it fixes a bug where the config-file flag would need to defined first in order to be taken into account (see https://github.com/sensu/sensu-go/issues/3714).
Fixes a bug introduced in https://github.com/sensu/sensu-go/commit/b092a579a36de2bf101bcbe83841da89429f4c02, which would require users to explicitly define a config-file for sensu-backend & sensu-agent.
Fixes https://github.com/sensu/sensu-go/issues/3714
Added
Nope
Nope
Nope
Manually verified; I'll also run this patch on staging.
Yes, but for an unreleased feature.
=> Fix the config-file flags

agent/transformers/prometheus.go, agent/transformers/prometheus_test.go, agent/transformers/timeproxy_test.go
This commit mocks out the time package in the prometheus transformer in
order to avoid a flaky test failure.
The test failed in CI with no provocation.
No, this is not a user-facing change.
We've used timeproxy successfully in several areas of the codebase, so I'm confident this won't cause any issues.
Yes, but it only affects developers so I've targeted main.
=> Mock out time with timeproxy to fix flaky test

CHANGELOG.md, asset/fetcher.go
It ensures the HTTP client for assets retrieval follows the `HTTP_PROXY` and other similar environment variables.
Following https://github.com/sensu/sensu-go/pull/3975, we started building an HTTP client with a custom transport for agents that had a `trustedCAFile` specified, which typically happens with mTLS. However, by doing so, we no longer used `DefaultTransport` which automatically includes `ProxyFromEnvironment`. 
Closes https://github.com/sensu/sensu-go/issues/4101
Added
Nope
Hard to test!
Nope
I had to manually test it. Unfortunately I don't see how we could easily test that, because of the following bit from the `ProxyFromEnvironment` docs:
> As a special case, if req.URL.Host is “localhost” (with or without a port number), then a …
=> Always use http.ProxyFromEnvironment with assets HTTP client

CHANGELOG.md, backend/eventd/eventd.go, backend/pipeline/handler.go, util/logging/logging.go
Replaces all instances where `event_uuid` was logged with `event_id`.
Closes #4093.
Yes.
Nope!
Nope!
Just unit/integration tests.
No.
=> Replace uuid with event id in logging

agent/cmd/start.go, agent/cmd/start_test.go, agent/cmd/windows.go, backend/cmd/init.go, backend/cmd/start.go, backend/cmd/start_test.go, backend/cmd/upgrade.go
It fixes a bug where configuration values for both sensu-agent & sensu-backend would be duplicated when using slices.
All flags need to be present when we first try to parse the config file attribute, otherwise it will silently fail because undefined flags were defined. However, we should use a different set of flags for the "main" command otherwise they will be parsed twice, which ends up duplicating values in configuration attributes holding a slice.
Fixes https://github.com/sensu/sensu-go/issues/4114
Nope, unreleased bug introduced via https://github.com/sensu/sensu-go/pull/4105
Nope
Nope
Nope
Manually verified. This is not something that's easy to test automatically.
Nope; it just needs to be included with the PR above.
=> Do not parse the same flag set twice

backend/api/generic.go, backend/api/generic_test.go, backend/store/v2/wrap/wrapper.go
This commit adds support for core/v3.Resource types in the backend API
GenericClient. The support is shimmed through the
core/v3.V2ResourceProxy type.
Users are expected to set up the GenericClient with a store/v2.Interface
and a Kind that is a V2ResourceProxy, if they want to work with core/v3
resources.
Supporting work for sensu-enterprise-go.
No, not a user facing change.
=> Add support for core/v3.Resource to backend/api

graphql/service.go
Correctly merge interfaces when applying type extension.
---
=> [GraphQL] Correctly merge interfaces when applying extension

backend/apid/graphql/globalid/encoder.go, backend/apid/graphql/globalid/encoder_test.go
Allows globalid encoder to encode resources without embedded metadata. (Such as v3 resources.)
---
=> [GraphQL] Account for resources without embedded metadata

agent/cmd/start.go, backend/cmd/start.go
It reverts a previous change that would handle errors while parsing flags in the `handleConfig` function. Unfortunately, as we recently discovered, this is problematic because it gets called by almost all subcommands, but not all flags are usually defined.
Fixes a bug found on `main`
Nope
Viper & Cobra are hard!
Nope
Nope
=> Continue to ignore flags parsing errors for now

backend/apid/graphql/entity.go, backend/apid/graphql/entity_test.go, backend/apid/graphql/meta.go, backend/apid/graphql/meta_test.go
`ObjectMeta` type previous expected that argument was a value and not a pointer.
Regression introduced in #4128.
---
=> [GraphQL] Fixes crash when selecting entity metadata

CHANGELOG.md, agent/agent.go, agent/cmd/start.go, agent/config.go, agent/entity_config_handler.go, backend/agentd/session.go, backend/agentd/watcher.go, backend/apid/actions/entities.go, backend/apid/routers/entities.go, backend/keepalived/keepalived.go, backend/keepalived/keepalived_test.go, cli/resource/parse.go, cli/resource/process.go, cli/resource/process_test.go
It introduces support for entities that are actively managed by agents; this re-introduces the behaviour we previously had with pre-6.0 agents.
sensu-agent now has a new `agent-managed-entity` configuration flag. When used, the entity managed by this agent will use the `sensu.io/managed_by` label to indicate that sensu-agent is now the source of truth for this entity.
keepalived (via its `handleEntityRegistration` method) is now responsible for updating the entity config on startup for entities managed by their agents, by using the new `sequence` field in events and the label mentioned above. In case the agent is restarted and no longer has the `agent-managed-entity` config attribute, we will then update the stored entity config to reflect that (by removing the `sensu.io/managed_by` …
=> Add support for entities managed by agents

CHANGELOG.md, api/core/v3/entity.go, api/core/v3/entity_test.go
With this change, when converting a (v3.EntityConfig, v3.EntityState) into a
v2.Entity, we carry over the CreatedBy metadata from the config, just like we do
for labels and annotations.
Addresses a bug that @palourde came across while working on something else.
Yes, added.
No.
After careful consideration, a test that asserts that, after a v3 to v2
conversion, the state's metadata ought to be the same as the resulting v2
entity's has been removed because it is not correct: metadata information is
copied from the config part. This change exposed this issue.
No change in documentation is required.
Unit tests only.
No?
=> Fix CreatedBy not being carried over when converting v3 to v2 entities

backend/agentd/agentd.go, backend/agentd/middlewares.go
Do less work in the hard agent limiter, by invoking less middleware.
=> Limit agent transport upgrades before hitting etcd

CHANGELOG.md, backend/keepalived/keepalived.go
This commit fixes a bug in keepalived, where entities are attempted to
be removed from rings that don't exist. Specifically, the entity
subscription.
On etcd this generates extra traffic, although no additional keys are
created. On postgres, this can result in many rows being inserted
needlessly.
Yes
Currently verifying on sensu-perf.
Yes
=> Don't remove entities from nonexistent rings

CHANGELOG.md, backend/apid/routers/silenced.go, backend/store/etcd/silenced_store.go, backend/store/etcd/silenced_store_test.go, cli/commands/silenced/info.go, cli/commands/silenced/info_test.go, cli/commands/silenced/list.go, cli/commands/silenced/list_test.go
It fixes a breaking change introduced in 6.2.0, which would set the remaining duration of a silenced entry (its TTL) rather than the configured duration.
Instead, we now make sure to calculate the ExpireAt field value, and use that for display purpose in sensuctl.
Fixes https://github.com/sensu/sensu-go/issues/4143
Added
Nope
Nope
Nope
Manually tested & adjusted the unit tests.
Yep
=> Do not override the expire attribute of silenced entries

backend/agentd/session.go
This commit finishes the other bugfix to do with rings.
See https://github.com/sensu/sensu-go/pull/4140
This PR is necessary, as the other one did not catch all instances of `ringPool.Get`.
=> Reduce extra ring work further

CHANGELOG.md, backend/store/etcd/event_store.go, backend/store/etcd/event_store_integration_test.go, backend/store/etcd/event_store_test.go
Adds the first event received to its own history before persisting it to the store & sending it through the pipeline.
Fixes #4145.
I realized when looking into the issue that the first event received is never stored in the check's history (even when a second event has been received). This PR fixes both issues.
Yes.
No.
No documentation updates are required.
I added some new tests, existing tests pass, and I tested locally by ensuring check history exists when a new event is first received.
Yes.
=> Store new events in their own history

backend/store/v2/etcdstore/store.go, backend/store/v2/etcdstore/store_test.go, backend/store/v2/resource.go
Adds option to list request, allowing results to be sorted by key in an ascending or,
descending order. While this has some obvious limitations, (case-insensitivity for one,)
it is much more efficient that pulling the entire list and sorting in memory.
Required to properly implement https://github.com/sensu/sensu-enterprise-go/pull/1418
---
=> [Store] Add option to sort list results

CHANGELOG.md, api/core/v2/event.go, api/core/v2/event_test.go
This commit fixes a bug where events from all namespaces are dumped when
sensuctl dump is invoked, even if a specific namespace is requested. The
bug was presentational in nature and does not represent a security
issue.
Fixes #4166 
Yes
I used the issue reproduction steps to verify the change and also included a unit test.
Yes
=> Fix sensuctl dump event output

CHANGELOG.md, agent/cmd/start.go, agent/cmd/start_test.go
It fixes a bug found during 6.2.2 QA, when the `agent-managed-entity` config attribute is used with sensu-agent and no labels are defined.
Added
Nope
Nope
Nope
Manually verified + added a unit test. Our QA crucible was also able to catch this bug.
Yep
=> Fix the agent-managed-entity config attribute

CHANGELOG.md, backend/cmd/init.go
Adds a new `wait` flag to the `sensu-backend init` command to allow users to wait indefinitely for etcd to become available instead of requiring a timeout.
This will allow us to remove a the retry logic from the Docker entrypoint.sh file which will resolve some of the issues we've seen.
Partially fixes https://github.com/sensu/sensu-go/issues/4147.
Yes.
No.
No.
New documentation will be required. See https://github.com/sensu/sensu-docs/issues/2942.
1. Stop sensu-backend.
2. Run `sensu-backend init --wait`.
3. Watch it continuously attempt connecting to the etcd servers defined.
4. Start sensu-backend.
5. The init command executes.
No.
=> Add wait flag to sensu-backend init

agent/cmd/start.go, agent/cmd/start_test.go
This fixes an issue where the `managed_by` label wasn't persisted to the agent's config.
=> Add managed_by label to cfg.Label

CHANGELOG.md
Moves "...events from namespaces other than the one requested could appear in sensuctl dump output..." item from 6.2.2 release to 6.2.3
This change actually happened in 6.2.3 rather than 6.2.2
Yes :)
No
No
https://github.com/sensu/sensu-docs/pull/2946
Confirmed w/ @portertech 
No
=> Move sensuctl dump for all namespaces to 6.2.3

CHANGELOG.md, backend/cmd/init.go
This reverts commit b3336a534c806a680e714e3b851ef2a22ad95857.
There are race conditions with this implementation and we discovered that there are issues with locking in etcd preventing a proper solution to this at the moment.
=> Revert init wait flag

CHANGELOG.md, api/core/v3/entity.go, api/core/v3/entity_test.go, api/core/v3/validation.go, backend/store/v2/wrap/wrapper.go
Validates V2 & V3 resources before they are wrapped in the storev2 wrap package.
Validation is not happening on any resources in storev2.
Yes.
I don't believe labels or annotations are mandatory so I modified the ObjectMeta Validate method to initialize as an empty map when the values are nil. I'm not sure if this is the best or correct approach; please let me know.
I ensured that the new BSM resources get validated with this change in place.
No.
=> Validate resources in storev2

CHANGELOG.md, go.mod, types/go.mod, types/go.sum, types/wrapper.go, types/wrapper_test.go
Initializes the Labels & Annotations metadata fields in core/v3-compatible resources when the fields are nil when unmarshaling a wrapped resource.
V3 resources will not validate when the labels & annotations fields aren't set within the metadata of a wrapped resource.
Yes.
No.
No new documentation required.
I created a new test case with @echlebek as well as testing that the BSM Rule Template resource can be created without specifying labels or annotations.
No.
=> Initialize Labels & Annotations for v3 resources when fields are nil

CHANGELOG.md, api/core/v3/go.sum, api/core/v3/resource_generated.go, api/core/v3/resource_generated_test.go, api/core/v3/resource_template.go, api/core/v3/resource_template_test.go, api/core/v3/typemap.go, api/core/v3/typemap_test.go, backend/cmd/upgrade.go, backend/seeds/seeds.go, backend/store/etcd/migrations.go, backend/store/etcd/migrations_test.go, backend/store/etcd/version.go, types/wrapper.go
This change adds ResourceTemplate, a basic facility for populating newly created namespaces with pre-fabbed data structures.
We'll be using this to populate namespaces with resources from the enterprise product. The facility might be of further use in OSS Sensu as well.
Closes #4202.
Yes
No
=> Add ResourceTemplate, and enterprise migration system

backend/apid/graphql/check.go, backend/apid/graphql/check_test.go, backend/apid/graphql/schema/check.gql.go, backend/apid/graphql/schema/check.graphql
Allows client to request a check's output be truncated, reducing the size of the response payload.
---
=> [GraphQL] Add argument to request truncated check output

CHANGELOG.md, backend/schedulerd/roundrobin_cron.go, backend/schedulerd/roundrobin_interval.go
This commit fixes a potential crash in the scheduler when using round
robin checks. The crash only occurs when using postgres with the
"enable_round_robin: true" configuration option.
It fixes a latent bug exposed by the enterprise product. OSS users are unaffected.
Yes
Manually. To trigger the bug, I created a round robin interval check using proxy_requests and splay.
Yes.
=> Fixed a potential crash in the scheduler

backend/apid/graphql/node.go, backend/apid/graphql/node_test.go, backend/apid/graphql/query.go, backend/apid/graphql/relay/node.go, backend/apid/graphql/relay/resolver.go, backend/apid/graphql/relay/resolver_test.go, backend/apid/graphql/service.go
Export `NodeResolver` for use by downstream products.
* moves to `relay` package
* expands test coverage
---
=> [GraphQL] Export NodeResolver

CHANGELOG.md, api/core/v2/entity.go
-------
Add a constant in the `corev2` package representing an entity that is a BSM
service.
The constant has been defined for BSM related work in the enterprise repository,
but it really belongs here with the other constants representing entity types.
Sure, I added one...
Documentation about what a "service" entity class is is covered by the BSM
documentation.
I didn't, because it's just a new constant definition.
No.
=> Add EntityServiceClass

CHANGELOG.md, backend/store/etcd/watchers.go, backend/store/store.go
-------
This adds `GetResourceV3Watcher()` to the `store/etcd` package. Similarly to the
other `GetXWatcher()` functions, it returns a channel with events related to the
given key, representing a store path to any type of `corev3.Resource`.
This function and the associated `WatchEventResourceV3` type were written for
more specific work in the enterprise code, but they are useful in general and
should be moved here.
Yes, added.
Used in enterprise feature. Unit tests for the various `GetXWatcher()` functions
would be nice, although a bit of refactoring might be necessary.
No.
=> Add ResourceV3 watcher

.github/workflows/semgrep.yml, .semgrep.yml, backend/apid/graphql/asset_test.go, backend/apid/graphql/check_test.go, backend/apid/graphql/entity_test.go, backend/apid/graphql/event_filter_test.go, backend/apid/graphql/event_test.go, backend/apid/graphql/handler_test.go, backend/apid/graphql/health_test.go, backend/apid/graphql/hook_test.go, backend/apid/graphql/metric_test.go, backend/apid/graphql/mutations_test.go, backend/apid/graphql/mutator_test.go, backend/apid/graphql/namespace_test.go, backend/apid/graphql/query_test.go, backend/apid/graphql/silenced_test.go, backend/apid/graphql/version_test.go
Adds semgrep github action. There are two separate semgrep runs performed. One that uses the `dgryski/semgrep-go` repo, and one that relies on sensu-go's `.semgrep.yml`.
=> Add semgrep github action

CHANGELOG.md, backend/api/namespace.go, backend/api/namespace_test.go, backend/apid/apid.go, backend/apid/routers/namespaces.go, backend/apid/routers/namespaces_test.go, backend/backend.go
This commit causes sensu-go to implicitly create resources in newly
created namespaces when they are defined. So far, there are no
ResourceTemplates defined, so no new resources will be created for OSS.
This is supported work for the BSM enterprise feature. We may leverage it in the future and expose it to users, but for now it is internal only.
Yes.
Unit tests only.
No.
=> Instantiate ResourceTemplates on namespace create

CHANGELOG.md, backend/backend.go
This commit removes the functionality that causes sensu-go's internal
daemons to restart on SIGHUP. Instead, SIGHUP is now a no-op.
In the enterprise product, SIGHUP is used to rotate the special event
log file, so the restarting behaviour was undesirable.
We don't anticipate anyone should ever want to force an internal daemon
restart, users should instead restart the whole sensu-backend process if
that's what they want to do. So, support for doing this is now removed.
Fixes #4217 
Yes
I ran sensu-backend and sent SIGHUP to it manually several times. It had no effect, as expected.
No.
=> Make SIGHUP a no-op

CHANGELOG.md, backend/pipeline/filter.go
The following information has been added to the log messages:
- check name and namespace
- entity name and namespace
- event id
- filter name
Makes it easier to correlate the error with a specific filter, or event.
The change includes one:
- Added more context when logging JavaScript filter evaluation errors.
No.
No.
I don't believe this require a documentation change.
Install the sensu-email-handler asset:
```
sensuctl asset add sensu/sensu-email-handler
```
Create an event filter with a syntax error in the expression:
```
cat << EOF | sensuctl update
---
type: EventFilter
metadata:
annotations: null
labels: null
name: state_change_only
spec:
action: allow
expressions:
- event.occ == 1
runtime_assets: []
EOF
```
Create the email handler:
```
cat << …
```
=> Added more context when logging JavaScript filter evaluation errors

cli/resource/parse.go, cli/resource/parse_test.go
Fixes parsing of yaml resources with an initial `---` prefix.
It fixes a regression that I noticed when attempting to spin up a staging stack.
No as it fixes a regression that has not yet been released.
I created test cases that reproduced the error and then re-ran them after fixing the bug.
No.
=> Fix parsing of yaml resources with --- prefix

CHANGELOG.md, cli/commands/commands.go
Suggestions provided by shell auto-completion included extraneous flags and arguments (e.g. -f, FILE). This fix removes them.
To only show the available auto-completion arguments.
Yes, added.
No.
No.
No new documentation required.
- Setup bash and zsh auto-completion following the instructions here.
- Rebuild sensuctl
- Restart your shell to make sure the latest auto-completion logic is loaded
- Type `sensuctl <tab><tab>`
- Observe the suggested options and make sure there only valid commands and nothing like `-f`, `[blahblah]`
No.
=> sensuctl: fix shell auto-completion

backend/api/namespace.go, backend/api/namespace_test.go, backend/apid/routers/namespaces.go
This commit changes the namespace CRUD API to implement the same side
effects for create-or-update as currently exist for create. The
namespace POST API has also been updated to make use of the
functionality.
It fixes an unreleased defect that largely applies to an upcoming enterprise feature.
No.
The change is covered by unit tests and also by automated QA.
No.
=> Enable namespace creation side effects for updates

backend/agentd/session.go, backend/agentd/session_test.go
On a couple of occasions the `agentd/TestSession_Start` unit test timed out when executed in the build pipeline on CircleCI. 
The test goroutine is trying to stop the Session and is blocked on the `stopWG` workgroup before it can complete.
```
goroutine 241 [semacquire]:
sync.runtime_Semacquire(0xc0005a5d90)	                                     /usr/local/go/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc0005a5d88)	                                     /usr/local/go/src/sync/waitgroup.go:130 +0xb1
github.com/sensu/sensu-go/backend/agentd.(*Session).Stop(0xc0005a5c80)	     /home/circleci/project/backend/agentd/session.go:528 +0x95
github.com/sensu/sensu-go/backend/agentd.TestSession_Start.func7(0xc0002c6800) …
```
=> Prevent agentd unit test from timing out

api/core/v3/validation.go, backend/apid/handlers/patch.go, backend/apid/handlers/patch_integration_test.go, backend/apid/handlers/patch_test.go, backend/store/v2/wrap/wrapper.go
Removes the validation that was happening for V3 resources in the PATCH API.
The initial validation of V3 resources in the PATCH API would always fail as it was trying to validate incomplete resources.
Closes #4241.
No as this is fixing a regression for code that has not yet been released.
Attempting to patch a resource using a non-existent field will succeed & the non-existent field will be ignored.  I'm not sure if there's some way we can validate that the fields are correct. Errors are still returned if the data type of a field does not match the resource field's data type.
I added specs to reproduce the issue and then implemented a fix.
No.
=> Remove validation for partial V3 resources in PATCH API

CHANGELOG.md, backend/tessend/tessend.go
This change adds a length check on the `ringv2.Event.Value` before accessing it
since it is possible, though unlikely, that it has a zero length, leading to a
bad memory access and a crash.
Prevent potential but rare crash of `tessend`.
Yes, added.
I'm still a bit unclear about how the ring is even able to emit such
`ringv2.EventTrigger` events with a zero-length `Value`.
The length check is warranted in `tessend` in any case.
I believe that the conditions under which this crash can happen are so rare that
it doesn't warrant making this change a patch and that it's OK to just include
it in our next minor release.
=> Fix potential crash in tessend

CHANGELOG.md, backend/agentd/agentd.go, backend/schedulerd/check_watcher.go, backend/tessend/tessend.go
=> Nil check pointer fields in some watchers before using them

backend/agentd/agentd.go, backend/agentd/agentd_test.go, backend/agentd/routers.go
Add a function to replace the agentd's health controller to be used by sensu-enterprise-go to include Postgres health information.
We need to include the Postgres health information from the agentd health endpoint accessible at http://[host]:8081. For this the default health controller needs to be replaced with an extended one that includes the Postgres health.
Fixes #4182 
Closes #4182 
The releated sensu-enterprise-go change will require one but it is a transparent change in this project.
agentd's HealthRouter needs to be accessible from sensu-enterprise-go to be able to swap the HealthControler. I'm not sure if it is the best way to make the HealthRouter accessible however it seems a similar approach was implemented for agentd's …
=> Make the agentd health router public so it can be extended.

CHANGELOG.md
The CHANGELOG was clobbered when merging the `release/6.2` branch back to main.
=> Fix CHANGELOG clobbering

.circleci/config.yml, .github/workflows/golangci-lint.yml
Bumps Go from 1.16 to 1.16.3 which includes:
* security fixes to the archive/zip and encoding/xml packages
* fixes to cgo, the compiler, linker, the go command, and the syscall and time packages
* fixes to the compiler, linker, runtime, the go command, and the testing and time packages
=> Bump Go to 1.16.3

.appveyor.yml, CHANGELOG.md, cli/client/authentication_test.go, cli/client/client.go, cli/client/config/basic/basic.go, cli/client/config/basic/reader.go, cli/client/config/basic/reader_test.go, cli/client/config/config.go, cli/client/config/mock.go, cli/client/testing/mock_config.go, cli/commands/env/env_test.go, cli/commands/hooks/ensure_configured.go, cli/commands/hooks/ensure_configured_test.go, cli/commands/root/root.go, go.mod
- Add the --api-key command-line parameter to sensuctl
- If `sensuctl config` has not been run the --api-url argument is also required
- If `sensuctl config` has been run the --api-key argument will have precedence over the access/refresh tokens
Add the `--api-key` command line parameter to sensuctl to bypass username/password authentication.
Prevents having to run `sensuctl configure` beforehand which is useful for automated tasks or CI/CD pipeline integrations.
Added the following:
- Added API key authentication support to sensuctl
No
No
New documentation is necessary to document the new --api-key option for sensuctl. Will link to this PR once updated.
- Generate an API key using `sensuctl api-key grant`
- Write down the API key
There …
=> Add API key authentication support to sensuctl

CHANGELOG.md, agent/cmd/start.go, cmd/sensu-agent/main.go, cmd/sensu-agent/main_windows.go
Moves the Viper aliases to their own function which is called after all Cobra commands have been added.
Fixes deprecation warnings from showing when the deprecated configuration options aren't being set. On Windows the `handleConfig` function is called multiple times as its used within the start & service commands.
Yes.
No
No.
I reproduced the deprecation warnings on Windows and then ensured they no longer showed after making this change, with and without using a config.
No.
=> Register Viper aliases after Cobra commands are added

.github/workflows/golangci-lint.yml, go.sum
Just fixes a small syntax error in the golangci-lint GitHub workflow.
=> Syntax error in GitHub workflow

cmd/loadit/main.go
Added a `--namespace` flag to the `loadit` tool, set the namespace for the agent sessions.
Load test with multiple namespaces.
No.
No.
No.
Ran on my local machine.
=> loadit namespace support

command/proc_unix.go
Sets Pdeathsig to subprocesses to be sure of their termination on agent restart.
Usually that isn't something required, but you'll be more sure that nothing left from previous execution.
Possibly no. It's likely that user won't ever notice that.
No.
No.
No doc changes required.
Runs on our systems.
That change may be backported, but probably not required.
=> command: set Pdeathsig

CHANGELOG.md, backend/apid/middlewares/authorization.go, backend/apid/middlewares/authorization_test.go, backend/authorization/rbac/rbac.go, backend/authorization/rbac/rbac_test.go
This CL fixes a bug where the HTTP API returns a 500 status instead of 403 when an RBAC role specified in a RoleBinding RoleRef is missing. The API now returns status 403 and also explains that the referred role is missing.
Fixes #4268
Yes
It's unclear if anything needs to be done in `backend/api` or in the `graphql` layer.
I created tests that fail without the added changes. I also manually tested that a user bound to a nonexistent role would be given a better error message when using sensuctl.
Yes, but is not targeted for the current release branch.
=> Fix an RBAC bug where missing roles are fatal

command/proc_group_linux.go, command/proc_group_unix.go, command/proc_group_windows.go, command/proc_unix.go, command/proc_windows.go
Addresses https://github.com/sensu/sensu-go/pull/4281#issuecomment-839367779
> Unfortunately this PR is breaking the build for every platform except Windows and Linux because [that `.Pdeathsig` field is available on Linux only](https://golang.org/src/syscall/exec_linux.go) but it has been added in a file that's used for all Unices!
> 
> The CI for sensu-go didn't catch that because it only runs in a Linux environment.
> 
> I think a quick fix to be able to include this work would be to create a new file, proc_linux.go, that's specific to Linux and change the build tags so that proc_unix.go is not used for Linux.
---
=> Only reference deathsig on linux platform

CHANGELOG.md, cmd/loadit/main.go, testing/testutil/util.go
Adds a new test helper to generate random V4 UUIDs. Updates loadit to use V4 UUIDs for agent names.
From https://www.sohamkamani.com/uuid-versions-explained/#v1--uniqueness:
```
UUID v1 is generated by using a combination the host computers MAC address and the current date and time. In addition to this, it also introduces another random component just to be sure of its uniqueness.
```
As loadit is generating tens of thousands of UUIDs in a short amount of time there is a higher chance of collision. I believe we've seen these collisions in our PostgreSQL tests on our commercial repository. By moving to V4 we will significantly reducing the chance of any collisions.
Yes.
=> Add RandomUUIDV4 test helper, use UUIDv4 for loadit

cli/commands/configure/configure.go
We refer to the WebSocket URL as "backend URL", leading users to incorrectly think the API here is the websocket port. Calling  it "Backend API URL" might help disambiguate it
Unsure, seems too small :sweat_smile: 
There may be a more specific term, like "Backend HTTP API URL" but that might confuse things more.
=> disambiguate API URL from WebSocket URL

api/core/v2/entity.go, api/core/v2/event.go
Instead of using the default library use the json-tier library to encode events to JSON. This increase performance by about 75%. This is part of https://app.zenhub.com/workspaces/sensu-go-5ca3b7d249384649e4b7964e/issues/sensu/sensu-enterprise-go/1620. This change will be included in sensu-enterprise-go.
Slow performance was observed when encoding events.
No there will be one in the sensu-enterprise-go change.
No
No
n/a
Local encoding performance test.
No
=> Use jsoniter instead of encoding/json for json encoding

backend/cmd/start.go
If `EtcdLogLevel` is not specified, it will use the value of `LogLevel`, or use `debug` if `LogLevel` is set to `trace` as `trace` is not compatible with the etcd logger.
Having to configure log levels with two separate flags is an inconvenience. This change still allows each log level to be configured independently if so desired.
No, this is a change to unreleased code & there's already a changelog for the addition of `EtcdLogLevel`.
https://github.com/sensu/sensu-docs/issues/3066
No.
=> Use LogLevel as default EtcdLogLevel

backend/cmd/start.go
`cfg.LogLevel` is not set; compare against `level` variable. Use `logrus.Level` types for comparisons. Logrus also outputs its `warn` level as `warning`; use `warn` in that case.
The `main` branch will fail without this change unless `--etcd-log-level` is explicitly set.
=> Use level instead of cfg.LogLevel, use proper types

backend/backend.go, backend/store/proxy.go, backend/store/proxy_test.go
This commit removes EventStoreProxy and replaces it with StoreProxy.
StoreProxy is like EventStoreProxy, but allows replacement of the entire
Store.
Unlike EventStoreProxy, StoreProxy uses a sync.RWMutex for
synchronization, instead of a pointer swap. This should be fast enough
for the store, while removing the use of package unsafe.
Projects that relied on EventStoreProxy should adapt their usage of it
to StoreProxy, which can be done relatively easily.
Closes #4288
No, this is not a user-facing change.
No.
=> Remove EventStoreProxy, add StoreProxy

js/js.go, js/js_test.go
Adding additional time helper functions for filter expressions.
- add minute() function output int 0-59 
- add second() function output int 0-59
- add seconds_since() function outputs float64, useful when needing to look at age of timestamp relative to current time. 
- added test for each function.
we only expose hour() and weekday() right now, customer interested in minute() granularity.
Yes and a docs PR as well once this is merged.
nope
New documentation is required, but impact is limited just need to provide example filter examples for the additional functions.
wrote some additional golang tests that call the new functions inside an Otto vm with a fixture event with specified timestamp.
I think is qualifies as a new feature so, not a patch.
=> extend time helper functions for filters

CHANGELOG.md, backend/keepalived/deregisterer.go, backend/keepalived/deregisterer_test.go
Removes the empty subscription from the deregistration handler's event check.
Fixes #4307  
Breaks the handler's event validation.
Yes, added one.
No.
No.
No docs required.
Validated the email deregistration handler doesn't fail on event validation anymore.
No.
=> Internally generated deregistration events are invalid 

CHANGELOG.md, command/command.go, command/command_windows_test.go, command/proc_windows.go, util/bytes/buffer.go
Windows child processes were not getting killed correctly when processing the command timeout.
Closes #3979 
To prevent having stale processes on the host.
Added the following:
- Fixed issue with Windows agent not handling command timeouts properly
No
No
Create a check running on a Windows agent with the following command:
`PowerShell.exe Write-Host "start sleep"; Start-Sleep -s 20 ; Write-Host "sleep done"`
and a timeout of 2 seconds. When executing the check result should show the execution time to be close to 2 seconds. Also by looking at the Windows task manager make sure the `powershell.exe` process is terminated properly after 2 seconds.
No
=> Windows process timeouts

CHANGELOG.md, backend/cmd/init.go
Treats the `--timeout` flag for `sensu-backend init` as a duration instead of converting it to seconds. If the timeout is less than 1 second, the value is converted to seconds. (e.g. a value of `5` is read as `5ns` which is less than 1 second, it will be converted to `5s`.
The `--timeout` flag has always had a type of duration but we've mistakingly been converting it to seconds. This can cause confusion and and different behaviours when the value is set to `1` vs `1s`.
Yes.
Documentation will likely need to be updated. cc @hillaryfraley 
I tested various inputs to the timeout flag:
* `1` becomes `1s`
* `5` becomes `5s`
* `1s` does not change
No.
=> Treat the timeout flag for sensu-backend init as a duration

README.md
The link to the install Sensu page in the docs is incorrect (although it does redirect to the correct page). I replaced this redirected link with a direct link to the correct page.
Just eliminating a redirected incoming link.
No
No
No
None needed
Correct link is https://docs.sensu.io/sensu-go/latest/operations/deploy-sensu/install-sensu/
No
=> Update Install Sensu link in README

CHANGELOG.md, backend/keepalived/keepalived.go
Adds a prometheus metric for counting keepalive statuses over time.
This will help identify instability due to keepalive failure storms.
Included.
=> Add sensu_go_keepalives prometheus counter metric

CHANGELOG.md, backend/keepalived/keepalived.go
This commit changes the behaviour of keepalived such that roundrobin
ring errors are now logged but don't result in an internal restart being
triggered.
Under extreme load, etcd rings can be highly unstable, but it's usually
preferable to continue on when there are lease faults but K/V operations
are still generally working.
The etcd ring facility can emit errors under extreme load, when the lease that the ring is using expires before a key can be written using it. This circumstance has never been observed under regular operation, and is an attempt to bring greater stability to sensu-go when it is under load.
Yes, included.
=> Don't emit fatal ring errors from keepalived

backend/seeds/seeds.go
The RuleTemplates were not automatically created alongside the Namespace.
Yes this broke all the BSM tests.
No, the regression was never shipped.
no
no 
no
Using **sensu-enterprise-go**:
* Fresh install/etcd db
* sensu-backend init
* sensuctl create namespace francis
* sensuctl dump bsm/v1.RuleTemplate --format yaml --namespace francis
The RuleTemplate should be displayed
No
=> Regression: RuleTemplate not automatically created with Namespace

CHANGELOG.md, go.mod, go.sum
Bumps gopsutil to the version we use in our internal repository.
Sense Go won't compile on `darwin/arm64` with the current version of gopsutil that this repository is using.
Yes.
The Sensu Go agent, backend and sensuctl all build successfully with `GOOS=darwin GOARCH=arm64`.
Yes.
=> Bump gopsutil for darwin/arm64 support

cli/commands/cluster/health.go
Signed-off-by: Francis Guimond <francis@sensu.io>## What is this change?
Prevents `sensuctl cluster health` from panic when running against a etcd cluster that has lost quorum.
No. It's a fix for unreleased code.
No new documentation required.
Copied the new sensuctl to our QA stack and ran against etcd without quorum.
Yes.
=> Guard against nil etcd response header

CHANGELOG.md, backend/cmd/init.go
Fixes a regression that shipped with 6.4.0 where `sensu-backend init` returns an exit code of 0 when the store is already initialized.
This is a regression causing issues with configuration management.
Yes.
Tested with a new store and an existing store. New store initialization exits with 0 as expected. Existing store initialization exits with 3 as expected.
Yes.
=> Fix backend init exit code when store already initialized

command/command_windows_test.go
On appveyor it appears the windows command doesn't have time to execute before timing out. Increase the timeout and sleep time to give it more time.
Increase the command timeout to 10s and the timeout to 20s to give it enough time to launch and be killed. With a one second timeout the pre-sleep part of the command is not even executed before the command is killed.
To prevent unit tests from failing.
No
No
No
Not necessary
Ran the unit test locally.
No
=> Fix windows command execution test

CHANGELOG.md, cli/commands/cluster/member-list.go
The same fix as https://github.com/sensu/sensu-go/pull/4339 but for the sensuctl cluster member-list command.
Guards against a potential crash.
Yes.
Yes.
=> Guard against nil etcd response header in member-list

CHANGELOG.md, backend/cmd/init.go
Adds a new `--ignore-already-initialized` flag to sensu-backend init which will exit 0 if a cluster has already been initialized.
Closes #4161.
Yes.
The new flag will needs to be documented.
https://github.com/sensu/sensu-docs/issues/3246
Tested with and without the new flag against an initialized cluster. Without the flag it still exits 3. With the flag it exits 0.
No, but we could target `release/6.4` if required. cc @calebhailey
=> Add ignore-already-initialized to backend init

CHANGELOG.md, agent/agent.go, agent/cmd/start.go, agent/config.go, transport/client.go
Three new flags have been added for configuring exponential backoff in
agent session connection retry scenarios. They are --retry-min,
--retry-max, and --retry-multiplier. Users can adjust these flags to
control how aggressive the agent's retry behaviour is. The --retry-min
and --retry-max flags expect duration values, like 1s, 10m, 4h. The
--retry-multiplier flag expects a multiplier expressed as a decimal
number.
Additionally, the default retry delays have been changed. Previously,
the initial delay was 10ms. It is now 1s. The maximum delay was 10s, it
is now 120s. The multiplier was 10.0, it is now 2.0.
Closes #4328 
Yes
I manually tested the change unfortunately. The agent code is quite difficult to unit test and I wasn't able to get any unit tests written in a timely fashion.
No
=> Add agent config for session retry

backend/apid/graphql/entity.go, backend/apid/graphql/schema/entity.graphql
Closes #1461
If an entity doesn't have any events that's strange, we don't really know what's up with it because it doesn't even have a keepalive. This is more correct than saying it's passing
=> [Graphql] Entity to return -1 if no events present

CHANGELOG.md, agent/event.go, agent/event_test.go
This changes the payload validation so that events with only metrics in
them are accepted. Events that have neither check nor metrics are still
rejected.
Fixes #4232.
Yes, added.
No.
No.
Unit testing.
No.
=> Make agent API accept pure metrics events

cli/client/apikey.go, cli/client/apikey_test.go
This commit adds the support of apikey lifecycle for the restclient.
This change is necessary in order to align the cli with the restclient and also as some others modules are using this module like https://github.com/jtopjian/terraform-provider-sensu.
This change has been tested with the forked project [terraform-provider-sensu](https://github.com/fgouteroux/terraform-provider-sensu/commit/0fd372c57dbd3a132839e2d1a16151d48ca7ecc3)
=> add restclient apikey support

CHANGELOG.md, backend/cmd/start.go
Increase eventd, keepalived, and pipelined buffer defaults from 100 to 1000.
Increasing the Sensu Go backend internal bus buffer default size from 100 to 1000 (items). The default values are generally too low, new users typically need to increase the buffer size even with a small testing deployment.
Improve initial Sensu Go deployment experience with little to no downside for local/laptop deployments.
Yes.
No.
No.
Not yet.
Local build.
No.
=> Increase eventd, keepalived, and pipelined buffer defaults

CHANGELOG.md, cli/commands/apikey/revoke.go, cli/commands/asset/delete.go, cli/commands/check/delete.go, cli/commands/clusterrole/delete.go, cli/commands/command/delete.go, cli/commands/entity/delete.go, cli/commands/event/delete.go, cli/commands/filter/delete.go, cli/commands/handler/delete.go, cli/commands/helpers/prompts.go, cli/commands/hook/delete.go, cli/commands/mutator/delete.go, cli/commands/namespace/delete.go, cli/commands/role/delete.go, cli/commands/rolebinding/delete.go, cli/commands/silenced/delete.go
Signed-off-by: Luc Dandoy <luc.dandoy@gmail.com>
Displaying resource type in the deletion confirmation prompt.
Proposal to fix #3812.
An entry was added to the changelog file
No.
Not really. Not sure if my fix is the most "efficient"/"beautiful" one
I don't think so as it's mainly a "cosmetic" change
I've been deleting various resource on a test environment to check if the new prompt was correctly displayed.
no
=> Displaying resource type when deleting item

command/command_test.go, command/command_unix_test.go
move test to non-windows platform
One of the kill command test kept failing on windows. Moved it to non-Windows build.
To prevent the build from failing.
No.
No.
No.
Not necessary.
Local test run and CI pipeline succeeded.
No.
=> unit test: command test failing on windows

cmd/loadit/main.go
Customise settings for user, password, and test hostname.
This does change the default hostname from random uuid, to: test-host-1, test-host-2, test-host-n
The user and password change were required to be able to connect if the default credentials are not being used.
The test host allows easily checking on events and such in api.
- Added -user and -password flags for loadit to set credentials if required (still defaults to default settings).
- Changed test entity name for loadit to "test-entity-1"... "test-entity-n". The "test-entity" can be customized with new -base-entity-name flag
None
So far no complications.
No documentation for loadit
Verified against my test sensu cluster.
No.
=> Customise settings for username, password, and test hostname.

cli/commands/check/interactive.go, cli/commands/hook/interactive.go, cli/commands/silenced/interactive.go
This regression caused sensuctl to crash in some circumstances. The
regression was not released and therefore does not require a changelog
update.
Closes #4376 
=> Fix a regression introduced by survey package v2

api/core/v2/mutator.go, cli/commands/mutator/create.go, cli/commands/mutator/interactive.go
This is work that got missed in the initial implementation of javascript mutators. Without this work, it's not possible to create javascript mutators with sensuctl.
No
=> Add updates to sensuctl for mutator type and eval

CHANGELOG.md, backend/agentd/agentd.go, backend/agentd/session.go, backend/metrics/events.go, backend/metrics/metrics.go, backend/store/etcd/event_store.go, backend/store/etcd/store.go
Adds event size, in bytes, Prometheus metrics for check, metric, and check+metric events in both the agentd & store (etcd/postgres) packages.
Closes #4298.
Yes.
I don't believe that we document all of the metrics exposed by the `/metrics` endpoint, so no new documentation should be required.
Deployed to the perf cluster.
No.
=> Event bytes per second

CHANGELOG.md, asset/fetcher.go
In some cases, it was possible for the agent to leave temporary files behind
when downloading assets. That shouldn't be the case anymore now.
Fix #4180
Yes, added.
No.
Issue was inaccurate. Otherwise no.
No documentation change needed.
Local testing to the extent possible.
No.
=> Cleanup asset downloads

CHANGELOG.md, backend/cmd/init.go, backend/seeds/seeds.go
Adds the ability to init the cluster with an API key.
Closes #4162
Included
@hillaryfraley we should update the documentation to reflect that API keys are now supported by sensu-backend init.
Manual testing in interactive and CLI mode.
No
=> Support cluster admin API keys on cluster init

CHANGELOG.md, backend/agentd/agentd.go, backend/apid/apid.go, backend/backend.go
This PR improves logging of sensu-go readiness. A warning is now issued when the backend is ready to process events, and info-level logs that mention that APId and Agentd have started on a particular address are now at warn level.
Closes #4390
Yes
Yes
=> Improve logging somewhat

CHANGELOG.md, backend/apid/graphql/mutations.go, cli/resource/parse.go, types/wrapper.go
This commit allows creating resources with unknown fields in them,
through sensuctl, the API, and federation.
To reduce sharp edges a warning system has been added to sensuctl, in
order to reduce the likelihood of typos.
Yes
Yes
=> Allow resources without unknown fields

CHANGELOG.md, backend/agentd/agentd.go, backend/agentd/session.go, backend/metrics/events.go, backend/metrics/metrics.go, backend/store/etcd/event_store.go, backend/store/etcd/store.go
Backports the event size metrics from the `main` branch into the `release/6.4` branch.
Yes.
Yes.
=> Backport event size metrics to 6.4

CHANGELOG.md, go.mod, go.sum
Fixes a crash when running the backend on `darwin/arm64`.
The following segfault occurs when running the backend on `darwin/arm64`, which affects some of our development machines:
```
{"component":"backend","level":"warning","msg":"backend is running and ready to accept events","time":"2021-09-02T15:55:44-07:00"}                                                                                                            
unexpected fault address 0xa1a3832312f3396                                                                                                                                                                                                    
fatal error: fault …
```
=> Bump snappy to v0.0.4

cli/client/config/basic/basic_test.go, cli/client/config/basic/writer_test.go
Creates a temporary directories for any sensuctl tests which result in a config being created.
Running tests prior to this would result in dirtying the git state as it was using the local directory whenever `config-dir` was empty.
No.
Tests pass and no longer dirty the git state.
No as this only affects the `main` branch at the moment.
=> Use temp dirs in sensuctl tests which create configs

CHANGELOG.md, agent/cmd/start.go
`--retry-min`, `--retry-max` and `--retry-multiplier` were missing from the
output of `sensu-agent start --help`. This change adds them, along with a short
description.
Closes #4406.
Added.
No.
No.
No.
Manual testing to see that the aforementioned flags are now listed along with
their description.
No.
=> Add help for retry related flags

CHANGELOG.md, backend/backend.go, backend/backend_test.go, backend/cmd/start.go, backend/config.go, backend/eventd/eventd.go, backend/eventd/eventd_test.go, backend/eventd/logger.go, backend/eventd/logger_test.go, backend/eventd/logging.go, backend/eventd/silenced_test.go, backend/logging/logrus.go, backend/logging/rotate_writer.go, backend/logging/rotate_writer_test.go, backend/messaging/message_bus.go, backend/messaging/signal_multiplexer.go, go.mod, go.sum, metrics/influx_bridge.go, metrics/influx_bridge_test.go
This commit adds platform metrics logging to sensu-go. The feature
defaults to being enabled, but can be disabled via flag, config file, or
environment variable. See documentation for details.
This commit also adds event logging, previously an enterprise-only
feature, to OSS sensu. The flag names and behaviours for this feature
are the same as in the enterprise product.
Both of these logs can be rotated by sending SIGHUP to sensu-backend
after mv-ing the log files.
Closes #4299
Yes
I had to do some significant refactoring to send one signal to two different components. I also moved the enterprise-only event logging into OSS (with leadership's blessing).
@hillaryfraley documentation updates will be needed, as there are several new flags available. Please schedule some time with me to go …
=> Add platform metrics logging and event logging

.appveyor.yml, .circleci/config.yml, .github/workflows/golangci-lint.yml, CHANGELOG.md, api/core/v3/resource_test.go, go.mod, go.sum
Updates Go to 1.17.1 and golangci-lint to 1.14.1. It also bumps gopsutil & go-ole to the latest versions. The latest gopsutil brings a change/fix for killing Windows processes and go-ole brings lazy DLL loading & arm/arm64 architecture support.
To get the improvements that Go 1.17.1 brings.
Yes, only for the Go 1.17.1 change.
I'm not sure if we track the version of Go we use to build our apps. cc @hillaryfraley 
No.
=> Bump to Go 1.17.1 and golangci-lint 1.42.1

backend/apid/actions/error.go, backend/apid/graphql/health.go, backend/apid/graphql/health_test.go, backend/apid/graphql/mock_test.go, backend/apid/graphql/query.go, backend/apid/graphql/schema/health.gql.go, backend/apid/graphql/schema/health.graphql, backend/apid/graphql/service.go, backend/apid/routers/graphql.go, backend/apid/routers/routers.go
Closes https://github.com/sensu/sensu-enterprise-go/issues/1781
---
* Previously no deadline was provided when querying etcd health from the GraphQL service,
this meant that in cases where the health was irretrievable the http server's writetimeout would
trigger before the query completed. In the web client this led to the offline banner being
displayed briefly and the health dialog being stuck in an infinite loading state.
* I've also updated the GraphQL endpoint with a deadline and now respond with a 504 if the service
takes too long to finish resolving the query. This change should make it easier to capture, and possibly
retry the request later.
---
=> Add deadline to etcd health field resolver

CHANGELOG.md, cli/commands/command/exec.go, cli/commands/env/env.go, cli/commands/env/env_test.go
- Make `sensuctl env` include `SENSU_API_KEY` and `SENSU_TIMEOUT` in its output
- Make `sensuctl command exec` include `SENSU_API_KEY` and `SENSU_TIMEOUT` in the executed command's environment
Fixes #4411.
Yes, added.
No.
No.
@hillaryfraley 
Are there example outputs that we need to update in the docs for `sensuctl env` maybe?
Updated existing unit tests and manual testing.
No.
=> Fix missing env vars in env and command exec

CHANGELOG.md, backend/pipeline/adapter.go, backend/pipeline/adapterv1.go, backend/pipelined/pipelined.go, cli/client/interface.go, cli/client/pipeline.go, cli/client/testing/mock_pipeline_client.go, cli/commands/commands.go, cli/commands/pipeline/LICENSE, cli/commands/pipeline/delete.go, cli/commands/pipeline/delete_test.go, cli/commands/pipeline/help.go, cli/commands/pipeline/info.go, cli/commands/pipeline/info_test.go, cli/commands/pipeline/list.go, cli/commands/pipeline/list_test.go
Adds pipeline commands to `sensuctl`:
* `sensuctl pipeline list`
* `sensuctl pipeline info [NAME]`
* `sensuctl pipeline delete [NAME]`
It allows for quick viewing of configured pipelines & deleting pipelines without needing to use `sensuctl delete`.
Yes.
Yes.
I created pipeline resources using `sensuctl create -f` and used the new commands against those resources.
No.
=> Add sensuctl pipeline commands

CHANGELOG.md, api/core/v2/go.mod, api/core/v2/go.sum, api/core/v2/token.go, api/core/v3/go.mod, api/core/v3/go.sum, backend/apid/actions/silenced_test.go, backend/apid/middlewares/authorization_attributes_test.go, backend/apid/middlewares/authorization_test.go, backend/authentication/jwt/jwt.go, backend/authentication/jwt/jwt_test.go, cli/client/authentication.go, cli/commands/helpers/user.go, go.mod, go.sum, licenses/bom.json, types/go.sum
Signed-off-by: Sebastian Spaink <sspaink@influxdata.com>
The package https://github.com/dgrijalva/jwt-go has been archived and contains a CVE (https://github.com/advisories/GHSA-w73w-5m7g-f7qc), the project has migrated to https://github.com/golang-jwt/jwt. This pull request just replaces the dependency to use the new project following the migration guide: https://github.com/golang-jwt/jwt/blob/main/MIGRATION_GUIDE.md this should be backwards compatible.
My motivation for this change is that the Telegraf project has a output plugin for [Sensu](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/sensu) and uses sensu-go which is indirectly pulling in `dgrijalva/jwt-go`.
Yes, changelog has been updated
Not sure to be honest, but I did run `./build.sh`
=> Update package dgrijalva/jwt-go to golang-jwt/jwt

cli/resource/resolve.go
Adds `corev2.Pipeline` to the list of resources that are returned when running `sensuctl dump all`.
No.
Documentation changes have already been made.
I ran the `sensuctl dump all` command and saw a pipeline resource that I had created.
No.
=> Add corev2.Pipeline to cli resources

api/core/v2/mutator.go, api/core/v2/mutator_test.go
This commit fixes a bug where mutators can be defined that are of type
javascript, but have command instead of eval. The combination is now
considered to be an error.
This configuration error pattern was encountered when doing QA.
No, unreleased code.
=> Don't let javascript mutators have command defined

CHANGELOG.md, backend/store/etcd/misc_test.go, backend/store/etcd/silenced_store.go
The number of silenced entries in a given transaction could exceed the
default number of etcd transaction operations, which is 128. This commit
changes the silenced entry store so that it makes at most 64 transaction
operations, and handles silenced expiration by creating multiple
transactions that are each no longer than 64 items.
Closes #4384
Yes
On the contrary, this change was easy to make, and that's what I decided to make it ahead of 6.6.
I tested that the partitioning logic I wrote functions as expected. Beyond that, I expect the existing integration tests to hold water.
Yes.
=> Partition silenced entry transactions

asset/boltdb_manager.go
A recent PR made a change to assets that changes the way expansion
happens, but the error from the new function call was not handled.
=> Fix a bug where asset expansion err not handled

CHANGELOG.md, backend/backend.go, graphql/tracing/prometheus.go, graphql/tracing/prometheus_test.go
Add objectives (0.5, 0.9, 0.99) to the `graphql_duration_seconds` metric and add GraphQL metrics to the metrics log.
It adds clarity and allows us to look into the duration GraphQL operations.
Yes.
No documentation is required.
Spun up a backend, browsed the dashboard, and verified that `graphql_duration_seconds` metrics are in `/metrics` and the metrics log.
Yes.
=> Metricslog graphql

CHANGELOG.md, asset/boltdb_manager.go, backend/eventd/eventd.go, backend/keepalived/keepalived.go, backend/pipeline/adapterv1.go, backend/pipeline/filter.go, backend/pipeline/handler.go, backend/pipeline/mutator.go
The `timer.ObserveDuration()` method in Prometheus uses seconds but the rest of our metrics in these packages are in milliseconds. This updates the observation of the timer to use milliseconds for consistency.
Also fixes a bug in the timeout duration that is logged when adding entities to the ring.
We had meant to use milliseconds.
Yes.
I created a handler with the command `sleep 60` & a check that uses the handler. The metrics are returned in milliseconds (60000.0).
```
sensuctl handler create sleepy --command "sleep 60 && cat"
sensuctl check create foo --command "false" --subscriptions "all" --interval 60 --handlers "sleepy"
```
```
sensu_go_pipelined_message_handler_duration{has_pipelines="0",status= …
```
=> Use milliseconds for new duration metrics

CHANGELOG.md, backend/etcd/etcd.go
This change makes it so etcd related configuration flags parsed by Sensu are only applied if they are not a zero value (`""`, 0, empty slice, ...). This is to avoid overwriting default values set by the etcd developers.
Fix #3952.
Added.
I think it's a good change to make, but I'm not sure if this had caused any problem so far; the issue (#3952) doesn't give information.
No.
I don't think any documentation needs to be changed.
- All unit tests passing
- All integration tests passing
- Manual tests
No.
=> Avoid overwriting etcd defaults

CHANGELOG.md, backend/backend.go, metrics/influx_bridge.go, metrics/influx_bridge_test.go
Add the backend label to the logged metrics.
Closes #4450 
We need the ability to associate metrics from the metrics log file with the backend they were generated on.
Yes, added.
No.
No.
No.
Unit test. Also tested manually by adding the following to my backend.yml:
```
platform-metrics-log-file: "/Users/fguimond/sensu/sensu-backend/logs/backend-stats.log"
```
No.
=> Add backend label to logged metrics

CHANGELOG.md, backend/apid/apid.go, backend/backend.go, backend/cmd/start.go, backend/config.go
Adds `api-write-timeout` & `dashboard-write-timeout` flags to allow users to configure the respective HTTP server's write timeout. Useful when some requests might reasonably take more than a few seconds to complete.
---
=> Add flag to configure API & dashboard's write timeouts

CHANGELOG.md, backend/backend.go
When a sensu backend is initialized with an external etcd service `--no-embed-etcd`, pull the etcd cluster version from the remote service to reflect in the sensu `/version` endpoint. 
https://github.com/sensu/sensu-go/issues/4174
The version API is currently tailored towards the situation where etcd is running embedded in sensu-backend.
It reflects both the version of that particular embedded instance of etcd, `etcdserver`, and the lowest common version of all cluster members, `etcdcluster`.
**Example with single sensu-backend instance:**
```
{
"etcd": {
"etcdserver": "3.5.0",
"etcdcluster": "3.5.0"
},
"sensu_backend": "(devel)"
}
```
Today when using external etcd endpoints the output is misleading, sharing the etcd client version as `etcdserver` and leaving `etcdcluster` blank. …
=> Set External etcd version in /version API

CHANGELOG.md, transport/transport.go
This commit changes the way websocket connections are handled, by both
the backend and the agent.
It replaces one sync.RWMutex with two sync.Mutex values, one for reads,
and one for writes. The gorilla websocket docs state that reads and
writes can be concurrent, so it's not correct to use a single mutex for
both resources.
The commit also avoids setting the internal "closed" flag to true when a
connection error is encountered. Instead, it only sets the flag to true
when a ClosedError is found on receive.
The commit also makes sure the write mutex is locked when sending a
close message.
The commit also removes sync.Pool use for transport messages, which was
a speculative optimization we applied. However, it seems unlikely that
this optimization is really necessary, so I have removed it in …
=> Fix several websocket handling bugs

CHANGELOG.md, backend/liveness/liveness.go
Adds retry behaviour to lease grants, since they can fail due to rate limiting.
Closes #4500. I found this issue as part of an ongoing investigation into sensu-backend stability and error handling.
Included!
Verified by load testing and is also covered by existing integration tests. While the retry behaviour itself is not tested for, the retry mechanism itself is well tested.
Yes.
=> Retry keepalive lease grant requests

CHANGELOG.md, agent/agent.go, backend/agentd/agentd.go, backend/agentd/session.go, backend/agentd/session_test.go, backend/backend.go, backend/etcd/id.go, backend/etcd/metrics.go, backend/liveness/liveness.go, backend/queue/queue.go, backend/ringv2/ringv2.go, backend/store/etcd/initialization.go, backend/store/etcd/silenced_store.go
Cherry-pick lease metrics work from `main` to `release/6.5`. Fix the changelog that erroneously included the lease metrics as an addition to the 6.5.1 release.
We want this functionality in the next 6.5 patch release.
Yes.
The 6.5.1 changelog on our website will need to be updated to remove the lease metrics addition.
Yes.
=> Lease metrics

CHANGELOG.md, backend/etcd/id.go
This commit fixes a bug in the BackendIDGetter where failed etcd client
requests are not retried.
Fixes #4509
Yes
Testing on sensu-perf and existing integration tests.
Yes
=> Fix a bug that could cause sensu-backend to crash

backend/store/etcd/event_store.go, backend/store/etcd/event_store_integration_test.go, backend/store/proxy.go, backend/store/store.go, testing/mockstore/events.go
The CountEvents store method will be used by the Web UI to know how many
pages of results are available, when using pagination.
Supporting work for ongoing maintenance related to #4487
No
Integration testing.
No.
=> Add CountEvents store method

CHANGELOG.md, api/core/v2/check.go, api/core/v2/check_config.go
Adds the error returned by the cron library to the validation error we return when validating the Check & CheckConfig resources.
Is can be unclear why the validation fails without this change.
Closes https://github.com/sensu/sensu-go/issues/4385.
Yes.
No new documentation is needed.
Spun up a Docker container before and after this commit. Analyzed the output returned by `sensuctl create -f` when using the following file:
```yaml
---
type: CheckConfig
metadata:
name: cron_test
spec:
command: "true"
cron: 'CRON_TZ=Asia/Tokyo * * * * *'
handlers: []
publish: true
subscriptions:
- system/linux
---
type: CheckConfig
metadata:
name: cron_test
spec:
command: "true"
cron: 'TZ=Asia/Tokyo * * * * *'
handlers: []
publish: true
subscriptions:
- system/linux …
```
=> Log errors returned by cron library when validating Checks & CheckConfigs

backend/api/event.go, backend/apid/graphql/interfaces.go, backend/apid/graphql/mock_test.go, backend/apid/graphql/namespace.go, backend/apid/graphql/namespace_test.go, backend/apid/graphql/service.go, backend/store/etcd/event_store.go, backend/store/etcd/event_store_test.go, backend/store/proxy.go, backend/store/store.go, testing/mockstore/events.go
Overwrites the Namespace Events graphql field resolver for situations where the backing event store supports filtering and sorting (i.e. postgres in the enterprise product)
Prevents the web ui from using excessive memory by loading large collections of events.
? 😬 
No
=> Store Based Event Filtering Aware Graphql Field Resolver

backend/apid/graphql/namespace.go
Fixes a recent change to graphql event ordering, so that sorting by severity works.
@c-kruse I don't need you for review, as this is time sensitive. However, I don't have time to write a unit test for this. Would you mind back-filling one when you return next week?
=> Fix severity ordering

backend/apid/graphql/namespace.go
The previous commit fixed severity ordering but got the direction wrong.
=> Invert ordering of events by severity

CHANGELOG.md, backend/pipeline/adapterv1.go
Removes the following log entry spamming the log files.
```
Nov 29 09:48:22 ensengoa001 sensu-backend[4179342]: true
Nov 29 09:48:22 ensengoa001 sensu-backend[4179342]: true
Nov 29 09:48:22 ensengoa001 sensu-backend[4179342]: true
Nov 29 09:48:22 ensengoa001 sensu-backend[4179342]: true
```
To prevent log files from growing too big too fast.
Added.
No
No
Not necessary.
Manual test.
Yes, submitting against release/6.6.
=> Remove over zealous log entry

backend/apid/graphql/namespace_test.go
Signed-off-by: c-kruse <ctkruse99@gmail.com>
Adding unit test coverage around the sort ordering mapping per https://github.com/sensu/sensu-go/pull/4516.
Documenting desired sort ordering.
✅ 
No
No
No
Unit test suite change only / N/A
Yes.
=> Add test cases for missing orderings

README.md
=> Clarify that Go 1.13 is the minimum version required

backend/backend.go, backend/opampd/protocol.go, backend/opampd/types.go, cli/commands/opampagent/configure.go
Update the StatusReport handler to include a RemoteConfig when an `api/opamp/agentconfig` is set in the backend.
PartyMode is a silly name, but the issue I was working around was that the opamp client from otelcol-sumo doesn't announce that it is capable of remote config. Instead of just disobeying the spec on this capability and commenting out that gate, I am bypassing it with the PartyMode flag.
* build/install sensuctl and sensu-backend. Start sensu-backend
* Using a valid otel conf `cfg.yaml`, configure sensu's opamp agent with `sensuctl opampagent configure -f /path/to/cfg.yml`
example cfg.yaml:
```
receivers:
otlp:
protocols:
http:
exporters:
logging:
extensions:
opamp:
config_path: /tmp/config-opamp.yaml
endpoint: ws://localhost:4320/v1/opamp
service:
pipelines:
metrics:
receivers: …
```
=> Opampd Provide RemoteConfig

api/core/v2/entity.go, backend/keepalived/keepalived.go, backend/opampd/protocol.go
Create a new Sensu entity when a new opamp agent connects to the WS server.
=> Create a new entity when an agent comes online.

backend/backend.go, backend/opampd/opampd.go, backend/opampd/protocol.go
This makes `opampd` collect some simple statistics and emit a metrics event with them every 30 seconds.
=> Add PoC opampd metrics event

backend/opampd/opampd.go, backend/opampd/protocol.go, backend/opampd/types.go
This makes `opampd` emit events when receiving `StatusReport` messages from clients.
I would love feedback on which fields should be filled (and with what) in the events we are emitting.
**I HAVEN'T YET**
=> Make opampd emit events

.github/workflows/semgrep.yml
The semgrep config name was renamed from `p/dgryski.semgrep-go` to `p/semgrep-go-correctness`. This change should fix CI.
=> Update semgrep-go config name

CHANGELOG.md, backend/eventd/eventd_test.go, backend/keepalived/keepalived.go, backend/keepalived/keepalived_test.go, backend/liveness/liveness.go
Adds a new `BuryAndRevokeLease` method to SwitchSet which is used by keepalived instead of `Bury`. This allows the lease associated with a keepalive SwitchSet to be revoked when buried, preventing leases from being orphaned.
It eliminates leases from being leaked when agents continuously reconnect.
Yes.
Our agent registration & lease code is tough to grok.
The first keepalive that the backend processes for an agent is generated by the backend when the session starts. This keepalive is generated using information from the HTTP headers on connection, which does not include keepalive thresholds. If we had access to the keepalive thresholds, we could conditionally bury keys depending on if the TTL has changed.
I wrote a tool to track lease usage …
=> Revoke orphaned leases on bury

CHANGELOG.md, backend/backend.go
Updates the daemon start order so that agentd starts after all of the other daemons. This change works best when paired with the `agent-rate-limit` flag set to something low enough for the cluster to handle.
Also applies EtcdLogLevel to the internal Etcd client.
When agentd starts before keepalived, the backend will start processing events and putting load on the store(s) before we can process keepalive events. The `initFromStore` method in keepalived can time out when the cluster is under heavy load which prevents apid from starting and triggers an internal restart.
Yes.
I reproduced a crash loop where `initFromStore` would fail. Using a combination of this change and `agent-rate-limit` set to something low enough (I used 5 in the test but is likely …
=> Start agentd after all other daemons

CHANGELOG.md, backend/liveness/liveness.go
Removes unused rate limiting code in the liveness monitor method.
After discussing this with @echlebek it was determined that this code isn't actually doing anything.
I added it but it may not be necessary for release notes.
@echlebek so graciously proved that this code doesn't change the function with a Go playground link.
No.
=> Remove unused rate limiting code in liveness monitor

CHANGELOG.md, backend/liveness/liveness.go
This commit fixes an infinite loop that can occur when another backend
revokes a lease for an agent, or if an operator manually revokes the
lease.
Yes
Yes
=> Fix an infinite loop that can occur in keepalives

CHANGELOG.md, backend/backend.go, backend/backend_test.go, backend/cmd/start.go, backend/config.go, backend/etcd/etcd.go
Adds a `etcd-client-log-level` flag for setting the log level of the internal etcd client we use within sensu-backend. The default value is set to `error` as `warning` is overly verbose and doesn't typically add value when troubleshooting.
The logs are currently flooded with unhelpful log lines generated by the etcd client (e.g. `retrying of unary invoker failed`). We already log errors returned by the etcd client.
Yes.
Setting the log level differs between the client we create for embedded vs. external etcd clusters.
New documentation is required.
https://github.com/sensu/sensu-docs/issues/3552
I tested that the logs shown for etcd client are at error by default for both embedded & external etcd. I then tested that setting the log …
=> Add --etcd-client-log-level flag to sensu-backend

CHANGELOG.md, backend/backend.go, backend/backend_unit_test.go
sensu-backend now crashes with a panic when daemons are asked to
stop but do not respond.
If daemons hang, then the overall ability to operate sensu-backend is compromised. This change ensures that when asked to stop, sensu-backend will do so within 30s.
Yes
Verification on SPDC pending.
Yes.
=> On daemon stop, crash when not responding

CHANGELOG.md, backend/eventd/eventd.go, backend/tessend/tessend.go
Adds a count of metric points processed.
https://github.com/sensu/sensu-enterprise-go/issues/1872
This metric will help us better understand how much metric data is flowing through sensu.
Y
N
N
N - ~~do we have "data we collect" sort docs around tessen?~~ We have some examples of tessen data but no exhaustive list: https://docs.sensu.io/sensu-go/latest/operations/monitor-sensu/tessen/#tessen-metrics-log-examples.
Manual/local validation running cluster_id = `d075d31d-cb38-4650-9c4f-41cabd43bf62` with a check with metric points scheduled.
`psql $TESSEN_DB_URL -c "SELECT name, value, time FROM metrics WHERE cluster_id='d075d31d-cb38-4650-9c4f-41cabd43bf62' AND name like 'sensu_go%'"`
```
name                  | value |          time …
```
=> Add event metric points processed counter

backend/agentd/agentd.go, backend/agentd/session.go, backend/keepalived/keepalived.go, backend/liveness/liveness.go, backend/messaging/message_bus.go
This commit adds synchronization to agentd's sessions so that we can be
sure burial events are fully processed before setting a keepalive switch
to the "alive" state.
Also, a situation where leases are created but never used has been
resolved.
This commit fixes a regression caused by a previous unreleased change, and also further reduces the possibility of dangling leases.
No.
Yes.
=> Ensure that agent burial events happen before keepalive refresh

CHANGELOG.md, backend/eventd/entity.go
Proxy entity state is now created if it does not exist but matching proxy entity config does exist.
There seems to be a race condition when switching the store from Etcd to Postgres where entity state is not migrated from Etcd to Postgres. This can cause events for proxy entities return an error when attempting to handle them.
Yes.
I've only run the unit & integration tests.
Yes.
=> Create proxy entity state when missing if entity config exists

CHANGELOG.md, agent/transformers/prometheus.go, agent/transformers/prometheus_test.go
Tooling around mapping sensu corev2 metrics back to prometheus is being built in the plugin sdk. This solidifies some of the conventions these tools will rely on.
Per https://github.com/sensu/sensu-plugin-sdk/issues/65 - it is going to be valuable for sensu handlers to marshal sensu corev2 metrics back to the prometheus exposition format.
Without this change, HELP info in prometheus formatted check output will be discarded by the sensu agent.
This change also hopes to make it clearer that the `prom_type` and `prom_help` tag names are special and likely depended on outside the system.
Y
**Q:** Persisting HELP info on each metric point is pretty inefficient. I can imagine sensu with the plain ole etcd event storage might be noticeably impacted by this if folks had lots of metrics. Anyone …
=> Update agent prometheus transformer to map prometheus help message

.github/workflows/golangci-lint.yml
It not clear to me if this was intentional, but patch pull requests against the release/x branch was not triggering the golangci-lint github action.
Would be cool to not be surprised by a failing workflow in main after merging the release branch.
Github Workflow syntax: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags
**tl;dr**
>The * wildcard matches any character, but does not match slash (/)
The ** wildcard matches any character including slash (/) in branch and tag names.
=> Update github workflow to run golangci-lint on patch PRs

backend/ringv2/ringv2.go, backend/tessend/tessend.go
This commit adds a context value that indicates to ring implementations
that associated entities should be deleted when removed from a ring.
This only applies to the postgresql ring implementation, which is not
implemented in sensu-go directly.
Part of an issue being worked on in the enterprise product.
No, this is not a user facing change.
Yes
=> Request backend entity deletion in tessend

.appveyor.yml, .circleci/config.yml, .github/workflows/golangci-lint.yml
Bump Go version to 1.17.6.
No as we do not produce binaries from this repository.
No.
=> Bump Go version to 1.17.6

CHANGELOG.md, token/token_test.go, types/dynamic/dynamic.go
Updates the dynamic pkg to set fields (with omitempty) to a map-typed nil value instead of not setting the field at all.
It fixes a bug where token substitution can result in an unexpected error when attempting to use a key that doesn't exist in labels.
Closes https://github.com/sensu/sensu-go/issues/4236.
Yes.
I wrote new specs to confirm the bug in the issue linked above. After adding the changes the new specs (& old specs) pass.
It can be if we'd like it to be but I've targeted main for now.
=> Use typecasted nil for empty maps in dynamic pkg

backend/pipeline/adapterv1.go
Signed-off-by: Conor Evans <coevans@tcd.ie>
correct the spelling of requests in Help of sensu_go_handler_requests metric
It's not, I just noticed it when reviewing the CHANGELOG for upgrade and figured I'd fix it. Feel free to close if deemed overly trivial.
No
No
No
No
With my eyes
No
=> fix: correct the spelling of requests in Help of sensu_go_handler_requests metric

CHANGELOG.md, api/core/v2/version.go, backend/apid/actions/version.go, types/versions.go, types/versions_test.go
This commit adds module version info to the /version endpoint. Due to an
open Go bug, the commit is not testable yet. A unit test has been added
anyways, with a canary that should die when Go fixes the bug on their
end.
Closes #4590 
Yes
While the change does work, as validated by starting up sensu-backend and querying the `/version` endpoint, it is not testable with `go test` yet, due to a Go bug. See https://github.com/golang/go/issues/33976
Manually.
No.
=> Add module versions to /version info

CHANGELOG.md, agent/agent.go, agent/cmd/start.go, agent/config.go, cmd/loadit/main.go
```
This makes the agent disconnect and reconnect after some configurable
amount of time (+ built-in jitter). The aim of this change is to have
agents organically rebalance their connections to the backends over
time.
Signed-off-by: Cyril Cressent <cyril@sensu.io>
```
Close #3329.
Yes, added.
Yes: I am suggesting a different way to calculate the final session length (including jitter) such that `--max-session-length` feels more "natural". Let me know if it makes sense to go ahead with that.
```
maxSessionLength = x/2 + randFloat() * x
where x is the value given to the flag
```
Given that `randFloat()` gives a value in the range `[0, 1(`, it makes it so the maximum amount of time before a disconnect/reconnect is really bounded by the value given to the flag.
Yes. The connection manager in …
=> Add max-session-length flag and logic

backend/apid/graphql/namespace.go
Bumps the maximum number of events that will be read into memory when fetching events from the store. This will increase response time and memory usage for very large namespaces, but is less likely to leave events out of the response.
Note: No limitation is applied when using the postgresql store; only applicable for etcd store.
---
=> [GraphQL] Bump events max fetch size to 50k

CHANGELOG.md, backend/ringv2/ringv2.go, backend/ringv2/ringv2_test.go
Adds the context.Context to ringv2 watcher key
BSM and potentially other usages of ringv2 occasionally "abandon" subscriptions (cancel the context used to create the subscription and stop reading from the subscription channel) and then create a fresh but otherwise identical subscription with a new context from another goroutine. By returning the channel of an existing watcher form another context, there is a potential for subsequent subscriptions to unexpectedly be cancelled.
✅ 
@echlebek  I'm iffy about this one. It was a quick change so I made it and it seems to work, but it feels like the change could have a pretty large surface area.
No doc updates required.
Manual/local validation so far.
?
=> Ringv2 Create Watcher per Subscription

backend/apid/graphql/interfaces.go, backend/apid/graphql/mock_test.go, backend/apid/graphql/namespace.go, backend/apid/graphql/namespace_test.go, backend/apid/graphql/pagination.go, backend/apid/graphql/schema/pagination.gql.go, backend/apid/graphql/schema/pagination.graphql, backend/apid/graphql/service.go
* Adds a `partialCount` flag to pagination that communicates whether or not the `totalCount` in fact represents the total count of entities or if the count was abandoned.
* When queries entities, in the case where no filter was given, the total count of entities is retrieved from the metrics daemon to avoid having to scan the entire keyspace for determine the count.
---
=> [GraphQL] Partial count field

backend/apid/graphql/namespace.go
Switches to using a chunk size of between 250 and 500 records. In cases where the page size is small (eg. 25 items) this will lead to a bit more memory usage but it greatly reduce the amount to round trips. As I/O is likely a bigger bottleneck than CPU or memory, this should greatly reduce resolver execution time.
---
=> [GraphQL] Use a sliding chunk size

CHANGELOG.md, agent/agent.go, agent/cmd/start.go, agent/cmd/start_test.go, agent/config.go
Add 2 new flags to the agent, `--keepalive-check-labels` and `--keepalive-check-annotations` to let the agent inject labels and annotations in the keepalive events produced by the backend.
- Close #4042 
- Integrate @agm650's PR (#4357) after bringing it up to speed with current `main` and making a few alterations.
Yes, added.
Can the reviewers share their opinion one last time on the new flag names?
No.
New documentation is required for the 2 new flags, `--keepalive-check-labels` and `--keepalive-check-annotations`.
@hillaryfraley 
- Unit tests for new configuration flags
- Manual testing to check that the configured labels/annotations appear in keepalive events
- Manual testing using the `curl` commands shared in #4042, to check that one can now retrieve keepalives based on labels …
=> Integrate PR 4357 (Metadata configuration for keepalive)

CHANGELOG.md, api/core/v3/go.sum, backend/store/v2/wrap/wrapper_test.go, types/go.mod, types/go.sum, types/versions.go, types/versions_test.go, types/wrapper.go, types/wrapper_test.go
This commit makes changes that allows users to specify richer version in
the api_version field of a wrapped resource. Users can now specify
versions like core/v2.3.0, to require that Sensu has at least version
2.3.0 available.
Since the first version of Sensu that implements this functionality has
core/v2.6.0 and core/v3.3.0, requiring versions smaller than this has no
effect.
There are no published modules for enterprise APIs yet, so only core
APIs can be gated this way as of this writing.
Closes #4591 
Yes
Modules are not yet available for enterprise APIs.
New documentation will eventually be required, but I don't think it needs to be altered just yet.
Testin'
No.
=> Allow specifying more precise API versions

types/wrapper.go
Fix bug #4610 by calling `APIModuleVersions()` before read-locking `packageMapMu`.
Required to be able to start the backend node.
Perhaps yes?
No.
No.
No.
Yes, after that backend works again.
Yes.
=> types: Fix ResolveType/ResolveRaw deadlock

README.md
I'm updating the Install Sensu page in the docs to clarify that the installation instructions are specific to our supported packages and sending readers to this readme for binary/OSS instructions.
This suggestion would make sure we are providing this clarification in both spots (here and in the docs).
No
No
No
I am updating https://docs.sensu.io/sensu-go/latest/operations/deploy-sensu/install-sensu/ to provide clarification about what the page covers as well. This is the only docs update required.
n/a
No
=> Clarify Install Sensu in the docs is for supported packages

CHANGELOG.md, backend/apid/graphql/namespace.go, backend/apid/graphql/namespace_test.go
Continues to scan through entities until the requested slice (offset + limit) has been satisfied.
Previously if the current matches had exceeded the `maxCountNamespaceListEntities` constant, the resolver would stop the scan and return whatever it had collected up to that point. This didn't really match the intent of `maxCountNamespaceListEntities` constant which had only been meant to signify when we give up on determining the total count<sup>[1](https://github.com/sensu/sensu-go/blob/4086938e0e61e99e175c2120bf80fbc34ccdca53/backend/apid/graphql/namespace.go#L21-L24)</sup>.
Closes https://github.com/sensu/sensu-enterprise-go/issues/2026
---
=> [GraphQL] Continue paging until requested slice has been satisfied

CHANGELOG.md, agent/agent.go, agent/cmd/start.go, agent/cmd/start_test.go, agent/config.go, api/core/v2/resource_reference.go, api/core/v2/resource_reference_test.go, backend/keepalived/keepalived.go
https://github.com/sensu/sensu-go/issues/4589
Adds a keepalive-pipelines flag to the sensu agent in order to allow operators to target pipelines for agent keepalive events.
Adds flexibility (pipeline support) that is not currently supported using the special keepalive handler.
Yes
No
Spoke in #sensu-product slack and agreed on adopting the already familiar syntax from sensuctl edit. Ended up with regex that matches both `api_version.type.name` (dot) and `api_version.type name` (space).
No
New flag, so I assume so. @hillaryfraley 
Although I'd caution you to not get started until we land on the convention we want to use above.
Minimal unit testing + manual verification.
WIP:  https://github.com/sensu/sensu-go-qa-crucible/pull/217 and https://github.com/sensu/sensu-staging/pull/300
N
=> Pipelines for agent keepalives

backend/apid/graphql/service.go, graphql/tracing/prometheus.go, graphql/tracing/prometheus_test.go
Adds an additional label with the type of error that occurred. Specifically it should help capture which errors are occurring, how frequently, and time elapsed before the resolver encountered an err.
---
=> [GraphQL] Collect error types in metrics

CHANGELOG.md, backend/etcd/etcd.go
Increased the embedded etcd heatbeat interval and election timeout defaults.
Closes https://github.com/sensu/sensu-go/issues/4368
Values based on this discovery https://github.com/sensu/sensu-go/pull/4369#pullrequestreview-837806968
Increased the embedded etc heartbeat interval and election timeout defaults, making etcd more latency tolerant for our use-case.
Quality network an more importantly storage is harder to come by then expected. The etcd default values for the heartbeat interval and election timeout are too low, too sensitive to network and storage latency. etcd elections are expensive and destructive, increasing the default values helps avoid them while still not being too high that leader failover takes too long.
Yes.
No.
No.
No.
Local build.
No.
=> change default embedded etcd heartbeat to 300 and election timeout to 3000

CHANGELOG.md, api/core/v2/check.go
This commit fixes a bug where check pipelines aren't represented in event.check objects.
The full check configuration should be represented in events.
Yes
Yes
=> Add CheckConfig pipelines to Check on NewCheck

backend/apid/graphql/query.go, backend/apid/graphql/query_test.go, backend/apid/graphql/schema/query.gql.go, backend/apid/graphql/schema/query.graphql, backend/apid/graphql/suggest.go, backend/apid/graphql/suggest/resource.go, backend/apid/graphql/suggest/resource_test.go, graphql/generator/common.go, graphql/generator/kitchen-sink-schema/schema.graphql, graphql/generator/object.go
* Adds ability to use field & label selectors to further filter autosuggestion results beyond the existing fuzzy matching.
* To avoid monopolizing query execution, adds an aggressive deadline 
---
=> [GraphQL] Add filter option to autosuggestion API

CHANGELOG.md, system/cpu_arm.go
Correcting the detection of the arm version
At the present time the value retrieved for the arm version is invalid. Looking at some other code on internet ([here](https://gist.github.com/lucab/f7162ca2d95191c692edc12ea8ccaaef) or [here](https://github.com/creativeprojects/resticprofile/blob/master/arm.go) ) doing the same manipulation, it appears that the goarm needs to be define as a uint8.
Since int8/uint8 is not a valid type for protobuf exchange, the getARMVersion still return an int32. I'm just casting goarm to int32.
This is solving #4636
Yes and I updated the changelog
Nothing I can think off
Not really. I just realised that protobuf doesn't support int8/uint8 as a type so I had to refrain myself from updating the .proto file.
I don't think this change has any impact on the …
=> Correcting arm version

backend/apid/graphql/mock_test.go, backend/apid/graphql/node.go, backend/apid/graphql/node_test.go, backend/apid/graphql/util/api/api.go, backend/apid/graphql/util/api/api_test.go, backend/apid/graphql/util/api/logger.go, backend/apid/graphql/util/relay/logger.go, backend/apid/graphql/util/relay/node.go, backend/apid/graphql/util/relay/node_test.go
* Brings over the GraphQL util packages from enterprise and adds additional unit tests,
* Uses said packages to implement a node resolver for the Pipeline type.
* Switches some of the existing node resolvers over to using the newer machinery and adds more units tests 
Closes https://github.com/sensu/sensu-enterprise-go/issues/2114
---
=> Add node resolver for Pipeline resources 

CHANGELOG.md, backend/pipeline/handler/legacy.go, backend/pipeline/handler/legacy_test.go
This changelog fixes a panic in sensu-backend when a socket handler gets an error mid-write. It also fixes another bug where socket handlers will stop respecting their timeout after the initial connection is established.
Closes #4675 
Yes
It was tricky to reproduce the bug with a test but I eventually succeeded.
Docs changes not required.
Fully verified with automated testing.
Yes.
=> Fix a panic in socket handlers

backend/api/generic.go, backend/api/generic_test.go, backend/apid/graphql/interfaces.go, backend/apid/graphql/mock_test.go
Adds method to api package allowing the consumer to test if they are able to perform an action.
Required by https://github.com/sensu/sensu-enterprise-go/pull/2150.
Replaces https://github.com/sensu/sensu-go/pull/4666
---
=> [backend/api] Allow consumer to test if authorized to perform action

.circleci/config.yml, api/core/v2/metric_threshold_test.go, api/core/v3/go.sum, types/go.sum
Add CircleCI job to test core/v2 and types modules
No use in tests that aren't ran!
Probs not.
Would y'all prefer build.sh always run types and core/v2 unit tests? I'm on the fence. It'd probably mean no go module caching in CI for those modules. Also go 1.18 seems to have problems with the types tests (making running the types test suite locally if you've upgraded to 1.18 a hassle - have so far successfully avoided a goenv type tool)
CircleCI is a mystery.
N/A
CircleCI
N
=> Run tests for all modules

.github/workflows/static-check.yml
The github workflows syntax for branch filtering is odd (glob-y not regex-y) so filtering to `branches: *` does not match target branches with a slash in them like `develop/6`
See https://github.com/sensu/sensu-go/pull/4689 as an example of a PR where staticcheck was not ran due to this filter.
No
No
No
N/A
See above
N
=> Always Run Staticcheck workflow

.appveyor.yml
Updates the AppVeyor configuration so that it triggers on `develop/[0-9.]+` and
`release/[0-9.]+` branches.
=> Add develop/ and release/ to AppVeyor config

CHANGELOG-6.md, CHANGELOG-7.md, backend/backend.go, backend/eventd/eventd.go, backend/eventd/eventd_test.go, backend/keepalived/deregisterer.go, backend/keepalived/deregisterer_test.go, backend/keepalived/integration_test.go, backend/keepalived/keepalived.go, backend/keepalived/keepalived_test.go, backend/silenced/silenced.go, backend/silenced/silenced_test.go, backend/store/cache/cache.go, backend/store/etcd/store.go, testing/mockcache/mockcache.go, testing/mockclientv3/mockclientv3.go
Adds support for silencing deregistration events. This may be seen as a breaking change so I've target the `main` branch meaning this will be shipped with the first 7.x release.
Closes #4627.
Yes.
No documentation updates are required.
I reproduced the bug locally and confirmed the bug is fixed by confirming deregistration handlers are not fired when a subscription or check, matching the entity being registered, is silenced.
No.
=> Add support for silencing deregistration events

CHANGELOG-6.md, api/core/v3/resource.go, api/core/v3/resource_test.go, types/compat/compat.go, types/compat/compat_test.go, types/go.mod
Closes https://github.com/sensu/sensu-go/issues/4697
* Adds a GlobalResource interface that corev3 Resoruces
can optionally implement in order to indicate they are not namespaced.
* Also updates the V2ResourceProxy to honor the core/v2 behavior
of no-op SetNamespace implementations to indicate a resource
is global.
* Fixes some unit tests that were making poor assertions.
* Updates the types/compat package to check for GlobalResources.
This will enable global resources to be implemented using the core/v3.Resource interface.
Yes
I am a bit iffy on the effects of adding api/core/v3 to the replace block of types/go.mod.
Not really. May need a followup pr to bump the version number on the dependency from types on api/core/v3?
N/A
Using the enterprise SensuProvider api WIP.
Without this change …
=> Add core/v3 support for global resources

CHANGELOG-6.md
ac3387abab was merged with its changelog entry under the 6.7.1 release.
This moves it back to unreleased.
=> Fix Changelog Merge

.gitignore, api/core/v3/go.mod, api/core/v3/go.sum, go.mod, go.sum, types/go.mod, types/go.sum
Removes the [go.mod replace directives](https://go.dev/ref/mod#go-mod-file-replace) from sensu-go.
The current workflow for upgrading `sensu-go`'s (root module) dependencies on the `types`, `api/core/v2` and `api/core/v3` modules makes it difficult to validate that it has been done "correctly".
The replace directives mean that all sensu-go builds and tests will use the source of the replaced modules rather than the version indicated in the root go.mod. This means that we wouldn't know if we forgot to bump one of these dependency versions, and potentially end up with a downstream project being built with with incompatible sensu-go modules [MVS](https://go.dev/ref/mod#mvs). 
Instead, developers with go 1.18+ installed locally can develop …
=> Remove go.mod replace directives from sensu modules

.appveyor.yml, .circleci/config.yml, .github/workflows/static-check.yml, CHANGELOG-7.md, README.md, api/core/v2/go.mod, api/core/v3/go.mod, api/core/v3/go.sum, backend/schedulerd/check_scheduler_test.go, go.mod, go.sum, types/versions.go, types/versions_test.go, types/wrapper_test.go
Bumps the Go version to 1.18.1 and makes Go 1.18 the minimum version required to build the project.
We need Go 1.18 for Sensu 7.0.
Yes.
Only if we refer to the version of Go required to build Sensu. cc @hillaryfraley 
I confirmed that Sensu still builds.
No.
=> Bump Go version to 1.18.1

CHANGELOG-6.md, backend/ringv2/ringv2.go, backend/ringv2/ringv2_test.go, backend/schedulerd/roundrobin_interval.go
This pull request fixes the information printed indicating which round robin scheduler is used (etcd or postgres). The actual fix that implements active polling for PostgresConfig changes will be created in sensu-enterprise-go.
This is related to https://github.com/sensu/sensu-enterprise-go/issues/2113.
The information was not accurate, etcd was always printed instead of postgres.
Yes.
No
No.
Not required.
Yes.
=> Round Robin Postgres Scheduler

CHANGELOG-6.md, backend/backend.go, backend/cmd/start.go, backend/config.go, backend/etcd/etcd.go
Adds the `etcd-unsafe-no-fsync` backend configuration option ("disables fsync, unsafe, may cause data loss").
This makes it possible to run a sensu-backend with an embedded etcd node for testing and development without placing lots of load on the file system.
Local disk/storage may not perform well enough for etcd.
YES
No.
No.
No. Yes.
Tested on my local host. Will test on the SPDC.
Yes.
=> etcd-unsafe-no-fsync pass-through etcd option flag

backend/backend.go
The store was never assigned to the backend, and so non-dev mode is broken.
=> Fix an issue with non-dev event store

.circleci/config.yml
Using a larger circleci executor should cut our CI tests time nearly in
half from ~4 minutes to ~2.
If you look at our previous `run_the_tests` workflow durations in circleci, they hover around 4 minutes: https://app.circleci.com/pipelines/github/sensu/sensu-go?branch=main&filter=all
Every once in a while I end up needing to wait around for these tests to pass. This looks like it will cut down test time to the 2-2:30 minute range.
Can we afford such nice things?
=> CI: Use xlarge resource class Executor for Tests

backend/store/postgres/common_schema.go, backend/store/postgres/common_schema_test.go, backend/store/postgres/migrations.go, backend/store/postgres/schema_test.go
Adds a PostgreSQL procedure for setting the `updated_at` column to the current time when used with a trigger.
This is required for #4744 and any other ongoing work that will be using triggers to set `updated_at`.
No.
I added new tests to ensure that everything works.
No.
=> Add procedure for updating updated_at

.circleci/config.yml, CHANGELOG-7.md
It updates the Docker image & PostgreSQL version (from 9.5 to 9.6) that we use for testing in CI.
The `circleci/*` Docker images are deprecated and the new `cimg/postgres` Docker image does not support Postgres 9.5.
Yes; it is a breaking change as PostgreSQL >= 9.6 will be required for 7.0.
We may need to update the minimum version requirement for PostgreSQL if it is listed anywhere in the docs. cc @hillaryfraley 
CI functions. :)
No.
=> Update Postgres CI image

api/core/v3/namespace.go, api/core/v3/resource_generated.go, api/core/v3/resource_generated.tmpl, api/core/v3/resource_generated_test.go, api/core/v3/resource_generated_test.tmpl, api/core/v3/typemap.go, api/core/v3/typemap_test.go, api/core/v3/validation.go, backend/store/v2/etcdstore/store.go, backend/store/v2/etcdstore/store_test.go, backend/store/v2/interface.go, go.mod, go.sum
Closes https://github.com/sensu/sensu-go/issues/4764
Closes https://github.com/sensu/sensu-go/issues/4771
* Adds a corev3 namespace type - like the regular core/v2 one but with the standard Metadata field.
* Adds namespace-specific store methods
* Implements an "index" as described in https://github.com/sensu/sensu-go/issues/4771 in store/v2 in order to keep track of whether a namespace is empty or not.
=> Add corev3 namespace and store methods

CHANGELOG-6.md, agent/agent.go, agent/check_handler.go, agent/check_handler_internal_test.go
Adds a new map of check keys -> issued timestamps that is used to determine if received check requests are older than or duplicates of the last executed check request.
Sensu backends currently send a check request to all matching subscriptions. If an agent and check have multiple matching subscriptions then the agent will receive the check request for every matching subscription. This can result in one of two undesirable behaviours:
1. If one of the check requests are still being executed when another is received it will result in the `check execution still in progress` error being logged.
2. If the check requests are executed quickly enough to avoid the `check execution still in progress` error then check history & features that rely on it (e.g. flap detection) may behave strangely.
Yes. …
=> Prevent executing old or duplicate check requests

api/core/v2/compat.go
StoreName is supposed to return an invariant string, not a computed one.
=> Use static strings for StoreName() in compat.go

api/core/v2/compat.go, backend/authorization/rbac/rbac.go, backend/authorization/rbac/rbac_test.go, backend/store/v2/interface.go, backend/store/v2/proxy.go, backend/store/v2/storetest/mock.go, testing/mockstore/v2.go
You must use go.work in order for this to work, core/v2 isn't tagged yet
=> Use only storev2 for rbac package

backend/agentd/agentd.go, backend/agentd/agentd_test.go, backend/agentd/middlewares.go, backend/agentd/session.go, backend/agentd/session_test.go, backend/agentd/watcher.go, backend/agentd/watcher_test.go, backend/api/entity.go, backend/api/generic.go, backend/api/namespace.go, backend/backend.go, backend/store/cache/v2/cache.go, backend/store/cache/v2/cache_integration_test.go, backend/store/cache/v2/cache_test.go
Moves agentd to the store/v2 package.
Updates the backend/store/cache/v2 package to remove dependency on etcd.
Migrates agentd to store/v2 by:
* Moving from cache to cache/v2 package
* Adding Config for HealthRouter instead of constructing it on creation to match apid and remove etcd dep.
* Using new storev2 WatchEvent
* Adding Config/dependency for an Authenticator to matche apid and remove dependency on UserStore.
* Updates usage of the store/v2 interface in session.go to use new calling convention (ctx, req).
* Update some backend/api package compile errors for now store/v2 interface calling conventions.
Haha, don't want to @ you to disrupt your rest. I suspect my changes to cache/v2 may step on your toes if you've already made some progress on the schedulerd task. I hope we've taken …
=> Move agentd to storev2

backend/store/postgres/counter_integration_test.go, backend/store/postgres/counter_test.go, backend/store/postgres/entity_configs_schema.go, backend/store/postgres/entity_store.go, backend/store/postgres/storev2_test.go, backend/store/postgres/watcher.go
Follow up to https://github.com/sensu/sensu-go/issues/4738
* Adds the polling implementation for the EntityConfig table
* Disables the counter integration test by default now that a real implementation is present. Was not sure what to do about that one, could be convinced to delete it, but it does the best job of simulating multiple random writers - a worst case for our polling implementation.
=> Postgres entityconfig watcher

backend/store/v2/generic.go, backend/store/v2/generic_test.go, types/wrapper.go
The Generic store sits on top of any store/v2.Interface implementation
and provides a type-safe API for dealing with corev3.Resource CRUD,
while allowing the user to avoid dealing with the storev2.Wrapper
abstraction.
=> Add Generic store

.appveyor.yml, .circleci/config.yml, CHANGELOG-6.md
Mitigates several CVEs. https://github.com/golang/go/issues?q=milestone%3AGo1.17.12+label%3ACherryPickApproved for details.
=> Upgrade Go to 1.17.12

backend/backend.go, backend/tessend/tessend.go, backend/tessend/tessend_test.go
Closes https://github.com/sensu/sensu-go/issues/4763
Updates access to the TessenConfig resource to use the store/v2 interface.
**DOES NOT** remove all store package dependencies or completely prepare tessend for sensu 7.0.
Tessend is responsible for both collecting and transmitting telemetry data. Much of the collection assumes etcd is in use and is the only data store. This all will need refactored moving forward, but may be a larger issue than #4763.
No - I imagine we should include this in a mega changelog entry on merge of the integration branch back to main?
N
The GetClusterID replacement in a postgres-only sensu has yet to be decided on. I just rearranged around it be requiring ClusterID in the tessend Config.
=> Move tessend to store/v2

api/core/v3/validation.go
#4766 added a corev3 utility for validating ObjectMeta for global resources. This backports the relevant part of that change, as I want to use it in https://github.com/sensu/sensu-enterprise-go/pull/2386
Without a api/core/v3 function for this, it will need duplicated by the enterprise version's code generation scripts.
Alternatively we could just copy+paste, like I've done here: https://github.com/sensu/sensu-enterprise-go/pull/2386/files#diff-8f69bc9581a1a0baf76dbe3e61271df802806a13792c710e2d45a10da84ba691R48
=> Backport addition of corev3.ValidateGlobalMetadata

CHANGELOG-6.md, backend/etcd/id.go, backend/etcd/id_test.go
Closes https://github.com/sensu/sensu-go/issues/4812
It looks like we intend to have retry logic in the BackendIDGetter's getLease function, but in practice it currently never retries. 
In a large environment we noticed that when the etcd cluster is overwhelmed, this tends to be a weak spot for sensu-go, triggering a restart due to an "etcdserver: too many requests" error returned from an etcd client. We intentionally include retry logic for this case in most of our store access logic, and should be consistent here.
Yes
N
N. Although I've found our retry util very difficult to reason about and easy to use incorrectly, as it appears was the case here.
N/A
Unit tests
N
=> Retry Etcd Requests in BackendIDGetter

CHANGELOG-6.md, backend/agentd/session.go, backend/eventd/eventd.go, backend/eventd/eventd_test.go, backend/keepalived/integration_test.go, backend/keepalived/keepalived.go
Closes https://github.com/sensu/sensu-go/issues/4813
Changes the flow of keepalive events from keepalived to eventd. Currently keepalive and other events are mixed together in the same topic going into eventd, so are handled at the same priority. This change uses the (until now) unused wizard bus topic "sensu:keepalive-raw" as a higher-priority topic between keepalived and eventd, allowing eventd to process time sensitive keepalive events ahead of regular events.
Keepalive events are time sensitive. Under high event load today, keepalives can fall behind and cause a keepalive storm where the events are being generated faster than they can be processed. In order to mitigate this, we should prioritize the handling of keepalive events in eventd.
Yes
I could use a second set of eyes on the …
=> Route Keepalive Events to Eventd with High Priority

CHANGELOG-6.md, backend/apid/apid.go, backend/apid/middlewares/awaitstartup.go, backend/apid/routers/ready.go, backend/backend.go, backend/cmd/start.go, backend/config.go
https://github.com/sensu/sensu-go/issues/4826
https://github.com/sensu/sensu-go/issues/4827
* Adds a `--api-serve-wait-time` flag to the backend to delay serving apid traffic.
* Adds a `/ready` API endpoint.
Sensu-go backends can be delicate during initial startup in high traffic environments. This allows users to configure a delay after startup before apid will serve API traffic.
Y
N
N
Big time.
This introduces a new readiness API endpoint and a new backend configuration option. @hillaryfraley 
Manual
Not unless it needs to be.
=> Adds API Serve Wait Time Backend Configuration

types/wrapper.go
Bypasses semverGreater by setting `foundVer = reqVer` when `foundVer` equals `(devel)`.
Cannot start sensu-backend when using Go workspaces.
No.
No documentation is required.
Sensu backend now starts when using a Go workspace.
No.
=> Bypass semverGreater when Go module version is (devel)

.circleci/config.yml
Replace directives can be useful when we need to fork
our own version of a dependency but do not wish to edit
all import paths.
=> Remove CI constraint forbiding go.mod replace

api/core/v3/internal/codegen/check_protoc/main.go, api/core/v3/resource_generated.go, api/core/v3/resource_generated_test.go, api/core/v3/symmetric_key.go, api/core/v3/typemap.go, api/core/v3/typemap_test.go, backend/api/authentication_test.go, backend/api/jwt.go, backend/api/jwt_test.go, backend/apid/apid.go, backend/apid/routers/authentication.go, backend/apid/routers/authentication_test.go, backend/authentication/jwt/jwt.go, backend/authentication/providers/basic/basic.go, backend/authentication/providers/basic/basic_test.go, backend/backend.go, backend/init.go
Removes store authentication dependencies and instead offers some new APIs built on top of store/v2.
=> Migrate authentication machinery to store/v2

CHANGELOG-6.md, backend/agentd/agentd.go, backend/agentd/agentd_test.go, backend/agentd/middlewares.go, backend/backend.go, backend/cmd/start.go, backend/config.go
Closes https://github.com/sensu/sensu-go/issues/4825
https://github.com/sensu/sensu-go/issues/4827
* Adds a `--agent-serve-wait-time` flag to the backend to delay serving agent traffic.
* Adds a `/ready` API endpoint to agent listener
Sensu-go backends can be delicate during initial startup in high traffic environments. This allows users to configure a delay after startup before agentd will accept agent traffic.
Y
N
N
Big time.
This introduces a new readiness API endpoint and a new backend configuration option. @hillaryfraley 
Manual
Not unless it needs to be.
=> Adds agent-serve-wait-time backend configuration

cmd/loadit/main.go
Adds a loadit flag for `--deregister` in order to help performance test issues with keepalives.
=> add deregister flag to loadit

backend/pipeline/adapter.go, backend/pipeline/adapterv1.go, backend/pipeline/adapterv1_test.go, backend/pipelined/pipelined.go
Closes https://github.com/sensu/sensu-enterprise-go/issues/2323
Makes logging adjustments for situations where an event processing pipeline can't be ran due to its configuration.
**Fixes misleading log messages**
Before either of these two situations resulted in a log line like this `pipeline has no workflows, skipping execution of pipeline`:
* (The obvious) An event references a pipeline for which no workflows are configured
* (The misleading) An event has handlers specified, but none of the handlers exist.
Now the log message is specific to the later situation: `legacy pipeline found no existing handlers: none of [handlerDNE] exist, skipping execution of pipeline`.
**Adjusts log levels**
Previously this log was emitted at a Warning level. I felt it was better at Info as there isn't …
=> Update logging for unrunable pipelines

CHANGELOG-7.md, backend/pipeline/filter/legacy.go, backend/pipeline/filter/legacy_test.go
This makes it so multi-expression "Deny" filters are correctly evaluated: their
expressions are OR'd together to decide whether to filter or not.
Closes https://github.com/sensu/sensu-enterprise-go/issues/2351
Yes, added.
No.
We were not 100% sure if this was a regression or not. It turned out to be
(introduced in 6.5).
No documentation change is required: this changes makes the behavior line up
with the documentation.
- Relevant unit tests
- Manual testing as described in https://github.com/sensu/sensu-enterprise-go/issues/2351
Yes, it needs to also be backported to `develop/6`
=> Fix multi-expression "Deny" filters

CHANGELOG-6.md, api/core/v2/time_window.go, api/core/v2/time_window_test.go
Closes https://github.com/sensu/sensu-go/issues/4847
Changes the evaluation of check subdues to be inclusive of the begin time and up to (but excluding) one second **past** the end time.
With this change subdues are a little more intuitive to use. The example straight from our docs to subdue a check all weekend currently has a second long gap (Sat night between 23:59:59 and Sun morning 00:00:00.0001.) By making the begin time inclusive and the end time + 1 second exclusive there is no longer a potential gap.
```
- begin: "2022-04-23T00:00:00-07:00"
end: "2022-04-23T23:59:59-07:00"
repeat:
- weekends
```
Alternately, users can bypass this issue today by setting the end time 2 seconds later (in this case overlapping into the next day) to …
=> Update Check Subdues to allow for overlapping intervals

CHANGELOG-6.md, agent/agent.go, backend/agentd/agentd.go, backend/backend.go
Closes https://github.com/sensu/sensu-enterprise-go/issues/2270
Adds a backend-id header to the agent ws upgrade response and log it on the agent side.
It can be difficult to debug issues that appear to only affect specific backends. Logging more backend connection info on the agent side may assist users in identifying problem backends.
Y
N
N
N/A
N
=> Include Backend Name with Agent WS Connection

backend/keepalived/keepalived.go
This commit modifies how keepalived startup works, so that when lease errors are encountered, sensu-backend does not crash.
=> Keepalived lease errors on startup no longer fatal

go.mod, go.sum
We've landed ourselves in a state. develop/6 currently does not build since the api/core/v3 dependency is pointing at a squashed commit.
This updates the dep to a commit that is not likely to ever be squished (the current develop/6 HEAD), but I believe we should follow up with merging the core/v3 changes into main and publishing a new v3.x tag for it to point at before a release.
=> Temporarily Fix the api/core/v3 dependency

CHANGELOG-6.md, backend/keepalived/keepalived.go, backend/keepalived/keepalived_test.go
Partial solution for https://github.com/sensu/sensu-enterprise-go/issues/2373
Closes: https://github.com/sensu/sensu-go/issues/4828
Instead of calling keepalived's initFromStore function to reconstruct failing keepalive switchset state in a blocking manner on backend startup, start it as a background goroutine and spread out the load across the default keepalive warning timeout of 120 seconds.
When many failing keepalives are present in an environment, this approach can put a heavy load on the etcd database immediately, and tends to flood the pipeline with keepalive events when they expire at the same time later.
Y
N
N
N/A
Performed a series of performance test comparing this strategy to the existing as well as others: https://docs.google.com/document/d/1s3xiZ4Dd_8UVZjUzpGGgjuH5aOfZu5dU1ke …
=> Background keepalive reconstruction

CHANGELOG-6.md, agent/agent.go, agent/check_handler.go, go.mod, go.sum
Closes https://github.com/sensu/sensu-enterprise-go/issues/2453
Updates agent log messages to include check name for errors preventing a check from being executed (duplicate and old requests, in progress check executions)
A followup to https://github.com/sensu/sensu-go/pull/4773
When multiple subscriptions configured on a check target an entity it can result in many duplicate check execution requests that can be difficult to find. Including check name should help operators identify misconfigured checks.
Y
N
N
N/A
Manual
```
{"check":"check-1","component":"agent","error":"check request has already been received - agent and check may have multiple matching subscriptions","level":"warning","msg":"error handling message","time":"2022-09-26T17:04:13-07:00"}
```
Y
=> Agent logs dup check name

CHANGELOG-6.md, backend/authentication/authenticator.go
*This change also needs to be ported to `main`*
An INFO level message is emitted upon successful login, with details about the
user and provider used. An ERROR level message is emitted upon authentication
failure, with the username that was tried.
Closes https://github.com/sensu/sensu-enterprise-go/issues/248
Yes, added.
No.
Manual testing with 2 providers and successful and unsuccessful logins.
=> Enhance logging for authentication providers

CHANGELOG-6.md, agent/cmd/install_windows.go
Updates the Windows service for Sensu Agent to auto-restart every 5 seconds after a failure.
Closes https://github.com/sensu/sensu-enterprise-go/issues/1575.
Yes.
I couldn't find a way of triggering a failure state in Sensu Agent to fully test this.
We may want to describe this behaviour in the docs; what do you think @hillaryfraley?
I can see the failure cases set in the service after this change.
No.
=> Auto-restart agent service on Windows

backend/store/postgres/config_store.go, backend/store/v2/generic.go, backend/store/v2/generic_test.go, backend/store/v2/interface.go
By supplying special methods that are checked at runtime, the generic store can make use of specialized store implementations for certain types.
=> Support specialized stores in the generic store

CHANGELOG-6.md, agent/transformers/graphite.go, agent/transformers/graphite_test.go
Graphite has support for storing data in tags to identify series of metrics. This change introduces support for this feature in the graphite text protocol. Presently the agent ingests
`my.series;tag1=value1 1 999999999` as a metric point with name "my.series;tag1=value1". Per the graphite spec this will now be ingested as a metric point with name "my.series" and a tag for ("tag1": "value1")
Closes https://github.com/sensu/sensu-go/issues/4677
=> Agent ingests graphite plaintext metric tags

graphql/service.go
We've got a graphql middlewares framework, but the Init functions currently do not have any side effects on the context used to service operations, despite their interface suggesting that it should:
> 	// Init is called at the beginning of an execution. Helpful for initializing
// anything used during the execution of the query.
Init(context.Context, *graphql.Params) context.Context
This changes that behavior.
Related to https://github.com/sensu/sensu-enterprise-go/issues/2558
Per a recently uncovered UI bug, it is helpful to scope some context variables to graphql operation (instead of http request scoped.) This will allow us to register graphql middlewares that enrich the context used throughout the request.
N
N
This was the complication.
N/A
TBD/Manual
Y
=> Allow Graphql Middleware Init funcs to add to Context

backend/store/postgres/config_schema.go, backend/store/postgres/config_store.go, backend/store/postgres/config_store_test.go, backend/store/postgres/entity_config_store.go, backend/store/postgres/entity_config_store_test.go, backend/store/postgres/entity_configs_schema.go, backend/store/postgres/entity_state_store.go, backend/store/postgres/entity_state_store_test.go, backend/store/postgres/entity_states_schema.go, backend/store/postgres/namespace_store.go, backend/store/postgres/namespace_store_test.go, backend/store/postgres/namespaces_schema.go, backend/store/v2/etcdstore/entity_config_store.go, backend/store/v2/etcdstore/entity_state_store.go, backend/store/v2/etcdstore/namespace_store.go, backend/store/v2/etcdstore/store.go, backend/store/v2/generic.go, backend/store/v2/generic_test.go, backend/store/v2/interface.go, backend/store/v2/proxy.go, backend/store/v2/storetest/entity_config_store.go, backend/store/v2/storetest/entity_state_store.go, backend/store/v2/storetest/mock.go, backend/store/v2/storetest/namespace_store.go, testing/mockstore/v2.go
Closes https://github.com/sensu/sensu-go/issues/4899
Adds Count Methods to Stores, largely mimicking their existing List behavior.
* Dropped the SelectionPredicate argument for Count, as ordering and pagination are not very useful in the context of generating a count.
* EntityConfigStore's Count method includes filtering for both namespace AND entity class.
=> Add Count Methods to Stores

backend/agentd/agentd.go, backend/agentd/session.go, backend/agentd/session_test.go, backend/store/v2/watcher.go
With the introduction of the OPC system, burial events are no longer needed in agentd. Additionally, an error where entity change events are not recognized properly by agentd has been resolved.
=> Fix API-managed entities, remove burial event concept

backend/agentd/agentd.go, backend/agentd/session_test.go, backend/eventd/eventd.go, backend/eventd/opc.go, backend/store/opc.go, backend/store/postgres/opc.go, backend/store/postgres/opc_schema.go, backend/store/postgres/opc_test.go, backend/store/v2/watcher.go
This commit makes check TTL work with the new OPC system. Each check that specifies the TTL field will have an entry stored in the OPC table for each agent entity that executes the check.
A new OPC monitoring option has been added to the
MonitorOperatorsRequest struct, which allows selecting all of the grandchildren of the requested controller operator instead of the children.
=> Make check TTL work again

backend/poll/polling.go, backend/store/postgres/store.go, backend/store/v2/generic.go, backend/store/v2/generic_test.go
Adds a Watch function to the generic store. Also fixes some watch poller bugs.
This turned out to be necessary for resource replicators in the enterprise product.
=> Generic Store Watch

CHANGELOG-6.md, agent/agent.go, agent/cmd/start.go, agent/config.go, backend/backend.go, backend/resource/backend.go, cli/cmdmanager/manager.go, system/system.go, system/system_test.go
Disable sending network information from sensu-agent to sensu-backend when a flag is passed to the agent
Solving #4787
Yes
No
No, I think it was easy to implement.
By default it will still add the information, the only behaviour change will be when the flag will be set. 
Documentation has been updated and [a pull request](https://github.com/sensu/sensu-docs/pull/4162) was created
I run the automated test.
In addition to this I build the sensu-agent binary for x86-64 linux & arm7 linux. I tested them against and up to date sensu-go-backend (6.9.1).
I performed 3 different tests (between each tests agents were removed from the backend):
- Start the agent without the flag to observe that network information were still retrieved (and visible in the sensu-go webui)
- Start the agent with the …
=> Strip network agent entity state

CONTRIBUTING.md
Now that sensu has migrated away from the github.com/sensu/sensu-go/core/* modules, update the CONTRIBUTING.md to reflect that.
I don't think that we really need to say anything about developing multiple modules at once. Now that there are no longer multiple modules in development in the sensu-go repo, it should work just like any other go project.
=> Update CONTRIBUTING.md for Core Migration

backend/apid/apid.go, backend/backend.go, backend/cmd/start.go, backend/config.go, backend/opc.go, backend/queue/queue.go, backend/schedulerd/adhoc_scheduler.go, backend/schedulerd/check_scheduler_test.go, backend/schedulerd/executor.go, backend/schedulerd/schedulerd.go, backend/schedulerd/schedulerd_test.go, backend/store/opc.go, backend/store/postgres/opc.go, backend/store/postgres/opc_schema.go, backend/store/postgres/opc_schema_test.go, backend/store/postgres/opc_test.go, testing/mockqueue/queue.go, testing/mockstore/opc.go
Reimplements ad hoc check scheduling.
Adds a ListOperators function to the OperatorQueryer Interface.
Adds a new backend configuration flag `--name` to allow us to override the hostname as a backend identifier.
Completes the queue.ClusteredQueue using the ListOperators interface.
Adds ad hoc scheduling back to schedulerd.
=> Enable ad hoc checks

backend/schedulerd/schedulerd.go
Prevent the backend from crashing when a round robin check is created.
=> disable round robin check scheduling

CHANGELOG-6.md, backend/apid/graphql/namespace.go, backend/apid/graphql/schema/silenced.gql.go, backend/apid/graphql/schema/silenced.graphql, go.mod, go.sum
Signed-off-by: Gustav Danielsson <gdanielsson@sumologic.com>
Wires up `SortSilencedByExpireAt` from sensu/core/v2 to provide silences sorting by expiration ascending and descending.
Related to https://github.com/sensu/sensu-go/issues/4159
Updated
=> Silences expiration sort

backend/store/postgres/sync.go, backend/store/postgres/sync_test.go, backend/store/sync.go
Adds a store-based Mutex and synchronized executor.
https://www.postgresql.org/docs/15/explicit-locking.html#ADVISORY-LOCKS
=> Add store based synchronization.

backend/apid/actions/health.go, backend/apid/actions/tessen.go, backend/apid/actions/version.go, go.mod
A low priority depen**d**abot ale**r**t https://github.com/sensu/sensu-go/security/dependabot/18 f**o**r the golang.org/x/net module has been **p**ublished. Rather than bumping to a patched version, we have the opportunity to drop the (direct) dependency on the module.
It **st**ill ends up being **a**n indirec**t** dependency, due to an older go**s**tatsd depen**d**ency.
=> Replace golang.org/x/net/context usage with stdlib

backend/queue/testspec/client.go, backend/store/postgres/sync_test.go
* Queue testspec: Expect queue.Reserve to return error wrapping context error on timeout instead of exact match.
* Queue testspec: don't panic in test on reserve error.
* TestSynchronizedExecutor: Adapt test to not rely on predictable goroutine scheduling.
=> Fix known issues in flapping integration tests

CHANGELOG-6.md, backend/apid/routers/graphql.go, graphql/service.go, graphql/validators.go, graphql/validators_test.go
This adds a GraphQL validator to limit max query depth. The validator is run on queries from un-authed requests
Logic inspired by:
- https://github.com/cungminh2710/graphql-depth-limiter (JS library for `graphql-js`, which is the basis for our `graphql-go`)
- https://github.com/graph-gophers/graphql-go/blob/master/internal/validation/validation.go (another GraphQL library in Go that has a max-depth validation built-in)
The query depth limit doesn't break un-authorized GraphQL queries we use which are listed here https://github.com/sensu/sensu-enterprise-go/issues/1952#issuecomment-1209485803
Relates to https://github.com/sensu/sensu-enterprise-go/issues/1952
Updated
Added tests. Also manually testing with a Web-UI and running queries with curl.
=> GraphQL service max query depth

backend/backend.go, backend/eventd/eventd.go, backend/eventd/opc.go, backend/keepalived/keepalived.go
Fix a bug where os.Hostname was used as the backend name in keepalived and eventd. This breaks keepalives and check TTLs when a backend name is configured in the backend config file. The backend name is now correctly passed through to these daemons.
=> Don't use os.Hostname in daemons

CHANGELOG-6.md, backend/backend.go, backend/cmd/start.go, backend/config.go, backend/etcd/etcd.go, backend/etcd/zap_time.go
The log-millisecond-timestamps configuration allows users to configure a sensu backend to use RFC3339 formatted timestamp strings with millisecond precision in its backend logs.
Closes https://github.com/sensu/sensu-enterprise-go/issues/2518
Y
N
N
Yes! New configuration flag.
`./sensu-backend start -c <base config path> --log-millisecond-timestamps --log-level debug |& jq .time`
N
=> Add log-millisecond-timestamps backend configuration flag

.gitignore, backend/backend.go, backend/licensing/getter.go, backend/store/postgres/ring.go, backend/store/postgres/silences_store.go, backend/store/proxy.go, backend/store/v2/interface.go, backend/tessend/data.go, backend/tessend/tessend.go
This updates `tessend` to make it not use etcd at all.
7.x work to get rid of etcd
I think it's already covered under the entry that says that etcd is not used/supported anymore in 7.x.
So not adding an entry.
There is still a TODO related to figuring out the number of backends in the cluster. I'm not sure what is the current best way to go about retrieving or figuring out this information. I thought I might be able to leverage the new OPC work, but it's not clear I can after all.
Many pieces of `tessend` were hardcoded to read/write keys in etcd, and many other moving pieces were necessary to complete this work (new store counting and watching methods, ...).
No documentation update needed: the user facing interface that lets one enable/disable `tessend` is not changing. This change is …
=> Update tessend to not use etcd

backend/keepalived/keepalived.go, backend/store/postgres/migrations.go
This change adds indices to the opc table and also relaxes the keepalive monitoring loop so that it is only every 10 seconds.
=> Make keepalive monitor less CPU intensive

backend/store/postgres/event_store.go
=> Remove debugging panic

cmd/loadit/main.go
Allows us to extend the default handshake timeout between agents and backends. Hopefully reduces timeouts.
Sensu 7.0 is (so far) more sensitive to mass herds of agents connecting to a backend. In addition to tuning backends to use appropriate agent connection rate limiting, extending the handshake timeout to 45s (the default suggested by our websocket library) should result in fewer client connection timeouts.
=> Loadit backend handshake timeout

backend/store/postgres/entity_config_store_test.go, backend/store/postgres/entity_configs_schema.go, backend/store/postgres/entity_store.go, backend/store/postgres/entity_store_test.go
* Fixes the EntityStore's DeleteEntityByName method, previously untested
and broken.
* Fixes the EntityConfigStore's GetEntities method which had been
returning soft deleted entities.
=> Fix consistency errors when deleting entities

graphql/service.go, graphql/validators.go
Changes GraphQL service to run query depth limit validation on all requests (previously running just for un-authenticated requests). Ups the depth limit as our Web UI requires deeper queries. The default limit is about double what the Web UI needs – one could conceive of queries in GraphIQL that exceed this limit. 
Also introduces notion of mandatory GraphQL validation that can't be skipped with a parameter. The depth limit validation doesn't conflict with the reason for allowing validation to be skipped outlined here https://github.com/sensu/sensu-go/pull/3379 
In the future, we could group built-in GraphQL validators into skippable and not https://pkg.go.dev/github.com/graphql-go/graphql#SpecifiedRules. However, changes to federation in future Sensu versions could make this unnecessary …
=> GraphQL authenticated query depth limit

backend/keepalived/keepalived.go
Not totally sure what was going on here. It appears that there is a redundant CheckIn operation in handleUpdate. Stats from the performance testing cluster's postgres instance show that it is spending more time executing this statement than any others at baseline (many agents connected, but not processing significant event load.) This should cut that baseline in half 😄, although I suspect it will still be at or near the top.
First CheckIn immediately preceding calling handleUpdate: https://github.com/sensu/sensu-go/blob/main/backend/keepalived/keepalived.go#L283-L317
=> remove redundant OPC CheckIn

backend/store/postgres/entity_config_store_test.go, backend/store/postgres/poller_test.go, backend/store/postgres/test_helpers.go
The entity config poller test isn't working well in CI, and I suspect the reason is resource constraints that do not play well with the time sensitive nature of the test as written (ex: [this ](https://github.com/sensu/sensu-go/blob/3cd917904ddd81d639f4dd66821b34ecb3e8c21f/backend/store/postgres/poller_test.go#L107-L108) delay is meant to give the poller time to catch up and deliver any events after the final change occurs, but picking a duration for that delay becomes a difficult balancing act). This should cover most of the code paths as before while being much less sensitive to goroutine scheduling and postgres responsiveness.
=> rewrite TestEntityConfigPoller test

CHANGELOG-7.md, asset/filtered_manager.go, asset/filtered_manager_test.go
Updates `asset.FilteredManager` to evaluate all asset build filters and returns the asset build with the most specific (highest number of filters) matching the entity. This is a breaking change as it can alter which asset build is installed on existing clusters.
Closes https://github.com/sensu/sensu-go/issues/3655
Closes https://github.com/sensu/sensu-go/issues/4455
Yes.
No.
No.
The docs should be updated to describe this behaviour.
https://github.com/sensu/sensu-docs/issues/4185
I used TDD to define the behaviour before I made the change. The tests should be sufficient.
No.
=> Use asset build with most specific filters

backend/apid/actions/users.go, backend/apid/actions/users_test.go
Fixes bug in the UserController where it was not forwarding the SelectionPredicate to the store implementation. Broke user api pagination.
=> Pass predicate through UserController to store

go.mod, go.sum, graphql/service.go
Bumps graphql-go to v0.8.1.
See https://github.com/sensu/sensu-enterprise-go/pull/2665.
No, added to the changelog in the enterprise repository.
No.
=> Bump graphql-go to v0.8.1

backend/eventd/entity.go
Eventd creates proxy entities when they are contained in an event but do not already exist. Avoid a SQL NOT NULL constraint by creating the entity config before entity state.
Found in staging from this log line
```
{
"check_name": "proxy-check",
"check_namespace": "default",
"component": "eventd",
"entity_name": "staging-agent-0-managed-entity",
"entity_namespace": "default",
"error": "internal error: ERROR: null value in column \"entity_config_id\" violates not-null constraint (SQLSTATE 23502)",
"event_id": "2cc79025-b6ed-403b-ae4a-b8e858300ce8",
"level": "error",
"msg": "error handling event from event channel",
"time": "2023-04-24T22:51:54Z"
}
```
=> Reorder proxy entity state and config creation

backend/store/v2/context.go, backend/store/v2/context_test.go, backend/store/v2/interface.go
This commit adds some utility functions for putting ETag directives into store requests, and also a way for stores to write back transaction metadata with TxInfo.
These functions are going to be used by the postgres store, as well as apid, to provide end-to-end support for the HTTP ETag, If-Match, and If-None-Match headers.
=> Add context helpers for TxInfo and ETag directives

backend/store/postgres/config_schema.go, backend/store/postgres/config_store_test.go, backend/store/postgres/migrations.go, backend/store/postgres/store.go, backend/store/store.go, backend/store/v2/context_test.go, backend/store/v2/interface.go, backend/store/v2/wrap/wrapper.go, backend/store/v2/wrap/wrapper_test.go
This commit adds support for store preconditions and etags. Store users can request IfMatch and IfNoneMatch by way of context value. Resources returned by the store now encode a base64-encoded ETag in their annotations.
It's also possible to detect the side effects a given store method had, by providing a TxInfo object to the method, also via context value. The store will write into TxInfo whether the object has been created, updated, or deleted.
=> Add support for etag and preconditions to store

CHANGELOG-6.md, backend/api/authentication.go, backend/api/authentication_test.go, backend/apid/routers/authentication.go, backend/apid/routers/authentication_test.go, backend/authentication/authenticator.go, backend/authentication/jwt/jwt.go, backend/authentication/jwt/jwt_test.go, backend/store/etcd/session.go, backend/store/etcd/session_test.go, backend/store/proxy.go, backend/store/store.go, go.mod, go.sum, testing/mockstore/session.go
- Add refresh token rotation, to reduce the impact of stolen refresh tokens
- Add a session store, used to detect and prevent refresh token reuse
- Use a new `SessionID` custom claim in the JWTs
- The session store allows for server side "refresh JWT invalidation"
Fix and mitigate https://github.com/sensu/sensu-enterprise-go/issues/2605
Added.
No new documentation needed.
- Unit and integration tests
- Manual testing
No.
=> JWT Authentication Rework

CHANGELOG-6.md, backend/pipeline/handler/legacy.go
When a handler returns an error (i.e. a non-zero return value) log the error at the error level instead of info.
Helps customers troubleshoot handler errors since they typically use the error log level by default. It prevents them from having to change the log level and restart the backend.
Added.
There was no error returned in case of handler so I left the behavior as is.
No.
No.
=> Log handler error at error level instead of info level

CHANGELOG-7.md, backend/pipeline/handler/legacy.go
When a handler returns an error (i.e. a non-zero return value) log the error at the error level instead of info.
Helps customers troubleshoot handler errors since they typically use the error log level by default. It prevents them from having to change the log level and restart the backend.
Added.
There was no error returned in case of handler so I left the behavior as is.
PR for 7.0/main.
No.
No.
=> Log handler errors at error level instead of info level

.circleci/config.yml, ci/install-go.ps1
CI tests on Windows are broken due to restoring Go from cache overtop of the built-in Go installation. To quickly remediate this I've removed the caching of Go installations and added caching of the Go installer. Caching the Go installer vs no cache improves build times by approximately 4 minutes.
=> Remove Go installation cache, cache Go installer instead

backend/apid/routers/checks_test.go, go.mod, go.sum
Bump github.com/sensu/core/v2 to v2.20.0-alpha1 in order to include changes needed to register core/v2.AdhocRequest as a resource.
Closes https://github.com/sensu/sensu-go/issues/5023
=> Fix the adhoc check execute api

CHANGELOG-6.md, agent/transformers/influx_db.go, agent/transformers/influx_db_test.go
#5030 Implementation.
Here is also #5030 as shown.
Yes. Added.
This is an extension of the existing InfluxDB Line format, so it is marked as Added instead of Changed.
No. I do not think there is any need for this.
Tested with Mimir 2.9.0 and InfluxDB 2.7.1.
Both confirm that the metrics are stored correctly.
<details>
<summary>spoilers</summary>
- CheckConfig
```yaml
---
type: CheckConfig
metadata:
name: output_metrics_as_influxdb_line
spec:
command: |
cat << 'EOS'
test_metrics1,test_tag1=foo,test_tag2=bar value=1
test_metrics2,test_tag1=ho\ ge,test_tag2=hu\,ga,test_tag3=hi\=ge,test_tag4=ha"ge value=1
EOS
output_metric_format: influxdb_line
output_metric_handlers:
- mimir
- influxdb
subscriptions:
- test
interval: 15
publish: true
```
- Handlers
```yaml
---
type: …
```
=> Add support escape special characters in InfluxDB Line (for 6.x)

CHANGELOG-7.md, agent/check_handler.go, agent/check_handler_internal_test.go
This PR adds annotations to the event even if the threshold check is normal.
In addition, the format is changed so that the min-max range can be output in a single annotation.
See #4987
Adding the threshold annotation when normal will allow to ensure that the thresholds are normal when notifying some communication platform of the Event.
This change also makes it easier to ensure that the threshold checks are working correctly.
Yes, required as **Added** and **Changed**.
This PR is for Sensu Go 7.0 (main branch).
This section [Add event annotations based on metric threshold evaluation](https://docs.sensu.io/sensu-go/6.9/observability-pipeline/observe-schedule/metrics/#add-event-annotations-based-on-metric-threshold-evaluation) may need to be rewritten.
But there is no documentation for 7.0 …
=> Improvement threshold annotations format (for 7.x)

backend/apid/graphql/corev3.go, backend/apid/graphql/globalid/components.go, backend/apid/graphql/health.go, backend/secrets/provider_test.go, backend/store/postgres/entity_store.go, testing/mockpipeline/filter.go
This mostly fixes some places where the name of the function in the comment didn't match its definition.
Background: I'm doing a research study on function comments that may be incorrect. You can find more info and a short and optional anonymous survey [here](https://forms.office.com/e/yHv4PRXM2i).
 
Thanks for reviewing!
=> Fix small mistakes in function doc comments

.circleci/config.yml, CHANGELOG-6.md, backend/authorization/rbac/rbac_test.go
Upgrades Go to 1.21.3.
We're far behind on keeping up to date with the latest Go versions.
Yes.
No.
Yes, we had to merge #5033 to fix an issue with the types module.
Unit tests.
No.
=> Upgrade to Go 1.21.3

.github/workflows/semgrep.yml
The GitHub Action that we were using for Semgrep was deprecated and has now been removed. Use native Semgrep instead.
=> Use native Semgrep in CI

CHANGELOG-6.md, backend/schedulerd/executor.go, backend/schedulerd/executor_test.go
Closed https://github.com/sensu/sensu-go/issues/5002
**Description**
Each manual execution of a check via the web UI or sensuctl, must execute normally as it runs when scheduled.
**Change in behavior**
Manual execution of check used to throw an error of -'no matching entity found". With the changes made in context pass, the behaviour and fixed and matching entities are found.
**Added**
Nothing added ,only modification in existing function
**Changed**
The adhoc request of check execution is now processsed with the Context from resource that that an added namespace key in it.
changes are made listenQueue() and ProcessCheck() in executor.go in schedulered directory.
**Fixed**
This fixes the entity fetch for the manual executed check and is shown in logs after execution.
**Change …
=> 5002-manual check execution bugfix

CHANGELOG-6.md, backend/authentication/jwt/jwt.go, backend/authentication/jwt/jwt_test.go, backend/store/etcd/session.go
closed #5063
**Description**
The user sessions gets piled up in etcd occupying upto 2bg space .
**Change in behavior**
Deleting the etcd user_sesssions them after 6 minutes of creation ( Access token of session gets expired in 5 mnts) This change will make sure the memory occupancy uptil 1.8 GB will be eradicated
**Added**
Added TTL time of 6 minutes in session.go file for each entry regarding user-sessions.
**Fixed**
This fixes the etcd space occupancy issue .
**Change verification**
Do sensuctl configure.
Check respective entry in etcd ar /sensu.io/user-sessions/admin/xxyyzz[session_id]
this entry will be deleted automatically after 11 minutes if the backend keep .
I have the video of default behaviour ( which caused the issue) and the video of fixed behaviour with TTL=2mins , …
=> Etcd cleanup

backend/apid/middlewares/authorization_attributes.go, backend/apid/routers/users.go, backend/apid/routers/users_test.go
This change allows web UI users to update password by themselves.
feature request in ticket [https://github.com/sensu/sensu-enterprise-go/issues/2631](url)
requires entry to changelog, api documentation
Manual testing done, attached recording.
https://github.com/sensu/sensu-go/assets/24804960/145ef6f7-da91-4da8-91ea-659726a1df05
=> condition change to support password reset

.github/dependabot.yml
Dependabot must scan develop/6 branch for dependencies.
Github dependabot used to check for dependencies in main branch only, After this changes made, it will check for develop/6 branch.
Added dependabot.yml configuration inside .github folder.
Dependabot now will scan branch develop/6 for dependency , in this case "go" packages updates (if any available) and raise PR.
=> Add Dependabot config for scanning branch develop/6 
